### ISSUE TITLE
[SR-9] Activate enum import tests on Linux

### ISSUE THREAD

**Issue by jopamer** [apple/swift#42635]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9      |
   |Radar             | rdar://problem/20651533         |
   |Original Reporter | @jopamer      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | King (JIRA)      |
   |Priority          | Medium      |

   

   md5: 18e965d66c831b43c6feca10c1b21c92

  </details>

**Issue Description:**

Many of the Swift compiler tests in test/ClangModules that exercise enum import are broken on Linux and currently disabled there.

**Comment by CodaFi** [comment]
This issue was closed in 2018.
