### ISSUE TITLE
[SR-93] Implement overlay for Glibc.open()

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42715]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-93      |
   |Radar             | None         |
   |Original Reporter | jpedrosa (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, Linux, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 5503e7dff6511ec3887463506f7df5c9

  </details>

**Issue Description:**

The file at:  
<https://github.com/apple/swift/blob/8d9ef80304d7b36e13619ea50e6e76f3ec9221ba/stdlib/public/SDK/Darwin/Misc.mm>

Enables a few functions for Darwin that don't seem to be available for Linux yet.

The problem seems to be related to variadic functions being harder to map to from Swift.

I was interested in the "open" function. I was actually interested in the "open64" function which I used from FFI in another language, but "open" may work OK too. Since the "open" function seems to be present in the Darwin version, it seems that people are interested in it.

In the absence of "open", it seems that people have tried to use "fopen" instead. But they take different parameters and different programming styles, resulting in perhaps noticeable differences.

Thanks.

**Comment by oozoofrog** [comment]
is this moved to swift/stdlib/SwiftShims/swift/shims/LibcOverlayShims.h?
