### ISSUE TITLE
[SR-98] Red-hat - Support - Ninja binary name. 

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42720]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-98      |
   |Radar             | None         |
   |Original Reporter | thawkins (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1713d6536502cd9eca7d69967d0ebcd0

  </details>

**Issue Description:**

1'm positing a few bugs for redhat support issues, whilst it is not an official supported distro, there are only a couple of small blockers for easy integration

On Redhat based distros the name of the ninja binary installed by

sudo dnf install ninja-build is "ninja-build" not "ninja"

Would it be feasible for the build system to check for both and use the appropriate.

Workaround is to sym-link  
ln-s /usr/bin/ninja-build /usr/bin/ninja

**Comment by AnthonyLatsis** [comment]
I am going to assume this was fixed by #2352 (see https://github.com/apple/swift/pull/2352/files#diff-f2c23c7767232ac9308ea5f20bc2cdcc3de875cd05ecf8386d2d137397ca6a91R48)
