### ISSUE TITLE
[SR-129] Move AutoreleasingUnsafeMutablePointer to the ObjectiveC overlay

### ISSUE THREAD

**Issue by gribozavr** [apple/swift#42751]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-129      |
   |Radar             | rdar://problem/23681261         |
   |Original Reporter | @gribozavr      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Task, AffectsABI, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3b71bdf0662dc85a1c16b7e89ab838ef

  </details>

**Issue Description:**

AutoreleasingUnsafeMutablePointer is an @objc only concept, so it should be moved to the ObjectiveC overlay.

**Comment by Azoy** [comment]
Unfortunately we've committed this type to the stdlib's ABI by now. We may still be able to move it, but it'd probably be more work than the resulting benefit now.
