### ISSUE TITLE
[SR-156] A struct is not found in another file (ld: symbol(s) not found for architecture x86_64)

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42778]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-156      |
   |Radar             | None         |
   |Original Reporter | davidrichards (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode Swift 2.2 Snapshot (December 1, 2015) – only using the binary as shown above (not using  
Xcode).

OS X 10.11.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4cd8eae00c140b70e0f1a7b1c021b22a

  </details>

**Issue Description:**

This is how you reproduce the bug:

**1.**  
Create a Swift program with three files: **main.swift**, **CoolStruct.swift**, and **CoolStructProtocol.swift**.

**main.swift:**

``` none
//main.swift is empty.
```

**CoolStruct.swift:**

``` none
struct CoolStruct {
    let coolFactor: Double
}
```

**CoolStructProtocol.swift:**

``` none
protocol CoolStructProtocol {
    var coolFactor: Double { get }
}
extension CoolStruct : CoolStructProtocol {}
```

**2.**  
When I compile this program using Xcode Swift 2.2 Snapshot (December 1, 2015), I get the following compile-time error. (Note: My program directory is named CoolProgram, my Package.swift file is empty, the three files above are located within CoolProgram/Sources, and I built the program using "swift build" from within CoolProgram using the swift binary from the Swift 2.2 snapshot just mentioned.)

``` none
Compiling Swift Module 'CoolProgram' (3 sources)
Linking Executable:  .build/debug/CoolProgram
Undefined symbols for architecture x86_64:
  "__TFV11CoolProgram10CoolStructg10coolFactorSd", referenced from:
      __TTWV11CoolProgram10CoolStructS_18CoolStructProtocolS_FS1_g10coolFactorSd in CoolStructProtocol.swift.o
ld: symbol(s) not found for architecture x86_64
<unknown>:0: error: build had 1 command failures
```

**3.**  
If I remove CoolStruct from the CoolStruct.swift file and add it to the CoolStructProtocol.swift file instead, the program now compiles.  
So the problem is that Swift is not properly locating CoolStruct when it's in a separate file.

**Comment by AnthonyLatsis** [comment]
[Here](https://github.com/apple/swift/blob/main/test/multifile/protocol-conformance-member.swift) is the regression test; closing.
