### ISSUE TITLE
[SR-214] Swift 2: Guard let can shadow func param but not let-bound local constant

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42836]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-214      |
   |Radar             | rdar://problem/22609757         |
   |Original Reporter | rsmoz (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 2.2 OS X

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 57b1448c42c33942b5fa1e72da00755f

  </details>

**is duplicated by**:  
* [SR-9070](https://bugs.swift.org/browse/SR-9070) Variable shadowing inconsistency with guard  

**relates to**:  
* [SR-1687](https://bugs.swift.org/browse/SR-1687) Swift does not warn about shadowing  
* [SR-8524](https://bugs.swift.org/browse/SR-8524) Shadowing in protocols leads to difficult to find bugs  

**Issue Description:**

``` java
func a(x: Int?) {
    if let x = x { //No compiler error when if-let shadows parameter
        print(x+1)
    }
}

func b(x: Int?) {
    guard let x = x else { return } //No compiler error when guard-let shadows parameter
    print(x+1)
}

func c() {
    let x: Int? = nil
    if let x = x { //No compiler error when if-let shadows local constant
        print(x+1)
    }
}


func d() {
    let x: Int? = nil
    guard let x = x else { return } //!Compiler error! when guard-let shadows local constant
    print(x+1)
}
```

There's also a corresponding Radar: <https://openradar.appspot.com/22609757>

**Comment by AnthonyLatsis** [comment]
We do support this now [apparently](https://github.com/apple/swift/blob/main/test/DebugInfo/guard-let-scope.swift).
