### ISSUE TITLE
[SR-216] Increase test coverage on Linux

### ISSUE THREAD

**Issue by gribozavr** [apple/swift#42838]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-216      |
   |Radar             | rdar://problem/19648117         |
   |Original Reporter | @gribozavr      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, Standard Library    |
   |Labels            | Task, Linux, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 66b0885b16ee37449ebb1fc7351185e9

  </details>

**is blocked by**:  
* [SR-417](https://bugs.swift.org/browse/SR-417) Case of printed UUIDs differs in a platform dependent way  

**relates to**:  
* [SR-451](https://bugs.swift.org/browse/SR-451) Add protocol mirror test back to Runtime.swift test  

**Issue Description:**

Many important tests are XFAIL'ed on Linux. Usually this is because one or few parts of the test use the Objective-C runtime or rely on Foundation.

These parts can usually be separated into separate files, or guarded with \`#if \_runtime(\_ObjC)\`. Sometimes these failures are real issues that we are unaware of and need to start tracking in the bug tracker.

It is easy to find disabled tests with:

``` java
$ git grep 'XFAIL: linux'
```

I consider the following tests to be of high value to be looked at first.

Standard library:

``` java
test/1_stdlib/Print.swift
test/1_stdlib/ReflectionHashing.swift
test/1_stdlib/Runtime.swift
validation-test/stdlib/Dictionary.swift
validation-test/stdlib/Set.swift
validation-test/stdlib/String.swift
validation-test/stdlib/Unicode.swift
validation-test/stdlib/UnicodeTrie.swift.gyb
```

SIL and the optimizer:

``` java
test/Serialization/basic_sil.swift
```

\[Update\] These ones are done:

``` java
test/1_stdlib/ArrayTraps.swift.gyb
test/1_stdlib/SetTraps.swift
test/1_stdlib/StringTraps.swift
validation-test/stdlib/UnicodeUTFEncoders.swift
```

``` java
test/SIL/Parser/basic.sil
test/SILOptimizer/cse.sil
test/SILOptimizer/definite_init_diagnostics.swift
test/SILOptimizer/sil_combine.sil
```

**Comment by AnthonyLatsis** [comment]
The issues with these tests are either stale or resolved. Here is a resolution table for those that are not marked as been dealt with in the original post.

|||
| ------------- | ------------- |
| `test/Serialization/basic_sil.swift` | XFAIL removed in #842 |
| `test/1_stdlib/Print.swift`<br />Present-day `test/stdlib/Print.swift` | Appears to have never been XFAILed on Linux |
| `test/1_stdlib/ReflectionHashing.swift`<br />Present-day `test/stdlib/ReflectionHashing.swift` | XFAIL removed in #4867 |
| `test/1_stdlib/Runtime.swift`<br />Present-day `test/stdlib/Runtime.swift.gyb` | XFAIL removed in #862 |
| `validation-test/stdlib/Dictionary.swift` | XFAIL removed #2544 |
| `validation-test/stdlib/Set.swift` | XFAIL removed in #2561 |
| `validation-test/stdlib/String.swift` | XFAIL removed in #1111 |
| `validation-test/stdlib/Unicode.swift`<br />Present-day `validation-test/stdlib/Unicode.swift.gyb` | XFAIL removed #2544 |
| `validation-test/stdlib/UnicodeTrie.swift.gyb` | Deleted in #11409 |
