### ISSUE TITLE
[SR-236] Segmentation fault when casting an array

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42858]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-236      |
   |Radar             | None         |
   |Original Reporter | papierschiff (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961061-9a792290-c648-4a82-bb0a-d738d13b1728.gz)

      
<details>
  <summary>Environment</summary>

ubuntu15.10; swift2.2 (dec 10);

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug, CompilerCrash, Linux        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 9d396f0bc3b6340bec2f69a5792f574c

  </details>

**Issue Description:**

swiftc crashs with a Segmentation fault:

\<unknown\>:0: error: unable to execute command: Segmentation fault  
\<unknown\>:0: error: compile command failed due to signal (use -v to see invocation)

when downcasting an array. it works fine with xcode on osx

**Comment by Azoy** [comment]
This has since been resolved, the compiler now gives an error.
