### ISSUE TITLE
[SR-238] Support throwing subscripts

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42860]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-238      |
   |Radar             | None         |
   |Original Reporter | anviking (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 24         |
   |Component/s       |     |
   |Labels            | Improvement, LanguageFeatureRequest        |
   |Assignee          | @theblixguy      |
   |Priority          | Medium      |

   

   md5: d1f830bfd05395ee30fb2819cb12b391

  </details>

**relates to**:  
* [SR-115](https://bugs.swift.org/browse/SR-115) Support generic constraints in subscripts  

**Issue Description:**

Support for throwing subscripts would together with [generic ones](https://bugs.swift.org/browse/SR-115) be really nice for JSON mapping/deserializing libraries like mine <https://github.com/Anviking/Decodable>. It would make subscripts an alternative to custom operators.

For example:  
subscript\<T: SomeProtocol\>(key: String) throws -\> T

Would most likely be useful on its own for a lot of other things as well.

**Comment by endeavour42** [comment]
SE-0310 only allows throwing getter-only subscripts, setters are prohibited when getter is marked as throwing. I believe having a throwing subscript with both getter and setter would be handy:

```
let element = try array[index]
try array[index] = value
```
