### ISSUE TITLE
[SR-279] Attempting to return non-void from void closure behaves differently than for void functions

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42901]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-279      |
   |Radar             | None         |
   |Original Reporter | rothomp3 (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Mac OS X, tried with both the release Swift 2.1 from Xcode 7.2, and with the Swift 2.2 snapshot.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 80095b87ea7e3c07e77ff4f3bbd62bf6

  </details>

**is duplicated by**:  
* [SR-1211](https://bugs.swift.org/browse/SR-1211) Explicit return ignored in single-line blocks  

**Issue Description:**

Surprisingly, the following compiles and runs:

``` none
let thing = { (foo: Bool) -> Void in return foo }
```

Calling `thing(true)` returns Void, of course…

However,

``` none
func thingFunc(foo: Bool) -> Void { return foo }
```

Does *not* compile, as you would expect. It seems to me that both of these should have the same behavior; specifically, they should both fail to compile with "error: unexpected non-void return value in void function."

**Comment by AnthonyLatsis** [comment]
The contextual mismatch is now diagnosed properly: [regression test](https://github.com/apple/swift/blob/7e843559efd6e41d436a932322172eede4c530a1/test/Constraints/closures.swift#L996).
