### ISSUE TITLE
[SR-278] function overload

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42900]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-278      |
   |Radar             | None         |
   |Original Reporter | someguy (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Tested on  
Swift version 2.2-dev (LLVM 7bae82deaa, Clang 53d04af5ce, Swift 7dfcd4ea56)  
Target: x86_64-unknown-linux-gnu

and swift 2.1 on osx.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e287ffc493bc03b5bd0543802d0d5328

  </details>

**Issue Description:**

Swift seems to perform overload resolution incorrectly for operators.

**Comment by AnthonyLatsis** [comment]
Closing due to missing reproducer and lack of specifics.
