### ISSUE TITLE
[SR-306] Add stable sort algorithm

### ISSUE THREAD

**Issue by gribozavr** [apple/swift#42928]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-306      |
   |Radar             | rdar://problem/18221680         |
   |Original Reporter | @gribozavr      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 5         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, NewAPIRequest, StarterBug, StarterProposal        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 37f09a79466d145bd076877be8089150

  </details>

**Issue Description:**

The standard library should provide a stable sorting algorithm, next to the regular, unstable, sort() and sortInPlace().

This needs a proposal to swift-evolution (the design should be trivial, new methods should mirror existing sorting APIs), and implementation. The standard library already contains an internal implementation of insertion sort, so implementing this should amount to providing public entry points and writing tests.

**Comment by AnthonyLatsis** [comment]
Proposal: SE-0372
