### ISSUE TITLE
[SR-337] hasPrefix and hasSuffix not implemented in Swift

### ISSUE THREAD

**Issue by alblue** [apple/swift#42959]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-337      |
   |Radar             | None         |
   |Original Reporter | @alblue      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7139ff1a5de95a9c013b0ae4cb94233c

  </details>

**Issue Description:**

In stdlib/public/core/StringLegacy.swift there is a fixme to implement hasPrefix and hasSuffix without Objective-C

// FIXME: Implement hasPrefix and hasSuffix without objc  
// rdar://problem/18878343

I'd like to give this a go.

**Comment by AnthonyLatsis** [comment]
Fixed in https://github.com/apple/swift/commit/f9b3e14137ac2f50e93aa2c1db28511e05f88e75.
