### ISSUE TITLE
[SR-356] Optimize retains and releases on recursive function calls

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#42976]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-356      |
   |Radar             | None         |
   |Original Reporter | Pascal (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961083-de1085af-bbe3-49db-a9a0-32ba4e53eefd.gz)

      
<details>
  <summary>Environment</summary>

swift-2.2-SNAPSHOT-2015-12-18-a on OS X 10.11.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @gottesmm      |
   |Priority          | Medium      |

   

   md5: 8ec0a1f615837d6a25e85a6f5915eb94

  </details>

**Issue Description:**

**Problem**

``` java
func sumArrayRecursive(array: Array<Int>, index: Int = 0) -> Int {
    guard index < array.count else {
        return 0
    }
    return array[index] + sumArrayRecursive(array, index: index + 1)
}
```

The recursive function above (or similar recursive functions) compiled with -O produces unnecessary retains/releases on each recursive invocation.  
The equivalent function using the inout keyword for the array parameter produces code without unnecessary retains/releases and is therefore faster (\~13x).

**Expected Behaviour**  
The ARC optimizer should be able to optimize the unnecessary retains and releases away on each recursive invocation.

Attached is a small test case for both versions of the function.

[Filed as requested](https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20151221/000580.html)

**Comment by AnthonyLatsis** [comment]
This is fixed. I presume these days the array parameter will be `@guaranteed` whether or not the function is recursive, and, if so, we definitely have the test coverage.

@gottesmm You are welcome to prove me wrong.
