### ISSUE TITLE
[SR-368] Binary search algorithms are missing in the standard library

### ISSUE THREAD

**Issue by gribozavr** [apple/swift#42987]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-368      |
   |Radar             | rdar://problem/17743336         |
   |Original Reporter | @gribozavr      |
   |Type              | New Feature    |
   |Status            | In Progress        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 6         |
   |Component/s       | Standard Library    |
   |Labels            | New Feature, StarterBug, StarterProposal        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 09fcbb527f0d270cf27b2cd24be810a8

  </details>

**Issue Description:**

We have no analog to C++'s binary_search, lower_bound, upper_bound, and equal_range algorithms.

**Comment by Rajveer100** [comment]
Where would these additional features (as in algos) go to? And I suppose these need to be generic based right?

**Comment by Rajveer100** [comment]
@AnthonyLatsis

**Comment by AnthonyLatsis** [comment]
This issue warrants discussion on the forums and an [evolution proposal](https://www.swift.org/swift-evolution/).

**Comment by Rajveer100** [comment]
Ok!

**Comment by Azoy** [comment]
I think these would be good candidates for the swift-algorithms package here: https://github.com/apple/swift-algorithms to experiment with before committing to the standard library.
