### ISSUE TITLE
[SR-421] Fail to build stdlib on osx with region set to non US

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43038]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-421      |
   |Radar             | None         |
   |Original Reporter | johnlinvc (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

osx 10.12.2  
Sphinx (sphinx-build) 1.3.3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Bug, BuildScript        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 05b2459d737fd1a4f9c218fbd5da0065

  </details>

**Issue Description:**

## Reproduce steps

1\. Open Language & Region setting panel, set region to Taiwan.  
2. invoke build-script

``` java
./utils/build-script
```

[Error log](https://gist.github.com/johnlinvc/fc56af91713e1f3cd8cb)

## Root Cause

If language is set to English, but the region is set to non US, the LC_CTYPE Env var will be set to "UTF-8", which will cause error in sphinx-doc.  
see <https://bugs.python.org/issue18378#msg215215>

## workaround

build the project with LC_CTYPE set to "en_US.UTF-8"

``` java
LC_CTYPE=en_US.UTF-8 ./utils/build-script   
```

**Comment by AnthonyLatsis** [comment]
Optimistically closing this since the underlying python issue [has been fixed](https://github.com/python/cpython/pull/14736).
