### ISSUE TITLE
[SR-461] prefix() chained after filter() confuses type inference when used on a sequence that uses AnyGenerator

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43078]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-461      |
   |Radar             | None         |
   |Original Reporter | itchingpixels (JIRA User)      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler, Standard Library    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7a921301033d688e26e6764735b18b41

  </details>

**duplicates**:  
* [SR-851](https://bugs.swift.org/browse/SR-851) Result of dropFirst differs between 2.1.1 and 2.2  

**Issue Description:**

When this code is typed in:

``` java
struct NaturalNumbers : SequenceType {
  internal func generate() -> AnyGenerator<Int> {
    var i = 0
    return anyGenerator {
      return i++
    }
  }
}


let standalonePrefix = (1...100).lazy.prefix(3)
print(Array(standalonePrefix))

let prefixWithFilter1: AnySequence<Int> = NaturalNumbers().lazy.filter { (number) -> Bool in
  return number % 2 == 0
  }.prefix(3)
print(Array(prefixWithFilter1))

let prefixWithFilter2 = NaturalNumbers().lazy.filter { (number) -> Bool in
  return number % 2 == 0
  }.prefix(3)
print(Array(prefixWithFilter2))

```

The compiler warns about "Ambiguous use of 'filter'" on the line where prefixWithFilter2 is defined.  
I spent some time on trying to find the source problem, and this post helped me:  
<https://forums.developer.apple.com/thread/26147>

I'm wondering if there's no way around the compiler making a choice of which type chain variation to go for, would it be possible to display a more detailed error message?  
Unfortunately "Ambiguous use of 'filter'" didn't help me that much understanding the problem, and it also didn't suggest any resolution (which is actually quite easy).

**Comment by AnthonyLatsis** [comment]
Fixed by #12520
