### ISSUE TITLE
[SR-456] Confusing build error when calling 'max' function  within 'extension Int'

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43073]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-456      |
   |Radar             | None         |
   |Original Reporter | kyleve (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961099-f7c5e5ed-b226-41c9-9f87-6e1aa36cbf61.gz)

      
<details>
  <summary>Environment</summary>

**Xcode Version**: Version 7.2 (7C68)  
**OS X Version**: 10.11.1 (15B42)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c80716cfb9eccad98f648bc05dc3a005

  </details>

**is duplicated by**:  
* [SR-609](https://bugs.swift.org/browse/SR-609) 'Cannot call value of non-function type' error when calling initializer of class with same name as enum case  

**relates to**:  
* [SR-5594](https://bugs.swift.org/browse/SR-5594) Unexpected error: Cannot call value of non-function type 'Data?'  

**Issue Description:**

When trying to build code that calls *max()* within an *extension Int*, a compiler error occurs.

``` java
import Foundation


func thisWorksCorrectly()
{
    let maxValue = max(0, 1)
}

internal extension Int
{
    static func thisDoesNotBuild()
    {
       // Error: Cannot call value of non-function type 'Int'
        let maxValue = max(0, 1)
    }
    
    static func butThisDoesBuild()
    {
        let maxValue = Swift.max(0, 1)
    }
}
```

This problem can be worked around by changing *max(0, 1)* to *Swift.max(0, 1)*, but the error message seems unclear.

**Comment by AnthonyLatsis** [comment]
This is diagnosed accurately now, and backed up with tests [here](https://github.com/apple/swift/blob/5b6ec5dfea62377cb53604093bc833b674e74503/test/Constraints/members.swift#L416)—closing.
