### ISSUE TITLE
[SR-470] Segmentation fault: 11

### ISSUE THREAD

**Issue by krzyzanowskim** [apple/swift#43087]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-470      |
   |Radar             | None         |
   |Original Reporter | @krzyzanowskim      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode Version 7.2 (7C68)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CompilerCrash        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 5366a25f0083648754be12fb590936f3

  </details>

**Issue Description:**

Suddenly my application can't compile any longer and I have no idea why. This is the only information I can see in logs now:

\`\`\`  
0 swift 0x000000010bde6fbb llvm::sys::PrintStackTrace(\_\_sFILE\*) + 43  
1 swift 0x000000010bde76fb SignalHandler(int) + 379  
2 libsystem_platform.dylib 0x00007fff8d3b3eaa \_sigtramp + 26  
3 libsystem_platform.dylib 000000000000000000 \_sigtramp + 1925497200  
4 swift 0x000000010a55dd69 swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl\*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver\*) + 201  
5 swift 0x000000010a55dd9d swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl\*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver\*) + 253  
6 swift 0x000000010a55de12 swift::ConformanceLookupTable::updateLookupTable(swift::NominalTypeDecl\*, swift::ConformanceLookupTable::ConformanceStage, swift::LazyResolver\*) + 370  
7 swift 0x000000010a560f95 swift::ConformanceLookupTable::lookupConformances(swift::NominalTypeDecl\*, swift::DeclContext\*, swift::LazyResolver\*, swift::ConformanceLookupKind, llvm::SmallVectorImpl\<swift::ProtocolDecl\*\>**, llvm::SmallVectorImpl\<swift::ProtocolConformance**\>**, llvm::SmallVectorImpl\<swift::ConformanceDiagnostic\>**) + 53  
8 swift 0x000000010a5a5449 swift::DeclContext::getLocalConformances(swift::ConformanceLookupKind, llvm::SmallVectorImpl\<swift::ConformanceDiagnostic\>\*, bool) const + 201  
9 swift 0x000000010a234689 swift::serialization::Serializer::writeDecl(swift::Decl const\*) + 2617  
10 swift 0x000000010a23b8ef swift::serialization::Serializer::writeAllDeclsAndTypes() + 8447  
11 swift 0x000000010a23c789 swift::serialization::Serializer::writeAST(llvm::PointerUnion\<swift::ModuleDecl\*, swift::SourceFile\*\>) + 2505  
12 swift 0x000000010a23ed87 swift::serialization::Serializer::writeToStream(llvm::raw_ostream&, llvm::PointerUnion\<swift::ModuleDecl\*, swift::SourceFile\*\>, swift::SILModule const\*, swift::SerializationOptions const&) + 135  
13 swift 0x000000010a23f9b2 withOutputFile(swift::ASTContext&, llvm::StringRef, llvm::function_ref\<void (llvm::raw_ostream&)\>) + 226  
14 swift 0x000000010a23f836 swift::serialize(llvm::PointerUnion\<swift::ModuleDecl\*, swift::SourceFile\*\>, swift::SerializationOptions const&, swift::SILModule const\*) + 214  
15 swift 0x0000000109ed7f08 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef\<char const\*\>, int&) + 12840  
16 swift 0x0000000109ed4ad3 frontend_main(llvm::ArrayRef\<char const\*\>, char const\*, void\*) + 2691  
17 swift 0x0000000109ed1154 main + 2324  
18 libdyld.dylib 0x00007fff911f25ad start + 1  
19 libdyld.dylib 0x0000000000000078 start + 1860229836  
\`\`\`

**Comment by AnthonyLatsis** [comment]
The reduced example works fine now. Digging for the reasons this once crashed is going to be a nightmare though, so I am going to err on the optimistic side and assume we have the test coverage.
