### ISSUE TITLE
[SR-476] Confusing error message when declaring a property with "unowned lazy var"

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43093]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-476      |
   |Radar             | None         |
   |Original Reporter | loic (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 1f2908b4f7)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 69a74e928d6d67c2bfdae21f991bd1c1

  </details>

**Issue Description:**

This program:

``` none
class A { }
class B {
    unowned lazy var property = A()
}
```

fails to compile, and gives this error message:

``` none
error: cannot convert return expression of type 'A' to return type 'A'
```

which is confusing.

**Comment by AnthonyLatsis** [comment]
The error message is on-target now; tests [here](https://github.com/apple/swift/blob/main/test/Sema/diag_ownership_lazy.swift).
