### ISSUE TITLE
[SR-528] NSStringAPI.swift incorrectly declares propertyListFromStringsFileFormat as not nullable

### ISSUE THREAD

**Issue by phausler** [apple/swift#43145]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-528      |
   |Radar             | None         |
   |Original Reporter | @phausler      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d2ce84ce33f58bd1549c0e4160182b81

  </details>

**Issue Description:**

propertyListFromStringsFileFormat can and will return nil when the plist is not in the strings format. So given a valid plist of an array such as:  
\[ "foo", "bar" \]  
this method in Foundation will return nil and cause a crash.

extension NSString {

/\* These methods are no longer recommended since they do not work with property lists and strings files in binary plist format. Please use the APIs in NSPropertyList.h instead.  
\*/  
public func propertyList() -\> AnyObject  
public func propertyListFromStringsFileFormat() -\> \[NSObject : AnyObject\]?  
}

**Comment by AnthonyLatsis** [comment]
This is no longer a Swift issue and the [method now nil-coalesces with an empty dictionary](https://github.com/apple/swift-corelibs-foundation/blob/cd988935ddf500cab069effe7ccd73aa5cf42fd1/Sources/Foundation/NSStringAPI.swift#L1089) rather than just force-casting to a non-optional type, which seems intentional—closing.
