### ISSUE TITLE
[SR-524] AnyObject unresolved dot expr does not work across files in the same module

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43141]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-524      |
   |Radar             | rdar://problem/20217221         |
   |Original Reporter | emanuel (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 6e4f61c072)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: fbc1db1ee131fe26d1687a21de8dd692

  </details>

**relates to**:  
* [SR-525](https://bugs.swift.org/browse/SR-525) AnyObject unresolved dot expr fails oddly and intermittently  

**Issue Description:**

Description:

If a property is defined in another file in the current module, the compiler appears to be unwilling to resolve an unresolved dot expression on an AnyObject instance to refer to that property.

Sample Case:

File main.swift

``` java
testObject.property
```

File Bug.swift

``` java
import Foundation
public class Foo : NSObject {
  public var property : Int = 33
}

let testObject : AnyObject = Foo()
```

Run command, with appropriate SDKROOT set.

``` java
swiftc main.swift Bug.swift
```

Expected result: compilation with no errors.

Actual result:

    main.swift:2:1: error: value of type 'AnyObject' has no member 'property'
    testObject.property
    ^~~~~~~~~~ ~~~~~~~~

If all the code is stored in the same file, this works okay.

**Comment by AnthonyLatsis** [comment]
Interesting, this is not a bug. Dynamic lookup will not find `Foo.property` unless you expose it to Objective-C with `@objc`—inheriting from `NSObject` does not count. The `property` it finds when you place everything in a single file is [Foundation.Stream.property(forKey:)](https://developer.apple.com/documentation/foundation/stream/1410226-property), and the reason this fails in the original example is because you forgot to import `Foundation` in `main.swift`.
