### ISSUE TITLE
[SR-537] Crash when printing `self.dynamicType` in a protocol extension constrained on Objective-C subclass

### ISSUE THREAD

**Issue by jpsim** [apple/swift#43154]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-537      |
   |Radar             | http://www.openradar.me/24173309         |
   |Original Reporter | @jpsim      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Tested on "Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)" and "swift-2.2-SNAPSHOT-2016-01-11-a"

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Standard Library    |
   |Labels            | Bug, RunTimeCrash, Runtime        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d6db625cc8d2b370e712c91d95a576af

  </details>

**Issue Description:**

Cross-posted from rdar://24173309

Summary:  
Accessing \`self.dynamicType\` in a protocol extension constrained on Objective-C subclass in Swift causes a bad memory access.

Steps to Reproduce:  
Run the following code:

``` none
import Foundation
// doesn't crash when subclassing a non-Objective-C class, or not subclassing
class Class1: NSObject, Protocol1 {}

protocol Protocol1 {}
// doesn't crash without the type constraint, or with a different constraint ('Self: Hashable')
extension Protocol1 where Self: Class1 {
    func printType() {
        print(self.dynamicType)
        // also crashes:
        // _ = String(self.dynamicType)
        // self.dynamicType.description()
    }
}

Class1().printType() // EXC_BAD_ACCESS
```

Expected Results:  
Accessing \`self.dynamicType\` in a protocol extension constrained on Objective-C subclass in Swift should return the calling type.

Actual Results:  
Accessing \`self.dynamicType\` in a protocol extension constrained on Objective-C subclass in Swift causes a bad memory access.

Regression:  
Tested on "Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)" and "swift-2.2-SNAPSHOT-2016-01-11-a"

**Comment by AnthonyLatsis** [comment]
@slavapestov This is fixed, but I would rather supplement an existing test file than add a fixed crasher. Could you give me a tip on where to look? I found several candidates that have `_typeName` tests (`test/stdlib/TypeName.swift`, `test/stdlib/RuntimeObjC.swift`), but I'm not sure which one fits best.
