### ISSUE TITLE
[SR-581] Pass parameter to generic class init function , the properties can not get the data

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43198]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-581      |
   |Radar             | None         |
   |Original Reporter | zhengying (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

iOS7.1.2 iphone5 xcode7.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Runtime        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2cad164f48f80a6f9ba7d8758e8a2f69

  </details>

**Issue Description:**

this bug occurs in xcode 7.2, xcode 7.3 beta  
the bug not exist in xcode 7.1

The bug only found in iOS7 (only test in 7.1.2)  
the bug not exist in iOS8 and iOS9

``` none
class ListItem<T> {
    var title: String
    var value:T
    
    init(title:String, value:T) {
        self.value = value
        self.title = title
    }
}

let item = ListItem<Int>(title: "test", value: 10)
print("item:\(item.value)")  // the item.value is unexpected data
```

**Comment by AnthonyLatsis** [comment]
Unfortunately, iOS 7 appears to be out of reach for the latest Swift release. You are welcome to reopen the issue if it happens to reemerge on a less distant deployment target.
