### ISSUE TITLE
[SR-595] CERT VU#903934 and oCERT #2011-003 Hash Table Vulnerability

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43212]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-595      |
   |Radar             | None         |
   |Original Reporter | dturnbull (JIRA User)      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961132-0d6fb784-6f2c-4765-86a1-16beaa0034be.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: add549f9e811da84efa8213f1ccb1c38

  </details>

**Issue Description:**

In Hashing.swift, \_HashingDetail.getExecutionSeed() is unimplemented. This can leave Swift web services vulnerable to attacks as described by these advisories...

<http://www.ocert.org/advisories/ocert-2011-003.html>  
<https://www.kb.cert.org/vuls/id/903934>

There's already a FIXME comment: "This needs to be a per-execution seed. This is just a placeholder implementation."

Attached is an example that shows an attack can actually be crafted. If you're not using the Jan 6 snapshot it might require finding a different collision.

**Comment by AnthonyLatsis** [comment]
> I believe this can be closed since [SE-0206](https://github.com/apple/swift-evolution/blob/master/proposals/0206-hashable-enhancements.md) was implemented in Swift 4.2.

Closing.
