### ISSUE TITLE
[SR-601] No supported branch of compiler-rt on github

### ISSUE THREAD

**Issue by vedantk** [apple/swift#43218]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-601      |
   |Radar             | None         |
   |Original Reporter | @vedantk      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Task        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 25acf566edb3fe37d928d95c09378942

  </details>

**Issue Description:**

There is (a) no recommended version of compiler-rt to use with upstream-with-swift or swift-2.2-branch, and (b) no support in the build script for enabling/disabling compiler-rt builds.

This is a serious problem because attempts to use \`-profile-generate -profile-coverage-mapping\` fail with, e.g:

ld: file not found: /Users/vk/github-swift/build/Debug+Asserts/swift-macosx-x86_64/lib/swift/clang/3.8.0/lib/darwin/libclang_rt.profile_osx.a

It isn't feasible to drop in a random version of compiler-rt, because compiler-rt is more or less rev-locked with llvm.

**Comment by AnthonyLatsis** [comment]
[compiler-rt](https://github.com/apple/llvm-project/tree/next/compiler-rt) is now part of `llvm-project`, so I guess this can be said to be resolved.
