### ISSUE TITLE
[SR-611] [String: *] can't be converted to [String:Any]

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43228]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-611      |
   |Radar             | None         |
   |Original Reporter | kallner (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 27194decf19f004bc50356c8328cec10

  </details>

**Issue Description:**

Dictionary instances don't properly bridge to Dictionary types with the same key type and a value type of Any.

Here is an example of \[String: Int\] failing to bridge to \[String: Any\]:

Welcome to Swift version 2.2-dev (LLVM 3ebdbb2c7e, Clang f66c5bb67b, Swift 42591f7cba). Type :help for assistance.  
1\> let a = \["a":1\]  
a: \[String : Int\] = 1 key/value pair {  
\[0\] = {  
key = "a"  
value = 1  
}  
}  
2\> a is Any  
$R0: Bool = true  
3\> a is \[String:Int\]  
$R1: Bool = true  
4\> a is \[String:Any\]  
repl.swift:4:3: error: '\[String : Int\]' is not convertible to '\[String : Any\]'  
a is \[String:Any\]  
\~<sub>^</sub>\~\~\~\~\~\~\~\~\~\~\~\~\~

4\> 1 is Any  
$R2: Bool = true  
5\>  
6\>  
7\> let b:Any = \["a":1\]  
b: \[String : Int\] = 1 key/value pair {  
\[0\] = {  
key = "a"  
value = 1  
}  
}  
8\> b is \[String:Int\]  
$R3: Bool = true  
9\> b is \[String:Any\]  
$R4: Bool = false

The same failure is seen if the type of the value is other types such as String, Double, etc.

**Comment by AnthonyLatsis** [comment]
Fixed in 232a314a9fa97d25d6ef033a04d5d468234f72c0
