### ISSUE TITLE
[SR-610] _copyCollectionToNativeArrayBuffer uses indexing to iterate over elements

### ISSUE THREAD

**Issue by lorentey** [apple/swift#43227]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-610      |
   |Radar             | None         |
   |Original Reporter | @lorentey      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift master branch as of 2016-01-24

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug, Performance        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2bb7732b12d7d4e98a0a917a9ab2ad6c

  </details>

**Issue Description:**

stdlib uses `_copyCollectionToNativeArrayBuffer` to perform `Array` conversion for types that implement `CollectionType`. This function uses indexing to iterate over elements in the collection:

      var p = result.firstElementAddress
      var i = source.startIndex
      for _ in 0..<count {
        // FIXME(performance): use _initializeTo().
        p.initialize(source[i])
        i._successorInPlace()
        p._successorInPlace()
      }

I believe it would be better to use the collection's `Generator` instead, as in `_copySequenceToNativeArrayBuffer` — indexing is the more general API, so it is often harder to optimize than generation. For example, I have some collection types (based on COW search trees) where the most pragmatic/useful implementation of subscripting is O(log(n⁠)), while `Generator.next()` can be easily done in amortized O(1). Modifying the code above to use a simple for-in loop results in a complexity class improvement from O(n\*log(n⁠)) to O(n⁠) for these types, which is very noticeable in benchmarks.

      var p = result.firstElementAddress
      for element in source {
        // FIXME(performance): use _initializeTo().
        p.initialize(element)
        p._successorInPlace()
      }

**Comment by AnthonyLatsis** [comment]
@lorentey `_copyCollectionToContiguousArray` switched to using `_copyContents` in b519d1d8734f1145cb86d53737ea1f110b1c64c3, which is a customization point, so I guess this can be considered resolved?

**Comment by AnthonyLatsis** [comment]
Considering resolved.
