### ISSUE TITLE
[SR-646] ObjectIdentifier shouldn't be Comparable

### ISSUE THREAD

**Issue by 05109ee7-7cd9-4cd4-92d0-698e676fc6af** [apple/swift#43263]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-646      |
   |Radar             | None         |
   |Original Reporter | @an0      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 3 in Xcode 8.0 beta 3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: bca157293557f4aef9f92d2ea17b006b

  </details>

**Issue Description:**

ObjectIdentifier shouldn't be Comparable because its order is meaningless.

Reference: <https://twitter.com/an0/status/693186785875091456>

**Comment by AnthonyLatsis** [comment]
@belkadan Do you reckon we can close this? The conformance could be removed for non-Apple OSs, but IMO that hardly sounds like a promising or worthy evolution proposal.

**Comment by belkadan** [comment]
Yeah, kind of sad about it because I agree with the bug report, but when it was filed in 2016 we were still open to breaking tweaks in the standard library and now we're not.

**Comment by AnthonyLatsis** [comment]
Hm... why am I hesitating now? 😅
@airspeedswift Is there even a slight chance the core team could reach consensus on a low-risk ABI break such as this one?

**Comment by belkadan** [comment]
If it were to happen now it would have to be something like `@available(swift, unavailable: 6)` on the conformance itself, it can't ever be removed from the Apple stdlib. I don't think it's worth everyone's time.

**Comment by AnthonyLatsis** [comment]
Alright then, closing.
