### ISSUE TITLE
[SR-643] Type inference chooses LazyMapSequence over LazyMapCollection 

### ISSUE THREAD

**Issue by natecook1000** [apple/swift#43260]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-643      |
   |Radar             | None         |
   |Original Reporter | @natecook1000      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 3.0-dev (LLVM 46be9ff861, Clang f66c5bb67b, Swift e8ea22747a)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | @jopamer      |
   |Priority          | Medium      |

   

   md5: 0f68d5233757c08995531f1e8a42c886

  </details>

**Issue Description:**

The compiler is inferring the wrong type for lazyStrings in the following code. It should be a **LazyMapCollection\<\[Any\], String?\>**, but ends up inferred as a **LazyMapSequence\<\[Any\], String?\>**. Since lazy sequences have different capabilities and performance characteristics than lazy collections, this is not good.

``` java
let list: [Any] = [1, 2, "3", 4, 5, 6, 7, "8", 9, 10]
let lazyStrings = list.lazy.map { $0 as? String }
```

Explicitly typing lazyStrings as a LazyMapCollection solves the problem.

**Comment by AnthonyLatsis** [comment]
@natecook1000 `LazyMapCollection` is just a type alias of `LazyMapSequence` with `Base` conforming to `Collection`. Also, `lazy` is only declared once along the `Sequence` protocol hierarchy in an extension of `Sequence` and returns a `LazySequence`, so the compiler is doing the right thing here. We would need to restate `lazy` in `Collection`, `BidirectionalCollection` etc. to make these expressions pick up the right sugared type. Do you think it is worth the visual relief?
