### ISSUE TITLE
[SR-653] Strange performance anomaly with a certain generic function & Dictionary

### ISSUE THREAD

**Issue by lorentey** [apple/swift#43270]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-653      |
   |Radar             | None         |
   |Original Reporter | @lorentey      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961141-2298dd6b-09db-4d59-8fb3-1466bb14514f.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Performance        |
   |Assignee          | @aschwaighofer      |
   |Priority          | Medium      |

   

   md5: e374a8910cbccada2f37d785b2e8b117

  </details>

**Issue Description:**

While working on possible performance improvements in stdlib, I ran across a strange performance anomaly that smells like a bug. When `S` is a `Dictionary`, the function below is about 20% faster when `underestimateCount` is zero than when it's set to `source.count`. (I attached the complete benchmarking code to this ticket.)

    extension TestBuffer {
        mutating func genericAddFrom<S: SequenceType where S.Generator.Element == Element>(source: S, underestimateCount: Int) {
            assert(underestimateCount <= remainingCapacity)

            var generator = source.generate()
            for _ in 0..<underestimateCount {
                addWithExistingCapacity(generator.next()!)
            }
            while true {
                for _ in 0..<remainingCapacity {
                    guard let element = generator.next() else { return }
                    addWithExistingCapacity(element)
                }
                guard let element = generator.next() else { return }
                add(element)
            }
        }
    }

The anomaly disappears for all other SequenceType implementations I tried. It also goes away when I manually specialize the function.

When run, the attached code produces benchmark results like this, produced on a mid-2012 rMBP.

    Experiment                                               Average   RSD    
    genericAddFrom<Dictionary> with underestimateCount = 0   157.3ms   1.6%   
    specializedAddFrom with underestimateCount = 0           163.2ms   1.6%   
    specializedAddFrom with underestimateCount > 0           163.3ms   1.8%   
    genericAddFrom<Dictionary> with underestimateCount > 0   204.6ms   1.3%

**Comment by AnthonyLatsis** [comment]
`Dictionary.Iterator.next` was made `@inline(__always)` in #1940; I am going to assume this is fixed.
