### ISSUE TITLE
[SR-672] LLVM -Os and Swift -O generate a `retain` message send crash.

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43287]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-672      |
   |Radar             | rdar://24704771         |
   |Original Reporter | cananito (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961149-9a968970-0d42-4f8b-b1d7-6533fe3259fc.gz)

      
<details>
  <summary>Environment</summary>

-   OS X 10.11.3 (15D21).

-   Xcode 7.2.1 (7C1002) (and previous version).

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CompilerCrash, OptimizedOnly        |
   |Assignee          | @gottesmm      |
   |Priority          | Medium      |

   

   md5: 3539a96d1d7e56f2285a82a9704d0d64

  </details>

**Issue Description:**

Repro steps:

1\. Run the LocalizationCSV app.  
2. On the first field, point it to the TestProject folder.  
3. Click \`Generate CSVs\`.  
4. It should crash on line 39 of \`LocaleDatabase.swift\`.

I suppose the current workaround this issue is to compile the release version with no optimizations.

**Comment by AnthonyLatsis** [comment]
I am going to consider this resolved. Closing as is, since mocking up a regression test out of such an outdated project is pure guesswork.
