### ISSUE TITLE
[SR-742] Run time performance regression in 2.2

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43357]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-742      |
   |Radar             | rdar://24705037         |
   |Original Reporter | dturnbull (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961166-c115cdb5-41e6-406f-83da-acce24407153.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Performance        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: bd47f887a3fcbab0bba8cfc35dd20552

  </details>

**Issue Description:**

Example compiled with 2.2 (Feb 8 snapshot) is 5-10% slower than 2.1 included with Xcode.

To repro, use <https://github.com/AE9RB/SwiftGL> to decode a PNG.  
Add function in SwiftGLres target so WMO specializes:

``` java
public func testWMO() {
    let loader = SGLImageLoader(fromFile: "buildingtex.png")
    if (loader.error != nil) { fatalError(loader.error!) }
    let image = SGLImageRGB<UInt8>(loader)
    if (loader.error != nil) { fatalError(loader.error!) }
    let _ = image
}
```

then a measure block in a test:

``` java
measureBlock { testWMO() }
```

The exact PNG I used is attached. It's not special in any way.

**Comment by AnthonyLatsis** [comment]
Only relative measurements were provided, and FWIW a 10% delta is not worth investigating this late in the game—closing.
