### ISSUE TITLE
[SR-815] Generic classes with default property initializers bug

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43427]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-815      |
   |Radar             | rdar://problem/25318716         |
   |Original Reporter | wiruzx (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 2.1.1, iOS 7  
Swift 2.2, iOS 9.3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 22         |
   |Component/s       | Compiler    |
   |Labels            | Bug, RunTimeCrash        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ab6cd5d5f6905bbd52b11768623b6abf

  </details>

**is duplicated by**:  
* [SR-1659](https://bugs.swift.org/browse/SR-1659) Swift2.2.1 generics property crash  

**relates to**:  
* [SR-1201](https://bugs.swift.org/browse/SR-1201) All generic class crash on iOS 7  

**Issue Description:**

``` java
class Test<T> {
    let object = NSObject()
    var value: T?
    
    func test() {
        print(object) // EXC_BAD_ACCESS here
    }
}

let x = Test<Int>()
x.test()

```

It doesn't matter if object will be NSObject or Swift's ref type.

Bug is not being reproduced if you either:

-   make class non-generic,

-   remove \`value\` property,

-   swap \`object\` and \`value\` properties declarations,

-   initialize object in \`init\`

This issue reproduces only on iOS 7

**Comment by AnthonyLatsis** [comment]
Unfortunately, iOS 7 appears to be out of reach for the latest Swift release. You are welcome to reopen the issue if it happens to reemerge on a less distant deployment target.
