### ISSUE TITLE
[SR-847] Swift support for UInt128

### ISSUE THREAD

**Issue by colemancda** [apple/swift#43459]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-847      |
   |Radar             | None         |
   |Original Reporter | @colemancda      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Ubuntu 14

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler, Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: bf62d95aea57e2c7dd48ba106a59e114

  </details>

**relates to**:  
* [SR-743](https://bugs.swift.org/browse/SR-743) When Developing a UnsignedIntegerType Larger Than 64 Bits, 64+ Left Shifts Won't Compile with Optimizations  

**Issue Description:**

I am currently working with BlueZ on Linux and came across `uint128_t`. I would like this to be part of the Swift Standard Library. In the meanwhile, is there a solution I can put together? It seems to me that the compiler with have to use some of its "builtin" type magic for any solution to be performant.

**Comment by AnthonyLatsis** [comment]
@colemancda Why are we closing this as completed? If no longer relevant or you wish to withdraw it, I think it best to close as not planned.

**Comment by colemancda** [comment]
Ok
