### ISSUE TITLE
[SR-893] Compiler fails to infer return type of the transform closure in a map call

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43505]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-893      |
   |Radar             | None         |
   |Original Reporter | Neil Faiman (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Observed with Xcode 7.2.1 on OS X 10.11.3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c0ac1ad743999c1756dbbe9d58a76fbd

  </details>

**is duplicated by**:  
* [SR-1664](https://bugs.swift.org/browse/SR-1664) Improve diagnostic for inability to infer return types from multi line closures  
* [SR-1773](https://bugs.swift.org/browse/SR-1773) ..< is ambiguous together with map for certain closures  

**relates to**:  
* [SR-1570](https://bugs.swift.org/browse/SR-1570) 'Generic parameter 'Result' could not be inferred' compiler error for wrapper functions like autoreleasepool that return the result of their closure argument.  

**Issue Description:**

When the **map** method is called with closure for its transform argument, and the closure return type specification is omitted, everything works fine if the type of the returned expression is implicit – for example,

``` java
let x1 = [1,2].map { _ in
    return "abc"
}
```

But if the same expression is assigned to a variable, and the variable is returned:

``` java
let x2 = [1,2].map { _ in
    let x = "abc"
    return x
}
```

then the compiler gives an error. In Xcode 7.2.1, the error is

``` java
Cannot invoke 'map' with an argument list of type '(@noescape (Int) throws -> _)'
Expected an argument list of type '(@noescape (Self.Generator.Element) throws -> T)'
```

It seems that in both calls, the transform closure is returning a String, and the compiler knows it is a String, so the error in the second call looks like a compiler bug.

(Making the return type explicit – "map { \_ -\> String in ... }" – works around the bug.)

**Comment by AnthonyLatsis** [comment]
Fixed by [SE-0326](https://github.com/apple/swift-evolution/blob/main/proposals/0326-extending-multi-statement-closure-inference.md)
