### ISSUE TITLE
[SR-889] Collection algorithms that return indices of minimum and maximum elements

### ISSUE THREAD

**Issue by gribozavr** [apple/swift#43501]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-889      |
   |Radar             | rdar://problem/24999612         |
   |Original Reporter | @gribozavr      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, StarterBug        |
   |Assignee          | valeriyvan (JIRA)      |
   |Priority          | Medium      |

   

   md5: 323a62523ad9d65ac164670698a6c6ee

  </details>

**relates to**:  
* [SR-890](https://bugs.swift.org/browse/SR-890) Sequence.minmax() and Collection.minmaxIndices()  

**Issue Description:**

Some collections naturally maintain sorted order and can implement \`minElement()\` and \`maxElement()\` in O(1). But these APIs only return elements themselves. It is sometimes useful to get indices instead (e.g., if you want to mutate the element in the collection).

**Comment by Azoy** [comment]
This is currently implemented in the swift-algorithms package here: https://github.com/apple/swift-algorithms
