### ISSUE TITLE
[SR-1155] Make Metadata structures standard layout

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#43763]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1155      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug, AffectsABI, Runtime        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: be73d29de5928d07f20f663a7491e3e1

  </details>

**Issue Description:**

Metadata structures are complaining about using \`offsetof\` on non-standard layout types, probably because the metadata kind is a private member in the base TargetMetadata class. It's private because the kind may actually be a class's metadata pointer, so it checks for that and returns 0 (MetadataKind::Class) in that case.

**Comment by Azoy** [comment]
Metadata has been ABI stable for a few years now, I think we can close this.
