### ISSUE TITLE
[SR-1179] Compiler bug: initialising subclass skips to super when using Whole Module optimisation

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43787]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1179      |
   |Radar             | None         |
   |Original Reporter | timwindsorbrown (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Whole Module optimisation

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Miscompile, OptimizedOnly        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c2c39cc40e2d6cf403c4fc4ca19d6ecc

  </details>

**relates to**:  
* [SR-1117](https://bugs.swift.org/browse/SR-1117) Overridden function is not being called when sublassing generic class in Release Build with Whole Module Optimization  

**Issue Description:**

When running with Whole Module Optimisation, a subclassed object is initialized as it's parent. I've only seen it happen once, but I created a project to demonstrate it.

<https://github.com/TimMumsnet/TestChatApp.git>

If you run the project on release configuration, a crash will occur because of the bug.

**Comment by AnthonyLatsis** [comment]
Closing because the issue is very old and the reproduction is no longer accessible.
