### ISSUE TITLE
[SR-1197] Single-expression closures with variadic arguments crashes the compiler

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43805]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1197      |
   |Radar             | None         |
   |Original Reporter | dfrib (JIRA User)      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Swift 3.0 (Xcode 8.0, OS X 10.11)  
Swift 3.0-release (IBM Sandbox)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CompilerCrash, TypeChecker        |
   |Assignee          | adminXAX (JIRA)      |
   |Priority          | Medium      |

   md5: 86589aa4bf645d7d5105a7c0a228867f

  </details>

**Issue Description:**

If attempting to compile a program with a single-expression closure containing variadic arguments, the compiler crashes, unless explicitly including the (variadic) argument type in the closure

```swift
// Bug: crashes
let a: (Int...) -> () = { (args) in print(args) }
 
// Workaround: explicitly state argument type
let b: (Int...) -> () = { (args: Int...) in print(args) }
 
// Workaround: extend to more than one expression in the closure
let c: (Int...) -> () = { (args) in (); print(args) }
```

The crash stack trace seems to be similar to the crash described in the resolved bug report SR-7.

```
.../llvm/include/llvm/Support/Casting.h:237: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = swift::TupleType, Y = swift::TypeBase]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
...
```

Stack trace from IBM Sandbox: Swift version 3.0-release.

For additional details, see [the following SO thread](http://stackoverflow.com/a/36511231/4573247).

**Comment by AnthonyLatsis** [comment]
This works in Swift 5.7.2.
