### ISSUE TITLE
[SR-1272] Use of UnicodeScalarView on a literal String created by interpolation seem to create a view without actual backing String in the memory

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#43880]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1272      |
   |Radar             | None         |
   |Original Reporter | courteouselk (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 3.0-dev (LLVM 752e1430fc, Clang 3987718dae, Swift 36739f7b57)  
Target: x86_64-unknown-linux-gnu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 19d5bdbe0822b79a3293ad1f2e13188c

  </details>

**Issue Description:**

Use of UnicodeScalarView on a literal String created by interpolation seem to create a view without actual backing String in the memory.

E.g. see the snippet below. The assert is not supposed to fail. Also, the printed result string shows some bogus characters (apparently whatever happens to be in the given memory region).

``` java
let inputString = "Lorem ipsum dolor sit amet..."
var iterator = "\(inputString)".unicodeScalars.makeIterator()
var scalars = String.UnicodeScalarView()
scalars.append(contentsOf: IteratorSequence(iterator))
let outputString = String(scalars)

print(inputString, outputString, separator: "\n")
// Lorem ipsum dolor sit amet...
// H«Y  @x«Y  r sit amet...

assert(inputString == outputString)
// assertion failed
```

**Comment by Azoy** [comment]
This has been fixed.
