### ISSUE TITLE
[SR-1507] String should have {{indices}} property?

### ISSUE THREAD

**Issue by ddunbar** [apple/swift#44116]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1507      |
   |Radar             | None         |
   |Original Reporter | @ddunbar      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e6307b831ec685caf4f8e34dc469025a

  </details>

**Issue Description:**

It is surprising that String does not have an `indices` property when it has `startIndex` and `subscript`, for example.

**Comment by glessard** [comment]
There is a slight usability gotcha here, as noted by @mattneub. We do expect the type `Collection.Indices` to be able to supply the valid indices, but the range by itself cannot in the case of `String` (and `Collection` in general,) thus the reliance on the `DefaultIndices` type. It would be easy to have a `Range` initializer that takes a `DefaultIndices` instance, or to add a `range: Range` computed property on `DefaultIndices`. Either of these would require a small evolution proposal.
