### ISSUE TITLE
[SR-1712] "Generic parameter could not be inferred"

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#44321]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1712      |
   |Radar             | None         |
   |Original Reporter | swillits (JIRA User)      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Xcode 7.3.1 playground

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 88ef42577c91d6188a46a376a3614c08

  </details>

**Issue Description:**

The compiler in this case can't correctly infer the type of the second parameter even though it's identical to the first parameter.

``` java

class StrokeOp : NSOperation, ColorHoldingOperation {
    var color: NSColor = NSColor.redColor()
}


class FillOp : NSOperation, ColorHoldingOperation {
    var color: NSColor = NSColor.redColor()
}


protocol ColorHoldingOperation {
    var color: NSColor { get set }
}


func draw<T: NSOperation where T: ColorHoldingOperation>(stroke stroke: T, fill: T) {
    ...
}


let a = StrokeOp()
let b = FillOp()
draw(stroke: a, fill: b) // Generic parameter 'T' could not be inferred
```

If "a" is used as the value for the fill parameter instead of "b" it compiles correctly.

If "draw" has separate but identical type restrictions for the second parameter, it also compiles.

``` java
func draw<T: NSOperation, U: NSOperation where T: ColorHoldingOperation, U: ColorHoldingOperation>(stroke stroke: T, fill: U) {
    ...
}
```

This seems to be a bug that the original case does not compile.

**Comment by LucianoPAlmeida** [comment]
Auditing some of those old issues to see if they are still relevant, now the compiler produces a better message for this `conflicting arguments to generic parameter 'T' ('StrokeOp' vs. 'FillOp')`. So I think we can close this, feel free to reopen if you still think there is still something to be discussed.
