### ISSUE TITLE
[SR-1812] HashTable init error: "Generic parameter ObjectType could not be inferred"

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#44421]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1812      |
   |Radar             | None         |
   |Original Reporter | brett (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 3 / Xcode 8 beta 1 (8S128d)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 307de2e06433bb33c9405df667523633

  </details>

**Issue Description:**

In Swift 3, Xcode 8 gives a buildtime error "Generic parameter 'ObjectType' could not be inferred" when initializing the HashTable class, both through \`init()\` and through \`weakObjects()\`.

``` java
var hashes = HashTable.weakObjects()
```

NSHashTable worked correctly in Swift 2.2.

**Comment by LucianoPAlmeida** [comment]
Auditing some of those old issues to see if they are still relevant, this seems to be fixed so I think we can close. Feel free to reopen if you still think there is still something to be discussed.
