### ISSUE TITLE
[SR-1834] strange compilation error

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#44443]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1834      |
   |Radar             | None         |
   |Original Reporter | VladimirS (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

IBM Swift Sandbox  
Swift Ver. 3.0 (Jun 6, 2016)  
Target: x86_64-ubuntu-linux-gnu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 20812fa1fc8126fe7e5b31e9d5e21b04

  </details>

**Issue Description:**

If I have this code, it compiles without errors:

``` none
    func group<I: Equatable>(i: I) {
        var groups = [(key:I, value:Int)]()
        groups.append((key: i, value: 1))
            
        if groups[0].key == i {
            print("Yes")
        }
    }
```

But if I remove ": Equatable" from declaration, I got strange error :

    ERROR at line 16, col 18: cannot subscript a value of type 'inout [(key: I, value: Int)]' (aka 'inout Array<(key: I, value: Int)>')
            if groups[0].key == i {
               ~~~~~~^

I.e. error appears for this code:

``` none
    func group2<I>(i: I) {
        var groups = [(key:I, value:Int)]()
        
        groups.append((key: i, value: 1))

        if groups[0].key == i {
            print("Yes")
        }
        
    }
```

I believe compiler produces wrong description of the error and it is a bug.

**Comment by LucianoPAlmeida** [comment]
Auditing some of those old typechecker issues to see if they are still relevant, this seems to be fixed compiler now produces `referencing operator function '==' on 'Equatable' requires that 'I' conform to 'Equatable'` so I think we can close. Feel free to reopen if you still think there is still something to be discussed.
