### ISSUE TITLE
[SR-2063] Binary operator '||' cannot be applied error when using short syntax for enum

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#44672]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2063      |
   |Radar             | None         |
   |Original Reporter | sofacoder (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 643294ba9d3d7b88981d16881fad8cda

  </details>

**Issue Description:**

The following code creates the error "Binary operator '\|\|' cannot be applied to two 'Bool' operands"

``` java
@objc public enum TestEnum: Int
{
    case First
    case Second
}

public class TestClass
{
    public static func demoProblem()
    {
        let number = 1
        let test = true || number == .First.rawValue // error!
        print(test)
    }
}
```

if the line with the '\|\|' operand is change in the following way, everything works fine.

``` java
        let test = true || number == TestEnum.First.rawValue
```

This is probably because the expression `.First.rawValue` is ambiguous, but then the compiler should say so. The current error is misleading.

Tested with: Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)

**Comment by AnthonyLatsis** [comment]
The error now says `type 'Int' has no member 'First'`, which I believe is enough of an improvement to close this.
