### ISSUE TITLE
[SR-2095] Deprecated generic type constraint emits triplicated warnings

### ISSUE THREAD

**Issue by 41412bb9-c79a-4f5a-8a7f-383cb40aa74b** [apple/swift#44703]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2095      |
   |Radar             | None         |
   |Original Reporter | @rintaro      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0fe09e78e0ef94bf7c6604b2c7c8beb7

  </details>

**Issue Description:**

Compiling

``` java
@available(*, deprecated) protocol Bar {}
func foo<T : Bar>(_: T) {}
```

emits

``` java
test4.swift:2:14: warning: 'Bar' is deprecated
func foo<T : Bar>(_: T) {}
             ^
test4.swift:2:14: warning: 'Bar' is deprecated
func foo<T : Bar>(_: T) {}
             ^
test4.swift:2:14: warning: 'Bar' is deprecated
func foo<T : Bar>(_: T) {}
             ^
```

**Comment by gregomni** [comment]
And in only 6 years we are down to one!
```
[7:21:24] toon:Swift $ ./build/Ninja-ReleaseAssert+swift-DebugAssert/swift-macosx-arm64/bin/swiftc -typecheck warn.swift   
warn.swift:2:14: warning: 'Bar' is deprecated
1 | @available(*, deprecated) protocol Bar {}
2 | func foo<T : Bar>(_: T) {}
  |              `- warning: 'Bar' is deprecated
3 |
