### ISSUE TITLE
[SR-2145] Incorrect fix-it application when correcting optionals as booleans in a ternary in a lazy-var initializer

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#44753]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2145      |
   |Radar             | None         |
   |Original Reporter | fbartho (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

-   Xcode: Version 8.0 beta 3 (8S174q)

-   Commandline tools: Xcode 8.0 (8S174q)

-   macOS: 10.11.6 (15G31)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, StarterBug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c713c996341946e49c76cdb770caa2f1

  </details>

**Issue Description:**

1\. Write a simple class that has optional member vars.  
2. Add a lazy var, and prepare an initializer for a lazy member variable.  
Example:

``` java
class Original {
    var opt1: String? = nil
    var opt2: String? = nil
    enum Foo : String {
        case unknown
        case one
        case two
    }
    lazy var type: Foo = {
        return self.opt1 ? .one
            : self.opt2 ? .two
            : .unknown
    }()
}
```

3\. Notice that there's a compile error with a fix-it on the return line suggesting to test for != nil instead  
4. Click the fix-it to apply the suggested correction:  
This produces the following output:

``` java
    lazy var type: Foo = ({
        return self.opt1 ? .one
            : self.opt2 ? .two
            : .unknown
        }() != nil) /// Now a compiler error highlighting this line
```

Expected Result:

``` java
    lazy var type: Foo = {
        return (nil != self.opt1) ? .one
            : (nil != self.opt2) ? .two
            : .unknown
    }()
```

Reproduces in an iOS project & in a playground

**Comment by gregomni** [comment]
Xcode 15.4: 

- Correctly figures out Foo's enum cases (i.e. "new" bug in the last comment is fixed).
- Fixits for the `!= nil` are still in the right places (i.e. the original bug is still fixed).
