### ISSUE TITLE
[SR-2152] @availability: Adding or inferring @noescape/@escaping attribute doesn't produce FIXIT

### ISSUE THREAD

**Issue by 177d8476-2756-4152-91d7-984f74d3896c** [apple/swift#44760]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2152      |
   |Radar             | None         |
   |Original Reporter | @milseman      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c1dc6f466a7678780e3f0a3019a5c934

  </details>

**Issue Description:**

From attr_availability.swift:

    @available(*, unavailable, renamed: "Int.foo(self:execute:)")
    func trailingClosure(_ value: Int, fn: () -> Void) {} // expected-note {{here}}
    ...
      trailingClosure(0) {} // expected-error {{'trailingClosure(_:fn:)' has been replaced by instance method 'Int.foo(execute:)'}} {{3-18=0.foo}} {{19-20=}}

But, if we add a @noescape, or @escaping, the FIXIT is no longer generated:

    @available(*, unavailable, renamed: "Int.foo(self:execute:)")
    func trailingClosure(_ value: Int, fn: @noescape () -> Void) {} // expected-note {{here}}
    ...
      trailingClosure(0) {} // expected-error {{'trailingClosure(_:fn:)' has been replaced by instance method 'Int.foo(execute:)'}} {{3-18=0.foo}} // NO FIXIT HERE

**Comment by gregomni** [comment]
Xcode 14.5:

Fixit is now generated with `@escaping` (`@noescape` is now an invalid attribute).
