### ISSUE TITLE
[SR-2295] wrong error message "'super.init' cannot be called outside of an initializer" when calling non-public superclass initializer

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#44902]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2295      |
   |Radar             | None         |
   |Original Reporter | comex (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 3.0-dev (LLVM 3a878c6fdb, Clang 4ca9e01a7c, Swift 2ef0a8fdcb)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c55b61471569d5cc25dc7f80e596bc31

  </details>

**Issue Description:**

a.swift:

``` java
open class A {
    init() {}
}
```

b.swift:

``` java
import a
class B: A {
    init(foo: Int32) {
        super.init()
    }
}
```

Compile:  
`swiftc -emit-module a.swift && swiftc -I. b.swift`

Results in:

``` java
b.swift:4:9: error: 'super.init' cannot be called outside of an initializer
        super.init()
```

But the call *is* from an initializer. The actual issue is that A's init is not public, and marking it public causes compilation to succeed.

**Comment by gregomni** [comment]
Fixed in 5.10:

```
b.swift:4:15: error: 'A' initializer is inaccessible due to 'internal' protection level
        super.init()
              ^~~~
a.A (internal):2:14: note: 'init()' declared here
    internal init()
             ^
```
