### ISSUE TITLE
[SR-2501] Confusing error message about inout argument

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#45106]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2501      |
   |Radar             | None         |
   |Original Reporter | rnikander (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 8, beta 6, Swift 3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: fc534b72d2c88f282cb53409cbf355b2

  </details>

**relates to**:  
* [SR-7543](https://bugs.swift.org/browse/SR-7543) diagnostics behave incorrectly when passing parameter as inout argument in closure  

**Issue Description:**

The following code compiles and runs:

``` java
struct A {
    var x: Int
}
var a = A(x: 123)
let result = withUnsafePointer(to: &a) {
    print("ptr is \($0)")
    // return 1
}
print("result is \(result)")
```

But, if you uncomment that `return 1` line, the compile fails. It highlights the `&a` and says: *Cannot pass immutable value of type 'inout A' as inout argument.*

It seems like the type checking failed and produced a misleading error message.

**Comment by gregomni** [comment]
Swift 5.10, typechecks and compiles correctly
