### ISSUE TITLE
[SR-2900] binary operator `==` cannot be applied to two MyEnum operands

### ISSUE THREAD

**Issue by mattneub** [apple/swift#45494]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2900      |
   |Radar             | None         |
   |Original Reporter | @mattneub      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 8. Swift 3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 4da3829a65b5e5dc537fe5c501b942aa

  </details>

**Issue Description:**

```swift
enum WeatherType {
    case cloudy(coverage: Int)
    case sunny
    case windy
}
let w = WeatherType.sunny
if w == .sunny {} // error
if WeatherType.sunny == w {} // error
```

This seems unnecessarily severe. Use of `==` with enum instances is a natural convenience; in fact, it's kind of the point of enums. Telling me I can't do it just because some case has an associated value is a bit rough.

**Comment by AnthonyLatsis** [comment]
This is SE-0185.
