### ISSUE TITLE
[SR-2939] False/misleading diagnostic with incorrectly typed CGFloat expression

### ISSUE THREAD

**Issue by sharplet** [apple/swift#45533]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2939      |
   |Radar             | None         |
   |Original Reporter | @sharplet      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961678-658d8860-4c93-42c0-950d-1d78c66daf5e.gz)

      
<details>
  <summary>Environment</summary>

Xcode Version 8.1 beta (8T46g)  
Apple Swift version 3.0.1 (swiftlang-800.0.56 clang-800.0.42)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 270e2410a3df22bcf0a8270509b0c5ca

  </details>

**Issue Description:**

Given this program:

``` swift
import struct QuartzCore.CGFloat

let foo: CGFloat = 1
let bar: CGFloat = 2
let foobar: Int = foo + bar
print(foobar)
```

We get the following diagnostic:

``` java
$ xcrun -sdk macosx swiftc sure_it_can.swift
sure_it_can.swift:5:23: error: binary operator '+' cannot be applied to two 'CGFloat' operands
let foobar: Int = foo + bar
                  ~~~ ^ ~~~
sure_it_can.swift:5:23: note: expected an argument list of type '(Int, Int)'
let foobar: Int = foo + bar
                      ^
```

I've attached an image of what it looks like in Xcode. In a more complicated expression like a closure, it's baffling, because the extra note that hints as to what is really going on is hidden unless you expand the diagnostic in the Issues navigator.

Even though the hint is useful in working out where the types are mismatched, ultimately the statement "Binary operator '+' cannot be applied to two 'CGFloat' operands" is still false.

**Comment by gregomni** [comment]
Swift 5.10 much better diagnostic:
```
cgfloat.swift:5:23: error: cannot convert value of type 'CGFloat' to specified type 'Int'
let foobar: Int = foo + bar
                  ~~~~^~~~~
                  Int(     )
```
