### ISSUE TITLE
[SR-3050] enum cases should be enumerable

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#45640]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3050      |
   |Radar             | rdar://problem/28952398         |
   |Original Reporter | russ (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Compiler    |
   |Labels            | Improvement, Reflection        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: abaa7fad97302a7f478a955d30d3dd52

  </details>

**relates to**:  
* [SR-30](https://bugs.swift.org/browse/SR-30) Enumerations could have a "allValues" property  

**Issue Description:**

Swift should be able to enumerate the cases of an enum. The machinery appears to be there, the case mirrors just need to be returned as children from the metatype Mirror. (Case mirrors already allow you to enumerate associated values as children.)

**Comment by tshortli** [comment]
This was [SE-0194](https://github.com/apple/swift-evolution/blob/master/proposals/0194-derived-collection-of-enum-cases.md).
