### ISSUE TITLE
[SR-3062] Ambiguous selector in Swift 3 for CoreBluetooth delegate methods

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#45652]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3062      |
   |Radar             | None         |
   |Original Reporter | Julien Coudsi (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961716-61d7889d-3565-4798-8c71-ebf210fa53b4.gz)

      
<details>
  <summary>Environment</summary>

Xcode 8.1, Swift 3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 36322bb25de0649b7703eec4d6a684e0

  </details>

**Issue Description:**

I need to declare a selector on CBPeripheralDelegate functions, for example :

``` java
func peripheral(peripheral: CBPeripheral, didUpdateValueForCharacteristic characteristic: CBCharacteristic, error: NSError?)
```

In swift3, it is renamed to :

peripheral(\_: didUpdateValueFor:error), and it is same as the func peripheral(peripheral: CBPeripheral, didUpdateValueForDescriptor descriptor: CBDescriptor, error: NSError?)

So, when I try to define a selector like this :

``` java
#selector(CBPeripheralDelegate.peripheral(_:didUpdateValueFor:error:))
```

It will cause a compile error: ambiguous use.

So I try to define with the parameters types :

``` java
#selector(((CBPeripheralDelegate.peripheral(_:didUpdateValueFor:error:)) as (CBPeripheralDelegate) -> (CBPeripheral, CBCharacteristic, NSError?) -> Void)
```

I try also :

``` java
#selector(((CBPeripheralDelegate.peripheral(_:didUpdateValueFor:error:)) as (CBPeripheralDelegate) -> (CBPeripheral, CBCharacteristic, NSError) -> Void)
```

But it failed either.

**Comment by freak4pc** [comment]
Sorry for the huge bump but seems like this just became an issue again in Xcode 14. Should I just open a new bug for it?

The workaround no longer works, too.

![image](https://user-images.githubusercontent.com/605076/172306714-0418bc12-ff23-4332-9eeb-f9faf749b87a.png)

**Comment by kennyevo** [comment]
> Sorry for the huge bump but seems like this just became an issue again in Xcode 14. Should I just open a new bug for it?
> 
> The workaround no longer works, too.
> 
> ![image](https://user-images.githubusercontent.com/605076/172306714-0418bc12-ff23-4332-9eeb-f9faf749b87a.png)

Trying to figure out the same issue, let me know if you find a workaround :D

**Comment by r-peck** [comment]
@freak4pc @kennyevo It looks like getting the function as a value for an optional protocol method changed from being an optional functional value to being a non-optional function that takes the instance and returns the instance function as an optional, so the position of the parentheses has to change. The following compiles for me (previous version shown commented out for comparison):

```
static let decidePolicyNavigationResponse: Selector = 
// #selector(WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:) as ((WKNavigationDelegate) -> (WKWebView, WKNavigationResponse, @escaping (WKNavigationResponsePolicy) -> Void) -> Void)?)
   #selector(WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:) as (WKNavigationDelegate) -> ((WKWebView, WKNavigationResponse, @escaping (WKNavigationResponsePolicy) -> Void) -> Void)?)
static let decidePolicyNavigationAction: Selector = 
// #selector(WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:) as ((WKNavigationDelegate) -> (WKWebView, WKNavigationAction, @escaping(WKNavigationActionPolicy) -> Void) -> Void)?)
   #selector(WKNavigationDelegate.webView(_:decidePolicyFor:decisionHandler:) as (WKNavigationDelegate) -> ((WKWebView, WKNavigationAction, @escaping(WKNavigationActionPolicy) -> Void) -> Void)?)
```

**Comment by AnthonyLatsis** [comment]
> It looks like getting the function as a value for an optional protocol method changed from being an optional function value to being a non-optional function that takes the instance and returns the instance function as an optional

Yes, this is mentioned in the change log. Unbound references to `optional` protocol methods should be of a non-optional function type that takes an instance and returns an optional function type, i.e. `(P) -> ((args) -> result)?`. It was a bug that the *entire* type was getting wrapped in an optional. [Here's](https://twitter.com/davedelong/status/1508994407323738113?s=21&t=Jh1UKSXxz0hPq1160UkSKA) a related twitter thread.

**Comment by AnthonyLatsis** [comment]
> So would this have to live inside a compiler directive?

You would have to use a `#if swift(>=5.7)` branch if you also need it to compile with older compilers. Where do these declarations come from?

**Comment by freak4pc** [comment]
There are a few open source projects that use this, we also have some internal stuff that uses it and we won't be moving everyone to Xcode 14 immediately, for obvious reasons :) 

Thanks you for the quick response 🙏

**Comment by AnthonyLatsis** [comment]
Sorry for the trouble! Apparently a selector is the only place where such a method ref did not cause a compiler crash, and the Objective-C runtime seemed to just played along. Was not expecting this to become a source compat issue, but since compelled selector disambiguation is a fairly narrow case, I believe the consistency in how we treat these refs across different expression contexts is for the best in the log term.

**Comment by diyxiaoshitou** [comment]
> Sorry for the huge bump but seems like this just became an issue again in Xcode 14. Should I just open a new bug for it?
> 
> The workaround no longer works, too.
> 
> ![image](https://user-images.githubusercontent.com/605076/172306714-0418bc12-ff23-4332-9eeb-f9faf749b87a.png)

有没有解决方案啊

**Comment by jabdahandb** [comment]
update to xcode14 and getting this error.. need help...
![image](https://user-images.githubusercontent.com/98383435/190059065-f491c794-7a1f-4038-9834-17b519a123e1.png)

**Comment by AnthonyLatsis** [comment]
In Swift 5.7, the type of an unbound reference to an `optional` method was fixed and changed from `((x) -> (y) -> z)?` to 
`(x) -> ((y) -> z)?`. Please read earlier comments for more details.

**Comment by AnthonyLatsis** [comment]
I’m closing this because the disambiguation problem originally reported turned out to be a matter of spelling the types correctly rather than a missing feature. I’ve extracted the error quality bug that was found along the way into a fresh issue: #63834.
