### ISSUE TITLE
[SR-3190] Misleading error message: cannot subscript a value of type 'inout [PathPoint]' with optional field

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#45778]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3190      |
   |Radar             | None         |
   |Original Reporter | rmann (JIRA User)      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961750-f7d34ada-0d1f-4738-bad6-185c190a795e.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Improvement, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1e7073afd5cd3139cc5bda61b452b44c

  </details>

**Issue Description:**

The attached playground has the following code, and gets this error on the last line. The real problem is that anchorPt is Optional. This is in Xcode 8.1.

**Comment by gregomni** [comment]
Swift 5.10. The error now specifically asks to unwrap the optional and offers a fixit to force-unwrap:
```
point.swift:21:11: error: value of optional type 'CGPoint?' must be unwrapped to a value of type 'CGPoint'
points[0].anchorPt += dv
          ^
point.swift:21:11: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
points[0].anchorPt += dv
          ^
                  !
```
Seems fixed!
