### ISSUE TITLE
[SR-3251] Unhelpful error message for an unspecialized generic init

### ISSUE THREAD

**Issue by natecook1000** [apple/swift#45839]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3251      |
   |Radar             | None         |
   |Original Reporter | @natecook1000      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift/master at ccc050576c85a7c7e2fb85e8618724796d582d81  
Xcode 8.2 beta (8C30a)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 97f05186f9ebaddf911d94c47408daea

  </details>

**Issue Description:**

If I try to create a new dictionary using the following code:

``` java
let a = [1, 2, 3, 4, 5]
let b = Dictionary(minimumCapacity: a.count)
```

I get unhelpful error messages:

``` java
error: ambiguous reference to member 'count'
let b = Dictionary(minimumCapacity: a.count)
                                    ^
Swift.Array<Element>:66:16: note: found this candidate
    public var count: Int { get }
               ^
Swift.Collection:47:16: note: found this candidate
    public var count: Self.IndexDistance { get }
               ^
```

If I pass an integer literal instead or just use the plain init(), I get a much nicer error message:

``` java
error: generic parameter 'Key' could not be inferred
let b = Dictionary(minimumCapacity: 5)
        ^
...
```

**Comment by gregomni** [comment]
Swift 5.10 correct errors:
```
gen.swift:2:9: error: generic parameter 'Key' could not be inferred
let b = Dictionary(minimumCapacity: a.count)
        ^
gen.swift:2:9: error: generic parameter 'Value' could not be inferred
let b = Dictionary(minimumCapacity: a.count)
        ^
gen.swift:2:9: note: explicitly specify the generic arguments to fix this issue
let b = Dictionary(minimumCapacity: a.count)
        ^
                  <<#Key: Hashable#>, Any>
```

```
summary.swift:10:54: error: missing argument label 'actual:' in call
    bar(summary: (1 == files.count) ? .one : .notOne({files.count}))
                                                     ^
                                                     actual: 
```

```
hash.swift:6:13: error: generic parameter 'T' could not be inferred
let table = HashTable(capacity: array.count) // Ambiguous reference to member 'count
            ^
hash.swift:1:17: note: 'T' declared as parameter to type 'HashTable'
class HashTable<T> {
                ^
hash.swift:6:13: note: explicitly specify the generic arguments to fix this issue
let table = HashTable(capacity: array.count) // Ambiguous reference to member 'count
            ^
                     <Any>
```
