### ISSUE TITLE
[SR-3397] Various Index types should be nested inside their Collection types

### ISSUE THREAD

**Issue by airspeedswift** [apple/swift#45985]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3397      |
   |Radar             | rdar://problem/31414906         |
   |Original Reporter | @airspeedswift      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, AffectsABI, StarterProposal, swift-evolution-proposal-needed        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3c83d1b6fbe2723eae39af2904d67ffe

  </details>

**Issue Description:**

A number of collections declare a custom index type. Due to historical compiler constraints on nested generics, these are declared outside their collection types. This restriction is now lifted and they should be moved to be nested types.

For example, `DictionaryIndex` should be `Dictionary.Index`, and `ClosedRangeIndex` should be `ClosedRange.Index`.

For Swift 3 compatibility reasons, deprecated typealiases should be created. Currently, these will not be extensible if anyone is doing this (unlikely but possible), so compiler work to allow this would be required for true backwards compatibility.

**Comment by AnthonyLatsis** [comment]
Regarding the ones mentioned here:
* `DictionaryIterator` was nested [here](https://github.com/apple/swift/pull/18181/commits/3f9cd3fb4bf3d6a47401f80bdc31ecfa16d13a81#diff-b0bf543a9e080cc5a08141890a943495c1fa2c6b321bc13e6cd5cb16f9c09c6aR4387)
* `DictionaryIndex` was nested [here](https://github.com/apple/swift/pull/5600/commits/9a4c0488bacb6c7d650a29e08707b69d267c67cb#diff-00867d364e31963c9640faac6037d6336e46611ebb39b10b05814ebdb2bb73b1R4784)
* `Zip2Iterator` was nested [here](https://github.com/apple/swift/pull/13489/commits/76e8579b5f2cd16c60072e987682b9ea57aa877d#diff-b049e39267145c5d16814ed6f9d1946f3f6d5d21cb9ec4ee13b3f72444a2ccf6R157)
* `ClosedRangeIndex` was nested [here](https://github.com/apple/swift/pull/13342/commits/086414b496431359f2f976e3b267961735799dc0#diff-709a05dda43bb73ed187f97259f9a5ff3167e6421fd672c396b30961ce5ebb31R476)
* `StrideToIterator` and e.g. `StrideThroughIterator` are still top-level and there is little if anything we can do about that at this point.

It seems none of these changes went through evolution though, so I’m dropping the label.

@airspeedswift Why were `DictionaryIterator`, `SetIterator`, etc. not deprecated and moved to migration support like others?
