### ISSUE TITLE
[SR-3412] Use of closure inside withUnsafeBytes considered escaping

### ISSUE THREAD

**Issue by karwa** [apple/swift#46000]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3412      |
   |Radar             | None         |
   |Original Reporter | @karwa      |
   |Type              | Improvement    |

<details>
  <summary>Environment</summary>

Swift 7493fee618e0a74eb6cf726745c480391f237635 (7th Dec, 2016)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Improvement, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1155e21d26d9281209fb4692fe100eca

  </details>

**Issue Description:**

The following code fails to compile:

```swift
extension DispatchData {

  func asFoundationData<T>(execute: (Data) throws -> T) rethrows -> T {

    //FIXME: SWIFT(SR-3097) - DispatchData.withUnsafeBytes crashes when empty.
    guard isEmpty == false else {
      return try execute(Data())
    }

    return try withUnsafeBytes { (ptr: UnsafePointer<Int8>) -> Void in
      let foundationData = Data(bytesNoCopy: UnsafeMutableRawPointer(mutating: ptr), count: count, deallocator: .none)
      return try execute(foundationData) //< ERROR: Closure use of non-escaping parameter 'execute' may allow it to escape
    }
  }
}
```

The error in this case has nothing at all to do with the problem: the issue is that execute returns a `T` but the withUnsafeBytes closure is annotated as returning a `Void`.

**Comment by gregomni** [comment]
Swift 5.10, these errors look good to me:
```
dispatch.swift:12:16: error: cannot convert return expression of type 'Void' to return type 'T'
    return try withUnsafeBytes { (ptr: UnsafePointer<Int8>) -> Void in
           ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dispatch.swift:14:18: error: cannot convert value of type 'T' to closure result type 'Void'
      return try execute(foundationData) 
             ~~~~^~~~~~~~~~~~~~~~~~~~~~~
                                         as! Void
```

**Comment by AnthonyLatsis** [comment]
I reckon this deserves to be closed off with the addition of a validation test.
