### ISSUE TITLE
[SR-3470] Compiler displays wrong error message when calling a constructor to cause a type mismatch

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#46058]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3470      |
   |Radar             | None         |
   |Original Reporter | Sweeper (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961798-acbee842-94fb-46d0-bc54-aeadfe8795f0.gz)

      
<details>
  <summary>Environment</summary>

Xcode 8.1

macOS Sierra 10.12

Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 01e588e13a060ad512276df0a96a822f

  </details>

**Issue Description:**

If you compile the code in the attachment, you will see two different compiler error messages on line 6 and 7.

On line 6,

— *Cannot convert value of type 'A' to specified type 'Void' (aka '()')*

On line 7,

— *Cannot invoke initializer for type 'A' with an argument list of type '(x: Int, y: Double)'*

But in theory, the real problem of the two lines are the same - assigning `A` to `Void`. I expected the messages to both be

— *Cannot convert value of type 'A' to specified type 'Void' (aka '()')*

**Comment by gregomni** [comment]
Swift 5.10, this is fixed:
```
bug.swift:6:15: error: cannot convert value of type 'A' to specified type 'Void'
let a: Void = A(x: 1, y: 2)
              ^~~~~~~~~~~~~
bug.swift:7:15: error: cannot convert value of type 'A' to specified type 'Void'
let b: Void = A(x: 1, y: 2.0)
              ^~~~~~~~~~~~~~~
```
