### ISSUE TITLE
[SR-3631] Introduce ContiguouslyStored protocol and kill ArraySlice type

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#46216]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3631      |
   |Radar             | rdar://problem/30541077         |
   |Original Reporter | @dabrahams      |
   |Type              | Improvement    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961835-16c81216-05b1-4765-8dcb-0567f07f08a5.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Improvement, AffectsABI, StarterProposal        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0b822da3966dafcaf6527038fc805b6a

  </details>

**relates to**:  
* [SR-3633](https://bugs.swift.org/browse/SR-3633) Support for segmented data structures  
* [SR-3087](https://bugs.swift.org/browse/SR-3087) No way to arbitrarily initialise an Array's storage  

**Issue Description:**

Sketch:

``` java
protocol ContiguouslyStored : RandomAccessCollection {
  func withUnsafeBufferPointer<R>(...) -> R
  mutating func withUnsafeMutableBufferPointer<R>(...) -> R
}

extension Slice : ContiguouslyStored where Base : ContiguouslyStored {
  func withUnsafeBufferPointer<R>(...) -> R { ... }
  mutating func withUnsafeMutableBufferPointer<R>(...) -> R { ... }
}

typealias ArraySlice<T> = Slice<Array<T>>
```

(This is related to <https://bugs.swift.org/browse/SR-3633>)

**Comment by AnthonyLatsis** [comment]
Closing this as partially implemented. If anyone wishes to revisit the `ArraySlice` part, please open a new issue and start a discussion on the [forums](https://forums.swift.org/c/evolution/discuss).
