### ISSUE TITLE
[SR-3846] Misleading error when return statement returns a Set instead of Array

### ISSUE THREAD

**Issue by aciidgh** [apple/swift#46431]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3846      |
   |Radar             | None         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3a041970c52b5e8cffd0ffc7a883ddc1

  </details>

**Issue Description:**

``` java
extension Array where Element: Hashable {
    func findDuplicates(_ other: Array<Element>) -> [Element] {
        return Set(self).intersection(Set(other))
    }
}

main.swift:3:39: error: cannot convert value of type 'Set<Element>' to expected argument type 'Set<(_)>' (aka 'Set<_>')
        return Set(self).intersection(Set(other))
                                      ^~~~~~~~~~
                                                 as! Set<(_)>
```

PS:  
"return Array(Set(self).intersection(Set(other)))" or changing return type to "Set\<Element\>" works.

**Comment by gregomni** [comment]
Swift 5.10 error message now better and refers to the correct expression:
```
array.swift:3:26: error: cannot convert return expression of type 'Set<Element>' to return type '[Element]'
        return Set(self).intersection(Set(other))
               ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
```
