### ISSUE TITLE
[SR-3916] Light-weight preconditions on (protocol) method parameters

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#46501]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3916      |
   |Radar             | None         |
   |Original Reporter | Reitzig (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e627ff48c34c472ba7d52c1a3b9736ad

  </details>

**Issue Description:**

Say I have a protocol like this:

**Comment by AnthonyLatsis** [comment]
Closing because the description of this feature seems to have been lost during the transition from Jira.
