### ISSUE TITLE
[SR-3958] Warn when trap-on-overflow operators are used in a `hashValue` implementation

### ISSUE THREAD

**Issue by jckarter** [apple/swift#46543]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3958      |
   |Radar             | None         |
   |Original Reporter | @jckarter      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: aa877ba8e87c5cd1c396a50e2df96512

  </details>

**Issue Description:**

It's a common mistake to use trapping arithmetic in `hashValue` implementations by accident. We can at least warn about it in obvious cases:

```swift
struct AwesomeKey: Hashable {
  var x: Int, y: Int, z: Int

  // warning: non-wrapping arithmetic '*' and '+' used in 'hashValue';
  // did you mean '&*' and '&+'?
  var hashValue: Int { return x * 199 + y * 13 + z }
}
```

**Comment by gregomni** [comment]
Probably obsoleted by the introduction of `Hasher` and deprecation of directly computing `hashValue`?

**Comment by AnthonyLatsis** [comment]
Yeah — SE-0206.
