### ISSUE TITLE
[SR-3968] Shebang #! not handled in round-trip tests

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46553]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3968      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 6c04b0b5f6b91afdf6874e501abf3337

  </details>

**Issue Description:**

Whoops - forgot this special case.

**Comment by AnthonyLatsis** [comment]
Closing because `libSyntax` is [no more](https://github.com/apple/swift/pull/62145).
