### ISSUE TITLE
[SR-3984] Bogus "reorder argument" diagnostic

### ISSUE THREAD

**Issue by ddunbar** [apple/swift#46569]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3984      |
   |Radar             | None         |
   |Original Reporter | @ddunbar      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: caeb778cf0ac78d1d9a8dad9e7a9d99c

  </details>

**Issue Description:**

Sometimes Swift incorrectly requests re-ordering of an argument parameter when the argument parameter could never be valid – when the problem is just a typo this leads to annoying reshuffling of the parameters just because the name was misspelled, instead of pointing out the typo.

Example:

``` java
$ cat z.swift 
func f0(a: Int = 0, b: Int = 0) {}
f0(b: 1, x: 1)

$ swiftc -c z.swift 
z.swift:2:10: error: argument 'x' must precede argument 'b'
f0(b: 1, x: 1)
   ~~~~  ^~~~
   x: 1  b: 1
```

**Comment by gregomni** [comment]
Swift 5.10, fixed:
```
x.swift:2:3: error: incorrect argument labels in call (have 'b:x:', expected 'a:b:')
f0(b: 1, x: 1)
  ^~     ~
   a     b
```
