### ISSUE TITLE
[SR-3992] Add round-trip tests for fallthrough-statement

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46577]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3992      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 520a89d643aac79c669a8d93f878f087

  </details>

**Issue Description:**

Include semicolons.

**Comment by AnthonyLatsis** [comment]
Closing because `libSyntax` is [no more](https://github.com/apple/swift/pull/62145).
