### ISSUE TITLE
[SR-3994] Add round-trip tests for break-statement

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46579]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3994      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: ea545fa584530a822fe477b30efb1a05

  </details>

**Issue Description:**

Include semicolons.

**Comment by AnthonyLatsis** [comment]
Closing because `libSyntax` is [no more](https://github.com/apple/swift/pull/62145).
