### ISSUE TITLE
[SR-3993] Add round-trip tests for continue-statement

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46578]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3993      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 9bfb566e23137aa046081e2ec9b1c250

  </details>

**Issue Description:**

Include semicolons.

**Comment by AnthonyLatsis** [comment]
Closing because `libSyntax` is [no more](https://github.com/apple/swift/pull/62145).
