### ISSUE TITLE
[SR-3995] Put semicolons in Cursors and Layout

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46580]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3995      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 9faa5d22f83ed26f7c7daabbccb46407

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
