### ISSUE TITLE
[SR-4047] Reconcile setting parent pointers in the AST transformer

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46630]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4047      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 9a8b7058149c73574103444851323193

  </details>

**Issue Description:**

The `LegacyASTTransformer` populates a `lib/Syntax` → `lib/AST` mapping, which means that we will unfortunately need to force caching of child `SyntaxData` nodes, which is not ideal.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
