### ISSUE TITLE
[SR-4078] Errors about inout type mismatches should specifically mention inout invariance

### ISSUE THREAD

**Issue by jckarter** [apple/swift#46661]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4078      |
   |Radar             | None         |
   |Original Reporter | @jckarter      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1a4a17de77548a2134f1b7b75ea41f7b

  </details>

**Issue Description:**

The type checker correctly prevents you from converting an inout argument to a different type, but the error messages don't make the reason clear. For example:

```swift
class C {}
class D {}

func f1(f : @escaping (inout D) -> ()) {}

func f2(f : @escaping (inout C) -> ()) {
    f1 { f(&$0) }
}
```

says:

```
/Users/jgroff/foo.swift:7:13: error: cannot convert value of type 'D' to expected argument type 'C'
    f1 { f(&$0) }
            ^~
```

which is wrong; it should more clearly specify that `inout D` cannot be converted to `inout C` and also ideally mention **why** (an inout is both "in" and "out", so can be neither covariant nor contravariant). Other type combos are even worse. For instance:

```
/Users/jgroff/foo.swift:7:12: error: cannot pass immutable value as inout argument: implicit conversion from 'Int' to 'Any' requires a temporary
    f1 { f(&$0) }
           ^~~
```

The verbiage about "immutable values" and "requiring a temporary" is nonsense.

**Comment by gregomni** [comment]
As written, the error `cannot convert value of type 'D' to expected argument type 'C'` is right. I think the example was missing inheritence: `class D : C {}`.

Swift 5.10, this now produces a much better error: `inout argument could be set to a value with a type other than 'D'; use a value declared as type 'C' instead`
