### ISSUE TITLE
[SR-4094] Syntax Transformer: DeclRefExpr -> SymbolicReferenceExprSyntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46677]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4094      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: d3b08ad89c61488b0fa23012fc7e6d4d

  </details>

**Issue Description:**

I think we might also need to store the `<` and `>` token locations.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
