### ISSUE TITLE
[SR-4106] Implement as-pattern in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46689]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4106      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 96f76009e0103981200d3d9b3d3c01f0

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
