### ISSUE TITLE
[SR-4101] Return early if cached children are present in Syntax nodes

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46684]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4101      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 13aed5b30928c4c2786db62d5e70c8d5

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
