### ISSUE TITLE
[SR-4105] Implement is-pattern / is-cast in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46688]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4105      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 1b52417227e9c816b4699d19f7d1f41e

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
