### ISSUE TITLE
[SR-4104] Implement subscript-declaration in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46687]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4104      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: b25a3ccffbdba50068dc109f45cb44bd

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
