### ISSUE TITLE
[SR-4107] Implement initializer-declaration in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46690]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4107      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 16e416e73302bd04d431e92d9ec7f471

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
