### ISSUE TITLE
[SR-4116] Implement protocol-associated-type-declaration in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46699]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4116      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: cb8260295d828a4e2f80b54f147aee02

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
