### ISSUE TITLE
[SR-4109] Implement protocol-declaration in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46692]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4109      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 83b20d7fda538adfb4b86463fd4ba1d4

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
