### ISSUE TITLE
[SR-4115] Implement switch-case in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46698]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4115      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: 442a23d08f2038aef2b85c2d53491720

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
