### ISSUE TITLE
[SR-4113] Create an open-brace formatting prototype utilizing lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46696]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4113      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Format, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 830fd042edeeb561d97d38325dbac460

  </details>

**Issue Description:**

**Comment by AnthonyLatsis** [comment]
`libSyntax` is no more. We got [swift-syntax](https://github.com/apple/swift-syntax) and [swift-format](https://github.com/apple/swift-format) for this.
