### ISSUE TITLE
[SR-4108] Implement class-declaration in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46691]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4108      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: f40257ec07aab2fc5fb395b10dfe3b97

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
