### ISSUE TITLE
[SR-4117] Implement protocol-composition-type in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46700]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4117      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: f2e2cb08a8c7713879a16c2afee53b36

  </details>

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
