### ISSUE TITLE
[SR-4118] Implement key-path-expression in lib/Syntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46701]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4118      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: d3729ec1886e2747ed52b1db9f8a3954

  </details>

**Comment by AnthonyLatsis** [comment]
Closing because `libSyntax` is [no more](https://github.com/apple/swift/pull/62145).
