### ISSUE TITLE
[SR-4145] Make Syntax DataType, Kind, and constructors public

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46728]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4145      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: d7ba8ba13d43593fba50030ce4768b69

  </details>

**Issue Description:**

Probably too extreme to hide these and it can interfere with template instantiation for SyntaxCollection types.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
