### ISSUE TITLE
[SR-4148] Indexed access to a complex type representation

### ISSUE THREAD

**Issue by nkcsgexi** [apple/swift#46731]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4148      |
   |Radar             | None         |
   |Original Reporter | @nkcsgexi      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 5332377ec4d12158f94cc129bc84d56d

  </details>

**Issue Description:**

For syntax nodes for type repr, we should have a generic way to navigate the complexity of type repr. For instance, from a complex type repr like (C1, (C2, C3?))-\>C4, we can get the C3 by a given index chain of 0:1:1:0.

API example:  
Optional\<TypeReprSyntax\> getSubTypeRepr(ArrayRef\<unsigned\> Indices, UnfoundReason &Reason) {  
....  
}

This feature will allow us to bridge syntax tree with swift-api-digester because the later always dumps type change info in a mechanical way, for instance:

TYPE_CHANGE(REMOVE_OPTIONALITY, "objc@someUSRofAFunction", "1"/**second parameter**/, "0:1:1"/**type indices**/) // from api-digester

This tells us the second parameter of the given function should change from  
(C1, (C2, C3?))-\>C4  
to  
(C1, (C2, C3))-\>C4

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
