### ISSUE TITLE
[SR-4156] Stub out SyntaxRewriter with example in Readme

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46739]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4156      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: f24203b98597e1870edd2ecd8bb16acf

  </details>

**Issue Description:**

The example in the Readme should compile.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
