### ISSUE TITLE
[SR-4150] Remove collection-like interface on CodeBlockSyntax

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46733]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4150      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   md5: acf55b01633a474ac8ce4ab393d86bca

  </details>

**Issue Description:**

Let the `StmtListSyntax` within provide that interface.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
