### ISSUE TITLE
[SR-4157] Collect all substructure in LegacyASTTransformer

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46740]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4157      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 1fa909287a37680c11d8fc92b6c7d064

  </details>

**Sub-Tasks**:  
* [SR-4158](https://bugs.swift.org/browse/SR-4158) Don't drop dot when parsing an import declaration  

**Issue Description:**

This is predicated on

-   The parser not dropping any tokens during consumption (any bugs there would block this)

-   The LegacyASTTransformer dissecting entities into at least an Unknown\*Syntax

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
