### ISSUE TITLE
[SR-4158] Don't drop dot when parsing an import declaration

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46741]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4158      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Sub-task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Sub-task, Parser, Syntax        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 974e2eb0d9d9e5cc0dafc0ff1462d526

  </details>

**Parent-Task**:  
* [SR-4157](https://bugs.swift.org/browse/SR-4157) Collect all substructure in LegacyASTTransformer  

**Issue Description:**

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
