### ISSUE TITLE
[SR-4217] Copy DMP tests to unittests

### ISSUE THREAD

**Issue by bitjammer** [apple/swift#46800]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4217      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Task, Syntax, Test        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   

   md5: 7574b562e863cdbcbe27a47212a65e1e

  </details>

**Issue Description:**

Might be a good idea to migrate to gtest, haven't looked in detail.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
