### ISSUE TITLE
[SR-4230] Type mismatch reported as extraneous argument label

### ISSUE THREAD

**Issue by ChristopherRogers** [apple/swift#46813]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4230      |
   |Radar             | None         |
   |Original Reporter | @ChristopherRogers      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 3.0.1/Xcode 8.2.1, Swift 3.1/Xcode 8.3 beta 4 (8W143q)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0e72b0d48819cdf639d1d9ae40f4f8ae

  </details>

**Issue Description:**

``` java
var strings: [String] = ["foo", "bar"]
strings.insert(contentsOf: ["baz"], at: strings!.count - 1)
```

Expected error:  
Cannot force unwrap value of non-optional type '\[String\]'

Actual error:  
Extraneous argument label 'contentsOf:' in call

Somewhat related: SR-718

**Comment by gregomni** [comment]
Swift 5.10, correct error:
```
strings.swift:2:48: error: cannot force unwrap value of non-optional type '[String]'
strings.insert(contentsOf: ["baz"], at: strings!.count - 1)
                                        ~~~~~~~^
                                               
```
