### ISSUE TITLE
[SR-4246] Generic Parameter is Missing in Vague Error Message

### ISSUE THREAD

**Issue by 56ed3025-6cad-4bf8-b972-9c308205a0af** [apple/swift#46829]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4246      |
   |Radar             | None         |
   |Original Reporter | @palimondo      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961946-85c1ef27-45e0-48db-ace9-c636befb8079.gz)

      
<details>
  <summary>Environment</summary>

Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1bda1dd32a2bee653ddb7117169bec0e

  </details>

**Issue Description:**

Following code:

``` java
public struct ComposedSequence<Element, State> {
    var _state: State
    var _next: (inout State) -> Element?
}

func composePrefix<BaseIterator : IteratorProtocol>(_ prefix: Int, _ iterator: BaseIterator) -> ComposedSequence<BaseIterator.Element, (count: Int, iterator: BaseIterator)> {

    func _prefix(state: inout (count: Int, iterator: BaseIterator)) -> BaseIterator.Element? {
        return nil
    }
    
    // The first member in tuple is deliberatly of wrong type (String instead of Int) to force error
    return ComposedSequence(_state: ("prefix", iterator), _next: _prefix)
}
```

produces following compiler error (scroll right for the interesting part):

    GenericParameterMissingInVagueErrorMessage.swift:13:66: error: cannot convert value of type '(inout (count: Int, iterator: BaseIterator)) -> BaseIterator.Element?' to expected argument type '(inout (String, _)) -> _?'
        return ComposedSequence(_state: ("prefix", iterator), _next: _prefix)
                                                                     ^~~~~~~

Notice how the generic parameter `BaseIterator` is missing from the reported expected type:  
`(inout (String, _)) -> _?`

That type should be `(inout (String, BaseIterator)) -> BaseIterator.Element?`

**Comment by gregomni** [comment]
Swift 5.10, the produced error messages are now very good.

Original code now produces error:
```
sequence.swift:13:37: error: cannot convert return expression of type '(String, BaseIterator)' to return type '(count: Int, iterator: BaseIterator)'
    return ComposedSequence(_state: ("prefix", iterator), _next: _prefix)
                                    ^
```
And follow up code in the last comment produces error:
```
sequence2.swift:9:53: error: missing argument labels '_state:_next:' in call
        return ComposedSequence<I.Element, (Int, I)>((prefix, iterator), _prefix)
                                                    ^
                                                     _state:             _next: 
```

**Comment by AnthonyLatsis** [comment]
> ```
> sequence.swift:13:37: error: cannot convert return expression of type '(String, BaseIterator)' to return type '(count: Int, iterator: BaseIterator)'
>     return ComposedSequence(_state: ("prefix", iterator), _next: _prefix)
>                                     ^
> ```

This message is suboptimal because it refers to the argument as the return expression. Although, the message regressed in 5.6, and the original problem was completely different, so here’s the sequel: #74463.
