### ISSUE TITLE
[SR-4275] Dismal diagnostic for passing an existential to a generic function

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#46858]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4275      |
   |Radar             | None         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 76d1083157d5c3a29793785f26bf8ccb

  </details>

**Issue Description:**

``` java
protocol P {}
func f<T: P>(_: T) {}
func g(x: P) { f(x) }
```

yields:

    x.swift:3:16: error: cannot invoke 'f' with an argument list of type '(P)'
    func g(x: P) { f(x) }
                   ^
    x.swift:3:16: note: expected an argument list of type '(T)'
    func g(x: P) { f(x) }
                   ^

There is no type `(T)`, and an argument list doesn't have a type so even the way it's phrased hasn't made sense since tuple-splat died. The real problem is that instances of `P` don't conform to `P`, which is confounding enough to start with and deserves a good explanation, but at least we should accurately report it!

**Comment by xwu** [comment]
@dabrahams I guess, with implicit existential opening, this can be closed?

**Comment by gregomni** [comment]
Yep, compiles successfully now that implicit existential opening is in the compiler.

**Comment by AnthonyLatsis** [comment]
The feature is SE-0352.
