### ISSUE TITLE
[SR-4518] Remote mirrors needs to support multi-payload enums

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#47095]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4518      |
   |Radar             | rdar://31666592         |
   |Original Reporter | Jay18001 (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962010-873688fd-4a01-4e9b-ae98-ee4110b47a45.gz)

      
<details>
  <summary>Environment</summary>

I've only tested on iOS 10.3 with Xcode 8.3 on 10.12.3 (16D32)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Leak        |
   |Assignee          | @mikeash      |
   |Priority          | Medium      |

   

   md5: d6c09cb4c02ae76ce77a67ef1ead510e

  </details>

**Issue Description:**

There is a `swift_slowAlloc` leak when using an enum like the following. The leak only occurs when the second case is used in the third like `auto(estimate: .fixed(size: 10))`.

``` none
public indirect enum Enum {
case ratio(ratio: CGFloat)
 case fixed(size: CGFloat)
 case auto(estimate: Enum)
}
```

However it does not accure when the first case is used with the third like `auto(estimate: .ratio(ratio: 10))`

**Comment by slavapestov** [comment]
Looks like this was fixed in Swift 5.7.
