### ISSUE TITLE
[SR-4513] Compiler crash when `Range` incorrectly used with `BidirectionalCollection` instead of `CountableRange`

### ISSUE THREAD

**Issue by e2652f27-fdca-469d-a3e9-bf38e5bd1773** [apple/swift#47090]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4513      |
   |Radar             | None         |
   |Original Reporter | @jadengeller      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962008-31264b3a-d7eb-44bb-8317-6cfd0c1c84f6.gz)

      
<details>
  <summary>Environment</summary>

Version 8.2.1 (8C1002)  
Toolchain: Swift 3.1 Snapshot 2017-03-19 (a)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CompilerCrash, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 5445f8f68cdc39c1cfd02c8be2d54208

  </details>

**Issue Description:**

If changed to \`CountableRange\`, this compiles. The error message is bad, and the compiler crashes…

**Comment by glessard** [comment]
This works correctly with Swift 5.7.1.
