### ISSUE TITLE
[SR-4685] Can't infer associatedtypes with where clause

### ISSUE THREAD

**Issue by 41412bb9-c79a-4f5a-8a7f-383cb40aa74b** [apple/swift#47262]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4685      |
   |Radar             | rdar://problem/39040799         |
   |Original Reporter | @rintaro      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 3.1-dev (LLVM 1067090d70, Clang 5e8cb0e694, Swift f83d1a70c7)  
Target: x86_64-unknown-linux-gnu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | @DougGregor      |
   |Priority          | Medium      |

   

   md5: 3fae0cb45075895bc8535a198c649e47

  </details>

**is duplicated by**:  
* [SR-7304](https://bugs.swift.org/browse/SR-7304) typealias overriding associated type ... is better expressed as same-type constraint  

**Issue Description:**

The current master doesn't compile this.

``` java
protocol MySequence {
  associatedtype Element
  associatedtype Iterator: IteratorProtocol where Iterator.Element == Element
  func makeIterator() -> Iterator
}

struct Foo {}

struct FooIterator : IteratorProtocol {
  func next() -> Foo? { return Foo() }
}

struct FooSequence : MySequence {
  func makeIterator() -> FooIterator {
    return FooIterator()
  }
}
```

results:

``` java
test.swift:13:8: error: type 'FooSequence' does not conform to protocol 'MySequence'
struct FooSequence : MySequence {
       ^
test.swift:2:18: note: protocol requires nested type 'Element'; do you want to add it?
  associatedtype Element
                 ^
test.swift:3:18: note: protocol requires nested type 'Iterator'; do you want to add it?
  associatedtype Iterator: IteratorProtocol where Iterator.Element == Element
                 ^
```

This is basically the same structure as [PR-8939](https://github.com/apple/swift/pull/8939).

**Comment by slavapestov** [comment]
This was fixed by #70375.
