### ISSUE TITLE
[SR-4960] Missing Type Witness?

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#47537]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4960      |
   |Radar             | rdar://problem/32315429         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CompilerCrash, TypeChecker        |
   |Assignee          | @DougGregor      |
   |Priority          | Medium      |

   

   md5: 710899feedf1b4355048b385a8699bb6

  </details>

**Issue Description:**

    $ git fetch https://github.com/dabrahams/swift refs/bugs/missing-type-witness:BUG && git checkout BUG

    build-script --skip-build-ios-device --skip-build-tvos-device --skip-build-compiler-rt --debug-swift-stdlib --skip-build-benchmarks --release --swift-stdlib-assertions --swift-stdlib-build-type=Debug

    cd /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core && /usr/bin/python /Users/dave/src/s/swift/utils/line-directive @/Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/URwCj.txt -- /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./bin/swiftc -c -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -target x86_64-apple-macosx10.9 -resource-dir /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./lib/swift -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/../../../Developer/Library/Frameworks -Onone -g -D INTERNAL_CHECKS_ENABLED -I /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./lib/swift/macosx/x86_64 -module-cache-path /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./module-cache -no-link-objc-runtime -Xfrontend -enable-cow-existentials -nostdimport -parse-stdlib -module-name Swift -Xfrontend -group-info-path -Xfrontend /Users/dave/src/s/swift/stdlib/public/core/GroupInfo.json -Xfrontend -sil-serialize-all -swift-version 3 -warn-swift3-objc-inference-complete -Xllvm -sil-inline-generics -Xllvm -sil-partial-specialization -module-link-name swiftCore -force-single-frontend-invocation -Xcc -D__SWIFT_CURRENT_DYLIB=swiftCore -parse-as-library -o /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/macosx/x86_64/Swift.o @/Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/URwCj.txt
    Assertion failed: (memberType && "Missing type witness?"), function lookupMemberType, file /Users/dave/src/s/swift/lib/Sema/TypeCheckNameLookup.cpp, line 450.
    0  swift                    0x0000000107827748 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
    1  swift                    0x0000000107827df6 SignalHandler(int) + 454
    2  libsystem_platform.dylib 0x00007fffc210ab3a _sigtramp + 26
    3  libsystem_platform.dylib 0x0000145b02fffffc _sigtramp + 1089426652
    4  libsystem_c.dylib        0x00007fffc1f8f420 abort + 129
    5  libsystem_c.dylib        0x00007fffc1f56893 basename_r + 0
    6  swift                    0x000000010531f4a6 swift::TypeChecker::lookupMemberType(swift::DeclContext*, swift::Type, swift::Identifier, swift::OptionSet<swift::NameLookupFlags, unsigned int>) + 1750
    7  swift                    0x0000000105365e5d resolveIdentTypeComponent(swift::TypeChecker&, swift::DeclContext*, llvm::ArrayRef<swift::ComponentIdentTypeRepr*>, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, bool, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 1101
    8  swift                    0x00000001053656c6 swift::TypeChecker::resolveIdentifierType(swift::DeclContext*, swift::IdentTypeRepr*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, bool, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 150
    9  swift                    0x0000000105366543 (anonymous namespace)::TypeResolver::resolveType(swift::TypeRepr*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>) + 195
    10 swift                    0x000000010536644d swift::TypeChecker::resolveType(swift::TypeRepr*, swift::DeclContext*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 173
    11 swift                    0x0000000105364eb3 swift::TypeChecker::validateType(swift::TypeLoc&, swift::DeclContext*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 355
    12 swift                    0x0000000105301da4 (anonymous namespace)::DeclChecker::visitFuncDecl(swift::FuncDecl*) + 2980
    13 swift                    0x00000001052ef0c2 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 482
    14 swift                    0x00000001052f0cd3 swift::TypeChecker::validateDecl(swift::ValueDecl*) + 2179
    15 swift                    0x0000000105499897 swift::DeclContext::lookupQualified(swift::Type, swift::DeclName, swift::NLOptions, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ValueDecl*>&) const + 2071
    16 swift                    0x000000010531ec4c swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>)::$_1::operator()() const + 252
    17 swift                    0x000000010531eaf7 swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>) + 247
    18 swift                    0x0000000105336203 (anonymous namespace)::WitnessChecker::lookupValueWitnesses(swift::ValueDecl*, bool*) + 755
    19 swift                    0x000000010534078c (anonymous namespace)::ConformanceChecker::inferTypeWitnessesViaValueWitnesses(llvm::SetVector<swift::AssociatedTypeDecl*, std::__1::vector<swift::AssociatedTypeDecl*, std::__1::allocator<swift::AssociatedTypeDecl*> >, llvm::DenseSet<swift::AssociatedTypeDecl*, llvm::DenseMapInfo<swift::AssociatedTypeDecl*> > > const&) + 876
    20 swift                    0x000000010532e2f1 (anonymous namespace)::ConformanceChecker::resolveTypeWitnesses() + 433
    21 swift                    0x000000010532df84 swift::TypeChecker::resolveTypeWitness(swift::NormalProtocolConformance const*, swift::AssociatedTypeDecl*) + 132
    22 swift                    0x00000001054a553d swift::NormalProtocolConformance::getTypeWitnessAndDecl(swift::AssociatedTypeDecl*, swift::LazyResolver*, swift::SubstOptions) const + 1069
    23 swift                    0x00000001054a4fae swift::ProtocolConformance::getTypeWitnessAndDecl(swift::AssociatedTypeDecl*, swift::LazyResolver*, swift::SubstOptions) const + 286
    24 swift                    0x00000001054a4a18 swift::ProtocolConformance::getTypeWitness(swift::AssociatedTypeDecl*, swift::LazyResolver*, swift::SubstOptions) const + 104
    25 swift                    0x000000010531f309 swift::TypeChecker::lookupMemberType(swift::DeclContext*, swift::Type, swift::Identifier, swift::OptionSet<swift::NameLookupFlags, unsigned int>) + 1337
    26 swift                    0x0000000105365e5d resolveIdentTypeComponent(swift::TypeChecker&, swift::DeclContext*, llvm::ArrayRef<swift::ComponentIdentTypeRepr*>, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, bool, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 1101
    27 swift                    0x00000001053656c6 swift::TypeChecker::resolveIdentifierType(swift::DeclContext*, swift::IdentTypeRepr*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, bool, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 150
    28 swift                    0x0000000105366543 (anonymous namespace)::TypeResolver::resolveType(swift::TypeRepr*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>) + 195
    29 swift                    0x000000010536644d swift::TypeChecker::resolveType(swift::TypeRepr*, swift::DeclContext*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 173
    30 swift                    0x0000000105364eb3 swift::TypeChecker::validateType(swift::TypeLoc&, swift::DeclContext*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, swift::GenericTypeResolver*, llvm::function_ref<bool (swift::TypeCheckRequest)>*) + 355
    31 swift                    0x0000000105321202 validateParameterType(swift::ParamDecl*, swift::DeclContext*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, swift::GenericTypeResolver&, swift::TypeChecker&) + 130
    32 swift                    0x000000010532109b swift::TypeChecker::typeCheckParameterList(swift::ParameterList*, swift::DeclContext*, swift::OptionSet<swift::TypeResolutionFlags, unsigned int>, swift::GenericTypeResolver&) + 139
    33 swift                    0x000000010530d9c5 (anonymous namespace)::DeclChecker::semaFuncParamPatterns(swift::AbstractFunctionDecl*, swift::GenericTypeResolver&) + 181
    34 swift                    0x0000000105301db6 (anonymous namespace)::DeclChecker::visitFuncDecl(swift::FuncDecl*) + 2998
    35 swift                    0x00000001052ef0c2 (anonymous namespace)::DeclChecker::visit(swift::Decl*) + 482
    36 swift                    0x00000001052f0cd3 swift::TypeChecker::validateDecl(swift::ValueDecl*) + 2179
    37 swift                    0x0000000105499897 swift::DeclContext::lookupQualified(swift::Type, swift::DeclName, swift::NLOptions, swift::LazyResolver*, llvm::SmallVectorImpl<swift::ValueDecl*>&) const + 2071
    38 swift                    0x000000010531ec4c swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>)::$_1::operator()() const + 252
    39 swift                    0x000000010531eaf7 swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>) + 247
    40 swift                    0x0000000105336203 (anonymous namespace)::WitnessChecker::lookupValueWitnesses(swift::ValueDecl*, bool*) + 755
    41 swift                    0x000000010534078c (anonymous namespace)::ConformanceChecker::inferTypeWitnessesViaValueWitnesses(llvm::SetVector<swift::AssociatedTypeDecl*, std::__1::vector<swift::AssociatedTypeDecl*, std::__1::allocator<swift::AssociatedTypeDecl*> >, llvm::DenseSet<swift::AssociatedTypeDecl*, llvm::DenseMapInfo<swift::AssociatedTypeDecl*> > > const&) + 876
    42 swift                    0x000000010532e2f1 (anonymous namespace)::ConformanceChecker::resolveTypeWitnesses() + 433
    43 swift                    0x000000010532fe1c swift::TypeChecker::resolveWitness(swift::NormalProtocolConformance const*, swift::ValueDecl*) + 508
    44 swift                    0x00000001054a5bb2 swift::NormalProtocolConformance::getWitness(swift::ValueDecl*, swift::LazyResolver*) const + 242
    45 swift                    0x00000001054a5a8b swift::ProtocolConformance::getWitnessDecl(swift::ValueDecl*, swift::LazyResolver*) const + 43
    46 swift                    0x000000010531e436 (anonymous namespace)::LookupResultBuilder::add(swift::ValueDecl*, swift::ValueDecl*, swift::Type) + 854
    47 swift                    0x000000010531ec79 swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>)::$_1::operator()() const + 297
    48 swift                    0x000000010531eaf7 swift::TypeChecker::lookupMember(swift::DeclContext*, swift::Type, swift::DeclName, swift::OptionSet<swift::NameLookupFlags, unsigned int>) + 247
    49 swift                    0x00000001052824e2 swift::constraints::ConstraintSystem::lookupMember(swift::Type, swift::DeclName) + 322
    50 swift                    0x0000000105249355 swift::constraints::ConstraintSystem::performMemberLookup(swift::constraints::ConstraintKind, swift::DeclName, swift::Type, swift::FunctionRefKind, swift::constraints::ConstraintLocator*, bool) + 1429
    51 swift                    0x000000010524ae0f swift::constraints::ConstraintSystem::simplifyMemberConstraint(swift::constraints::ConstraintKind, swift::Type, swift::DeclName, swift::Type, swift::DeclContext*, swift::FunctionRefKind, swift::OptionSet<swift::constraints::ConstraintSystem::TypeMatchFlags, unsigned int>, swift::constraints::ConstraintLocatorBuilder) + 207
    52 swift                    0x0000000105236693 swift::constraints::ConstraintSystem::addValueMemberConstraint(swift::Type, swift::DeclName, swift::Type, swift::DeclContext*, swift::FunctionRefKind, swift::constraints::ConstraintLocatorBuilder) + 179
    53 swift                    0x0000000105236ced (anonymous namespace)::ConstraintGenerator::addMemberRefConstraints(swift::Expr*, swift::Expr*, swift::DeclName, swift::FunctionRefKind) + 237
    54 swift                    0x000000010522c760 swift::ASTVisitor<(anonymous namespace)::ConstraintGenerator, swift::Type, void, void, void, void, void>::visit(swift::Expr*) + 11584
    55 swift                    0x0000000105231d4a (anonymous namespace)::ConstraintWalker::walkToExprPost(swift::Expr*) + 58
    56 swift                    0x00000001054058fb (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) + 123
    57 swift                    0x0000000105404110 swift::ASTVisitor<(anonymous namespace)::Traversal, swift::Expr*, swift::Stmt*, bool, swift::Pattern*, bool, void>::visit(swift::Expr*) + 9472
    58 swift                    0x0000000105405953 (anonymous namespace)::Traversal::visitApplyExpr(swift::ApplyExpr*) + 211
    59 swift                    0x0000000105400f24 swift::Expr::walk(swift::ASTWalker&) + 84
    60 swift                    0x0000000105228a18 swift::constraints::ConstraintSystem::generateConstraints(swift::Expr*) + 264
    61 swift                    0x0000000105257b6f swift::constraints::ConstraintSystem::solve(swift::Expr*&, swift::Type, swift::ExprTypeCheckListener*, llvm::SmallVectorImpl<swift::constraints::Solution>&, swift::FreeTypeVariableBinding) + 415
    62 swift                    0x00000001052d6804 swift::TypeChecker::solveForExpression(swift::Expr*&, swift::DeclContext*, swift::Type, swift::FreeTypeVariableBinding, swift::ExprTypeCheckListener*, swift::constraints::ConstraintSystem&, llvm::SmallVectorImpl<swift::constraints::Solution>&, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>) + 340
    63 swift                    0x00000001052d986f swift::TypeChecker::typeCheckExpression(swift::Expr*&, swift::DeclContext*, swift::TypeLoc, swift::ContextualTypePurpose, swift::OptionSet<swift::TypeCheckExprFlags, unsigned int>, swift::ExprTypeCheckListener*, swift::constraints::ConstraintSystem*) + 655
    64 swift                    0x000000010535829c swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 4940
    65 swift                    0x000000010535701b swift::ASTVisitor<(anonymous namespace)::StmtChecker, void, swift::Stmt*, void, void, void, void>::visit(swift::Stmt*) + 203
    66 swift                    0x0000000105356449 (anonymous namespace)::StmtChecker::typeCheckBody(swift::BraceStmt*&) + 25
    67 swift                    0x00000001053557c9 swift::TypeChecker::typeCheckFunctionBodyUntil(swift::FuncDecl*, swift::SourceLoc) + 345
    68 swift                    0x000000010535560f swift::TypeChecker::typeCheckAbstractFunctionBodyUntil(swift::AbstractFunctionDecl*, swift::SourceLoc) + 111
    69 swift                    0x000000010535619b swift::TypeChecker::typeCheckAbstractFunctionBody(swift::AbstractFunctionDecl*) + 251
    70 swift                    0x00000001053729aa typeCheckFunctionsAndExternalDecls(swift::TypeChecker&) + 202
    71 swift                    0x000000010537391e swift::performTypeChecking(swift::SourceFile&, swift::TopLevelContext&, swift::OptionSet<swift::TypeCheckingFlags, unsigned int>, unsigned int, unsigned int) + 1806
    72 swift                    0x0000000104ec4399 swift::CompilerInstance::performSema() + 3881
    73 swift                    0x0000000104429f8b performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 2427
    74 swift                    0x000000010442853a swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2650
    75 swift                    0x00000001043e4ae0 main + 3312
    76 libdyld.dylib            0x00007fffc1efb235 start + 1
    77 libdyld.dylib            0x000000000000002c start + 1041255928
    Stack dump:
    0.  Program arguments: /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/bin/swift -frontend -c -filelist /var/folders/8v/9769m3ps7ds7h9pg23lzcls00000gn/T/sources-de6fc0 -disable-objc-attr-requires-foundation-module -target x86_64-apple-macosx10.9 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./lib/swift/macosx/x86_64 -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/../../../Developer/Library/Frameworks -g -module-cache-path /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./module-cache -module-link-name swiftCore -nostdimport -parse-stdlib -resource-dir /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/./lib/swift -swift-version 3 -D INTERNAL_CHECKS_ENABLED -enable-cow-existentials -group-info-path /Users/dave/src/s/swift/stdlib/public/core/GroupInfo.json -sil-serialize-all -Xllvm -sil-inline-generics -Xllvm -sil-partial-specialization -Xcc -D__SWIFT_CURRENT_DYLIB=swiftCore -Onone -parse-as-library -module-name Swift -o /Users/dave/src/s/build/Ninja-ReleaseAssert+stdlib-DebugAssert/swift-macosx-x86_64/stdlib/public/core/macosx/x86_64/Swift.o 
    1.  While type-checking 'makeIterator' at /Users/dave/src/s/swift/stdlib/public/core/CharacterUnicodeScalars.swift:35:10
    2.  While type-checking expression at [/Users/dave/src/s/swift/stdlib/public/core/CharacterUnicodeScalars.swift:36:12 - line:36:48] RangeText="Iterator(_base: _base.makeIterator())"
    3.  While validating 'index' at /Users/dave/src/s/swift/stdlib/public/core/StringUnicodeScalarView.swift:523:10
    4.  While type-checking 'index' at /Users/dave/src/s/swift/stdlib/public/core/StringUnicodeScalarView.swift:523:10
    5.  While resolving type String.UnicodeScalarView.IndexDistance at [/Users/dave/src/s/swift/stdlib/public/core/StringUnicodeScalarView.swift:524:31 - line:524:56] RangeText="String.UnicodeScalarView.I"
    6.  While resolving requirement Swift.(file)._Indexable.IndexDistance@/Users/dave/src/s/swift/stdlib/public/core/Collection.swift:182:18 in conformance String.UnicodeScalarView: _Indexable module Swift
    7.  While validating 'distance' at /Users/dave/src/s/swift/stdlib/public/core/StringUnicodeScalarView.swift:529:10
    8.  While type-checking 'distance' at /Users/dave/src/s/swift/stdlib/public/core/StringUnicodeScalarView.swift:529:10
    9.  While resolving type String.UnicodeScalarView.IndexDistance at [/Users/dave/src/s/swift/stdlib/public/core/StringUnicodeScalarView.swift:531:8 - line:531:33] RangeText="String.UnicodeScalarView.I"

## Other hashes

    clang                              b6369bdc96 Merge remote-tracking branch 'origin/swift-4.0-branch' into stable
    cmark                              d875488 Merge pull request #&#8203;4 from llvm-beanz/generate-cmark-exports
    compiler-rt                        cbf6089b1 Merge remote-tracking branch 'origin/swift-4.0-branch' into stable
    llbuild                            79f182e Extract the `isLocatedUnderRootPath` check (#169)
    lldb                               4cd935b4a Don't override the SDKs and force the use of /System/Library/Frameworks to find the python headers when buiding crashinfo.c <rdar://problem/32288076>
    llvm                               f61cc3ca1f3 Merge remote-tracking branch 'origin/swift-4.0-branch' into stable
    ninja                              (not checked out)
    swift                              8a8e9128e7b [stdlib] String index interchange, part III (UTF8)
    swift-corelibs-foundation          2e50a38 Add tests for Scanner.atEnd. (#992)
    swift-corelibs-libdispatch         0b6c22e Merge pull request #&#8203;249 from dgrove-oss/update-docs
    swift-corelibs-xctest              2e0aedc Merge pull request #&#8203;189 from tkremenek/force-tests-swift-ver-3
    swift-integration-tests            641971a Merge pull request #&#8203;21 from apple/revert-20-revert-19-revert-6a20dc2
    swift-xcode-playground-support     05737c4 Merge pull request #&#8203;14 from tkremenek/update-swift-4
    swiftpm                            b589f985 Merge pull request #&#8203;1193 from aciidb0mb3r/enable-prefetching

**Comment by slavapestov** [comment]
Stale.
