### ISSUE TITLE
[SR-5392] Inconsistent "invalid redeclaration of typealias"

### ISSUE THREAD

**Issue by jepers** [apple/swift#47966]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5392      |
   |Radar             | None         |
   |Original Reporter | @jepers      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 9 beta 2, tried both default toolchain and dev snapshot 2017-06-03

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: fa37b4ccfbea6b9fbc48f07ee361235d

  </details>

**relates to**:
* #49765
* #46378
* #48014

**Issue Description:**

```swift
protocol P {
    associatedtype A
    typealias B = Int
}
extension P where A == Bool {
    typealias B = Float // Compiles, but should it?
}
extension P where A == Double {
    typealias B = String // ERROR: Invalid redeclaration of `B`
}
// Note that Bool, Int, Float, Double and String can be any types; ie
// the topmost extension will always compile and the rest will not.
// Same behavior with generic typealiases.
// Should both compile (thus shadowing the default B) or should both be
// considered redeclarations?
```

```swift
// The same example but with a struct instead of a protocol consistently
// treats both as redeclarations:
struct S<A> {
    typealias B = Int
}
extension S where A == Bool {
    typealias B = Float // ERROR: Invalid redeclaration of `B`
}
extension S where A == Double {
    typealias B = String // ERROR: Invalid redeclaration of `B`
}
```

**Comment by AnthonyLatsis** [comment]
Both example expectedly compile now.
