### ISSUE TITLE
[SR-5860] Support "swift -e" for immediate execution

### ISSUE THREAD

**Issue by belkadan** [apple/swift#48430]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5860      |
   |Radar             | rdar://problem/34310802         |
   |Original Reporter | @belkadan      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, StarterBug        |
   |Assignee          | alberto.lagos (JIRA)      |
   |Priority          | Medium      |

   

   md5: faa7261c29c8eaec2f0913a8952f8e77

  </details>

**Issue Description:**

Currently `swift` (the command) always reads a file when you want to run a script; if you want to pass the code on the command line, you have to do it through STDIN:

``` none
% echo 'print("hello")' | swift -
hello
```

We can make this a little nicer by supporting `-e`, like Ruby and Perl:

``` none
% swift -e 'print("hello")'
hello
% swift -e 'let x = 42' -e 'print(x)'
42
```

**Comment by MarcoEidinger** [comment]
Fixed with https://github.com/apple/swift/pull/61171
