### ISSUE TITLE
[SR-6125] Compiles with wmo but reference to invalid associated type without wmo

### ISSUE THREAD

**Issue by jepers** [apple/swift#48680]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6125      |
   |Radar             | rdar://problem/34956654         |
   |Original Reporter | @jepers      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962379-53b37fe8-9702-4750-8b08-6f234fe1cbac.gz)

      
<details>
  <summary>Environment</summary>

Xcode 9 beta 1, using toolchain development-snapshot-2017-10-10

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 6506c68f4427aeaeae0775a16fbee482

  </details>

**Issue Description:**

The following two files (also attached) compiles if using -wmo, but results in the below error without -wmo.

main.swift:

``` none
struct Vector1<Element> : Vector {
    var e0: Element
    init(elementForIndex: (VectorIndex1) -> Element) {
        e0 = elementForIndex(.i0)
    }
    subscript(index: Index) -> Element {
        get { return e0 }
        set { e0 = newValue }
    }
}
```

Other.swift:

``` none
protocol VectorIndex {
    associatedtype Vector8 : Vector where Vector8.Index == Self, Vector8.Element == UInt8
}
enum VectorIndex1 : VectorIndex {
    case i0
    typealias Vector8 = Vector1<UInt8>
}
protocol Vector {
    associatedtype Index: VectorIndex
    associatedtype Element
    init(elementForIndex: (Index) -> Element)
    subscript(index: Index) -> Element { get set }
}
extension Vector where Index == VectorIndex1 {
    init(_ e0: Element) { fatalError() }
}
```

Compiles fine with -wmo:  
$ /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2017-10-10-a.xctoolchain/usr/bin/swiftc -wmo main.swift Other.swift

Compiling without -wmo results in the following error:  
$ /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2017-10-10-a.xctoolchain/usr/bin/swiftc main.swift Other.swift  
main.swift:6:22: error: reference to invalid associated type 'Index' of type 'Vector1\<Element\>'  
subscript(index: Index) -\> Element {

**Comment by slavapestov** [comment]
Fixed by https://github.com/apple/swift/pull/69826
