### ISSUE TITLE
[SR-6161] String.UTF8View subscript returns bogus value for UTF16 trailing surrogate position

### ISSUE THREAD

**Issue by 41412bb9-c79a-4f5a-8a7f-383cb40aa74b** [apple/swift#48713]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6161      |
   |Radar             | None         |
   |Original Reporter | @rintaro      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 4.0.1 (swiftlang-900.0.68 clang-900.0.38)  
Target: x86_64-apple-macosx10.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: cb230f35a6c224c679f2c77451e02b84

  </details>

**Issue Description:**

``` java
let str = "\u{29E3D}"
str.utf8[str.utf8.index(str.startIndex, offsetBy: 0)] // 240 (0xF0)
str.utf8[str.utf8.index(str.startIndex, offsetBy: 1)] // 169 (0xA9)
str.utf8[str.utf8.index(str.startIndex, offsetBy: 2)] // 184 (0xB8)
str.utf8[str.utf8.index(str.startIndex, offsetBy: 3)] // 189 (0xBD)

str.utf8[str.utf16.index(str.startIndex, offsetBy: 1)] // 239 (0xEF)
```

UTF16: 0xD867 0xDE3D  
UTF8: 0xF0 0xA9 0xB8 0xBD

Since UTF8View doesn't contain `239` in it, the last example shouldn't return `239`.

**Comment by glessard** [comment]
This no longer reproduces on Swift 5.9. `String` was rewritten to be UTF8-native in the intervening years.
