### ISSUE TITLE
[SR-6265] Remove "redundant layout constraint" warning

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift#48815]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6265      |
   |Radar             | None         |
   |Original Reporter | @NachoSoto      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 4.0.2 (swiftlang-900.0.69.1 clang-900.0.38)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 11         |
   |Component/s       | Compiler    |
   |Labels            | Bug, 4.0Regression, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 6696c6112b38ed2330b27fc56449fc4b

  </details>

**relates to**:  
* [SR-5753](https://bugs.swift.org/browse/SR-5753) Remove "redundant same-type constraints" warnings  
* [SR-7048](https://bugs.swift.org/browse/SR-7048) Layout constraint warning or compilation error  

**Issue Description:**

This is basically the same as SR-5753.  
This was my code (see [Twitter conversation](https://twitter.com/nachosoto/status/925500721587306496) too):

``` java
protocol A: class {}
protocol B: class, A {}
```

Starting from Swift 4.0.2 (Xcode 9.1), I started getting this warning:

    error: redundant layout constraint 'Self' : 'AnyObject'

Which, for starters, is not user friendly at all. The \`'Self' : 'AnyObject'\` part is totally a Swift implementation detail. But most importantly, I don't think this warning carries its weight. In my case, I don't want to rely on A enforcing reference semantics. What if A drops that constraint? I want B to always have them.

So like I said in SR-5753, without a way to turn these warnings off either globally or for a particular declaration, I think they're more annoying than anything.

**Comment by slavapestov** [comment]
Redundant requirement warnings are now disabled by default.
