### ISSUE TITLE
[SR-6372] SwiftSyntax fails to link with an Xcode project in a toolchain

### ISSUE THREAD

**Issue by harlanhaskins** [apple/swift#48922]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6372      |
   |Radar             | rdar://problem/35496844         |
   |Original Reporter | @harlanhaskins      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962428-ef1c992e-a745-447f-a22f-fa54f55ca362.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | Rostepher (JIRA)      |
   |Priority          | Medium      |

   

   md5: 9f7800063bff816f8510991a1cbee7b3

  </details>

**Issue Description:**

When I attempt to use a `master` toolchain and import SwiftSyntax in a blank Xcode project, it fails to link when building with Xcode. It works fine compiling via command line with the `swiftc` distributed.

Attached is a blank project. Use with the latest toolchain and you'll see:

 

`ld: library not found for -lswiftSwiftSyntax for architecture x86_64`

**Comment by ahoppen** [comment]
No longer applicable since we re-wrote the parser in Swift and the parser C++ dylib no longer exists.
