### ISSUE TITLE
[SR-6635] Inferring associatedtype from arguments of closure type works only when code is in the same file

### ISSUE THREAD

**Issue by jepers** [apple/swift#49184]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6635      |
   |Radar             | None         |
   |Original Reporter | @jepers      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 9.2, dev snapshot 2017-12-17

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2af789c030eceab59614d1c65266c0cc

  </details>

**is duplicated by**:  
* [SR-6224](https://bugs.swift.org/browse/SR-6224) Type inference in subscript fails unless moving declaration of containing struct to main.swift  

**Issue Description:**

Note that the following compiles as expected (because everything is in a single file):

``` none
$ cat > main.swift
protocol P {
    associatedtype AT
    func f(fn: () -> AT)
    func g(v: AT)
}
struct S : P {
    func f(fn: () -> Int) { }
    func g(v: AT) { }
}
let b = S()
print("The type of AT is", type(of: b).AT.self)

$ /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2017-12-17-a.xctoolchain/usr/bin/swiftc main.swift

$ ./main
The type of AT is Int
```

But if P and S are declared in a separate file, the following error is (incorrectly) reported:

``` none
$ cat > Other.swift
protocol P {
    associatedtype AT
    func f(fn: () -> AT)
    func g(v: AT)
}
struct S : P {
    func f(fn: () -> Int) { }
    func g(v: AT) { }
}

$ cat > main.swift
let b = S()
print("The type of AT is", type(of: b).AT.self)

$ /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2017-12-17-a.xctoolchain/usr/bin/swiftc main.swift Other.swift 
Other.swift:8:15: error: reference to invalid associated type 'AT' of type 'S'
    func g(v: AT) { }
```

(  
I also noticed that if the requirement of func g is commented out from P, it will compile, thus successfully inferring the type of AT from the closure-type argument:

``` none
$ cat > Other.swift
protocol P {
    associatedtype AT
    func f(fn: () -> AT)
    //func g(v: AT) // <-- Commented out
}
struct S : P {
    func f(fn: () -> Int) { }
    func g(v: AT) { }
}

$ cat > main.swift
let b = S()
print("The type of AT is", type(of: b).AT.self)

$ /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2017-12-17-a.xctoolchain/usr/bin/swiftc main.swift Other.swift 

$ ./main 
The type of AT is Int
```

)

**Comment by slavapestov** [comment]
Fixed by #69826.
