### ISSUE TITLE
[SR-6929] libSyntax: dangling comment is never attached as trivia

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#49477]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6929      |
   |Radar             | None         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug, Syntax        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d5e209bb6077b1009d0515befc33db24

  </details>

**Issue Description:**

If you make a source file that consists only of comments and whitespace, libSyntax doesn't generate any tokens and the content is "lost"

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
