### ISSUE TITLE
[SR-6931] libSyntax: StmtSyntax doesn't capture commonality among statements

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#49479]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6931      |
   |Radar             | None         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug, Syntax        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 931699f91fdd0d36b66d61e8d1c5d28e

  </details>

**Issue Description:**

For example, you can't ask whether any of the statements in a StmtListSyntax ends with a semicolon without downcasting each one.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
