### ISSUE TITLE
[SR-6932] libSyntax: Some trivia are not so trivial

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#49480]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6932      |
   |Radar             | None         |
   |Original Reporter | @dabrahams      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug, Syntax        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 99576744d57298235b0f4e2fea0f3023

  </details>

**Issue Description:**

We mostly think of trivia as things that could be dropped without changing semantics, but some are crucial. For example, the space in “`let x=1`” prevents tokenization as “**`letx`**, `=`, `1`.” Also, the newlines between statements, where there are no semicolons, are required. A formatter/pretty-printer that normalizes whitespace needs to be able to find-and-preserve or ensure-it-recreates nontrivial whitespace.

The current libSyntax API makes that especially difficult when multiple identifiers and/or keywords appear together, because the rules about what characters can be part of an identifier are complex. One could special-case all the known token combinations, but when the language grows a new token these rules are very likely to break down until the formatter is updated and rebuilt with a new libSyntax. It should be possible to handle this in an efficient way that is very likely to be resilient to future language changes.

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
