### ISSUE TITLE
[SR-7093] Index does not include reference to constructor of class/struct with generic types

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#49641]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7093      |
   |Radar             | rdar://problem/70955529         |
   |Original Reporter | Leitch (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Using [SourceKitten](https://github.com/jpsim/SourceKitten) to perform the SourceKit request.

 

Xcode 9.2  
Build version 9C40b

 

macOS 10.13.3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f31c557a78a7016c21e6bf633e9bada7

  </details>

**Issue Description:**

Given the following code:

 

``` java
class ClassA<T> {
    init(someVar: Int = 0) {}
}

class ClassB {
    private let classA: ClassA<String>

    init() {
        classA = ClassA<String>()
    }
}
```

 

A **`source.request.indexsource`** response does not include a `source.lang.swift.ref.function.constructor` reference for `ClassA<String>()` to the declaration `init(someVar:)`. The constructor has the USR `s:4test6ClassACACyxGSi7someVar_tcfc` and it is not referenced *anywhere* in the index.

 

This issue appears to only affect classes with generic types. If I remove the generic type from ClassA, the ClassB constructor declaration will contain a reference to `init(someVar:)`.

 

Full index response is here: <https://gist.github.com/ileitch/2b6b08ab247d712da752c5c24b5fca85>

 

/cc @nkcsgexi @benlangmuir

**Comment by keith** [comment]
dup of https://github.com/apple/swift/issues/54532, fixed on main, hopefully will make 5.9
