### ISSUE TITLE
[SR-7142] Conditional extension requirements redundant with type declaration are not flagged

### ISSUE THREAD

**Issue by d4adc30e-df4b-4925-bfeb-69e631c0be69** [apple/swift#49690]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7142      |
   |Radar             | rdar://problem/38394642         |
   |Original Reporter | @huonw      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

master as of 2018-03-08

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c1921c558f2a198500ffeca1e558dbe2

  </details>

**Issue Description:**

``` none
protocol P1 {}

struct Foo<T> {}
extension Foo where T: P1, T: P1 {}

struct Bar<T: P1> {}
extension Bar where T: P1 {}
```

compiles with:

``` none
redundant.swift:4:29: warning: redundant conformance constraint 'T': 'P1'
extension Foo where T: P1, T: P1 {}
                            ^
redundant.swift:4:22: note: conformance constraint 'T': 'P1' written here
extension Foo where T: P1, T: P1 {}
                     ^
```

That is, `Foo` gets a warning, but `Bar` does not.

**Comment by slavapestov** [comment]
I actually fixed this in https://github.com/apple/swift/pull/41820, but redundant requirement warnings are now disabled by default.
