### ISSUE TITLE
[SR-7270] error: subscript cannot be marked 'static'

### ISSUE THREAD

**Issue by aciidb0mb3r** [apple/swift#49818]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7270      |
   |Radar             | None         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, LanguageFeatureRequest        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 89549965ee1de5decf92a99abfbb7f1e

  </details>

**Issue Description:**

Why not? 🙁

**Comment by AnthonyLatsis** [comment]
Proposal: SE-0254
