### ISSUE TITLE
[SR-7432] Can't see through boxed _SwiftValue when casting from @objc Type

### ISSUE THREAD

**Issue by tkrajacic** [apple/swift#49975]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7432      |
   |Radar             | rdar://problem/39415812         |
   |Original Reporter | @tkrajacic      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Runtime        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: be79066c5a2ee131780c4b6bfd8678cb

  </details>

**Issue Description:**

When conforming to an @objc protocol, the check using \`is\` can't get the original type information.

In the Playground, uncomment the @objc in front of the protocol and suddenly the check at the end doesn't pick up on the fact that the passed type is in fact a \`User.Type\`

 

``` java
import Foundation

//@objc(Exporter)
protocol Exporter: NSObjectProtocol {
var type: Any { get }
func export(item: Any)
}

struct User { var name: String }

final class UserExporter: NSObject, Exporter {
var type: Any { return User.self }
func export(item: Any) {
guard let u = item as? User else {
return print("That's not a user")
}
print("Got user: \(u.name)")
}
}

let user = User(name: "Kermit")
let exporter: Exporter = UserExporter()

if exporter.type is User.Type {
print("Correct exporter")
}
exporter.export(item: user)
```

**Comment by AnthonyLatsis** [comment]
Fixed by #33561 (test [here](https://github.com/apple/swift/blob/eb7a23f53a69cd581327d0298a39c027256ce579/test/Casting/Casts.swift#L287)).
