### ISSUE TITLE
[SR-7467] associatedType having a default type is broken with more than two use

### ISSUE THREAD

**Issue by kateinoigakukun** [apple/swift#50010]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7467      |
   |Radar             | None         |
   |Original Reporter | @kateinoigakukun      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @kateinoigakukun      |
   |Priority          | Medium      |

   

   md5: f2f22b2ccca7f1fd5d33002d0d33e04f

  </details>

**Issue Description:**

Minimum code is here.

``` java
protocol P {
    associatedtype X = Int

    func f1(_ x: X)
    func f2(_ x: X)
}

struct S: P {
    func f1(_ x: X) {}
    func f2(_ x: X) {}
}
 
```

``` java
error: reference to invalid associated type 'X' of type 'S'
    func f2(_ x: X) {}
```

**Comment by slavapestov** [comment]
Fixed by https://github.com/apple/swift/pull/69826
