### ISSUE TITLE
[SR-7482] [Small String] NSStringConversion regression

### ISSUE THREAD

**Issue by 177d8476-2756-4152-91d7-984f74d3896c** [apple/swift#50025]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7482      |
   |Radar             | rdar://problem/39578066         |
   |Original Reporter | @milseman      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug, Performance        |
   |Assignee          | @milseman      |
   |Priority          | Medium      |

   

   md5: a3429e2bd7abbc6f6879ca42134c2c27

  </details>

**Issue Description:**

Due to aggressive attempts at forming small strings, NSStringConversion benchmark has regressed while trying to unpack tagged NSStrings. There may be some general tweaking and tuning to help, and ideally we'd reduce the overhead associated with CFStringGetBytes through a more direct access.

<https://github.com/apple/swift/pull/14755>

**Comment by Catfish-Man** [comment]
This was fixed in a bunch of pieces, but after https://github.com/apple/swift/pull/59823 it looks like we're ahead of where we were
