### ISSUE TITLE
[SR-7599] Inconsistent diagnostics when defining `count`

### ISSUE THREAD

**Issue by 177d8476-2756-4152-91d7-984f74d3896c** [apple/swift#50141]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7599      |
   |Radar             | None         |
   |Original Reporter | @milseman      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @xedin      |
   |Priority          | Medium      |

   

   md5: 61d5a9fc441e117c3b0132ad689198c7

  </details>

**Issue Description:**

When String defines \`count\`, diagnostic changes from "cannot call value of non-function type 'Int'" to "cannot invoke 'count' with no arguments": <https://github.com/apple/swift/pull/16358#issuecomment-386458161>

The original is better and offers a fixit.

**Comment by AnthonyLatsis** [comment]
Fixed in #27976
