### ISSUE TITLE
[SR-7692] Misleading error message when trying to extend a typealias that is an array

### ISSUE THREAD

**Issue by Cyberbeni** [apple/swift#50232]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7692      |
   |Radar             | None         |
   |Original Reporter | @Cyberbeni      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 6f1f738a669a4e36fe921be0328cd232

  </details>

**Issue Description:**

my code:

``` java
struct Payments {

    struct Transaction { }

    struct GetTransactionList {

        struct Request {}

        typealias Response = [Payments.Transaction]
    }

}

public extension Payments.GetTransactionList.Response: MyProtocol {
}

```

The compiler is saying that the typealias line is wrong because Payments doesn't have Transaction, when in reality, the problem is that the compiler can't translate the conditional conformance of .Response to `public extension Array: MyProtocol where Element == Payments.Transaction`.

edit: Also tested this on my personal MacBook and it's giving the correct error there.

**Comment by slavapestov** [comment]
This was fixed a while ago.
