### ISSUE TITLE
[SR-7699] Comparable Self inside protocol extension

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#50239]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7699      |
   |Radar             | None         |
   |Original Reporter | wowlocal (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b743a70f72d1e3230bfe2130516de1ef

  </details>

**Issue Description:**

 

``` java
enum BoundedErrors: Error {
case crossedMaxValue
case crossedMinValue
}

public protocol Bounded where Self: Comparable {
init(_ val: Self) throws
var minValue: Self { get set }
var maxValue: Self { get set }
}


extension Bounded {
init(_ val: Self) throws {
guard val <= maxValue else { throw BoundedErrors.crossedMaxValue } //error
guard val >= minValue else { throw BoundedErrors.crossedMinValue } //error
self = val
}
}
```

error: Binary operator '\>=' cannot be applied to two 'Self' operands.

But Self is Comparable.

**Comment by AnthonyLatsis** [comment]
Duplicate of #48153
