### ISSUE TITLE
[SR-7702] SILVerifier ist still very slow with large arrays.

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#50242]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7702      |
   |Radar             | None         |
   |Original Reporter | andreasw (JIRA User)      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164962725-cfb7e0e8-f7af-40b2-8064-c1c48417de87.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @eeckstein      |
   |Priority          | Medium      |

   

   md5: 67d071791112b24d8587652a110980c4

  </details>

**Issue Description:**

Commit 652978798467deb3825a6a0678621cadde00097b by @eeckstein fixed quadratic behaviour in basic blocks for the SILVerifier reported in <https://bugs.swift.org/browse/SR-7632.>

But performance is still under par. For 10.000 Int elements it takes more than 4 seconds and gets unusable for matrix sizes of 50.000 elements.

See attached Makefile.

 

\+ 76,33% 0,54% swift swift \[.\] swift::SILInstructionVisitor\<(anonymous namespace)::SILVerifier, void\>::visit  
+ 76,11% 73,23% swift swift \[.\] (anonymous namespace)::SILVerifier::visitSILInstruction  
+ 51,63% 0,31% swift swift \[.\] (anonymous namespace)::SILVerifier::visitSILBasicBlock  
+ 14,17% 0,25% swift swift \[.\] (anonymous namespace)::SILVerifier::visitSILFunction  
+ 7,58% 0,00% swift swift \[.\] swift::SILFunction::verify  
+ 7,52% 0,00% swift swift \[.\] swift::SILModule::verify  
+ 6,07% 0,03% swift swift \[.\] (anonymous namespace)::CallEmission::apply  
+ 5,67% 0,03% swift swift \[.\] swift::Lowering::SILGenFunction::emitApply  
+ 5,52% 5,43% swift swift \[.\] llvm::StringRef::find_last_of  
+ 5,41% 0,01% swift swift \[.\] swift::SILLocation::decode  
+ 5,39% 0,01% swift swift \[.\] llvm::SourceMgr::getLineAndColumn

**Comment by gonsolo** [comment]
Swift 5.7 Linux:

20.000 elements: 1.1s.

I think this can be closed, @shahmishal, @eeckstein .

**Comment by eeckstein** [comment]
Well, we should keep it open if it's still a problem (which I didn't verify)

**Comment by eeckstein** [comment]
Yes, sounds good
