### ISSUE TITLE
[SR-7895] Relax Redundant Conformance Warning Child to Parent associatedtype Constraints

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#50430]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7895      |
   |Radar             | None         |
   |Original Reporter | plx (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b2016a673d683d580dfcaab7c188e075

  </details>

**Issue Description:**

Consider this type of arrangement:

``` none
protocol FooType {
  associatedtype A: Qux
}

protocol Bar {
  associatedtype A: Qux
  associatedtype Foo: FooType where A == Foo.A
}
```

In such cases Swift 4.2, as of Xcode 10, will warn that the \`A: Qux\` in protocol \`Bar\` is redundant.

This is completely true, but forces an annoying choice: either we live with the warning or we remove \`A:Qux\` from \`Bar\`'s declaration.

Living with the warning is annoying and the start of bad habits.

Removing \`A:Qux\`, however, makes the declaration of \`Bar\` less reflective of the intent: the intent is not \`Bar has a Foo, which has an A, which determines Bar's own A" but "Bar has an A, and a Foo, and Foo's A must be compatible-with Bar's A".

If possible to simply suppress redundancy warnings for associated type declarations on protocols that flow "upstream" (e.g. that flow "up" to an associated type from another associated type's associated type...) it would be greatly appreciated.

**Comment by slavapestov** [comment]
Redundant requirement warnings are now disabled by default.
