### ISSUE TITLE
[SR-7931] Document short-hand form for generic type aliases

### ISSUE THREAD

**Issue by jepers** [apple/swift#50466]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7931      |
   |Radar             | rdar://problem/41028037         |
   |Original Reporter | @jepers      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1cae1d1241f8af82feb6fd18d96e0fef

  </details>

**Issue Description:**

Related [forum thread](https://forums.swift.org/t/am-i-hitting-a-compiler-bug/13372).

For example this:

```swift
typealias Map = Dictionary
```

is a short hand form for:

```swift
typealias Map<K: Hashable, V> = Dictionary<K, V>
```

according to [this forum post](https://forums.swift.org/t/am-i-hitting-a-compiler-bug/13372/10) by @slavapestov.

But afaict there doesn't seem to be any mention of this in any documentation.

So I guess it should be documented in eg this section:  
<https://docs.swift.org/swift-book/ReferenceManual/Declarations.html#ID361>

And more generally, a lot of the behavior of type aliases, associated types and extensions is both undocumented and inconsistent/broken.

Properly documenting the intended behavior would certainly help not only us (new and seasoned) users but also the compiler devs.

**Comment by AnthonyLatsis** [comment]
Shorthand syntax is now documented. 

@amartini51 Could you help me transfer this to the book’s bug tracker, please?
