### ISSUE TITLE
[SR-7945] Ubuntu tarball breaks clang package

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#50480]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7945      |
   |Radar             | rdar://problem/41013178         |
   |Original Reporter | mcandre (JIRA User)      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Ubuntu 16.04, 18.04

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   Watchers: @shahmishal

   md5: eba13b8da8c4d54d3ff221461a923e2d

  </details>

**Issue Description:**

The official Ubuntu tarballs for installing Swift in Linux unfortunately appear to include a deprecated directory, /usr/lib/python2.7/site-packages, which results in \`sudo apt-get install -y clang\` failing when dpkg processes clang's \`python2.7-minimal\` dependency. Evidently, Python has shifted away from the /usr/lib/python2.7/site-packages structure and has trouble installing itself when this path is present on the system.

**Comment by keith** [comment]
Source tars no longer contain this directory
