### ISSUE TITLE
[SR-8028] Protocol with where class constraint fails to compile, but same extension succeeds

### ISSUE THREAD

**Issue by iby** [apple/swift#50561]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8028      |
   |Radar             | rdar://problem/42012633         |
   |Original Reporter | @iby      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: c93b6bd151a70d62522f417b2869296d

  </details>

**cloned to**:  
* [SR-8247](https://bugs.swift.org/browse/SR-8247) Associated type inheriting from generic class with Self as a parameter prints canonical type in errors  

**is duplicated by**:  
* [SR-9706](https://bugs.swift.org/browse/SR-9706) Compiler rejecting conformance  

**Issue Description:**

Apologies if the sample a little noisy, tried cleaning it up as much as could in available time. The following fails to build, but replaced with commented lines does compile. Intentional? Why?

**Comment by slavapestov** [comment]
Fixed by https://github.com/apple/swift/pull/71354
