### ISSUE TITLE
[SR-8168] @available(iOS, obsoleted: 10.0) Does Not Prevent Function Execution

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#50700]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8168      |
   |Radar             | None         |
   |Original Reporter | jhoffmann (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 8a0bd131195677f0720f33b822428475

  </details>

**Issue Description:**

Placing @avilable(iOS, obsoleted) above a function is not preventing the execution of that function on newer platforms.

 

Example: 

``` java
override func viewDidLoad() {
     super.viewDidLoad()        
     testFunc()
}
    
@available(iOS, obsoleted: 10.0)
func testFunc() {
     print("testFunc")
}
```

``` java
@available(iOS, obsoleted: 10.0)
    override func invalidationContext(forPreferredLayoutAttributes preferredAttributes: UICollectionViewLayoutAttributes, withOriginalAttributes originalAttributes: UICollectionViewLayoutAttributes) -> UICollectionViewLayoutInvalidationContext
```

**Comment by tshortli** [comment]
I believe this is implemented. The following fails to type check for a deployment target > macOS 11 with the Swift 5.6 compiler:
```swift
@available(macOS, obsoleted: 11.0)
func test() {} // note: 'test()' was obsoleted in macOS 11.0

test() // error: 'test()' is unavailable in macOS
```
