### ISSUE TITLE
[SR-8247] Associated type inheriting from generic class with Self as a parameter prints canonical type in errors

### ISSUE THREAD

**Issue by d4adc30e-df4b-4925-bfeb-69e631c0be69** [apple/swift#50779]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8247      |
   |Radar             | None         |
   |Original Reporter | @huonw      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: a7f630ed225df1f60e8817ca991f4aa5

  </details>

**cloned from**:  
* [SR-8028](https://bugs.swift.org/browse/SR-8028) Protocol with where class constraint fails to compile, but same extension succeeds  

**relates to**:  
* [SR-10612](https://bugs.swift.org/browse/SR-10612) Illegal Instruction: 4 when compiling with Xcode 10.2.1  
* [SR-10712](https://bugs.swift.org/browse/SR-10712) Cannot conform to protocol with associated type constrained to generic class specialised by associated type  

**Issue Description:**

Apologies if the sample a little noisy, tried cleaning it up as much as could in available time. The following fails to build, but replaced with commented lines does compile. Intentional? Why?

**Comment by slavapestov** [comment]
Generic superclass requirements in protocols were fixed by https://github.com/apple/swift/pull/71354.
