### ISSUE TITLE
[SR-8581] Swift version should not be parsed as float literal in libSyntax

### ISSUE THREAD

**Issue by ahoppen** [apple/swift#51099]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8581      |
   |Radar             | rdar://problem/43517085         |
   |Original Reporter | @ahoppen      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Syntax        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0c023a9e72db710706116e6c86e75b5b

  </details>

**Issue Description:**

The Swift version in availability attributes is currently parsed as

-   An integer literal for versions like Swift 4

-   A float literal of versions like Swift 4.2

-   A float literal, followed by a period followed by an integer literal for versions like Swift 4.2.1

This is clearly a hack and we should parse it more like \`\[0-9\]<u>(.\[0-9\]</u>(.\[0-9\]+)?)?\`, i.e.

-   An integer literal for the major version

-   Optionally followed by a period and an integer literal for the minor version

-   Optionally followed by a period and an integer literal for the patch version

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
