### ISSUE TITLE
[SR-8719] Associated type 1 == Associated type 2 requires explicitly stating both types

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#51230]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8719      |
   |Radar             | None         |
   |Original Reporter | Nasamura (JIRA User)      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | New Feature, AssociatedTypeInference        |
   |Assignee          | @DougGregor      |
   |Priority          | Medium      |

   

   md5: 583798a6a88eb7fa7fc4d602ce5716b8

  </details>

**relates to**:  
* [SR-8705](https://bugs.swift.org/browse/SR-8705) Attempt to use same type requirement in the method description causes compiler error  

**Issue Description:**

 Xcode: Version 10.0 beta 6 (10L232m)

``` java
public protocol Prot1 {
    
    associatedtype AType: StringProtocol
}


public protocol Prot2 {
    
    associatedtype BType: StringProtocol
}


public protocol Prot3: Prot1, Prot2 where AType == BType {
    
}


struct Struct1: Prot3 {
    
    typealias AType = String
}

Type 'Struct1' does not conform to protocol 'Prot2'
```

 

This is a simplified example of where I'm combining two protocols and AType will always equal  BType but the compiler is not able to infer one type from the other and has to be explicitly stated. This leads to unnecessary code duplication.

**Comment by slavapestov** [comment]
Fixed by #70375.
