### ISSUE TITLE
[SR-9223] Inliner exhibits slow compilation time with a large static array

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#51712]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9223      |
   |Radar             | None         |
   |Original Reporter | andreasw (JIRA User)      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963023-2032c98f-d613-4230-ae5b-06cc8bd3b766.gz)

<details>
  <summary>Environment</summary>

<a href="Makefile" class="attachment">Makefile</a>

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | @atrick      |
   |Priority          | Medium      |

   md5: c44b8d1ce0417361133fc33640032956

  </details>

**Issue Description:**

 Hi!

Please see the attached Makefile and perf report. This time it's the inliner (and verifier). 

With 5.000 elements compiling takes less than 3 seconds, with 10.000 more than 15, with 15.000 37 seconds.

It seems that commit bd28b0ea1b6ab1e981e1e591e10c42d5adcf71af (SILCloner and  SILInliner rewrite) is the culprit.

```
+ 71,47% 0,06% swift swift [.] runOnFunctionRecursively ◆
+ 71,29% 0,01% swift swift [.] swift::SILInliner::inlineFunction ▒
+ 71,22% 0,02% swift swift [.] swift::SILInlineCloner::cloneInline ▒

-   70,39% 70,19% swift swift [.] llvm::ilist_traits<swift::SILInstruction>::transferNodesFromList ▒
    70,19% runOnFunctionRecursively ▒
    swift::SILInliner::inlineFunction ▒
    + swift::SILInlineCloner::cloneInline ▒
    + 35,74% 0,01% swift swift [.] swift::mergeBasicBlockWithSuccessor ▒
    + 35,69% 0,01% swift swift [.] swift::mergeBasicBlockWithSingleSuccessor ▒
    + 35,63% 0,03% swift swift [.] swift::SILBasicBlock::spliceAtEnd ▒
    + 34,80% 0,04% swift swift [.] swift::SILBasicBlock::split ▒
    + 20,74% 0,04% swift swift [.] swift::SILFunction::verify ▒
    + 20,38% 0,26% swift swift [.] (anonymous namespace)::SILVerifier::visitSILBasicBlock ▒
    + 20,07% 0,13% swift swift [.] swift::SILInstructionVisitor<(anonymous namespace)::SILVerifier, void>::visit ▒
    + 19,46% 18,37% swift swift [.] (anonymous namespace)::SILVerifier::visitSILInstruction ▒
    + 17,22% 0,00% swift swift [.] swift::SILModule::verify
```

The functions inlined are from the builtin `UInt` and `Array` classes.

**Comment by gonsolo** [comment]
Swift 5.7 Linux:

15.000 elements: 0.8s
15.000 elements with "-O": 10.7s

Updated test case:

```
SIZE=15000
SHELL:=/bin/bash

#CONFIGURATION=-O

SWIFTC=swiftc

time: bug.swift
	@echo "Size: $(SIZE)"
	time $(SWIFTC) 	$(CONFIGURATION) bug.swift

bug.swift: Makefile

	@echo "let x: [UInt] = [" > $@
	@LANG=C printf '0x%x, ' $$(seq $(SIZE)) >> $@
	@echo "]" >> $@

.PHONY: c clean e edit
c: clean
clean:
	rm -f bug bug.swift
e: edit
edit:
	vi bug.swift
m:
	vi Makefile
p: perf
perf: bug.swift
	time perf record -e cycles -c 10000 --call-graph=lbr $(SWIFTC) $(CONFIGURATION) bug.swift
	perf report

```

**Comment by gonsolo** [comment]
Swift 5.8 Linux:

15.000 elements: 0.9s
15.000 elements with "-O": 11.3s

**Comment by AnthonyLatsis** [comment]
Is this still an issue with the optimization passes?

**Comment by gonsolo** [comment]
Depends on whether you find 11.3 seconds acceptable. C++ (as every other language I tried) is <0.5 seconds.
I haven't run perf on Swift 5.8 so I don't know where the time is spent, but the Makefile above should make it easy to spot the culprit.

**Comment by AnthonyLatsis** [comment]
No, definitely not acceptable. Was just wondering if you verified if/how the distribution had changed.

**Comment by gonsolo** [comment]
I ran perf again:

    21.11%  swift-frontend   swift-frontend                [.] llvm::DenseMapBase<llvm::DenseMap<swift::AliasAnalysis::AliasCacheKey, swift::AliasAnalysis::AliasResult, llvm::DenseMapInfo<swift::AliasAnalysis::AliasCacheKey, void>, llvm::detail::DenseMapPair<swift::AliasAnalysis::AliasCacheKey, swift::AliasAnalysis::AliasResult> >, swift::AliasAnalysis::AliasCacheKey, swift::AliasAnalysis::AliasResult, llvm::DenseMapInfo<swift::AliasAnalysis::AliasCacheKey, void>, llvm::detail::DenseMapPair<swift::AliasAnalysis::AliasCacheKey, swift::AliasAnalysis::AliasResult> >::LookupBucketFor<swift::AliasAnalysis::AliasCacheKey>
    12.60%  swift-frontend   swift-frontend                [.] swift::ProjectionPath::hasNonEmptySymmetricDifference
    10.72%  swift-frontend   swift-frontend                [.] swift::AliasAnalysis::alias
     8.17%  swift-frontend   swift-frontend                [.] (anonymous namespace)::DSEContext::invalidateBase
     5.84%  swift-frontend   swift-frontend                [.] (anonymous namespace)::BlockState::processStoreInst

**Comment by AnthonyLatsis** [comment]
Current stats make this a duplicate of #50243. Closing in favor of the older issue.
