### ISSUE TITLE
[SR-9301] Error using constrained associated type with generics

### ISSUE THREAD

**Issue by tjw** [apple/swift#51772]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9301      |
   |Radar             | None         |
   |Original Reporter | @tjw      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 5167f2807a64adb2d57100b995c4f29e

  </details>

**relates to**:  
* [SR-10612](https://bugs.swift.org/browse/SR-10612) Illegal Instruction: 4 when compiling with Xcode 10.2.1  

**Issue Description:**

I have a case where I'm creating a wrapper object for a enum type and wasn't able to previously specify all the types up front (prior to Swift 4.2). Trying to clean this up in Swift 4.2 doesn't work for me either. Narrowing down my attempt, this pattern doesn't compile:

``` java
protocol EnumValueType {
    associatedtype Wrapper : EnumValueObject<Self>
}
class EnumValueObject<EnumType : EnumValueType> {
}
```

This results in a error,

``` java
 generic class 'EnumValueObject' references itself
```

**Comment by slavapestov** [comment]
Fixed by https://github.com/apple/swift/pull/71354
