### ISSUE TITLE
[SR-9316] libSyntax: @convention function type is not supported in all contexts

### ISSUE THREAD

**Issue by dan-zheng** [apple/swift#51786]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9316      |
   |Radar             | None         |
   |Original Reporter | @dan-zheng      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift built from this commit: <https://github.com/apple/swift/commit/ab37099967571a1bcb2357f6fe56d09cc6156ba9>

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug, Syntax        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 34a2083c388b96b7ef7fc883dadbf305

  </details>

**Issue Description:**

Simple reproducer:

```swift
// convention.swift
// This passes syntax verification.
let f: @convention(c) (Int) -> Int = { x in x }

func foo<T>(_ x: T.Type) {}
// This does not.
foo((@convention(c) (Int) -> Int).self)
```

```
$ swiftc -Xfrontend -verify-syntax-tree convention.swift
convention.swift:6:6: error: unknown expression syntax exists in the source
foo((@convention(c) (Int) -> Int).self)
     ^
```

**Comment by AnthonyLatsis** [comment]
libSyntax was removed in #62145 and succeeded by [swift-syntax](https://github.com/apple/swift-syntax).
