### ISSUE TITLE
[SR-9341] Add tests for update-checkout (python starter bug)

### ISSUE THREAD

**Issue by gottesmm** [apple/swift#51811]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9341      |
   |Radar             | None         |
   |Original Reporter | @gottesmm      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Task, StarterBug, UpdateCheckout        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e48ffe6d05d7209bb3a01e63d82f523d

  </details>

**Issue Description:**

Recently I added support for adding tests for update-checkout. Without tests, we can not guarantee behavior will not change.

This seems like a useful starter bug for someone who knows python and wants to get involved in the project. The general idea is to create tests based around creating a mock git scheme and a test harness that sets up local git repos for the schema. Using that we can test the functionality of update-checkout locally without hitting github.

**Comment by AnthonyLatsis** [comment]
I think we can close this, given we presently have at least [some tests](https://github.com/apple/swift/tree/main/utils/update_checkout/tests).
