### ISSUE TITLE
[SR-9484] Accepts invalid where clauses for associated types

### ISSUE THREAD

**Issue by jepers** [apple/swift#51946]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9484      |
   |Radar             | None         |
   |Original Reporter | @jepers      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 10.1 default toolchain and recent snapshots

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 87628fd70d4bc413b5d6c5a47a32780d

  </details>

**Issue Description:**

I guess the following should not compile (but it does):

``` none
protocol P {
    associatedtype A
    associatedtype B where B == A
}

protocol Q where A == B {
    associatedtype A
    associatedtype B
}

protocol R where A == (B, C) {
    associatedtype A
    associatedtype B
    associatedtype C
}

protocol S where A == (B, C) -> D {
    associatedtype A
    associatedtype B
    associatedtype C
    associatedtype D
}
```

**Comment by slavapestov** [comment]
This code is fine, protocol where clauses can reference the protocol's own associated types.
