### ISSUE TITLE
[SR-9831] After porting sil combine for ownership, re-enable test/SILOptimizer/devirt_alloc_ref_dynamic_ownership.sil

### ISSUE THREAD

**Issue by gottesmm** [apple/swift#52248]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9831      |
   |Radar             | None         |
   |Original Reporter | @gottesmm      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Task        |
   |Assignee          | @gottesmm      |
   |Priority          | Medium      |

   

   md5: 110d5006f8f5f9879b19058372624928

  </details>

**Issue Description:**

A run of sil-combine is needed to transform an alloc_ref_dynamic =\> alloc_ref for this devirt test. I can't run it though without it being updated for ownership.

**Comment by AnthonyLatsis** [comment]
I assume #35606 or #35297 fixed this. The test now passes.
