### ISSUE TITLE
[SR-9881] SourceKit crashed making a CodeComplete request

### ISSUE THREAD

**Issue by SlaunchaMan** [apple/swift#52287]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9881      |
   |Radar             | rdar://problem/48088514         |
   |Original Reporter | @SlaunchaMan      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963127-cd504cd5-4c18-47e0-9e3f-916624aa9895.gz)

      
<details>
  <summary>Environment</summary>

macOS 10.14.3 (18D42)  
Xcode Version 10.1 (10B61)  
Toolchain: Swift Development Snapshot 2019-02-03 (a)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Bug, FoundByStressTester        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b0848850f7c94e4fd5878c8b0c659c71

  </details>

**Issue Description:**

This is in the \`master\` branch of Alamofire with a few modifications; I’ll attach my exact project too.

    Detected unexpected failure: SourceKit crashed
      request: CodeComplete in /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/EventMonitor.swift at offset 20612 with args: -incremental -module-name Alamofire -Onone -enable-batch-mode -enforce-exclusivity=checked -Xfrontend -disable-swift3-objc-inference -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -target x86_64-apple-macosx10.12 -g -module-cache-path /Users/jeff/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -application-extension -profile-coverage-mapping -profile-generate -enable-testing -index-store-path /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Index/DataStore -swift-version 4.2 -I /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Products/Debug -F /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Products/Debug -c -j12 /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/ParameterEncoding.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Protector.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/ResponseSerialization.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Response.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/URLConvertible+URLRequestConvertible.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/RequestTaskMap.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/AFError.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/URLSessionConfiguration+Alamofire.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/ParameterEncoder.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/OperationQueue+Alamofire.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/HTTPHeaders.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/HTTPMethod.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Notifications.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Alamofire.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/MultipartFormData.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/RequestRetrier.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/DispatchQueue+Alamofire.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/ServerTrustEvaluation.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/MultipartUpload.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/SessionStateProvider.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/NetworkReachabilityManager.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Request.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Validation.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/RequestAdapter.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Session.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/Result.swift /Users/jeff/Projects/Open-Source/Alamofire/Alamofire/Source/EventMonitor.swift -output-file-map /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Objects-normal/x86_64/Alamofire macOS-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Objects-normal/x86_64/Alamofire.swiftmodule -Xcc -I/Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Alamofire-generated-files.hmap -Xcc -I/Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Alamofire-own-target-headers.hmap -Xcc -I/Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Alamofire-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Alamofire-project-headers.hmap -Xcc -I/Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Products/Debug/include -Xcc -I/Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/DerivedSources/x86_64 -Xcc -I/Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/Objects-normal/x86_64/Alamofire-Swift.h -import-underlying-module -Xcc -ivfsoverlay -Xcc /Users/jeff/Library/Developer/Xcode/DerivedData/Alamofire-eywzzlrwfolthydwhfvhaegstzyp/Build/Intermediates.noindex/Alamofire.build/Debug/Alamofire macOS.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/jeff/Projects/Open-Source/Alamofire/Alamofire
    -- begin file content --------
    <unmodified>
    -- end file content ----------

**Comment by rintaro** [comment]
@SlaunchaMan Do you still see this crash? If not, could you close this bug?
