### ISSUE TITLE
[SR-9956] classes defined inside functions can't be made to conform to Equatable?

### ISSUE THREAD

**Issue by weissi** [apple/swift#52359]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9956      |
   |Radar             | None         |
   |Original Reporter | @weissi      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

c

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c2436514a3ae706e9e8ec30597e978fc

  </details>

**duplicates**:  
* [SR-3092](https://bugs.swift.org/browse/SR-3092) Function-level nested types cannot conform to Equatable  

**Issue Description:**

I have this Swift program

``` java
func foo() {
    final class Bar: Equatable {
        static func == (lhs: Bar, rhs: Bar) -> Bool {
            return lhs === rhs
        }
    }
}
```

which I think is totally fine but it claims that `Bar` doesn't conform to Equatable. Moving `Bar` outside the function `foo` however makes it compile.

Also: all works with {{struct}}s.

Error is

    $ swift test.swift
    test.swift:2:17: error: type 'Bar' does not conform to protocol 'Equatable'
        final class Bar: Equatable {
                    ^
    Swift.==:1:24: note: candidate would match if 'Bar' conformed to 'RawRepresentable'
    @inlinable public func == <T>(lhs: T, rhs: T) -> Bool where T : RawRepresentable, T.RawValue : Equatable
                           ^
    Swift.FloatingPoint:2:24: note: candidate would match if 'Bar' conformed to 'FloatingPoint'
        public static func == (lhs: Self, rhs: Self) -> Bool
                           ^
    Swift.BinaryInteger:2:24: note: candidate would match if 'Bar' conformed to 'BinaryInteger'
        public static func == <Other>(lhs: Self, rhs: Other) -> Bool where Other : BinaryInteger
                           ^
    Swift._Pointer:2:24: note: candidate would match if 'Bar' conformed to '_Pointer'
        public static func == (lhs: Self, rhs: Self) -> Bool
                           ^
    Swift.Strideable:3:35: note: candidate would match if 'Bar' conformed to 'Strideable'
        @inlinable public static func == (x: Self, y: Self) -> Bool
                                      ^
    Swift.StringProtocol:2:35: note: candidate would match if 'Bar' conformed to 'StringProtocol'
        @inlinable public static func == <RHS>(lhs: Self, rhs: RHS) -> Bool where RHS : StringProtocol
                                      ^
    Swift.SIMD:4:24: note: candidate would match if 'Bar' conformed to 'SIMD'
        public static func == (lhs: Self, rhs: Self) -> Bool
                           ^
    Swift.Equatable:2:17: note: protocol requires function '==' with type '(Bar, Bar) -> Bool'; do you want to add a stub?
        static func == (lhs: Self, rhs: Self) -> Bool
                    ^

**Comment by weissi** [comment]
@AnthonyLatsis I noticed you closed this as 'not planned'. But this is a bug, no?

**Comment by AnthonyLatsis** [comment]
Hi, Johannes! Apparently, all Jira duplicates, including this one, had already been closed 'as completed' when the issues were transferred. But when I was about to close some stray open duplicates of this issue I found the other day, I discovered that the 'duplicate' state is in the 'close as not planned' bucket (you can verify this by clicking the droplist next to the 'close' button), so I went ahead and reclosed the duplicates as 'not planned'. I realize this is misleading, and that I probably shouldn't have bothered reclosing them. With hindsight, I think we should mark duplicates using GitHub commands rather than closing them.

**Comment by AnthonyLatsis** [comment]
Like this:

Duplicate of #45682

**Comment by weissi** [comment]
@AnthonyLatsis that makes sense, thank you for the explanation. Happy to dupe!
