### ISSUE TITLE
[SR-10239] Superclass constraint 'Self.A' : 'Generic<Self.A>' is recursive

### ISSUE THREAD

**Issue by 7156ccc1-d3b8-4460-882a-3f5802920f8f** [apple/swift#52639]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10239      |
   |Radar             | None         |
   |Original Reporter | @DevAndArtist      |
   |Type              | Bug    |
   |Status            | In Progress        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)  
Target: x86_64-apple-darwin18.2.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @AnthonyLatsis      |
   |Priority          | Medium      |

   

   md5: f91bc71aa7e500ee429bed09cb3a6ba2

  </details>

**Issue Description:**

Swift 5 now allows CRTP. It would be great if CRTP constraints could be formed with associated types of a protocol.

``` java
class Generic<T> {}

protocol P {
  // CRTP with the associated type.
  // I read this as: the conforming type should have a type `A` that
  // is a sub-class of `Generic<A>` (CRTP).
  associatedtype A: Generic<A> // error: Superclass constraint 'Self.A' : 'Generic<Self.A>' is recursive
}
```

Forum thread: <https://forums.swift.org/t/why-is-this-super-class-constraint-recursive/22340>

**Comment by slavapestov** [comment]
I don't think we're going to add this.
