### ISSUE TITLE
[SR-10612] Illegal Instruction: 4 when compiling with Xcode 10.2.1

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#53012]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10612      |
   |Radar             | None         |
   |Original Reporter | heath (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

macOS 10.14.4, Xcode 10.2.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 825e290e69605050e1becb422112fc5f

  </details>

**relates to**:  
* [SR-8247](https://bugs.swift.org/browse/SR-8247) Associated type inheriting from generic class with Self as a parameter prints canonical type in errors  
* [SR-9301](https://bugs.swift.org/browse/SR-9301) Error using constrained associated type with generics  

**Issue Description:**

The following code fails to compile on Xcode 10.2.1:

    protocol P1: class {
        associatedtype P1P1: P1
        associatedtype P1AnyP2: AnyP2<P1P1>
        
        var anyP2: P1AnyP2? { get set }
    }

    protocol P2 {
        associatedtype P2P1: P1
    }

    final class AnyP2<AP2P1: P1>: P2 {
        typealias P2P1 = AP2P1
    }

Output:

    error: Illegal instruction: 4

Xcode also takes 57 seconds to compile this file, which seems suspect.

Available on GitHub: <https://github.com/hborders/SwiftBugs/tree/SR-10612>

**Comment by slavapestov** [comment]
I forgot when the circular references were fixed but the test case now passes on 5.9 and main.
