### ISSUE TITLE
[SR-10831] Associated type inference doesn't work when type is fully constrained

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#53221]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10831      |
   |Radar             | None         |
   |Original Reporter | marcpalmer (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: fddfa1e975a38ccef890a5c04e65bc5f

  </details>

**relates to**:  
* [SR-11671](https://bugs.swift.org/browse/SR-11671) Assoc == Self not treated as an abstract type witness upon conformance  

**Issue Description:**

``` java
struct G<T> {}
  
protocol P {
  associatedtype T
  associatedtype U
}

protocol Q: P where T == G<U> {}

protocol R: Q where U == Int {}

struct X: R {}
```

**Comment by slavapestov** [comment]
This works in 5.9 and main.
