### ISSUE TITLE
[SR-10988] Suggest `return` when the last statement of a multi-statement function body would be a valid return value

### ISSUE THREAD

**Issue by jckarter** [apple/swift#53378]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10988      |
   |Radar             | None         |
   |Original Reporter | @jckarter      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Task, DiagnosticsQoI, StarterBug        |
   |Assignee          | Moritz (JIRA)      |
   |Priority          | Medium      |

   

   md5: 3aba4962728f451223c8a69024161b98

  </details>

**Issue Description:**

Now that we allow return statements to be elided in single-expression bodies, it's easy to end up during refactoring where you end up with multiple statements, but haven't yet added the \`return\`. We could detect when the last statement in a block is an ignored expr, and the type of the expr would be a valid return value, and offer a fixit, instead of sometimes-misleading error messages:

``` java
// Currently diagnoses "has 'some' return type but no return statement", but
// it could offer to fixit `x` to `return x` instead
func foo() -> some Integer {
  let x = 0
  x
}

// Currently warns "ignored expression; insert '_ ='" and then later errors because
// of missing return, but could offer to insert 'return' instead
func bar() -> Int {
  let x = 0
  x
}

// Similarly, we could suggest returns in nested block statements too when appropriate
func bas(x: Bool) -> Int {
  if x {
    0
  } else {
    1
  }
}
```

**Comment by AnthonyLatsis** [comment]
The first example was fixed by #42415.

**Comment by xedin** [comment]
Alright then, I think we can close this issue!

**Comment by AnthonyLatsis** [comment]
>  I think we can close this issue!

@xedin What about the other two examples?
