### ISSUE TITLE
[SR-11421] Checked Cast Diagnostics Should Be More Specific When Literals Are Involved

### ISSUE THREAD

**Issue by CodaFi** [apple/swift#53822]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11421      |
   |Radar             | None         |
   |Original Reporter | @CodaFi      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, StarterBug        |
   |Assignee          | mohit.athwani (JIRA)      |
   |Priority          | Medium      |

   md5: 54d2d8b997d41666f9024642eb576483

  </details>

**cloned to**:  
* [SR-12093](https://bugs.swift.org/browse/SR-12093) Checked Casts With Literals Are Deeply Unintuitive  

**Issue Description:**

Checked casts on literals can have surprising effects at face value

```swift
let character = "A" as Character
let bad = "A" as? Character
```

The former is a character literal and is statically coerced. The latter is a `String` literal that is being dynamically cast to a `Character`. This cast will always fail, and we note as much - this also works with `as!` force casts.

```swift
warning: cast from 'String' to unrelated type 'Character' always fails
```

We could definitely do a better job phrasing this warning to let the user know what went wrong and can even offer a fixit that changes the dynamic cast to a static cast if it's going to succeed.

**Comment by Rajveer100** [comment]
@CodaFi Let me try this!

**Comment by Rajveer100** [comment]
Hey @CodaFi I have run the exact same code, I have got this output:

```
warning: conditional downcast from literal to 'Character' always fails; consider using 'as' coercion
let bad = "A" as? Character
              ^
```

What exact type of phrasing are you looking for, because the above seems very clear and is also giving a suggestion to use the `as` statically coerced cast, instead of `as?`.

**Comment by AnthonyLatsis** [comment]
@Rajveer100 This is definitely an improvement, but I think we can take another step forward and mention the inferred type of the literal as well. I can imagine people wondering why their supposed `Character` literal does not want to downcast to a `Character`. It is not immediately clear that the destination type of a dynamic cast does not participate in the inference of the left-hand side.

**Comment by Rajveer100** [comment]
Yeah I understand that, could you exactly specify to what it could be potentially changed to, what would be your suggestion?

**Comment by AnthonyLatsis** [comment]
Do you have any ideas in mind? Of course, I could just throw in a suggestion without asking you first, but to me that defeats the purpose of a good first issue.

**Comment by Rajveer100** [comment]
So overall, the fix is to change the diagnosed message to a more better phrasing and provide a fix it to it if the casting is possible. While I am solving another issue, I will get back to this.

**Comment by Rajveer100** [comment]
@AnthonyLatsis Back into this issue!
 I guess we were discussing about the suggestions?

**Comment by AnthonyLatsis** [comment]
Hey Rajveer, got any ideas on how to improve the message yet? Suppose you compile `"A" as? Character`, and the compiler reacts with `conditional downcast from literal to 'Character' always fails`. But why does the cast fail?

**Comment by tbkka** [comment]
`as?`,  `as!`, and `is` are variants of the same runtime operation.  In fact, you can define `as!` and `is` in terms of `as?`:
* `x as! T` is defined to be `(x as? T)!`
* `x is T` is defined to be `(x as? T) != nil`

`as?` supports a variety of casting and conversion operations, including bridging conversions (which are not really "casting" in the traditional OO sense) as well as both up and down casting.

**Comment by AnthonyLatsis** [comment]
`as` is special because it is not necessarily a run-time operation. It can act as both a known-to-succeed bridging conversion and a type inference hint or coercion, as in `0 as Double`.

___
Okay, so the reason the cast fails is that `String` and `Character` are unrelated types. The problem is, the error message says nothing about `String` (the inferred type the literal), it only says that the literal cannot be cast to `X`.

**Comment by Rajveer100** [comment]
> Okay, so the reason the cast fails is that `String` and `Character` are unrelated types. The problem is, the error message says nothing about `String` (the inferred type of the literal), it only says that the literal cannot be cast to `Character`.

In which perspective are they 'unrelated', since a string essentially is a stream / buffer of characters, i.e., String.Element.

**Comment by AnthonyLatsis** [comment]
They are "unrelated" in the type system, not logically. "Unrelated" in this sense means that neither is a descendent (subtype) of the other. With the exception of bridging conversions and presumably some other edge cases, Swift’s type safety implies that a type cast/coercion fails if the types are "unrelated".

**Comment by Rajveer100** [comment]
That makes sense.

**Comment by Rajveer100** [comment]
So we can probably update the diagnostic warning to, `warning: {literal_in_context} literal and %0 are 'unrelated' to each other, consider using 'as' coercion`, which in our case would be, `warning: 'String' literal and 'Character' are 'unrelated' to each other, consider using 'as' coercion`.

**Comment by AnthonyLatsis** [comment]
I suggest we align the second half with the wording we already have in `downcast_to_unrelated`: `... to unrelated type <to_type> always fails` rather than the current `... to <to_type> always fails`. `from <from_type> literal` sounds good, but I think we can still do better by mentioning that the literal was *inferred* to that type (and only then cast), to add some contrast between casting and coercing (the fix-it), e.g. `from literal of inferred type <from_type>`.

**Comment by Rajveer100** [comment]
Right...
