### ISSUE TITLE
[SR-11542] bad diagnostic when function invoked with trailing closure syntax and default args after closure

### ISSUE THREAD

**Issue by weissi** [apple/swift#53943]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11542      |
   |Radar             | rdar://problem/55806391         |
   |Original Reporter | @weissi      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | @gregomni      |
   |Priority          | Medium      |

   

   md5: 3a7dc68bd8326dd7437f59d25f32964e

  </details>

**Issue Description:**

The following program might not be quite correct (because the trailing closure syntax is used but it's not actually the last argument)

    func test(_ body: () -> Void, file: StaticString = #file, line: UInt = #line) {}

    test {}

The diagnostic however is pretty bad:

    $ swift repro.swift
    repro.swift:3:1: error: cannot invoke 'test' with an argument list of type '(() -> ())'
    test {}
    ^
    repro.swift:3:1: note: expected an argument list of type '(() -> Void, file: StaticString, line: UInt)'
    test {}
    ^

it claims that it can't invoke `test` with an argument list of `() -> ()` which totally works though 🙂

**Comment by gregomni** [comment]
Swift 5.10, this now compiles successfully, as the combination of trailing closures and arguments with defaults are handled better.
