### ISSUE TITLE
[SR-11560] OSS Swift 5.1 does not recognise macCatalyst as a platform.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift#53965]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11560      |
   |Radar             | rdar://problem/68869888         |
   |Original Reporter | @Lukasa      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 5.1 (swift-5.1-RELEASE)  
Target: x86_64-unknown-linux-gnu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @devincoughlin      |
   |Priority          | Medium      |

   

   md5: b512a39de2bfe46bfd0ebc6402d51081

  </details>

**Issue Description:**

If you have an availability annotation that wants to version guard the Catalyst SDK, this triggers warnings when using the OSS version of Swift. This seems like an unnecessary hardship to bear until the next Swift release:

``` java
warning: unrecognized platform name 'macCatalyst'
@available(iOS 13.0, macOS 10.15, watchOS 6.0, tvOS 13.0, macCatalyst 13.0, *)
```

**Comment by tshortli** [comment]
I believe this was resolved by https://github.com/apple/swift/pull/29017.
