### ISSUE TITLE
[SR-11568] libdispatch build reorganization inadvertently disabled tsan/libdispatch tests on linux CI

### ISSUE THREAD

**Issue by finagolfin** [apple/swift#53973]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11568      |
   |Radar             | None         |
   |Original Reporter | @buttaface      |
   |Type              | Task    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Project Infrastructure    |
   |Labels            | Task        |
   |Assignee          | @yln      |
   |Priority          | Medium      |

   

   md5: b72328092c42d46829347587214cb38a

  </details>

**Issue Description:**

[Julian Lettner enabled several of these tests for linux in May](https://github.com/apple/swift/pull/24756), but [they depend on libdispatch.so and other files being built in a specific location](https://github.com/apple/swift/pull/24756/files#diff-f913ebb5bc611de19290c715fcdad913R986). [A libdispatch pull for Windows a month ago moved some of those libraries around](https://github.com/apple/swift-corelibs-libdispatch/pull/515) and disabled all these tests, likely by mistake.

I reported this a couple weeks ago as a comment on that libdispatch pull but got no response, so I'm filing it here, so someone gets those tests enabled again.

Also, it would be worthwhile for the CI to report when a pull disables several tests like this, rather than only reporting failed tests, so this doesn't keep happening.

**Comment by buttaface** [comment]
@yln, I checked and these still aren't being run on the linux CI. I think simply reordering the build to make sure libdispatch is built first should fix it, should I look into it?

**Comment by yln** [comment]
@gottesmm is addressing this here: #65829
