### ISSUE TITLE
[SR-11995] Long time compiling with redefenition methods of protocol extension 

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#54429]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11995      |
   |Radar             | rdar://problem/58455435         |
   |Original Reporter | Kuluum (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963591-5eaa6d2e-434a-4690-b1e4-e9a7771e1eb8.gz)

      
<details>
  <summary>Environment</summary>

Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ad20b65285017395b5ac7ed13df0d0a1

  </details>

**Issue Description:**

In case when typealias of associatedtype is not defined, after \~20 redefined method type checking(I guess) time grows exponentially with each new method added. With \~35 methods compile time of one file takes about 4 hours.

 

time swiftc -typecheck LongTypeCheck.swift

real 10m41.692s

**Comment by CodaFi** [comment]
Things have improved substantially here:

```
time swiftc -typecheck ~/Desktop/test.swift

________________________________________________________
Executed in   82.51 secs    fish           external
   usr time   82.16 secs    0.07 millis   82.16 secs
   sys time    0.21 secs    1.26 millis    0.20 secs
```
