### ISSUE TITLE
[SR-12096] Index missing references to initializers in Result extensions

### ISSUE THREAD

**Issue by kastiglione** [apple/swift#54532]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12096      |
   |Radar             | rdar://problem/58997223         |
   |Original Reporter | @kastiglione      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963621-4060512a-f4b0-4584-9edf-37bd0d008e29.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1ee7c9ff01d3a11c55b26c435d413b5a

  </details>

**relates to**:  
* [SR-12047](https://bugs.swift.org/browse/SR-12047) Types referenced with `is Foo` not in index  
* [SR-12102](https://bugs.swift.org/browse/SR-12102) Discrepancy in indexstore for function parameter references  

**Issue Description:**

In a specific case, the index is missing references to initializers added in an `enum` extension. In this case, `Result`.

This example is two parts. First, an extension on `Result` that adds initializers:

``` swift
extension Result {
    public init(value: Success) {
        self = .success(value)
    }

    public init(error: Failure) {
        self = .failure(error)
    }
}
```

The second part is calling these initializers with explicit types:

``` swift
let value = Result<Int, SomeError>(value: 5)
let error = Result<Int, SomeError>(error: .mistake)
```

In this case, the index does not contain a reference to the initializers. This can be seen in Xcode, where searching for references to those initializers produce only the initializers themselves.

This problem only happens when the generic types are explicit. If they're inferred, then the index does correctly include proper references. Compare:

``` swift
let value: Result<Int, SomeError> = Result(value: 5)
let error: Result<Int, SomeError> = Result(error: .mistake)
```

In this case, the index works as expected.

In the problem case, the indexstore record files of the callers does not contain references to the initializer's symbol (USR).

Attached is a sample project, and a couple screenshots showing Xcode can't find references even though they exist in the test target.

**Comment by keith** [comment]
Less noisy case:

```swift
struct A<T> {
  init(value: T) {}
}

_ = A(value: 1)
_ = A<Int>(value: 1)
```

```swift
/*
       struct=A=s:3foo1AV=definition
       | typealias.swiftGenericParameter=T=s:3foo1AV1Txmfp=definition, childOf
       v v  */
struct A<T> {
  /*
  constructor=init(value:)=s:3foo1AV5valueACyxGx_tcfc=definition, childOf
  |    parameter=value=s:3foo1AV5valueACyxGx_tcfcADL_xvp=definition, childOf
  |    |      typealias.swiftGenericParameter=T=s:3foo1AV1Txmfp=reference, containedBy
  v    v      v  */
  init(value: T) {}
}

/*
    struct=A=s:3foo1AV=reference
    constructor=init(value:)=s:3foo1AV5valueACyxGx_tcfc=reference, call
    v  */
_ = A(value: 1)
/*
    struct=A=s:3foo1AV=reference
    | struct=Int=s:Si=reference
    v v  */
_ = A<Int>(value: 1)
```

**Comment by keith** [comment]
https://github.com/apple/swift/pull/65597
