### ISSUE TITLE
[SR-12140] Regression inferring associated type from subscript in Swift 5.2

### ISSUE THREAD

**Issue by sharplet** [apple/swift#54575]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12140      |
   |Radar             | rdar://problem/59302412         |
   |Original Reporter | @sharplet      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode Version 11.4 beta (11N111s)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f35b3525440447b3a5d1194e80b83b19

  </details>

**Issue Description:**

This code no longer compiles in Swift 5.2 (Xcode 11.4 beta 1):

``` swift
struct Section: RandomAccessCollection {
    var isVisible: (MyProfileViewController) -> Bool
    var header: String?
    var rows: [UITableViewCell]
    var footer: ((MyProfileViewController) -> String?)?

    var startIndex: Int { rows.startIndex }
    var endIndex: Int { rows.endIndex }
    subscript(position: Int) -> UITableViewCell { rows[position] }
}
```

In order to get it to compile, an explicit typealias needs to be introduced:

``` swift
struct Section: RandomAccessCollection {
    typealias Element = UITableViewCell

    var isVisible: (MyProfileViewController) -> Bool
    var header: String?
    var rows: [UITableViewCell]
    var footer: ((MyProfileViewController) -> String?)?

    var startIndex: Int { rows.startIndex }
    var endIndex: Int { rows.endIndex }
    subscript(position: Int) -> UITableViewCell { rows[position] }
}
```

**Comment by slavapestov** [comment]
No longer reproduces.
