### ISSUE TITLE
[SR-12376] Jenkins fails to clean workspace periodically

### ISSUE THREAD

**Issue by compnerd** [apple/swift#54812]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12376      |
   |Radar             | None         |
   |Original Reporter | @compnerd      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | @shahmishal      |
   |Priority          | Medium      |

   

   md5: b5c614a5aae47c2c9a6aea0cb0efebdb

  </details>

**Issue Description:**

<https://ci-external.swift.org/job/swift-PR-windows/771/>

There are many Jenkins bug reports of spurious failures requiring the connection to be restarted as a workaround.  Seems related to JGit.

**Comment by shahmishal** [comment]
This should no longer be a problem as we have moved to different system for cleaning up workspace.
