### ISSUE TITLE
[SR-12387] Self key path literal function expression failure

### ISSUE THREAD

**Issue by stephencelis** [apple/swift#54824]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12387      |
   |Radar             | rdar://problem/60832831         |
   |Original Reporter | @stephencelis      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 5.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c7e6a520962d91be27623d1bf56a50ce

  </details>

**Issue Description:**

The following code fails to compile in a playground:

 

``` java
struct Identified<A>: Identifiable {
  var value: A
  var id: AnyHashable  init<B: Hashable>(_ value: A, by hashable: (A) -> B) {
    self.value = value
    self.id = hashable(value)
  }

//  init<B: Hashable>(_ value: A, by hashable: KeyPath<A, B>) {
//    self.value = value
//    self.id = value[keyPath: hashable]
//  }
}

Identified(1, by: \.self)
```

> cannot convert value of type 'WritableKeyPath\<\_, \_\>' to expected argument type '(Int) -\> B'

The commented-out overload seems to be required. When commented-in, the code behaves as expected.

In general, the "self" key path doesn't seem to work in expected situations. For example:

 

``` java
[Optional(1), 2, 3].compactMap(\.self)
```

 

> error: type of expression is ambiguous without more context

**Comment by xedin** [comment]
I think this has been fixed by combination of the following PRs - https://github.com/apple/swift/pull/69742, https://github.com/apple/swift/pull/69742. All of the expressions mentioned in the description now type-check.

Please use the latest main compiler snapshot to verify and re-open.
