### ISSUE TITLE
[SR-12422] Identity KeyPath literal is not working properly according to SE-0249

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#54861]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12422      |
   |Radar             | rdar://problem/62201019         |
   |Original Reporter | pacheco (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963709-dcf21474-59cf-4094-91e1-7f792cc8d480.gz)

      
<details>
  <summary>Environment</summary>

Xcode 11.4 (11E146)  
macOS 10.15.3 (19D76)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: dff283ffe45d137ca02f1f96d564a0f1

  </details>

**Issue Description:**

When attempting to use the identity `KeyPath` literal (`.self`) as a function according to functionality in [SE-0249](https://github.com/apple/swift-evolution/blob/master/proposals/0249-key-path-literal-function-expressions.md), the code fails to compile. Example:

``` swift
let x: [Int?] = [1, nil, 2]
let x2 = x.compactMap(\.self) // doesn't work -> "Key path value type 'Optional<_>' cannot be converted to contextual type '_'"
let x3: [Int] = x.compactMap(\Int?.self) // doesn't work -> "Cannot convert value of type 'WritableKeyPath<Int?, Int?>' to expected argument type '(Int?) throws -> Int?'"
```

However if one assigns an identity `KeyPath` to a variable of type `(Root) -> Root`, it succeeds:

``` swift
let xFunc: (Int?) -> Int? = \Int?.self
let x4 = x.compactMap(xFunc) // works
```

It also succeeds if we define an operator on `KeyPath`:

``` swift
prefix operator ^
prefix func ^ <Root, Value>(_ kp: KeyPath<Root, Value>) -> (Root) -> Value { { root in root[keyPath: kp] } }

let x5 = x.compactMap(^\.self) // works
```

More examples can be found on the attached playground.

From my very basic understanding of this (and please excuse me if I'm saying something stupid!), could it be that the Identity `KeyPath`'s special handling (from [SE-0227](https://github.com/apple/swift-evolution/blob/master/proposals/0227-identity-keypath.md) is not playing well with the new logic implemented in [SE-0249](https://github.com/apple/swift-evolution/blob/master/proposals/0249-key-path-literal-function-expressions.md) to convert `KeyPath`'s to functions? Because if `.self` is translated to a `MutableKeyPath<T, T>` and `MutableKeyPath: KeyPath`, it should work like any other `KeyPath`.

Thanks!

**Comment by kateinoigakukun** [comment]
All of the examples in the description are now working. Closing as well as https://github.com/apple/swift/issues/55343#issuecomment-1846305300
