### ISSUE TITLE
[SR-12483] Weak variables deallocated too quickly in optimised (-O) builds

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#54923]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12483      |
   |Radar             | rdar://problem/62202438         |
   |Original Reporter | Aquis (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)  
Target: x86_64-apple-darwin19.4.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b87ad1b64715ab96b0b6f6b5dfcfb1c2

  </details>

**Issue Description:**

I noticed some strange errors in my iOS project when it was built for release in Swift 5.2, and I was eventually able to create a small test case. It seems that weak variables are deallocated too quickly (or at the very least, they have different semantics between optimised and unoptimised builds). The following produces a different output depending on optimisation:

``` swift
final class Object {}

final class Wrapper {
    weak var contents: Object? // Weak object declared here
    
    init(contents: Object? = nil) {
        self.contents = contents
    }
}

func test() -> Object? {
    let object: Object // Requires separate lines to replicate
    object = Object() // Strong variable should keep it alive
    
    let wrapper = Wrapper(contents: object)
    
    return wrapper.contents
}

print(test() as Any)
```

Interestingly, as annotated above, the declaration and the assignment have to be on different lines to replicate. The non-optimised build operates how I expect, the optimised build does not.

**Comment by amomchilov** [comment]
Looks like this issue can be closed
