### ISSUE TITLE
[SR-12605] #sourceLocation doesn't allow underscores in line numbers

### ISSUE THREAD

**Issue by beccadax** [apple/swift#55049]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12605      |
   |Radar             | rdar://problem/62202395         |
   |Original Reporter | @beccadax      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Near-master, 15 April 2019

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Parser, StarterBug        |
   |Assignee          | matthewspear (JIRA)      |
   |Priority          | Medium      |

   

   md5: 41076a6957823a7ff8a7fce6be55225d

  </details>

**Issue Description:**

``` none
  1> #sourceLocation(file: "a.swift", line: 1_000)
error: /var/folders/mw/1rhv6fn96gb8swwkt8zycwph0000gn/T/repl1-101710..swift:2:40: error: expected starting line number for #sourceLocation directive
#sourceLocation(file: "a.swift", line: 1_000)
                                       ^
  1> #sourceLocation(file: "a.swift", line: 1000)
  2> 1_000
$R0: Int = 1000
  3>  
```

Underscore separators in `#sourceLocation` directives probably ought to be supported.

**Comment by jaspergeer** [comment]
I'd like to give this a shot as my first contribution, seems like something I should be able to figure out. Could I be assigned to this?
