### ISSUE TITLE
[SR-12646] Ambiguous type name error in Module Interface

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#55090]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12646      |
   |Radar             | rdar://problem/62202466         |
   |Original Reporter | leavez (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963764-15f00166-d225-427c-8c13-d937d06d5406.gz)

      
<details>
  <summary>Environment</summary>

Test on xcode 11.4 and Swift toolchain snapshot 2020-04-19

##  

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, ParseableInterfaces        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 61fa54ea5c7a0723325eb34c5b8b74da

  </details>

**Issue Description:**

## Problem

The generated module interface file below will got an error when parsed by xcode. 

<img src="image-2020-04-22-02-10-11-427.png" width="595" height="110" />

``` swift
// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.3-dev (LLVM 5e4413896d, Swift f0df46771f)
// swift-module-flags: -target x86_64-apple-ios8.0-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -Onone -module-name A
@_exported import A
import Foundation
import Swift
public protocol Pt {
  typealias AnotherName = Swift.String
}
@_hasMissingDesignatedInitializers public class Name<T> : A.Pt {
  public typealias AnotherName = Swift.Int
  public func hi() -> A.Name<T>.AnotherName
  @objc deinit
}
```

("A" is the name of the framework)

Source code 

``` swift
public protocol Pt {
    typealias AnotherName = String
}

public class Name<T>: Pt {
    public typealias AnotherName = Int
    public func hi() -> AnotherName {
        return 0
    }
}
```

## Steps to Reproduce

1.  build a framework with the source above, with "Build Libraries for Distribution" enabled

2.  delete the .swiftinterface files in the framework

3.  add the generated framework to another project, import and build

## Why Important

The module interface cannot be used , which means module stability never achieve its goal.

**Comment by AnthonyLatsis** [comment]
> If I change the source code to reference AnotherName as a member of Name, I get the same error:

This appears to work as expected now. Closing.
