### ISSUE TITLE
[SR-12880] Autocomplete for multiple trailing closures produces invalid results

### ISSUE THREAD

**Issue by jshier** [apple/swift#55327]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12880      |
   |Radar             | rdar://problem/63627617         |
   |Original Reporter | @jshier      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963808-ee710fb8-d2d6-4acd-af4d-706aad43f55d.gz)

      
<details>
  <summary>Environment</summary>

Swift 5.3 toolchain from 5/19, Xcode 11.5.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 17f28578e5367659b43e96dc75a4fa99

  </details>

**Issue Description:**

New API is being built for Alamofire involving multiple closures, so it was designed with multiple trailing closure syntax in mind.

``` swift
func withAllRequests(completingOn queue: DispatchQueue = .main,
                     perform action: @escaping (Request) -> Void,
                     completion: (() -> Void)? = nil)
```

Xcode 11.5 with the latest 5.3 toolchain offers the completions shown in the attached screenshot:

-   The full function definition, with all parameters, which completes well (though there should be more combinations available).

-   The second, which appears to suggest only the non-defaulted closure argument.

Accepting the second suggestion inserts the following:

``` swift
session.withAllRequests { (<#Request#>) in
            <#code#>
        }
```

Due to the parameter the compiler considers this invalid, as the single closure syntax is only compatible with the last closure. The only way to enter the non-defaulted closure by itself is with the full function syntax.

Tagging @benlangmuir since he appeared to be working on the autocomplete during the review thread.

**Comment by bnbarham** [comment]
Not sure when this was fixed, but we now provide the following completions:
```
key.sourcetext: "withAllRequests(completingOn: <#T##DispatchQueue#>, perform: <#T##(Request) -> Void#>, completion: <#T##(() -> Void)?##(() -> Void)?##() -> Void#>)",
key.sourcetext: "withAllRequests(perform: <#T##(Request) -> Void#>)",
```

Expanding either placeholder in the first case will expand to multiple trailing closures:
```
  withAllRequests(completingOn: <#T##DispatchQueue#>) { <#Request#> in
    <#code#>
  } completion: {
    <#code#>
  }
```

Expanding `perform` in the second case expands just to the single trailing closure:
```
  withAllRequests { <#Request#> in
    <#code#>
  }
```
