### ISSUE TITLE
[SR-12943] "Associated type references itself" when defining default value.

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#55389]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12943      |
   |Radar             | None         |
   |Original Reporter | Lantua (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a3ae998d37de719ba38b7d2cee24e226

  </details>

**Issue Description:**

This fails to compile,

``` swift
struct Composite<Foo> { }
protocol Chain {
  associatedtype Next: Chain
  associatedtype Foo = Composite<Next.Foo> // Associated type `Foo` references itself.
}
```

But it shouldn't need to, since,  
1) conforming types can **override** \`Foo\`, and  
2) It's not referring directly to \`Foo\`, but \`Next.Foo\`.

This is one work around (from @filip-sakel over the Swift's forum):

``` swift
typealias CompositeWithoutFoo<Value> = Composite<Value.Foo> where Value: Chain

protocol Chain {
  associatedtype Next: Chain
  associatedtype Foo = CompositeWithoutFoo<Next> // ✅ 
}
```

So either the checking is too restrictive, or the second code block should be illegal. Either way, this looks like a bug.

**Comment by slavapestov** [comment]
Fixed on main, adding a regression test.
