### ISSUE TITLE
[SR-12977] Code completion: missing completion of typealias from conformed-to protocol

### ISSUE THREAD

**Issue by nathawes** [apple/swift#55423]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12977      |
   |Radar             | rdar://problem/64231415         |
   |Original Reporter | @nathawes      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | CodeCompletion    |
   |Labels            | Bug, FoundByStressTester        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0bdd5edca24eb4c55a8fd6c4c8933d36

  </details>

**Issue Description:**

Reproducer on master:

``` java
struct ButtonStyleConfiguration {}
protocol ButtonStyle {
  typealias Configuration = ButtonStyleConfiguration
}

struct BorderedBarButtonStyle: ButtonStyle {
  init() { }
  func makeBody(configuration: /*complete here*/Configuration) {} // Configuration not suggested
}
```

**Comment by ahoppen** [comment]
No longer reproduces on main.
