### ISSUE TITLE
[SR-13020] Concrete associated type leaks through opaque type

### ISSUE THREAD

**Issue by typesanitizer** [apple/swift#55465]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13020      |
   |Radar             | rdar://problem/64405639         |
   |Original Reporter | @typesanitizer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0f390e9405cf0f9b08177e5e6fe29492

  </details>

**Issue Description:**

Consider the following code:

``` java
protocol Container {
    associatedtype Item: Equatable
    var count: Int { get }
    subscript(i: Int) -> Item { get }
}
extension Array: Container where Element: Equatable { }
func f<T: Equatable>(_ items: [T]) -> some Container {
    return items
}
let x = f([0])
let y = f([1])
let z = x[0] == y[0]
```

I don't think this should compile, but it does! \`x\` and \`y\` are different containers, how/why is the compiler able to tell that the different calls to \`f\` are returning opaque types with the same associated type? I think the only information that should be accessible is that the element is *Equatable*. This means that \`x\[0\] == x\[1\]\` would compile but \`x\[0\] == y\[0\]\` would not. It seems like information about the concrete type is "leaking through" and being used to check the call to \`==\`.

**Comment by slavapestov** [comment]
x and y are different containers, but they have the same type because the opaque return type is known to always have the same underlying type. So even though the compiler doesn't know the types of x[0] and y[0], it knows they're the same.
