### ISSUE TITLE
[SR-13255] [swift-driver] Darwin-specific argument validation

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#55695]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13255      |
   |Radar             | None         |
   |Original Reporter | owenvoorhees (JIRA User)      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Improvement, StarterBug, swift-driver        |
   |Assignee          | srinikhil07 (JIRA)      |
   |Priority          | Medium      |

   

   md5: fc54056e575ca013a03072c8d28f5400

  </details>

**Issue Description:**

The current argument validation implementation specific to Darwin platforms (macOS, iOS, etc.) is incomplete. [DarwinToolchain.validateArguments](https://github.com/apple/swift-driver/blob/d0a312b1d4728e798a19db5b92b93dbbaa57fb6d/Sources/SwiftDriver/Toolchains/DarwinToolchain.swift#L141) contains a number of TODOs for porting over validation steps from the C++ driver. The original implementation of these checks can be found here: https://github.com/apple/swift/blob/d3ecf8848ede62368896410ec6b891c1a34f2e4c/lib/Driver/DarwinToolChains.cpp#L932

**Comment by AnthonyLatsis** [comment]
@owenv Could you see if we can close this (the associated pull request is merged)? Thanks.

@shahmishal Could we transfer this issue to the swift-driver repo?

**Comment by owenv** [comment]
Yes, this can be closed now, thanks for checking
