### ISSUE TITLE
[SR-13304] Remove explicit use of Python2

### ISSUE THREAD

**Issue by tbkka** [apple/swift#55744]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13304      |
   |Radar             | None         |
   |Original Reporter | @tbkka      |
   |Type              | Sub-task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Sub-task        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 38c0ab4bee9aefa3422c3e8887cda475

  </details>

**Parent-Task**:  
* [SR-13280](https://bugs.swift.org/browse/SR-13280) Migrate Swift to Python 3  

**Issue Description:**

gyb is still pinned to python2.7  
Several md documentation files refer to Python 2.7

\`git grep -i python2\` for a complete list of references to Python 2.

**Comment by dduan** [comment]
done in the following patches:

https://github.com/apple/swift/issues/58286
https://github.com/apple/swift/issues/58325
https://github.com/apple/swift/issues/58334
