### ISSUE TITLE
[SR-13301] Xcode 11.6 Code Coverage is incorrect

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#55741]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13301      |
   |Radar             | None         |
   |Original Reporter | sachinvas16 (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963905-bcb05167-b074-434e-8e37-a0abb5e551be.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 289ee2a2c0d01eadf38ec9760f27838a

  </details>

**Issue Description:**

Xcode 11.6 doesn't show all the files during code coverage.

**Comment by hamishknight** [comment]
Are you able to provide a project that reproduces the issue? I suspect if this was indeed being built with whole-module optimization, this may have been fixed by #61158, which stops us from dropping coverage maps if a function gets optimized out.

**Comment by hamishknight** [comment]
Please verify with Xcode 14.3 beta 2 and re-open if you are still experiencing this issue.
