### ISSUE TITLE
[SR-13326] Compilation very slow with Swift 5.2.4; 10 hours for ~300 files

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#55766]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13326      |
   |Radar             | None         |
   |Original Reporter | efirestone (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Running tests on a MacBook Pro 15', 2019. Xcode 11.6 (latest App Store version), with Swift 5.2.4. The slowness happens in both debug and release builds.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0813b7bead8b04071267775c8b205c8d

  </details>

**Issue Description:**

We're seeing very slow compile times for some files in our library. The files are all codegen'd, none of them are particularly long, and not all of them exhibit this behavior (although they're not all the same either). We had about 300 of these files in the same library and the library took around 10 hours to successfully compile. The attached project has those files broken up into 13 smaller libraries, which cuts the time down to about 7 minutes, but some particular files are taking several minutes on their own while others compile in milliseconds.

The methods which seem to be taking the longest (.init and .encode) do contain large switch statements, so it's (maybe) possible this is related to SR-13205 (although this is 5.2.4, not 5.3).

**Comment by benrimmington** [comment]
Duplicate of #55767
