### ISSUE TITLE
[SR-13576] UIDatePicker crashes app when enabling/disabling 24-hour time multiple times

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56014]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13576      |
   |Radar             | rdar://problem/69308996         |
   |Original Reporter | tassiomm (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

**XCode Version:** 11.3.1

**Device:** iPhone 6s Plus

**Device iOS Version:** 13.6

 Xcode Project:

**Swift 5**

**Target:** iOS 13.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: a3245dac2c3ee77de8e819d6cd8bd781

  </details>

**Issue Description:**

`UIDatePicker` will crash if user switches 24-hour time multiple times and opening the app between switches.

**Reproducible test case**:

Create a new Single View App Project in Swift. Go to ViewController that XCode already created and paste the code:

```swift
 import UIKit
 class ViewController: UIViewController {
     private var someDatePicker = UIDatePicker()
 }
```

Steps:

-   Before running the app make sure Settings \> General \> Date & Time \> 24-Hour Time is enabled.
-   Run the app
-   Close the app (do NOT kill it)
-   Switch 24-Hour Time toggle
-   Open the app again
-   Repeat the last 3 steps 3 Times
-   The app will crash and the console output should print the following exception:
    ```swift
    -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 2]
    ```

**Comment by AnthonyLatsis** [comment]
This sounds very much like an issue with UIKit (not the compiler or Standard Library). @tassiomm Assuming you are the author, please use the feedback assistant for these sorts of SDK bugs.
