### ISSUE TITLE
[SR-13646] Redundant conformance to protocols in generated swiftinterface file

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56082]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13646      |
   |Radar             | rdar://problem/69882459         |
   |Original Reporter | sascha (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963973-6521259f-550f-4562-bd46-ac547462eff0.gz)

      
<details>
  <summary>Environment</summary>

Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)  
Target: x86_64-apple-darwin19.6.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 27dfa65d430da11428d1847383f15e75

  </details>

**Issue Description:**

When building a framework with BUILD_LIBRARY_FOR_DISTRIBUTION set to YES and a public class derives from another public class which implements an internal protocol which derives from a public protocol, the generated .swiftinterface files have "Redundant conformance to protocol" errors.

This code

``` java
public protocol PublicProtocol {}

internal protocol InternalProtocol: PublicProtocol {}

public class A: InternalProtocol {}
public class B: A {}
```

generates this .swiftinterface file

``` java
// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
// swift-module-flags: -target x86_64-apple-ios14.0-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -Onone -module-name InterfaceGenerationBug
import Foundation
@_exported import InterfaceGenerationBug
import Swift
public protocol PublicProtocol {
}
@_hasMissingDesignatedInitializers public class A {
  @objc deinit
}
@_inheritsConvenienceInitializers @_hasMissingDesignatedInitializers public class B : InterfaceGenerationBug.A {
  @objc deinit
}
extension InterfaceGenerationBug.A : InterfaceGenerationBug.PublicProtocol {}
extension InterfaceGenerationBug.B : InterfaceGenerationBug.PublicProtocol {}
```

Notice the redundant conformance of class B to protocol PublicProtocol.

It's possible to work around the issue by explicitly specifying conformance to protocol PublicProtocol for class A. A sample project is attached. The issue also appears with Xcode 12.2 beta 2.

**Comment by tshortli** [comment]
This was fixed by https://github.com/apple/swift/pull/60897.
