### ISSUE TITLE
[SR-13723] Generic initializer with constrained parameter of generic structure doesn't recognize when the structure's generic parameter matches

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56120]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13723      |
   |Radar             | rdar://problem/70273586         |
   |Original Reporter | CTMacUser (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 12.0.1 (12A7300) on a MacBook Air (2014) running a macOS 11 Big Sur beta off an external drive.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 813fde2b1f0889d9005a65572954e5e3

  </details>

**Issue Description:**

Here's a pared down example:

``` java
struct Heap<Base> { // 2
    var storage: Base

    init<T: Collection>(base: T) where T.SubSequence == Base {
        storage = base[...] // 1
    }
}
```

The brackets at (1) are marked with an error of "Cannot assign value of type 'T.SubSequence' to type 'Base'" with a fix-it of "Insert ' as! Base'." But it looks like the code should work.

There's some variants.

-   If the header at (2) is changed to "Heap2\<Base: Collection\>," then a second error appears on (1), but on "storage." It's a nonsensical "Generic struct 'Heap2' requires that 'Base' conform to 'Collection'." If I change the protocol at (2) to either BidirectionalCollection or RandomAccessCollection, this new error goes away.

-   If I change the constraint at (2) back to Collection, then add another constraint of "where Base.SubSequence == Base," the error in the previous point comes back, along with a third error: "Generic struct 'Heap2' requires the types 'Base' and 'Base.SubSequence' be equivalent," which seems nonsensical too. If I change the main constraint on (2) back to BidirectionalCollection or RandomAccessCollection, both the error from the previous point and from this point go away.

There is a forum thread at \<https://forums.swift.org/t/problem-with-conditional-matching-for-an-initializer/41106\>.

**Comment by xedin** [comment]
This has been fixed in 5.7 or earlier, code snippet in the description should and does type-check now.
