### ISSUE TITLE
[SR-13733] .swiftinterface file should not add default intializer if we have explicit in base class

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56130]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13733      |
   |Radar             | rdar://problem/70298053         |
   |Original Reporter | Hailin (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963988-5e858614-adee-4b38-bc69-ec1ad6fb0b65.gz)

      
<details>
  <summary>Environment</summary>

This issue happens since Xcode 11 GM Seed 2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 4a36bee285ec81863a9a5a6cf58296af

  </details>

**Issue Description:**

**we had submitted a feedback ticket (FB7301109) since Sep, 2019. But never get response from Apple. we have to try report this issue on forums. swift.**

issue Description:  
There will be build error if use a framework which is generate with below code

import Foundation

open class ObjectBase {  
public init()  
{ }  
}

open class UntypedList : ObjectBase {  
public init(capacity:Int)  
{ }  
}

open class EmptyList : UntypedList {  
public init() {  
super.init(capacity: 5)  
}  
}

List the reproduce steps:

1.  Use above sample code to create a framework

2.  Archive it.

3.  xcodebuild -create-xcframework to create xcframework. (Refer page: <https://appspector.com/blog/xcframeworks> )

4.  Create another project, then import the created xcframework at step 3.

Actually result:  
In the generated \*.swiftinterface file in the xcframework Modules folder. the code looks like below:

// swift-interface-format-version: 1.0  
// swift-compiler-version: Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)  
// swift-module-flags: -target x86_64-apple-ios12.4-simulator -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -O -module-name XCInitTest  
import Foundation  
import Swift  
@\_exported import XCInitTest  
open class ObjectBase {  
public init()  
[@objc](https://forums.swift.org/u/objc) deinit  
}  
open class UntypedList : XCInitTest.ObjectBase {  
public init(capacity: Swift.Int)  
override public init()  
[@objc](https://forums.swift.org/u/objc) deinit  
}  
open class EmptyList : XCInitTest.UntypedList {  
public init()  
override public init(capacity: Swift.Int)  
[@objc](https://forums.swift.org/u/objc) deinit  
}

Expected result:  
The line 'override public init()' in open class UntypedList  
And  
The line 'public init()' in open class EmptyList  
should not be generated, because the ObjectBase has its explicit Initializers. no need Default Initializers for ObjectBase anymore.  
so no need to override init() in its subclass.

**Comment by tshortli** [comment]
This is a duplicate of https://github.com/apple/swift/issues/56231 which was fixed by https://github.com/apple/swift/pull/36333.
