### ISSUE TITLE
[SR-13742] Allow "case let value as [Int]" and remove the diagnostic that it is not implemented

### ISSUE THREAD

**Issue by ktoso** [apple/swift#56139]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13742      |
   |Radar             | rdar://problem/70336498         |
   |Original Reporter | @ktoso      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, StarterBug        |
   |Assignee          | @ktoso      |
   |Priority          | Medium      |

   

   md5: d4a4c363d3b5f5288974990ee8ab9dfc

  </details>

**Issue Description:**

The following code:

``` swift
extension Array {
    func lol() -> String {
        switch self {
            case let value as [Int]: return "int"
            default: return "no"
        }
    }
}
```

yields:

``` java
// Swift version 5.3-dev (LLVM 2ea629d94ab01c3, Swift d3108db2429b29b)
// Target: x86_64-apple-darwin20.1.0
$SWIFT_EXEC Hello.swift
Hello.swift:5:28: error: collection downcast in cast pattern is not implemented; use an explicit downcast to '[Int]' instead
            case let value as [Int]: return "int"
                           ^
```

@jckarter suggests that implementation wise this isn't true anymore, just that the diagnostic is outdated.

**Comment by simanerush** [comment]
@AnthonyLatsis please assign me
