### ISSUE TITLE
[SR-13898] "redundant conformance constraint" warning shows up (again?)

### ISSUE THREAD

**Issue by ffried** [apple/swift#56296]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13898      |
   |Radar             | rdar://problem/71914018         |
   |Original Reporter | @ffried      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)  
Target: x86_64-apple-darwin20.1.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c4edde1e87bd6db408682d93071bb508

  </details>

**relates to**:  
* [SR-5753](https://bugs.swift.org/browse/SR-5753) Remove "redundant same-type constraints" warnings  

**Issue Description:**

I'm not 100% sure, but I *think* this should have been removed by resolving SR-5753.

The following code triggers a warning on `associcatedtype Y: P0` which can be inferred by the `Z.X == Y` requirement on `associatedtype Z: P1` just beneath. While this is technically true, the warnings is not of much help, because it's hard to see this requirement of `Y: P0`, especially if `P0` and `P1` are defined in completely different modules.

``` swift
protocol P0 {}

protocol P1 {
   associatedtype X: P0
}

protocol P2 {
   associatedtype Y: P0
   associatedtype Z: P1 where Z.X == Y
}
```

Output:

``` java
TooMuchWarning.swift:8:22: warning: redundant conformance constraint 'Self.Y': 'P0'
   associatedtype Y: P0
                     ^
TooMuchWarning.swift:9:22: note: conformance constraint 'Self.Y': 'P0' implied here
   associatedtype Z: P1 where Z.X == Y
                     ^
```

**Comment by slavapestov** [comment]
Redundant requirement warnings are now disabled by default.
