### ISSUE TITLE
[SR-13906] Error message is unclear when a type conforms to AnyObject or a composition of it

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [apple/swift#56304]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13906      |
   |Radar             | rdar://problem/71913170         |
   |Original Reporter | @WowbaggersLiquidLunch      |
   |Type              | Improvement    |
   |Status            | In Progress        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Apple Swift version 5.3.2 (swiftlang-1200.0.44.1 clang-1200.0.32.28)

macOS 10.15.7 (19H15); x86_64-apple-darwin19.6.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Improvement, DiagnosticsQoI, StarterBug, TypeChecker        |
   |Assignee          | aniketiq (JIRA)      |
   |Priority          | Medium      |

   

   md5: fc60657a00f25cb82f7af51339e8e32b

  </details>

**Issue Description:**

Currently, the error message is "Inheritance from non-protocol type ..." when a type tries to conform to `AnyObject` or a composition of `AnyObject` and some other protocols:

``` swift
protocol P {}
typealias Q = P & AnyObject
struct S: Q {}
enum T: P & AnyObject {}
struct U: P, AnyObject {}
```

``` swift
error: inheritance from non-protocol type 'Q' (aka 'P & AnyObject')
struct S: Q {}
       ^
error: inheritance from non-protocol type 'P & AnyObject'
enum T: P & AnyObject {}
     ^
error: inheritance from non-protocol, non-class type 'AnyObject'
class U: P, AnyObject {}
       ^
```

It would be better if the error message is "non-protocol 'T' cannot conform to 'AnyObject'":

``` swift
error: non-protocol 'S' cannot conform to composition 'Q' (aka 'P & AnyObject')
struct S: Q {}
       ^
error: non-protocol 'T' cannot conform to composition 'P & AnyObject'
enum T: P & AnyObject {}
     ^
error: non-protocol 'U' cannot conform to 'AnyObject'
class U: P, AnyObject {}
       ^
```

**Comment by swiftlysingh** [comment]
Hey folks 👋 , was checking the error message on swift playgrounds, I got `Only protocols can inherit from 'AnyObject'` instead of expected (mentioned in issue) `error: inheritance from non-protocol type 'P & AnyObject'`.  

The message seams similar to what is required from the issue. What should be done here? 

@AnthonyLatsis @WowbaggersLiquidLunch

**Comment by xwu** [comment]
Good catch. Looks like #41537 has resolved this issue.
