### ISSUE TITLE
[SR-14035] Compiler toolchain build error on M1 mac

### ISSUE THREAD

**Issue by johnno1962** [apple/swift#56426]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14035      |
   |Radar             | rdar://problem/73014167         |
   |Original Reporter | @johnno1962      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, Project Infrastructure    |
   |Labels            | Bug        |
   |Assignee          | @shahmishal      |
   |Priority          | Medium      |

   

   md5: 10a69735b885909bbf12d3e950153532

  </details>

**Issue Description:**

HI Apple,

I've tried any number of things but have been unable to build a toolchain using swift/main & Xcode 12.3 and the swift/utils/build-toolchain script. It seems to be something to do with supporting multiple architectures for macOS and simulator w/lipo. This warning may be relevant:

warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: lib/swift/watchsimulator/i386/libswiftCompatibility51.a will be fat and ar(1) will not be able to operate on it

**Comment by johnno1962** [comment]
A year on, I've just tried again and basically utils/build-toolchain basically no longer works (on an M1 at least). The issues I mentioned above are still there along with a few new undefined symbols related to half-floats and the bootstrapping process to bring Swift sources into the compiler doesn't seem to work, failing to find a usable version of `swiftc`. I don't have an intel machine to test if it "just works" on that architecture.

**Comment by shahmishal** [comment]
@edymtt Looks like you had a fix for this previously, I wonder if something changed recently.

**Comment by johnno1962** [comment]
edymt's fix made a big difference but there are many other issues, at least on my machine. My clone is from a week ago.

**Comment by johnno1962** [comment]
An update on building a toolchain on M1, I've been able to get the build past the previous road blocks I mentioned by performing the whole build under rosetta! 

I've not been able to get a toolchain just yet as it trips up at the very last trying to build swift-driver multi-architecture but it does seem to indicate this isn't a holding it wrong issue or specific to my particular clone. The problem is very easy to replicate if you run build-toolchain on an M1. I'm sure someone with the right llvm and CMake knowledge could clear this up in an instant.

**Comment by johnno1962** [comment]
To finish the week  on a high note, I've been rewarded with a toolchain built on an M1 by running the whole thing inside Rosetta2. I had to edit the build.ninja file for libYams.a inside the swift-driver project to correct the -arch for target arm64 then build on the command line, edit that build out and retry the toolchain script. Seems like an obscure CMake problem for this configuration. Note, the "rosetta" trick only works with recent versions of CMake (I used 3.23.1 and Xcode 13.4)

**Comment by gottesmm** [comment]
@johnno1962 I am assuming that normal-ish builds work on M1? Are you only seeing this issue with build-toolchain?

**Comment by johnno1962** [comment]
Yes, I think the build-script with and without --xcode works now.

**Comment by gottesmm** [comment]
@johnno1962 I imagine that the issue here is that build-toolchain I don't think on our CI is being run on M1 machines. So I imagine that some incompatibilities have snuck in. @shahmishal we really should have a bot running build-toolchain on an Apple Silicon machine (maybe once a day) like the status bot.

**Comment by johnno1962** [comment]
I couldn't agree more but the first step would be investigating the problems I'm seeing and getting it working.

**Comment by johnno1962** [comment]
Bump.

**Comment by johnno1962** [comment]
Just did a fresh clone and build-toolchain. Worked 💯 Thanks to everyone who sorted this out.
