### ISSUE TITLE
[SR-14043] Swift.org Language Guide - Bad Hyperlink

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56434]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14043      |
   |Radar             | rdar://problem/73203070         |
   |Original Reporter | Micah333 (JIRA User)      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Task, Documentation        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 69855f9a540484ce9b1de20d5815f866

  </details>

**Issue Description:**

<https://docs.swift.org/swift-book/LanguageGuide/MemorySafety.html>

Memory Safety \> Understanding Conflicting Access to Memory \> Note

The hyperlink "Thread Sanitizer" points to:

<https://developer.apple.com/documentation/code_diagnostics/thread_sanitizer>

which presents a "Page Not Found" error from apple.com.

**Comment by amartini51** [comment]
Fixed in http://github.com/apple/swift-book/commit/5ae2129faa5394715bb54aaa966efb2f672aebab
