### ISSUE TITLE
[SR-14074] Calling async functions without async produces incorrect diagnostic

### ISSUE THREAD

**Issue by jshier** [apple/swift#56463]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14074      |
   |Radar             | rdar://problem/73460922         |
   |Original Reporter | @jshier      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 12.3, swift-DEVELOPMENT-SNAPSHOT-2021-01-19-a, 2020 iMac i9, macOS command line tool

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Concurrency        |
   |Assignee          | @etcwilde      |
   |Priority          | Medium      |

   

   md5: b8d957bcfa7a07a895e9a145a8df7793

  </details>

**is duplicated by**:  
* [SR-14150](https://bugs.swift.org/browse/SR-14150) Bogus Diagnostic When 'await' is Missing in async Closure Parameter  

**Issue Description:**

There appear to have been previous attempts at improving the diagnostic produced when calling async functions without the async keyword. However, this behavior seems to have regressed (or I'm in the wrong context).

This code:

``` swift
func makeNetworkCall(id: String) async throws -> String {}

runAsyncAndBlock {
    do {
        try makeNetworkCall(id: "1")
    } catch {
        
    }
}
```

Produces the diagnostic "'async' in a function that does not support concurrency". If I understand correctly it should instead say that the async keyword is required and offer a fixit to add it.

**Comment by hborla** [comment]
Sorry, I forgot to close this when I merged the PR!
