### ISSUE TITLE
[SR-14179] Upstream LLVM broke a bunch of Swift tests

### ISSUE THREAD

**Issue by davezarzycki** [apple/swift#56557]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14179      |
   |Radar             | rdar://problem/74189761         |
   |Original Reporter | @davezarzycki      |
   |Type              | Improvement    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Improvement        |
   |Assignee          | Aam54 (JIRA)      |
   |Priority          | Medium      |

   

   md5: f6d064e4766210eb1ea78e7f45019d7d

  </details>

**Issue Description:**

By default, \`lit\` in upstream now complains about unused check prefixes. This can be disabled but the bugs that it complains about seem legit. Here is the list:

Swift(linux-x86_64) :: APINotes/versioned.swift  
Swift(linux-x86_64) :: ClangImporter/clang_builtins.swift  
Swift(linux-x86_64) :: ClangImporter/enum-anon-sized.swift  
Swift(linux-x86_64) :: DebugInfo/value-witness-table.swift  
Swift(linux-x86_64) :: Demangle/clang-function-types.swift  
Swift(linux-x86_64) :: Driver/actions-dsym.swift  
Swift(linux-x86_64) :: Driver/actions.swift  
Swift(linux-x86_64) :: Driver/batch_mode_parseable_output_cancellation.swift  
Swift(linux-x86_64) :: Driver/embed-bitcode.swift  
Swift(linux-x86_64) :: IDE/complete_pound_directive.swift  
Swift(linux-x86_64) :: IDE/complete_testable.swift  
Swift(linux-x86_64) :: IDE/complete_unresolved_members.swift  
Swift(linux-x86_64) :: IDE/reconstruct_type_from_mangled_name_import.swift  
Swift(linux-x86_64) :: IRGen/autorelease.sil  
Swift(linux-x86_64) :: IRGen/big_types_corner_cases_as_library.swift  
Swift(linux-x86_64) :: IRGen/boxed_existential.sil  
Swift(linux-x86_64) :: IRGen/c_layout.sil  
Swift(linux-x86_64) :: IRGen/cf.sil  
Swift(linux-x86_64) :: IRGen/class_resilience.swift  
Swift(linux-x86_64) :: IRGen/class_resilience_thunks.swift  
Swift(linux-x86_64) :: IRGen/condfail.sil  
Swift(linux-x86_64) :: IRGen/conditional_conformances.swift  
Swift(linux-x86_64) :: IRGen/conditional_conformances_future.swift  
Swift(linux-x86_64) :: IRGen/dead_method.swift  
Swift(linux-x86_64) :: IRGen/default_function_ir_attributes.swift  
Swift(linux-x86_64) :: IRGen/dllexport.swift  
Swift(linux-x86_64) :: IRGen/dllimport.swift  
Swift(linux-x86_64) :: IRGen/enum_resilience.swift  
Swift(linux-x86_64) :: IRGen/enum_value_semantics.sil  
Swift(linux-x86_64) :: IRGen/enum_value_semantics_future.sil  
Swift(linux-x86_64) :: IRGen/enum_value_semantics_special_cases.sil  
Swift(linux-x86_64) :: IRGen/exact_self_class_metadata_peephole.swift  
Swift(linux-x86_64) :: IRGen/exclusivity.sil  
Swift(linux-x86_64) :: IRGen/fixed_layout_class.swift  
Swift(linux-x86_64) :: IRGen/framepointer.sil  
Swift(linux-x86_64) :: IRGen/generic_metatypes.swift  
Swift(linux-x86_64) :: IRGen/generic_metatypes_future.swift  
Swift(linux-x86_64) :: IRGen/generic_vtable.swift  
Swift(linux-x86_64) :: IRGen/indirect_argument.sil  
Swift(linux-x86_64) :: IRGen/keypaths.sil  
Swift(linux-x86_64) :: IRGen/lifetime.sil  
Swift(linux-x86_64) :: IRGen/metadata.swift  
Swift(linux-x86_64) :: IRGen/objc_simd.sil  
Swift(linux-x86_64) :: IRGen/opaque_result_type.swift  
Swift(linux-x86_64) :: IRGen/opaque_values_irgen.sil  
Swift(linux-x86_64) :: IRGen/open_boxed_existential.sil  
Swift(linux-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1ancestor-1distinct_use-1st_ancestor_nongeneric-external-resilient.swift  
Swift(linux-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_class.swift  
Swift(linux-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_function.swift  
Swift(linux-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-1distinct_use_tuple.swift  
Swift(linux-x86_64) :: IRGen/prespecialized-metadata/class-fileprivate-inmodule-1argument-2ancestor-1du-1st_ancestor_nongeneric-fileprivate-2nd_ancestor_generic.swift  
Swift(linux-x86_64) :: IRGen/protocol_resilience_thunks.swift  
Swift(linux-x86_64) :: IRGen/related_entity.sil  
Swift(linux-x86_64) :: IRGen/simple_partial_apply.sil  
Swift(linux-x86_64) :: IRGen/special_protocols.sil  
Swift(linux-x86_64) :: IRGen/struct_with_resilient_type.swift  
Swift(linux-x86_64) :: IRGen/undef.sil  
Swift(linux-x86_64) :: IRGen/yield_once.sil  
Swift(linux-x86_64) :: IRGen/yield_once_big.sil  
Swift(linux-x86_64) :: IRGen/yield_once_biggish.sil  
Swift(linux-x86_64) :: IRGen/yield_once_indirect.sil  
Swift(linux-x86_64) :: Interpreter/protocol_lookup.swift  
Swift(linux-x86_64) :: Interpreter/protocol_lookup_jit.swift  
Swift(linux-x86_64) :: Misc/floatTruncation.swift  
Swift(linux-x86_64) :: ModuleInterface/lazy-vars.swift  
Swift(linux-x86_64) :: ModuleInterface/property_wrappers.swift  
Swift(linux-x86_64) :: Reflection/inherits_Swift.swift  
Swift(linux-x86_64) :: Reflection/reflect_Enum_MultiPayload_value.swift  
Swift(linux-x86_64) :: Reflection/typeref_decoding_imported.swift  
Swift(linux-x86_64) :: SILGen/default_arg_multiple_modules.swift  
Swift(linux-x86_64) :: SILGen/generic_casts.swift  
Swift(linux-x86_64) :: SILGen/optional_to_bool.swift  
Swift(linux-x86_64) :: SILOptimizer/OSLogMandatoryOptTest.sil  
Swift(linux-x86_64) :: SILOptimizer/closure_lifetime_fixup.swift  
Swift(linux-x86_64) :: SILOptimizer/eager_specialize.sil  
Swift(linux-x86_64) :: SILOptimizer/eager_specialize_ossa.sil  
Swift(linux-x86_64) :: SILOptimizer/switch_enum_resilient.swift  
Swift(linux-x86_64) :: Sema/availability_nonoverlapping.swift  
Swift(linux-x86_64) :: Serialization/load-invalid-arch.swift  
Swift(linux-x86_64) :: multifile/require-layout-generic-arg-closure.swift  
Swift(linux-x86_64) :: multifile/require-layout-generic-arg-subscript.swift  
Swift(linux-x86_64) :: multifile/require-layout-generic-arg.swift  
Swift(linux-x86_64) :: stdlib/NewArray.swift.gyb

**Comment by tshortli** [comment]
This was addressed by https://github.com/apple/swift/pull/36584.
