### ISSUE TITLE
[SR-14215] Build target links to a symbol marked unavailable 

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56593]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14215      |
   |Radar             | rdar://problem/74357206         |
   |Original Reporter | martin9612 (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964086-c3add190-ac25-4c63-9aec-df5424e89be4.gz)

      
<details>
  <summary>Environment</summary>

Swift 5.3.2 on macOS 10.15.7 with Xcode 12.4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0d4b2c120ea5695cf2ee959f13050f85

  </details>

**Issue Description:**

I encountered dlopen errors when using a package in my project (<https://github.com/nalexn/ViewInspector>). I reduced the problem to the attached sample code. 

The failing code is a target containing a test (Tests/PackageLinkingTests/MyStructTests.swift). The target under test (Sources/PackageLinkingTests/MyStruct.swift) references SwiftUI. The test target build and executed on macOS fails do to not being able to resolve symbol not available on the platform.

 

SwiftUI exports `PageTabViewStyle` marked as

``` java
@available(iOS 14.0, tvOS 14.0, watchOS 7.0, *)
@available(macOS, unavailable)
```

MyStruct.swift extends `PageTabViewStyle`. The extension is marked as

``` java
@available(iOS 14.0, tvOS 14.0, watchOS 7.0, *)
@available(macOS, unavailable)
```

The test method in MyStructTest is marked as 

``` java
@available(iOS 14.0, tvOS 14.0, watchOS 7.0, *)
@available(macOS, unavailable)
```

It also contains a guard statement

``` java
guard #available(iOS 14.0, tvOS 14.0, watchOS 7.0, *) else { return }
```

 

Executing the test fails on a dynamic linker issue resolving `_$s7SwiftUI16PageTabViewStyleVMn`

``` java
2021-02-14 18:44:57.619 xctest[82498:1341308] The bundle “PackageLinkingPackageTests.xctest” couldn’t be loaded. Try reinstalling the bundle.
///     2021-02-14 18:44:57.619 xctest[82498:1341308] (dlopen(/Users/Martin/Downloads/Code/PackageLinking/.build/x86_64-apple-macosx/debug/PackageLinkingPackageTests.xctest/Contents/MacOS/PackageLinkingPackageTests, 265): Symbol not found: _$s7SwiftUI16PageTabViewStyleVMn
///       Referenced from: /Users/Martin/Downloads/Code/PackageLinking/.build/x86_64-apple-macosx/debug/PackageLinkingPackageTests.xctest/Contents/MacOS/PackageLinkingPackageTests
///       Expected in: /System/Library/Frameworks/SwiftUI.framework/Versions/A/SwiftUI
///      in /Users/Martin/Downloads/Code/PackageLinking/.build/x86_64-apple-macosx/debug/PackageLinkingPackageTests.xctest/Contents/MacOS/PackageLinkingPackageTests)
```

 

Having `@available` statements in the exporting library and all code paths I would expect that the compiled target does not link against `PageTabViewStyle` or avoids a failure by linking lazily

**Comment by tshortli** [comment]
I'm not able to reproduce this with the Swift 5.6 compiler. The references to SwiftUI symbols in the linked binary have weak linkage as expected:

```
> nm -mA PackageLinkingTests.xctest/PackageLinkingTests | grep "from SwiftUI" | xcrun swift-demangle
PackageLinkingTests.xctest/PackageLinkingTests:                  (undefined) weak external static SwiftUI.PageTabViewStyle.IndexDisplayMode.automatic.getter : SwiftUI.PageTabViewStyle.IndexDisplayMode (from SwiftUI)
PackageLinkingTests.xctest/PackageLinkingTests:                  (undefined) weak external type metadata accessor for SwiftUI.PageTabViewStyle.IndexDisplayMode (from SwiftUI)
PackageLinkingTests.xctest/PackageLinkingTests:                  (undefined) weak external SwiftUI.PageTabViewStyle.init(indexDisplayMode: SwiftUI.PageTabViewStyle.IndexDisplayMode) -> SwiftUI.PageTabViewStyle (from SwiftUI)
PackageLinkingTests.xctest/PackageLinkingTests:                  (undefined) weak external type metadata accessor for SwiftUI.PageTabViewStyle (from SwiftUI)
PackageLinkingTests.xctest/PackageLinkingTests:                  (undefined) weak external nominal type descriptor for SwiftUI.PageTabViewStyle (from SwiftUI)
```

`_$s7SwiftUI16PageTabViewStyleVMn` is the "nominal type descriptor for SwiftUI.PageTabViewStyle".
