### ISSUE TITLE
[SR-14277] Build error referencing RawValue.Stride for C imported enum

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56636]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14277      |
   |Radar             | rdar://problem/74794074         |
   |Original Reporter | lhunath (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 5.3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a81833ca13b773dcb09510610bc2d844

  </details>

**Issue Description:**

The following enum:

``` c
typedef NS_ENUM( uint32_t, Letter ) {
    a,
    b,
};
```

Causes the following code to fail in the compiler:

``` swift
extension Letter: Strideable {
    public func distance(to other: Self) -> RawValue.Stride {
        self.rawValue.distance( to: other.rawValue )
    }

    public func advanced(by n: RawValue.Stride) -> Self {
        Self( rawValue: self.rawValue.advanced( by: n ) )!
    }
}
```

With the following error:

``` java
<unknown>:0: error: circular reference
```

However, if we replace the imported type with a native equivalent:

``` swift
enum Letter : UInt32 {
    case a, b
}
```

The error goes away.

It is unclear what is supposedly circular about the code in question.

The error can also be avoided by changing this:

``` swift
    public func distance(to other: Self) -> RawValue.Stride {
```

into this:

``` swift
    public func distance(to other: Self) -> Int {
```

Suggesting the issue is with the resolution of `Self.Stride`

**Comment by slavapestov** [comment]
No longer reproduces, I'm adding a regression test.
