### ISSUE TITLE
[SR-14331] Trying to use swiftinterface file made by 5.3.2 results in a build error in 5.4

### ISSUE THREAD

**Issue by igor-makarov** [apple/swift#56690]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14331      |
   |Radar             | rdar://problem/75325576         |
   |Original Reporter | @igor-makarov      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 5.4

Xcode 12.5 beta 3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 69af16cd807265eb689fd78289feb49e

  </details>

**Issue Description:**

Having a deprecation warning in a `swiftinterface` results in a compile error in Swift 5.4 (Xcode 12.5 beta 3). The file builds fine in the released Xcode.

This is the offending code snippet, reduced to the problematic code by experiment:

 

``` java
@available(*, unavailable, renamed: "Y")
public enum X {
 case case1
 public static func == (a: X, b: X) -> Swift.Bool
}
@available(*, unavailable, renamed: "Y")
extension X : Swift.Equatable {}
```

The error is 

``` java
Conformance of 'X' to 'Equatable' is unavailable
```

**Comment by tshortli** [comment]
I'm not able to reproduce this with a compiler built from `main`. Starting with source like this:

```
@available(*, unavailable, renamed: "Y")
public enum X {
 case case1
}
```

The following `.swiftinterface`, which type checks successfully, is emitted:
```
// swift-interface-format-version: 1.0
// swift-compiler-version: Swift version 5.8-dev (LLVM 7cb891be0a2a60c, Swift 65c5573ad3bc26a)
// swift-module-flags: -target x86_64-apple-macosx10.9 -swift-version 4 -swift-version 5 -enable-library-evolution -module-name TestModule
import Swift
import _Concurrency
import _StringProcessing
@available(*, unavailable, renamed: "Y")
public enum X {
  case case1
  public static func == (a: TestModule.X, b: TestModule.X) -> Swift.Bool
  public func hash(into hasher: inout Swift.Hasher)
  public var hashValue: Swift.Int {
    get
  }
}
@available(*, unavailable, renamed: "Y")
extension TestModule.X : Swift.Equatable {}
@available(*, unavailable, renamed: "Y")
extension TestModule.X : Swift.Hashable {}```
