### ISSUE TITLE
[SR-14355] Wrongly generated swiftinterface

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56714]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14355      |
   |Radar             | rdar://problem/75451691         |
   |Original Reporter | kolya-j (JIRA User)      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift 5.3 and 5.4  
xcode 12.4 and 12.5

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @tshortli      |
   |Priority          | Medium      |

   

   md5: fa046b49f2808701c4be1b39791167c9

  </details>

**Issue Description:**

If literal value are string - they are emitted to swiftinterface file

``` swift
public enum Special: Unicode.Scalar {
    case tab = "\u{0009}"
}
```

In swiftinterface it will looks like this:

``` swift
public enum Special : Swift.Unicode.Scalar {
  case tab
}
```

And during compilation we getting a error:  
"error: enum cases require explicit raw values when the raw type is not expressible by integer or string literal"

Best guess here is that swift see that literal are string and do not translate them to swiftinterface, without checking, that enum raw value is not a string

**Comment by tshortli** [comment]
Closing this as resolved with https://github.com/apple/swift/pull/41009
