### ISSUE TITLE
[SR-14362] Crash running closures accessed via Mirror

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift#56720]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14362      |
   |Radar             | rdar://problem/75481739         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)  
Target: x86_64-apple-darwin20.3.0

Apple Swift version 5.4 (swiftlang-1205.0.26.4 clang-1205.0.19.54)  
Target: x86_64-apple-darwin20.3.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug, RunTimeCrash        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 656953fcd979edcfc3bb456375a2014f

  </details>

**Issue Description:**

The following code crashes when f(object) is called

``` swift
struct Object {
    let s: String
    let function: (Object) -> String
}
let object = Object(s: "Hello") { obj in
    return "\(obj.s)"
}
let mirror = Mirror(reflecting: object)
for child in mirror.children {
    if let f = child.value as? (Object) -> String {
        print(f(object))
    }
}
```

 If instead I store \`function\` as \`Any\` as below then everything works

``` swift
struct Object {
    let s: String
    let function: Any
    init(s: String, function: @escaping MyFunction) {
        self.s = s
        self.function = function
    }
}
```

-There seems to have been a regression from 5.3 ~~\> 5.4 as well. While the following code works in 5.3.2 it fails in 5.4~~

``` swift
struct A { let b: Any }
struct Z { let b: () -> Int }
let x = Int.random(in: .min ... .max)
assert((Mirror(reflecting: A { x }).descendant("b") as! () -> Int)() == x)
assert((Mirror(reflecting: Z { x }).descendant("b") as! () -> Int)() == x)
```

**Comment by tbkka** [comment]
This is basically the same issue as #54696 [SR-12268]
