### ISSUE TITLE
[SR-14435] Update SE-0211 with change from review

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56791]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14435      |
   |Radar             | rdar://problem/76117089         |
   |Original Reporter | ken (JIRA User)      |
   |Type              | Task    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Standard Library    |
   |Labels            | Task        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: faddd3ac292ad1192f04d3a3ec682b3b

  </details>

**Issue Description:**

SE-0211 proposed (among many other additions) a property called "isDefined". The SE was accepted, and today has "Status: Implemented (Swift 5)".

It looks like changeset 3a2ad050 added the isDefined property, and then d0e93acb removed it. The final merged changeset (for PR#20520, in Nov 2018) doesn't include it or make any mention of it.

In the review thread, there's an exchange:

"If the proposed isDefined property is equivalent to generalCategory != .unassigned, then I’m not sure that it’s worth adding. Or it could be called isAssigned instead."

"Good point; the ICU documentation appears to indicate that this is the case, but I’ll run some tests to see if they differ at any code points just to be sure. The difference may only be in the surrogate code points, which can’t be created as a Unicode.Scalar anyway; if that’s the case, I’ll drop it."

<https://forums.swift.org/t/se-0211-add-unicode-properties-to-unicode-scalar/12121/23>

The review summary doesn't mention this change, however:

<https://forums.swift.org/t/accepted-se-0211-add-unicode-properties-to-unicode-scalar/13857>

I propose that SE-0211 should be updated with the removal of Unicode.Scalar.Properties.isDefined.  (It'd be great if it also mentioned what to use instead.)  I think that all other SE proposals I've read were eventually updated with the actual interface that shipped.

**Comment by stephentyrone** [comment]
We consider this issue to be resolved by https://forums.swift.org/t/update-se-0211-add-unicode-properties-to-unicode-scalar/59727.
