### ISSUE TITLE
[SR-14470] Compiler says 'failed to produce diagnostic for expression'

### ISSUE THREAD

**Issue by swift-ci** [apple/swift#56826]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14470      |
   |Radar             | rdar://problem/76546626         |
   |Original Reporter | rnikander (JIRA User)      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964155-4bc28187-e314-4bdf-a839-c78bf9524431.gz)

      
<details>
  <summary>Environment</summary>

Xcode 12.4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0f49f88326055af4a6985c1795fe2905

  </details>

**Issue Description:**

I have a project that failed to compile. It gave no useful error, just the message: "*failed to produce diagnostic for expression; please file a bug report*". So, I took the time and boiled down the code some; here's the report.

See attached project. If you try to build it, you should see the error. Looks like a type mismatch that's not reported.

**Comment by xedin** [comment]
Looks like the issue has been fixed during 5.8 development, the compiler is going to produce two errors:

```
error: generic struct 'TableView' requires that 'Txn' conform to 'Identifiable'

error: cannot convert value of type 'Binding<[ColumnWidthModel.ColID : CGFloat]>' (aka 'Binding<Dictionary<Int, CGFloat>>') to expected argument type 'Binding<Dictionary<InvestmentActivityColumn.ID, CGFloat>>'
```

Please use a recent 5.8 or main branch toolchain to verify.
