### ISSUE TITLE
[SR-14508] Failed to produce diagnostic on accidentally pattern-matching on struct

### ISSUE THREAD

**Issue by typesanitizer** [apple/swift#56860]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14508      |
   |Radar             | rdar://problem/76825572         |
   |Original Reporter | @typesanitizer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 52d4efe57340bfe4c2ff8f6c45bb7c5f

  </details>

**Issue Description:**

``` java
import SwiftUI

struct S {}

struct V: View {
  var s: S
  var body: some View {
    switch self.s {
    case .a(_): Text("")
    }
  }
}
```

This fails to produce a diagnostic on a recent-ish `main` compiler @ a93593a6f5b4dff39dbe5cf11ef4ef6722dcd46c (Apr 8).

**Comment by xedin** [comment]
Fixed in 5.7:

```
error: '_' can only appear in a pattern or on the left side of an assignment
    case .a(_): Text("")
            ^
error: type 'S' has no member 'a' 
    switch self.s {
                ^
```
