### ISSUE TITLE
[SR-14574] Generic parameter could not be inferred if I add a print statement or any other line

### ISSUE THREAD

**Issue by 4brunu** [apple/swift#56926]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14574      |
   |Radar             | rdar://problem/77465708         |
   |Original Reporter | @4brunu      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

macOS Big Sur 11.3 (20E232)  
Xcode Version 12.5 (12E262)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c803cb239fb04957e1b303199f40a2c1

  </details>

**Issue Description:**

This code compiles normally, but if I uncomment one of the following print statements, or any other line, this will no longer compile, and throw the following error: Generic parameter 'T' could not be inferred

\`\`\`  
class Example {  
static func test() {  
Task.retry(task: { taskCompletion in  
DispatchQueue.main.async {  
//print("Uncomment me to throw error: Generic parameter 'T' could not be inferred")  
taskCompletion(.success(()))  
//print("Uncomment me to throw error: Generic parameter 'T' could not be inferred")  
}  
}, completion: { result in

switch result {  
case .success:  
print("success")  
case .failure:  
print("failure")  
}  
})  
}  
}

enum Task {  
static func retry\<T\>(  
task: @escaping (\_ completion: @escaping (Result\<T, Error\>) -\> Void) -\> Void,  
completion: @escaping (Result\<T, Error\>) -\> Void  
) {  
task { result in  
completion(result)  
}  
}  
}  
\`\`\`

**Comment by xedin** [comment]
This is fixed by SE-0326, example is the description type-checks successfully in 5.7.
