### ISSUE TITLE
[SR-14882] Assertion failed: (!concreteBuffer && "concrete buffer already formed?!")

### ISSUE THREAD

**Issue by xAlien95** [apple/swift#57229]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14882      |
   |Radar             | rdar://problem/80277465         |
   |Original Reporter | @xAlien95      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964254-55d37ade-a47d-437b-8bec-e292f072e927.gz)

      
<details>
  <summary>Environment</summary>

Xcode 12.5 (12E262)  
Toolchain: Swift 5.5 Development Snapshot 2021-07

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3dc20867ae08a0bbbd29cafe65948059

  </details>

**Issue Description:**

The following code snippet results in an abort trap:

``` swift
var foo: Int {
  get throws { 3 }
}

print(try? foo)
```

**Comment by xAlien95** [comment]
The issue is solved on main. Should a test be added?

**Comment by kavon** [comment]
https://github.com/apple/swift/pull/68600

**Comment by kavon** [comment]
fixed by https://github.com/apple/swift/pull/68600
