### ISSUE TITLE
[SR-14880] [AutoDiff] Crash caused by storing a closure into a variable member of a struct

### ISSUE THREAD

**Issue by vojtamolda** [apple/swift#57227]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14880      |
   |Radar             | rdar://problem/80278725         |
   |Original Reporter | @vojtamolda      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964253-90971621-abc4-4de2-bd65-74d9315cd859.gz)

      
<details>
  <summary>Environment</summary>

macOS 11.4 with Swift development snapshot 2021-06-13:

    Apple Swift version 5.5-dev (LLVM 75998a7b14501e1, Swift 38a8b008bc66b11)
    Target: x86_64-apple-macosx11.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, Swift for TensorFlow    |
   |Labels            | Bug, AutoDiff        |
   |Assignee          | @rxwei      |
   |Priority          | Medium      |

   

   md5: 7e18065aaef6b8633a9c9c49581ccbd4

  </details>

**Issue Description:**

Hello all,

I think I stumbled upon a in bug in the compiler. The code chunk below crashes with a failed assertion. The stack trace is attached.

I did some experimentation and the trigger seems to be storing a multi (two and more) argument \`@differentiable\` closure as \`var\` member of a struct. Single argument closures work well and non-mutable members, i.e. \`let\` works too.

``` swift
import _Differentiation


typealias FunctionOfX = (@differentiable(reverse) (Double) -> Double)
struct Struct1Let { // Works
    let f: FunctionOfX
}
var s1l = Struct1Let() { $0 }

struct Struct1Var { // Works
    var f: FunctionOfX
}
var s1v = Struct1Var() { $0 }


typealias FunctionOfXY = (@differentiable(reverse) (Double, Double) -> Double)

struct Struct2Let { // Works
    let f: FunctionOfXY
}
var s2l = Struct2Let() { $0 * $1 }

struct Struct2Var { // Crashes
    var f: FunctionOfXY
}
var s2v = Struct2Var() { $0 * $1 }
```

**Comment by BradLarson** [comment]
This no longer reproduces with top-of-tree Swift, so I'll close it out.
