### ISSUE TITLE
[SR-15018] -warn-concurrency warns on shared mutable state in an inherently single-threaded program

### ISSUE THREAD

**Issue by Lukasa** [apple/swift#57347]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15018      |
   |Radar             | rdar://problem/81468110         |
   |Original Reporter | @Lukasa      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-5.5-DEVELOPMENT-SNAPSHOT-2021-07-31-a

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 5c872de2bbb3863b09f38d8a3f8a4851

  </details>

**Issue Description:**

Consider the following program:

``` java
var foo = [1]
_ = foo.dropFirst()
```

When compiled using `swiftc -warn-concurrency` the following warnings are emitted:

``` java
test2.swift:2:5: warning: reference to var 'foo' is not concurrency-safe because it involves shared mutable state
_ = foo.dropFirst()
    ^
test2.swift:1:5: note: var declared here
var foo = [1]
    ^
```

These are obviously bogus. This is almost certainly the result of this being top-level code, as this does not warn if we put it inside a function.

**Comment by hborla** [comment]
This was fixed with the implementation of SE-0343: Concurrency in Top-level Code in Swift 5.7. Specifically:

> Top-level global variables are implicitly assigned a @MainActor global actor isolation to prevent data races.
