### ISSUE TITLE
[SR-15027] Associated type is not inferred

### ISSUE THREAD

**Issue by jepers** [apple/swift#57355]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15027      |
   |Radar             | rdar://problem/81587765         |
   |Original Reporter | @jepers      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 12.5.1, macOS 11.4

Xcode 13 beta3, macOS 11.5

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 695475a3af144ed4ae3cd8dbf8d77adb

  </details>

**Issue Description:**

This compiles:

``` swift
protocol P {
  associatedtype T
  var a: T { get }
  var b: T { get }
}

struct S: P {
  let a: Int
  let b: T
} 
```

but this does not (surprisingly):

``` swift
protocol P {
  associatedtype T
  var a: T { get }
  var b: T { get }
  var c: T { get }
}

struct S: P {
  let a: Int
  let b: T
  let c: T // ERROR: Reference to invalid associated type 'T' of type 'S'
}
```

Changing property to func produces same behavior.

Another similar example:

``` swift
protocol P {
  associatedtype T
  func foo(x: T) -> T
}

struct S: P {
  func foo(x: Int) -> T { 123 } // ERROR: Reference to invalid associated type 'T' of type 'S'
}
```

Originating thread:  
<https://forums.swift.org/t/associatedtype-not-inferred/50947>

**Comment by slavapestov** [comment]
Fixed by https://github.com/apple/swift/pull/69826
