### ISSUE TITLE
[SR-15025] Function type syntax doesn't accept variadics or __owned

### ISSUE THREAD

**Issue by al45tair** [apple/swift#57353]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15025      |
   |Radar             | rdar://problem/81587763         |
   |Original Reporter | @al45tair      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 5a6e203f141e5efccb8f8c0c07f6f328

  </details>

**Issue Description:**

While writing a test, I discovered that you can't directly write the type of a function with a variadic argument, or indeed the type of one with an `__owned` argument. This seems wrong.

``` swift
Welcome to Apple Swift version 5.5 (swiftlang-1300.0.24.13 clang-1300.0.25.10).
Type :help for assistance.
 1> func Variadic(_ ints: Int...) -> Int { return 0 }
 2> type(of:Variadic)
$R0: ((Int...) -> Int).Type = (Int...) -> Int
 3> ((Int...) -> Int).self
error: repl.swift:3:6: error: expected type before '->'
((Int...) -> Int).self
   ^

 3> func OwnedString(_ s: __owned String) -> () {}
 4> type(of:OwnedString)
$R1: ((__owned String) -> ()).Type = (__owned String) -> ()
 5> ((__owned String) -> ()).self
error: repl.swift:5:11: error: expected ',' separator
((__owned String) -> ()).self
     ^
     ,
```

**Comment by eeckstein** [comment]
@al45tair Looks like this is working with a recent compiler. `swiftlang-1300.0.24.13` is really old
