### ISSUE TITLE
[SR-15052] Improve diagnostics around async let + AsyncSequence

### ISSUE THREAD

**Issue by typesanitizer** [apple/swift#57379]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15052      |
   |Radar             | rdar://problem/81758415         |
   |Original Reporter | @typesanitizer      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Concurrency, DiagnosticsQoI, TypeChecker        |
   |Assignee          | @LucianoPAlmeida      |
   |Priority          | Medium      |

   

   md5: 71b51e349065e8bfc7ac314c05c57831

  </details>

**Issue Description:**

Based on <https://bugs.swift.org/browse/SR-15049>

``` java
func testAsyncSequence<Seq: AsyncSequence>(_ seq: Seq) async throws where Seq.Element == Int {
    async let result: Int = seq.reduce(0) { $0 + $1 }
}
tmp.swift:2:15: warning: immutable value 'result' was never used; consider replacing with '_' or removing it
    async let result: Int = seq.reduce(0) { $0 + $1 }
              ^~~~~~
              _
tmp.swift:2:29: error: call can throw, but it is executed in a non-throwing autoclosure
    async let result: Int = seq.reduce(0) { $0 + $1 }
                            ^
tmp.swift:2:29: note: call is to 'rethrows' function, but a conformance has a throwing witness
    async let result: Int = seq.reduce(0) { $0 + $1 }
                            ^
```

For this, I don't understand what autoclosure is being referred to. Even so, say I pay attention to the first warning and replace the name with '\_'. This leads to

``` java
func testAsyncSequence<Seq: AsyncSequence>(_ seq: Seq) async throws where Seq.Element == Int {
    async let _: Int = seq.reduce(0) { $0 + $1 }
}
tmp.swift:2:24: error: call can throw but is not marked with 'try'
    async let _: Int = seq.reduce(0) { $0 + $1 }
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
tmp.swift:2:24: note: call is to 'rethrows' function, but a conformance has a throwing witness
    async let _: Int = seq.reduce(0) { $0 + $1 }
                       ^
tmp.swift:2:24: error: expression is 'async' but is not marked with 'await'
    async let _: Int = seq.reduce(0) { $0 + $1 }
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
                       await
tmp.swift:2:24: note: call is 'async'
    async let _: Int = seq.reduce(0) { $0 + $1 }
                       ^
```

It's not clear why async let requires explicit `try` or `await` on the RHS. After all, the following code compiles without errors and explicit `try` or `await`:

``` java
func f() async throws -> Int { 3 }
func g() async {
    async let x: Int = f()
}
```

**Comment by LucianoPAlmeida** [comment]
Fixed on main #41661
