### ISSUE TITLE
[SR-15049] async let and @rethrows protocol functions don't work together

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift#57376]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15049      |
   |Radar             | rdar://problem/81787316         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

Using Xcode V13 beta 4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c534d42e41bdbf13e3d2e82e17ba9ad5

  </details>

**Issue Description:**

The following code generates the compile error "Call can throw, but it is executed in a non-throwing autoclosure".

``` java
func testAsyncSequence<Seq: AsyncSequence>(_ seq: Seq) async throws where Seq.Element == Int {
    async let result: Int = seq.reduce(0) { $0 + $1 }
    try await print(result)
}
```

This appears to be caused by \`AsyncSequence.reduce\` being tagged rethrows. If you change it to throws there is no compile error. Shouldn't the async let also work for functions tagged as rethrows? 

 I have managed to reduce the issue down to the following. With the following protocol and struct

``` java
@rethrows protocol TestRethrowProtocol {
    func fn() async throws
}
extension TestRethrowProtocol {
    func testRethrow() async rethrows {
        try await self.fn()
    }
}

struct TestRethrowStruct: TestRethrowProtocol {
    func fn() async throws {}
}

```

The following code will generate the error "Call can throw, but it is executed in a non-throwing autoclosure".

``` java
let s = TestRethrowStruct()
async let rt: () = s.testRethrow()
try await rt

```

**Comment by LucianoPAlmeida** [comment]
Resolved on main and test case added in #61175
