### ISSUE TITLE
[SR-15107] Source compatibility suite: FAIL: Kickstarter-ReactiveExtensions, 4.0, 6b7887, ReactiveExtensions-TestHelpers-iOS, generic/platform=iOS

### ISSUE THREAD

**Issue by hamishknight** [apple/swift#57433]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15107      |
   |Radar             | None         |
   |Original Reporter | @hamishknight      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

swift-main-source-compat-suite  
swift-main-source-compat-suite-debug  
swift-5.5-source-compat-suite

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 56bf0812752b289cc5b94862b2371771

  </details>

**Issue Description:**

<https://ci.swift.org/job/swift-main-source-compat-suite/6084/>  
<https://ci.swift.org/job/swift-main-source-compat-suite-debug/4198/>  
<https://ci.swift.org/job/swift-5.5-source-compat-suite/139/>

Kickstarter-ReactiveExtensions 4.0, 6b7887, ReactiveExtensions-TestHelpers-iOS is failing to build with:

``` java
ld: library not found for -lswiftXCTest
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by justice-adams-apple** [comment]
I will reach out to the Kickstarter-ReactiveExtensions owner and request a source update. Will report back once I hear anything from them

**Comment by justice-adams-apple** [comment]
This was fixed with https://github.com/apple/swift/issues/57433
