### ISSUE TITLE
[SR-15130] MainActor class isolation not enforced by compiler, crash at runtime

### ISSUE THREAD

**Issue by mattneub** [apple/swift#57456]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15130      |
   |Radar             | None         |
   |Original Reporter | @mattneub      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Version 13.0 beta 5 (13A5212g)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Concurrency        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1e46bd58ca4115165939402c606cec3a

  </details>

**Issue Description:**

The following compiles:

``` java
actor MyActor {
    func actorMethod() async {
        let vc = ViewController()
    }
}
class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        Task {
            await MyActor().actorMethod()
        }
    }
}
```

It shouldn't. The actor is calling the initializer of a MainActor-bound class. That should be illegal. We're not even being asked to say \`await\`! (Not that it would help if we did say it.) And indeed, we crash at runtime because we tried to instantiate ViewController on a background thread. That is *exactly* the kind of crash that should be impossible because the compiler should be keeping us from committing such crimes.

**Comment by hborla** [comment]
This is diagnosed in Swift 5.10.

**Comment by mneuburg-livefront** [comment]
Thank you @hborla !
