### ISSUE TITLE
[SR-15174] guard statement coverage regression with Swift 5.5

### ISSUE THREAD

**Issue by keith** [apple/swift#57497]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15174      |
   |Radar             | rdar://problem/82934324         |
   |Original Reporter | @keith      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964305-3c0afb18-f18d-4159-bd0f-c5fc4ab6bd3c.gz)

      
<details>
  <summary>Environment</summary>

Xcode 12.5.1, Xcode 13.0 beta 5

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | @keith      |
   |Priority          | Medium      |

   

   md5: 75370a7f19c1587377ec648d5c77d622

  </details>

**Issue Description:**

If you have code like this:

``` none
public func foo() -> String {
    let a: String? = ""
    // next line should be covered because `let b` is hit
    guard let b = a else {
        fatalError()
    }

    return b
}
```

With Swift 5.4 the \`guard let b = a\` line was shown in code coverage as covered, which makes sense because the \`let b\` definitely happens. With 5.5 it is shown as not covered (I assume because the body of the guard inside {} is not hit)

5.4:

``` none
/private/tmp/CoverageRegression/Sources/CoverageRegression/CoverageRegression.swift:
    1|      1|public func foo() -> String {
    2|      1|    let a: String? = ""
    3|      1|    // next line should be covered because `let b` is hit
    4|      1|    guard let b = a else {
    5|      0|        fatalError()
    6|      1|    }
    7|      1|
    8|      1|    return b
    9|      1|}
   10|       |
```

5.5:

``` none
/private/tmp/CoverageRegression/Sources/CoverageRegression/CoverageRegression.swift:
    1|      1|public func foo() -> String {
    2|      1|    let a: String? = ""
    3|      1|    // next line should be covered because `let b` is hit
    4|      0|    guard let b = a else {
    5|      0|        fatalError()
    6|      1|    }
    7|      1|
    8|      1|    return b
    9|      1|}
   10|       |
```

In the attached SwiftPM project you can see this by running \`swift test --enable-code-coverage\` and then:

``` none
xcrun llvm-cov show -instr-profile=.build/debug/codecov/default.profdata .build/debug/CoverageRegressionPackageTests.xctest/Contents/MacOS/CoverageRegressionPackageTests
```

**Comment by hamishknight** [comment]
Looks like the fix for this got picked up in Swift 5.6
