### ISSUE TITLE
[SR-15211] @main entry point can't be overridden w/ async version

### ISSUE THREAD

**Issue by natecook1000** [apple/swift#57533]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15211      |
   |Radar             | rdar://problem/83316060         |
   |Original Reporter | @natecook1000      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964316-1d496770-51f3-4e7f-846d-5973fcdd88f5.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, Concurrency        |
   |Assignee          | @etcwilde      |
   |Priority          | Medium      |

   

   md5: 7c01a56413afe811e5538c7bde206099

  </details>

**Issue Description:**

If I annotate a type with `@main` that receives its `static func main()` method from a protocol extension, I can't override that `main()` method with one that is `async`, either at the concrete type level or through a more refined protocol. This gets in the way of being able to design backward deployable libraries that offer an async entry point on supported platforms.

The following example shows the issue. Uncommenting `@main` on either of the first two types works as expected, with the concrete override being called, and printing "Overridden" and "OverriddenThrows", respectively. Neither of the last two types succeeds in overriding the `main()` method, however, so "MainProtocol" is printed for both of them, instead of the expected "OverriddenAsync" and "AsyncMainProtocol".

``` java
// Protocols.swift

protocol MainProtocol {}

extension MainProtocol {
  static func main() {
    print("MainProtocol")
  }
}

protocol AsyncMainProtocol: MainProtocol {}

extension AsyncMainProtocol {
  static func main() async {
    print("AsyncMainProtocol")
  }
}
```

``` java
// Types.swift

// These two types work as expected:

// @main
struct Overridden: MainProtocol {
  static func main() {
    print("Overridden")
  }
}

// @main
struct OverriddenThrows: MainProtocol {
  static func main() throws {
    print("OverriddenThrows")
  }
}

// Neither of these types work as expected;
// the program prints "MainProtocol" instead of
// the more specific message.

// @main
struct OverriddenAsync: MainProtocol {
  static func main() async {
    print("OverriddenAsync")
  }
}

// @main
struct ViaExtension: AsyncMainProtocol {}
```

**Comment by etcwilde** [comment]
This should be fixed in https://github.com/apple/swift/pull/42142.
