### ISSUE TITLE
[SR-15293] Bad diagnostic for var + func overload with mismatched call

### ISSUE THREAD

**Issue by hamishknight** [apple/swift#57615]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15293      |
   |Radar             | None         |
   |Original Reporter | @hamishknight      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, DiagnosticsQoI, TypeChecker        |
   |Assignee          | @hamishknight      |
   |Priority          | Medium      |

   

   md5: ad00afc1090ec27f18670e5009c04bf1

  </details>

**Issue Description:**

The following gives an unhelpful diagnostic:

``` java
func foo(x: Int, y: Int) {}
var foo: Any = 0
foo(0, x: 0) // error: Cannot call value of non-function type 'Any'
```

It would be better if we diagnosed the labeling mismatch.

**Comment by AnthonyLatsis** [comment]
This issue still reproduces in a local scope. I discovered this when I tried to wrap the [test case] in a `do` block whilst migrating the test suite to GitHub issues:

https://github.com/apple/swift/blob/bd220d5fb526a105d14f426116186e0a4c671e4c/test/Constraints/diagnostics.swift#L1334-L1339

@xedin Is this a standalone, perhaps known, issue, or rather an oversight?

**Comment by hamishknight** [comment]
@AnthonyLatsis That's a different issue, we do not currently do overloading between local variables and local functions. For example, even if the function call is correct it still fails to compile:

```swift
do {
  var foo = 0
  func foo() {}
  foo() // error: Cannot call value of non-function type 'Int'
}
```

We always prefer the variable in this case because of how we model scoping in the AST lookup scopes. I'm pretty sure we have a bug for this somewhere but I can't immediately find it.
