### ISSUE TITLE
[SR-15411] Report cursor info information for literals

### ISSUE THREAD

**Issue by xAlien95** [apple/swift#57725]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15411      |
   |Radar             | None         |
   |Original Reporter | @xAlien95      |
   |Type              | Improvement    |
   |Status            | Reopened        |
   |Resolution        |     |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Source Tooling    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 085af8993d7db2679bf69ce553a24cc0

  </details>

**Issue Description:**

In the following test case, SourceKit should provide cursor info for the literal `42`, reporting its type as `Double`. Currently, it doesn’t return any information at all.

``` java
// RUN: %sourcekitd-test -req=cursor -pos=5:17 -print-raw-response %s -- %s

func foo() {
    let x = 1.2
    let y = x + 42
}
```

------------------------------------------------------------------------

Original report:

Currently, clicking on a literal while holding the **alt** key in Xcode won't trigger a Quick Help pop-up. It may be useful for newcomers to be able to get the inferred type of a literal simply by invoking Quick Help.

In the Swift Forums' thread <https://forums.swift.org/t/how-to-understand-the-int-double-conversion-in-swift/53063>, a new user stumbled upon

``` swift
3 + 0.14 // allowed

let three = 3
let rest = 0.14

3 + rest // allowed
0.14 + three // compile error
three + 0.14 // compile error
```

Quick Help triggered on the literal `3` at the first line or at the third-to-last line, would show

``` swift
3: Double
```

------------------------------------------------------------------------

A similar enhancement could be made to operator identifiers too, which would make easier for users to understand which overload has been chosen by the constraint solver.

**Comment by barinsim** [comment]
This seems like it is not being worked on? I would be happy contribute a patch.
