### ISSUE TITLE
[SR-15498] TSan reporting a data race between withUnsafeContinuation and UnsafeContinuation.resume

### ISSUE THREAD

**Issue by kmahar** [apple/swift#57803]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15498      |
   |Radar             | rdar://problem/85611836         |
   |Original Reporter | @kmahar      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift 5.5.1, Ubuntu 18.04

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f7adb8fcac57a1e4cbfc368d1aba4136

  </details>

**Issue Description:**

I’m sporadically seeing some TSan data race warnings reported in CI coming from tests using new concurrency features including NIO's async/await APIs. I can't reproduce it reliably but it has shown up twice now, in two different tests.

GitHub gist with symbolicated TSan output here: <https://gist.github.com/kmahar/6efcae377dcac00f43cd39e0656365e9>

Per @weissi:

> This looks like a Swift bug or TSan misunderstanding... Swift.withUnsafeThrowingContinuation is writing a word and Swift.UnsafeContinuation.resume is reading a word and its unsynchronised. And resume must obviously be callable from another thread than withUnsafeThrowingContinuation was called on...

In case it's helpful, here are the tests where I saw it:  
1) <https://github.com/mongodb/mongo-swift-driver/blob/2c740668e8f8f9b8dec03f132daae63a9224aea9/Tests/MongoSwiftTests/AsyncAwaitTests.swift#L150>  
2) <https://github.com/mongodb/mongo-swift-driver/blob/2c740668e8f8f9b8dec03f132daae63a9224aea9/Tests/MongoSwiftTests/AsyncAwaitTests.swift#L119>

Both tests involve a type conforming to `AsyncSequence`, not sure if that is a possible hint at the issue, but I'll update here if I see it in any more tests.

**Comment by weissi** [comment]
@kmahar is this still an issue for you?

**Comment by kmahar** [comment]
Hey @weissi, no, I think we can close this
