### ISSUE TITLE
[SR-15633] SourceKit-LSP: New files are not registered and changes to Package.swift are not reflected

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift#57929]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15633      |
   |Radar             | None         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |
   |Status            | In Progress        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

VSCode 1.6.3.2

swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)

Target: x86_64-apple-macosx12.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | @ahoppen      |
   |Priority          | Medium      |

   

   md5: 3cdf5d87457acc541fc8aa99b1919384

  </details>

**is duplicated by**:  
* [SR-15679](https://bugs.swift.org/browse/SR-15679) SourceKit-LSP: Adding platform requirement in Package.swift is not propagated  

**Issue Description:**

When a new file is created the SourceKit-LSP server doesn't seem to register it. You get basic function completion for standard swift objects, but none of the symbols in your project are available.

This was replicated in the new vscode plugin <https://github.com/swift-server/vscode-swift> but can also be replicated using the sample extension code that is part of the SourceKit-LSP project.

The current version of the vscode plugin does not send \`workspace/didChangeWatchedFiles\` events but I have a PR which does this <https://github.com/swift-server/vscode-swift/pull/98.> For example new file will send

``` java
[Trace - 17:10:42] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {
    "changes": [
        {
            "uri": "file:///Users/adamfowler/Developer/tools/sourcekit-lsp/Sources/SKCore/test.swift",
            "type": 1
        }
    ]
}
```

Even with sending these events I am not seeing this working. I can see the merged PR <https://github.com/apple/sourcekit-lsp/pull/376> which adds support for at least parsing these events, but from what I can see it doesn't actually process the add/remove event.

**Comment by ahoppen** [comment]
Implemented file watching for Package.swift in https://github.com/apple/sourcekit-lsp/pull/471.
