### ISSUE TITLE
[SR-15679] SourceKit-LSP: Adding platform requirement in Package.swift is not propagated

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift#57958]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15679      |
   |Radar             | rdar://91230538         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |
   |Status            | Reopened        |
   |Resolution        |     |
        
<details>
  <summary>Environment</summary>

swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)

Target: x86_64-apple-macosx12.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 89724567877c11a1c46009ed4a119296

  </details>

**duplicates**:  
* [SR-15633](https://bugs.swift.org/browse/SR-15633) SourceKit-LSP: New files are not registered and changes to Package.swift are not reflected  

**Issue Description:**

If I add an asynchronous function to a package SourceKit-LSP complains that concurrency is only available in macOS 10.15 or newer as it should. If I then go to my Package.swift and add a platform requirement eg

``` java
platforms: [.macOS(.v10_15)],
```

 SourceKit-LSP stills continues to display the error, until I restart the sourcekit-lsp server. 

Platform requirements in the Package.swift should be propagated as soon as the Package.swift is saved, not after restarting the server.

**Comment by ahoppen** [comment]
This turned out to be the same underlying issue as #57929, which was fixed in https://github.com/apple/sourcekit-lsp/pull/471.
