### ISSUE TITLE
[SR-15683] Program crashes when adding many tasks to a TaskGroup on Windows

### ISSUE THREAD

**Issue by MarSe32m** [apple/swift#57962]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15683      |
   |Radar             | None         |
   |Original Reporter | @MarSe32m      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Windows, snapshot: swift-DEVELOPMENT-SNAPSHOT-2021-12-23-a.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug, Concurrency, Windows        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 33cb31c018b26c413b20c4f4c1356a81

  </details>

**Issue Description:**

When adding many tasks to a TaskGroup, the program crashes when waiting for the tasks to finish. This doesn't happen on "relatively low" values of upperBound. For example when upperBound = 2500, the code executes fine to the end and prints "Done: 2500". But when for example upperBound \> 10000, the program crashes. I cannot reproduce this behavior on macOS or Linux.

``` swift
@main
struct App {
    static func main() async {
        let upperBound = 10000
        await withTaskGroup(of: Void.self) { group in 
            for i in 0..<upperBound {
                group.addTask {
                    print(i)
                }
            }
        }
        print("Done:", upperBound)
    }
}
```

**Comment by MarSe32m** [comment]
I cannot reproduce this anymore with nightly toolchain. I think the fix that resolved https://github.com/apple/swift/issues/57976 also resolved this.

**Comment by ktoso** [comment]
Great to hear, thanks for looping back to let us know :+1:
