### ISSUE TITLE
[SR-15703] MainActor isolation fails when synthesized async function (from Objective-C method) throws an error

### ISSUE THREAD

**Issue by toddreed** [apple/swift#57982]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15703      |
   |Radar             | rdar://89479707         |
   |Original Reporter | @toddreed      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964417-a9f623f3-7e4e-40e2-97ae-5066d46dcdc9.gz)

      
<details>
  <summary>Environment</summary>

``` java
swift -version
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx12.0
```

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @kavon      |
   |Priority          | Medium      |

   

   md5: c52cb58ce3c02bb5270368dfb10304f1

  </details>

**Issue Description:**

When calling a synthesized async function (i.e. synthesize from an Objective-C method) from a @MainActor function in Swift, execution resumes on a background thread instead of the main thread when the function throws an error.

Example: in the code the below, the assertion in the `catch` block fails.

``` java
@main
class MainActorBug {

    @MainActor
    static func main() async {
        let adder = Adder()
        do {
            let result = try await adder.add(-5)
            assert(Thread.isMainThread)
            print("The answer is \(result)")
        } catch {
            assert(Thread.isMainThread, "Not on main thread")
            print(error)
        }
    }
}
```

To reproduce:

``` java
unzip MainActorBug.zip
cd MainActorBug
swift run MainActorBug
```

**Comment by kavon** [comment]
The implementation of this fix introduced a regression. It has been reverted in https://github.com/apple/swift/pull/58397 , so I'm reopening this issue until that is resolved.
