### ISSUE TITLE
[SR-15745] Actor methods able to be called from escaping closure without `await`

### ISSUE THREAD

**Issue by CharlesJS** [apple/swift#58022]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15745      |
   |Radar             | rdar://90354322         |
   |Original Reporter | @CharlesJS      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

``` java
$ swiftc --version
swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx12.0
```

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 581829c2432961ebf61e130142bf32e5

  </details>

**Issue Description:**

This compiles, and I'm pretty sure it shouldn't:

 

``` java
import Dispatch

func someFunctionThatDoesWhoKnowsWhatWithThis(closure: @escaping () -> ()) {
  DispatchQueue.main.async { closure() }
}

class SomeClass {}

actor Foo {
  var bar = SomeClass()

  func setBar(_ bar: SomeClass) { self.bar = bar }
 
  func baz() {
    someFunctionThatDoesWhoKnowsWhatWithThis {
      self.setBar(.init()) // shouldn't this require an `await`?
    }
  }
}
```

The code inside the \`@escaping\` closure is no longer running inside the actor's context, so it seems like it shouldn't be able to call the actor's methods without an \`await\`, and that this is therefore a bug.

Forum thread with related discussion: <https://forums.swift.org/t/calling-escaping-closure-from-actor-context-why-dont-i-need-await-here/51029>

**Comment by DougGregor** [comment]
As recently noted in the forum thread,  this is an artifact of the compiler suppressing Sendable diagnostics in code that hasn't adopted concurrency. You can turn on completely checking manually with -`Xfrontend -warn-concurrency` (in Swift 5.6) or Swift 5.7's upcoming -`strict-concurrency=complete`. Doing so with my local Swift 5.7 build produces this:

```
t2.swift:4:30: warning: capture of 'closure' with non-sendable type '() -> ()' in a @Sendable closure
  DispatchQueue.main.async { closure() }
                             ^
t2.swift:4:30: note: a function type must be marked '@Sendable' to conform to 'Sendable'
  DispatchQueue.main.async { closure() }
                             ^
```

as it should.
