### ISSUE TITLE
[SR-15811] [cxx-interop] Calling methods with multiple non-trivial parameters causes a crash.

### ISSUE THREAD

**Issue by zoecarver** [apple/swift#58088]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15811      |
   |Radar             | None         |
   |Original Reporter | @zoecarver      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug, CxxInterop, StarterBug        |
   |Assignee          | @zoecarver      |
   |Priority          | Medium      |

   

   md5: fcd401452ed8e997d62f088bdc94afdc

  </details>

**Issue Description:**

Assertion failed: (arg.hasLValueType() == param.isIndirectInOut()), function emit, file swift/lib/SILGen/SILGenApply.cpp, line 2894.

 

For an easy reproducer, look at test/Interop/Cxx/class/method/methods.swift.

**Comment by egorzhdan** [comment]
This has been fixed awhile ago.
