### ISSUE TITLE
[SR-15825] Miscompilation leads to reference of unavailable type at runtime

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift#58099]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15825      |
   |Radar             | rdar://problem/88513988         |
   |Original Reporter | @NachoSoto      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164964450-2c5193c3-215c-43a3-828c-93740e878212.gz)

      
<details>
  <summary>Environment</summary>

Xcode 13.2.1 (13C100)  
swift-driver version: 1.26.21 Apple Swift version 5.5.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0364d04118c34e43f2a2f813254337a7

  </details>

**Issue Description:**

This code:

``` java
import StoreKit

@available(iOS 15.0, tvOS 15.0, macOS 12.0, watchOS 7.0, *)
class Mock {
    var mockTransaction: StoreKit.Transaction?
}
```

Compiles, but when run in a unit test host app on iOS 14.x it crashes at runtime:

    dyld: lazy symbol binding failed: Symbol not found: _$s8StoreKit11TransactionVMa
      Referenced from: /Users/nachosoto/Library/Developer/CoreSimulator/Devices/47674D70-24C0-455B-BAB3-D0A5C218C75A/data/Containers/Bundle/Application/DD93C493-D46E-4CB5-BA2B-D83B4B7C77BB/StoreKitTest.app/PlugIns/StoreKitTestTests.xctest/StoreKitTestTests
      Expected in: /System/Library/Frameworks/StoreKit.framework/StoreKit

\`StoreKit.Transaction\` isn't available until iOS 15.0, and neither is \`Mock\`.

## Repro steps:

-   Download attached project

-   Select \`StoreKitTest\` scheme

-   Test (on iOS 14.x)

**Comment by NachoSoto** [comment]
Is this still not fixed?

**Comment by tshortli** [comment]
Looks like this should have been fixed with https://github.com/apple/swift/pull/40741.
