### ISSUE TITLE
[SR-15870] TSan SEGV involving async generics

### ISSUE THREAD

**Issue by kmahar** [apple/swift#58135]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15870      |
   |Radar             | rdar://problem/88984561         |
   |Original Reporter | @kmahar      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Ubuntu 18.04, Swift 5.5.3

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       |     |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 1ad0573291fb0fe02c2fddceae3b6ce1

  </details>

**Issue Description:**

Trying to run a test I've written with the thread sanitizer I've run into a TSan SEGV with output as follows:

    ThreadSanitizer:DEADLYSIGNAL
    ==27024==ERROR: ThreadSanitizer: SEGV on unknown address (pc 0x7f8f5f6dd4e0 bp 0x7ba000022450 sp 0x7f8f552991a8 T27030)
    ==27024==The signal is caused by a READ memory access.
    ==27024==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
        #&#8203;0 swift::TargetMetadata<swift::InProcess>::isCanonicalStaticallySpecializedGenericMetadata() const crtstuff.c:? (libswiftCore.so+0x3de4e0)
        #&#8203;1 swift_checkMetadataState ??:? (libswiftCore.so+0x3e97ed)
        #&#8203;2 $s10MongoSwift10WriteModelOMr /home/ubuntu/mongo-swift-driver/<compiler-generated>:? (mongo-swift-driverPackageTests.xctest+0x3f885f)
        #&#8203;3 swift::MetadataCacheEntryBase<(anonymous namespace)::GenericCacheEntry, void const*>::doInitialization(swift::ConcurrencyControl&, swift::MetadataCompletionQueueEntry*, swift::MetadataRequest) Metadata.cpp:? (libswiftCore.so+0x3ebebd)
        #&#8203;4 _swift_getGenericMetadata(swift::MetadataRequest, void const* const*, swift::TargetTypeContextDescriptor<swift::InProcess> const*) Metadata.cpp:? (libswiftCore.so+0x3dfb1d)
        #&#8203;5 __swift_instantiateGenericMetadata crtstuff.c:? (mongo-swift-driverPackageTests.xctest+0x2fc618)
        #&#8203;6 $s10MongoSwift10WriteModelOMa ??:? (mongo-swift-driverPackageTests.xctest+0x3ddfd1)
        #&#8203;7 $s10MongoSwift0A10CollectionV9updateOne6filter0D07options7session7NIOCore15EventLoopFutureCyAA12UpdateResultVSgG0B4BSON12BSONDocumentV_ArA0M7OptionsVSgAA13ClientSessionCSgtF ??:? (mongo-swift-driverPackageTests.xctest+0x43ea50)
        #&#8203;8 $s10MongoSwift0A10CollectionV9updateOne6filter0D07options7sessionAA12UpdateResultVSg0B4BSON12BSONDocumentV_AnA0I7OptionsVSgAA13ClientSessionCSgtYaKF /home/ubuntu/mongo-swift-driver/Sources/MongoSwift/AsyncAwait/MongoCollection+Write+AsyncAwait.swift:118 (mongo-swift-driverPackageTests.xctest+0x367e9c)
        #&#8203;9 <null> <null> (0x7f8f5529aae7)ThreadSanitizer can not provide additional info.
    SUMMARY: ThreadSanitizer: SEGV crtstuff.c:? in swift::TargetMetadata<swift::InProcess>::isCanonicalStaticallySpecializedGenericMetadata() const
    ==27024==ABORTING 

This consistently repros for me on every run; you should be able to reproduce this yourself by checking out this branch: <https://github.com/mongodb/mongo-swift-driver/tree/tsan-crash-2>

And then running `swift test --sanitize thread --enable-test-discovery --filter testTSANCrash`

 The test as written would technically expect a local MongoDB server to be running but the TSan crash occurs before any attempt to connect to the server is actually made.

The method that seems to be the culprit is the [async version of updateOne on MongoCollection\<T\>](https://github.com/mongodb/mongo-swift-driver/blob/76061092f6390ad2d2c4c16f3930369a6613e644/Sources/MongoSwift/AsyncAwait/MongoCollection%2BWrite%2BAsyncAwait.swift#L112), which delegates to the EventLoopFuture returning [version](https://github.com/mongodb/mongo-swift-driver/blob/76061092f6390ad2d2c4c16f3930369a6613e644/Sources/MongoSwift/MongoCollection%2BWrite.swift#L127) of the same method, which delegates to the bulk write API defined [here](https://github.com/mongodb/mongo-swift-driver/blob/tsan-crash-2/Sources/MongoSwift/MongoCollection%2BBulkWrite.swift). That API accepts a generic enum `WriteModel<T>` which is being referenced in the output above.

This might be related somehow to SR-15475 which I filed a few months back and also involved a TSan SEGV that resulted from a generic method on a generic type delegating to another one of the type's generic methods... not sure though.

If there's any more information I can provide to help with this please let me know!

**Comment by weissi** [comment]
neither on Linux

```
root@d7bc64b7d2eb:/tmp/mongo-swift-driver# swift test --sanitize thread --enable-test-discovery --filter testTSANCrash
Building for debugging...
Build complete! (0.39s)
Test Suite 'Selected tests' started at 2023-05-16 15:04:58.041
Test Suite 'AsyncAwaitTests' started at 2023-05-16 15:04:58.045
Test Case 'AsyncAwaitTests.testTSANCrash' started at 2023-05-16 15:04:58.045
2023/05/16 15:04:58.0062: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:04:58.0572: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:04:59.0076: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:04:59.0582: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:00.0086: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:00.0591: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:01.0094: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:01.0603: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:02.0118: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:02.0625: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:03.0132: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:03.0640: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:04.0144: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:04.0656: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:05.0160: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:05.0663: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:06.0166: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
2023/05/16 15:05:06.0676: [ 2344]:    DEBUG:      monitor: [localhost:27017] command or network error occurred: Failed to connect to target host: localhost:27017
```

for

```
root@d7bc64b7d2eb:/tmp/mongo-swift-driver# swift -version
Swift version 5.8 (swift-5.8-RELEASE)
Target: aarch64-unknown-linux-gnu
```

**Comment by kmahar** [comment]
@weissi nope, seems to be fixed now given you get to the point of connecting to the mongodb server in the test there!
