### ISSUE TITLE
[SR-15948] silgen crash referencing class constant as default parameter value

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift#58209]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15948      |
   |Radar             | None         |
   |Original Reporter | @NachoSoto      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode Version 13.2.1 (13C100)  
swift-driver version: 1.26.21  
Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)  
Target: arm64-apple-macosx12.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 530afc59643ac3068182d99e61b8a6a1

  </details>

**Issue Description:**

## Code

```swift
class A {
    func test(_ a: String = Self.s) {}

    static let s = "test"
}
```

## Expected result

Code compiles

## Actual result

    1.  Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
    2.  
    3.  While evaluating request ASTLoweringRequest(Lowering AST to SIL for module XXX)
    4.  While silgen emitDefaultArgGenerator  SIL function "@$s7XXX1AC4testyySSFfA_".
     for expression at [/xxx.swift:15:26 - line:15:31] RangeText="Self."
    Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
    0  swift-frontend           0x0000000108c8b9c4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
    1  swift-frontend           0x0000000108c8aacc llvm::sys::RunSignalHandlers() + 128
    2  swift-frontend           0x0000000108c8c004 SignalHandler(int) + 292
    3  libsystem_platform.dylib 0x000000018a4244e4 _sigtramp + 56
    4  swift-frontend           0x0000000104bb2d0c swift::MetatypeInst::create(swift::SILDebugLocation, swift::SILType, swift::SILFunction*) + 108
    5  swift-frontend           0x0000000104b6ca80 swift::SILBuilder::createMetatype(swift::SILLocation, swift::SILType) + 116
    6  swift-frontend           0x00000001050345b0 swift::ASTVisitor<(anonymous namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void, void, swift::Lowering::SGFContext>::visit(swift::Expr*, swift::Lowering::SGFContext) + 6780
    7  swift-frontend           0x0000000105034dfc swift::ASTVisitor<(anonymous namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void, void, swift::Lowering::SGFContext>::visit(swift::Expr*, swift::Lowering::SGFContext) + 8904
    8  swift-frontend           0x0000000105028c28 swift::Lowering::SILGenFunction::emitRValueAsSingleValue(swift::Expr*, swift::Lowering::SGFContext) + 40
    9  swift-frontend           0x0000000105057954 SILGenLValue::visitRec(swift::Expr*, swift::Lowering::SGFAccessKind, swift::Lowering::LValueOptions, swift::Lowering::AbstractionPattern) + 1292
    10 swift-frontend           0x0000000105056e34 swift::ASTVisitor<SILGenLValue, swift::Lowering::LValue, void, void, void, void, void, swift::Lowering::SGFAccessKind, swift::Lowering::LValueOptions>::visit(swift::Expr*, swift::Lowering::SGFAccessKind, swift::Lowering::LValueOptions) + 7156
    11 swift-frontend           0x0000000105036518 swift::ASTVisitor<(anonymous namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void, void, swift::Lowering::SGFContext>::visit(swift::Expr*, swift::Lowering::SGFContext) + 14820
    12 swift-frontend           0x0000000105090d30 swift::Lowering::SILGenFunction::emitReturnExpr(swift::SILLocation, swift::Expr*) + 592
    13 swift-frontend           0x000000010504e1fc swift::Lowering::SILGenFunction::emitGeneratorFunction(swift::SILDeclRef, swift::Expr*, bool) + 1824
    14 swift-frontend           0x0000000104fcabe8 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 12420
    15 swift-frontend           0x0000000104fcc070 emitOrDelayFunction(swift::Lowering::SILGenModule&, swift::SILDeclRef, bool) + 376
    16 swift-frontend           0x0000000104fcbe6c swift::Lowering::SILGenModule::emitArgumentGenerators(llvm::PointerUnion<swift::ValueDecl*, swift::AbstractClosureExpr*, swift::FileUnit*>, swift::ParameterList*) + 180
    17 swift-frontend           0x0000000104fcbc08 swift::Lowering::SILGenModule::emitAbstractFuncDecl(swift::AbstractFunctionDecl*) + 48
    18 swift-frontend           0x0000000104fc7aa4 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 32
    19 swift-frontend           0x000000010509bb24 swift::ASTVisitor<(anonymous namespace)::SILGenType, void, void, void, void, void, void>::visit(swift::Decl*) + 160
    20 swift-frontend           0x0000000105097e24 (anonymous namespace)::SILGenType::emitType() + 252
    21 swift-frontend           0x0000000104fcff9c swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 120
    22 swift-frontend           0x0000000104fce7e0 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 3308
    23 swift-frontend           0x000000010508a294 swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 216
    24 swift-frontend           0x0000000104fd245c llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 612
    25 swift-frontend           0x0000000104fcfa4c swift::performASTLowering(swift::ModuleDecl*, swift::Lowering::TypeConverter&, swift::SILOptions const&) + 124
    26 swift-frontend           0x00000001049fd714 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 6936
    27 swift-frontend           0x0000000104956df8 main + 932
    28 dyld                     0x000000010b0490f4 start + 520

**Comment by AnthonyLatsis** [comment]
I wonder why there’s no the crash on godbolt with Swift 5.5. Must have been a regression in a patch release. Anyway, no crash with a near-main checkout.
```
error: covariant 'Self' type cannot be referenced from a default argument expression
  func test(_ a: String = Self.s) {}
                          ^
```

The original fix was #27220.
