### ISSUE TITLE
[SR-15981] Requirement Machine Compiler Error

### ISSUE THREAD

**Issue by stephencelis** [apple/swift#58242]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15981      |
   |Radar             | rdar://problem/90348994         |
   |Original Reporter | @stephencelis      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode Swift Development Snapshot 2022-03-13 (a)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: eacdebce298ca41337deea5a3c423874

  </details>

**Issue Description:**

Sorry Slava! This one's a bit harder to minimize. If you try to build this repo at this commit:

<https://github.com/pointfreeco/swift-parsing/commit/c818e86878776f8d90050ac4f26a453466d43dd4>

I get the following error:

> RequirementMachine generic signature minimization is broken:
>
> RequirementMachine says:      \<τ_0\_0, τ_0\_1, τ_0\_2, τ_0\_3, τ_0\_4, τ_0\_5, τ_0\_6, τ_0\_7 where τ_0\_0 == Route\<Parsers.MapConstant\<Always\<URLRequestData, ()\>, Episode\>\>, τ_0\_1 == Route\<Parsers.MapConversion\<ParserBuilder.ZipVO\<Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6\>, CasePath\<Episode, Comments\>\>\>, τ_0\_2 == Parsers.MapConversion\<ParserBuilder.ZipVO\<Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6\>, CasePath\<Episode, Comments\>\>, τ_0\_3 == ParserBuilder.ZipVO\<Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6\>, τ_0\_4 == CasePath\<Episode, Comments\>, τ_0\_5 == Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6 : ParserPrinter, τ_0\_6 == τ_0\_7, τ_0\_6.\[Parser\]Input == URLRequestData, τ_0\_6.\[Parser\]Output == Comments\>
>
> GenericSignatureBuilder says: \<τ_0\_0, τ_0\_1, τ_0\_2, τ_0\_3, τ_0\_4, τ_0\_5, τ_0\_6, τ_0\_7 where τ_0\_0 == Route\<Parsers.MapConstant\<Always\<URLRequestData, ()\>, Episode\>\>, τ_0\_1 == Route\<Parsers.MapConversion\<ParserBuilder.ZipVO\<Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6\>, CasePath\<Episode, Comments\>\>\>, τ_0\_2 == Parsers.MapConversion\<ParserBuilder.ZipVO\<Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6\>, CasePath\<Episode, Comments\>\>, τ_0\_3 == ParserBuilder.ZipVO\<Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6\>, τ_0\_4 == CasePath\<Episode, Comments\>, τ_0\_5 == Path\<PathComponent\<From\<Conversions.SubstringToUTF8View, String.UTF8View\>\>\>, τ_0\_6 : ParserPrinter, τ_0\_6 == τ_0\_7, τ_0\_6.\[Parser\]Input == URLRequestData\>

The package enables the following flags:

> -Xfrontend -enable-parameterized-protocol-types
>
> -Xfrontend -requirement-machine-protocol-signatures=on

I believe I had a build working that defined the same ".parser()" types as dedicated structs that could be initialized instead of static functions that returned opaque types, so the bug appears to have appeared from that refactor.

**Comment by slavapestov** [comment]
I wasn't able to reduce this but I'm pretty certain it is now fixed.
