### ISSUE TITLE
[SR-16051] Type inference from default expressions (SE-0347) assertion failure

### ISSUE THREAD

**Issue by stephencelis** [apple/swift#58312]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16051      |
   |Radar             | rdar://problem/90717725         |
   |Original Reporter | @stephencelis      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift trunk snapshot 2022-03-22

``` java
-Xfrontend -enable-experimental-type-inference-from-defaults
```

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 34f1aee692f061e16d66c587b9a935a8

  </details>

**Issue Description:**

The following code causes the compiler to crash with an assertion:

``` java
struct A<B> {
  let b: B
  init(_ b: B = ()) {
    self.b = b
  }
}

let a = A() 
```

> Assertion failed: (!empty()), function back, file SmallVector.h, line 295.

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/59218
