### ISSUE TITLE
[SR-16076] Compiler crashes in release mode when using compactMap with a key path to an @objc optional property

### ISSUE THREAD

**Issue by davedelong** [apple/swift#58337]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16076      |
   |Radar             | None         |
   |Original Reporter | @davedelong      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Xcode 13.3 and Xcode 13.2.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | swift    |
   |Labels            | Bug        |
   |Assignee          | @AnthonyLatsis      |
   |Priority          | Medium      |

   

   md5: 2b2d253ea8e84f4670e030c4b62dd6c5

  </details>

**Issue Description:**

Given this code:

``` swift
@objc protocol OptionalVar {
    @objc optional var name: String { get }
}

extension NSObject: OptionalVar { }

let objects = [
    NSObject(),
    NSObject(),
    NSObject()
] as Array<OptionalVar>

let names = objects.compactMap(\.name)
print("Names: \(names)")
```

This will build and run fine in debug mode (`-Onone`), but the compiler crashes when in building in release mode (`-O`).

**Comment by AnthonyLatsis** [comment]
Fixed in #42137
