### ISSUE TITLE
[SR-16095] SourceKit-LSP server expects a params parameter in the Shutdown request

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift#58354]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16095      |
   |Radar             | rdar://91288093         |
   |Original Reporter | @adam-fowler      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 5.6 (swift-5.6-RELEASE)  
Target: x86_64-unknown-linux-gnu

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | SourceKit-LSP    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a65d66860c8ab33ed0fd6f1d62c95a20

  </details>

**Issue Description:**

SourceKit-LSP server expects a params parameter in the Shutdown request when the [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#shutdown) says it shouldn't include any parameters.

Here is the request/response in the logs

 

``` java
[Trace - 10:19:45] Sending request 'shutdown - (20)'.[Trace - 10:19:45] Received response 'shutdown - (20)' in 2ms. Request failed: missing expected parameter: params (-32602).
```

 

This occurs on Linux but not on macOS.

**Comment by ahoppen** [comment]
Fixed by https://github.com/apple/sourcekit-lsp/pull/474.
