### ISSUE TITLE
Passing a pointer in a ternary doesn't let you refer to local varible. "error: use of extraneous '&'"

### ISSUE THREAD

**Issue by cobbal** [apple/swift#58389]
```swift
func takesAPointer(_ y: UnsafeMutablePointer<OpaquePointer?>?) {
    // ...
}

var x: OpaquePointer?
takesAPointer(&x) // works
takesAPointer(true ? (&x) : nil) // test.swift:9:22: error: use of extraneous '&'
```

Same error with or without the inner parens. This problem showed up when calling a C API that behaves differently in the presence of an out parameter.

swift-driver version: 1.26.21 Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
Target: x86_64-apple-macosx11.0

**Comment by xedin** [comment]
@cobbal This is expected behavior, use of `&` is restricted to argument positions only because it represents `inout`. In your example `x` is converted to `inout OpaquePointer?` via `&` and since `inout` is convertible to pointer `inout OpaquePointer?` gets converted into `UnsafeMutablePointer<OpaquePointer?>` implicitly. In ternary you have to construct UnsafeMutablePointer directly e.g. `true ? UnsafeMutablePointer(x) : nil`

**Comment by cobbal** [comment]
@xedin Ah, I see. (Assuming you meant `UnsafeMutablePointer(&x)`) . The error message is very unhelpful though. Is there any chance that could be improved?

**Comment by cobbal** [comment]
For comparison, if you try to use `&` in a bad place in C, clang will say:

```c
test.c:4:14: error: cannot take the address of an rvalue of type 'int'
    int* x = &2;
             ^~
```

**Comment by xedin** [comment]
Try as I wrote it:

```
takesAPointer(true ? UnsafeMutablePointer<OpaquePointer>(x) : nil)
```

**Comment by cobbal** [comment]
I can now see that this is working as intended. I still thing the error message is bad. Should I leave this open? close it and file a new issue for the message? Or just close it because the message isn't bug-worthy?

**Comment by xedin** [comment]
What would be a more helpful message?

**Comment by cobbal** [comment]
"cannot pass 'x' as an inout parameter here" maybe?

**Comment by xedin** [comment]
That would not be correct though because `inout` is not connected to the argument and talking about `non-inout` parameter doesn't make it better either, and when it comes to a ternary specifically we cannot really say `argument`, that's why we ended up with just extraneous use of `&`...

**Comment by hamishknight** [comment]
Could we maybe change the error to something like `'&' may only be used to pass inout argument to function`?

**Comment by xedin** [comment]
Or add that as a note maybe?

**Comment by xedin** [comment]
`'&' may only be used to pass an argument to 'inout' parameter`

**Comment by hamishknight** [comment]
Personally I've always felt the wording of `extraneous use of &` isn't too helpful, so I'd prefer it to be replaced.

>  `'&' may only be used to pass an argument to 'inout' parameter`

That sounds good to me!
