### ISSUE TITLE
On Windows 10, lldb gets error regarding module 'six'

### ISSUE THREAD

**Issue by gandalfas** [apple/swift#58448]
This is due to a "bug" in the Swift installation procedure for Windows 10.  Below, after describing the issue, I have a solution.  I am new at Swift, and other thoughts are welcome!

### Environment
build number: Swift 5.6.1
OS: Windows 10 desktop computer

### Issue Description
On Windows 10, lldb gets error: ModuleNotFoundError: No module named 'six'

### Test Case
After an install of Swift on Windows 10, run 'lldb Factorial' as shown on [Swift - Getting Started](https://www.swift.org/getting-started/) > Using the LLDB Debugger.  That elicits the error above.

### Cause
The Python module 'six' has not been installed (it is not part of the python distribution), and/or the env var PYTHONPATH is missing the Python directory: (your-Python-root)\Lib\site-packages.

### Solution
See notes on PYTHONPATH and the 'six' module in #58438.

**Comment by Kim4444** [comment]
closing. I provided the solution right within the issue. I am accepting my own solution.

(Perhaps I should have kept the solution out of the initial issue, and then provided the solution immediately afterward?)

**Comment by AnthonyLatsis** [comment]
Resubmitted as part of https://github.com/apple/swift-org-website/issues/287
