### ISSUE TITLE
PDFKit Notification .PDFViewPageChanged Bug 

### ISSUE THREAD

**Issue by 92pino** [apple/swift#58442]
**Describe the bug**
Sometimes when I scroll the PDFView using PDFViewPage Changed Notification, the currentPage value of the PDFView is not being updated.

**To Reproduce**
1. Fast Scroll Up / Down
**Expected behavior**
if when i scroll PDFView Current Page number should update 6 -> 5 but currentPage number was not updated

**Screenshots**
https://user-images.githubusercontent.com/45158632/165461849-3240133d-9ed1-49ae-b86d-4977414b7b59.mov

**Environment (please complete the following information):**
 - OS: macOS 12.2.1
 - Xcode Version/Tag/Branch: Version 13.3.1 (13E500a)

**Comment by WowbaggersLiquidLunch** [comment]
It seems like you're reporting a bug in [`PDFView`](https://developer.apple.com/documentation/pdfkit/pdfview), which is a proprietary framework from Apple, and not part of the Swift open-source project. If this is the case, please report it to Apple via [Feedback Assistant](https://feedbackassistant.apple.com) instead.
