### ISSUE TITLE
On Windows 10, lldb 'v' and 'p' commands get error regarding scratch context

### ISSUE THREAD

**Issue by gandalfas** [apple/swift#58455]
I am unsure if this is due to a "bug" in the Swift installation procedure for Windows 10, or if there is an issue in LLDB itself.  I am new at Swift, and other thoughts are welcome!  And many thanks to all who helped bring Swift to Windows!!! :)

### Environment
build number: Swift 5.6.1
OS: Windows 10 desktop computer

### Issue Description
On Windows 10, lldb 'v' and 'p' commands get error: Cannot create Swift scratch context (couldn't load the Swift stdlib)

### Test Case
After an install of Swift on Windows 10, run swiftc and lldb as shown below:

  md Point
  cd Point
  create Point.swift with these lines:
```  
    class Point {
        var x: Double
        var y: Double

        init(_ x: Double, _ y: Double) {
            self.x = x
            self.y = y
        }
    }

    let int = 1
    var dbl = 3.14159
    var str = "alpha"
    var pt = Point(3.0, 5.0)

    print("int: \(int)")
    print("dbl: \(dbl)")
    print("str: \(str)")
    print("pt: \(pt)")
```
**compile it**
  set SWIFTFLAGS=-sdk %SDKROOT% -I %SDKROOT%\usr\lib\swift -L %SDKROOT%\usr\lib\swift\windows
  swiftc -g -use-ld=lld -Xlinker -debug:dwarf Point.swift -o Point.exe %SWIFTFLAGS%
  
**debug it**
  lldb point
```
(lldb) target create "point"
Current executable set to 'point' (x86_64).

(lldb) b 16
Breakpoint 1: where = point.exe`main + 206 at Point.swift:16:7, address = 0x00000001400012ce

(lldb) r
Process 18136 launched: 'K:\Point\point.exe' (x86_64)
Process 18136 stopped
* thread #1, stop reason = breakpoint 1.1
    frame #0: 0x00007ff6828a12ce point.exe`main at Point.swift:16:7
   13   var str = "alpha"
   14   var pt = Point(3.0, 5.0)
   15
-> 16   print("int: \(int)")
   17   print("dbl: \(dbl)")
   18   print("str: \(str)")
   19   print("pt: \(pt)")
Target 0: (point.exe) stopped.

(lldb) v int
(Int) int = 1

(lldb) v dbl
(Double) dbl = 3.1415899999999999

(lldb) v str
(String) str = "alpha"

(lldb) v pt
Cannot create Swift scratch context (couldn't load the Swift stdlib)Cannot create Swift scratch context (couldn't load the Swift stdlib)(lldb) (Point.Point) pt = 0x0000016dcb4a88c0 (x = 3, y = 5)

(lldb) v pt
(Point.Point) pt = 0x0000016dcb4a88c0 (x = 3, y = 5)
```

The first 'v pt' elicits the error above.  But it does at least display the value of 'pt'.
The second 'v pt' simply displays the value of 'pt' (no error).

Like 'v', the 'p' command elicits the error, but unlike 'v', it does not display the value at all - not for 'pt' and not even for 'int', 'dbl', or 'str':
```
(lldb) p int
Cannot create Swift scratch context (couldn't load the Swift stdlib)Cannot create Swift scratch context (couldn't load the Swift stdlib)(lldb) (lldb)
```

Is there a solution that eliminates the 'cannot create Swift stdlib' error for 'v' and 'p', and that gets 'p' to work?

**Comment by compnerd** [comment]
This should be fixed as of a recent build.  Thanks for reporting the issue!

**Comment by gandalfas** [comment]
@compnerd, Thanks so much!

**Comment by AnthonyLatsis** [comment]
@compnerd Was this fixed in the llvm fork? Do we know which PR is was?
