### ISSUE TITLE
On Windows 10, 'swift build' gets error regarding module ucrt

### ISSUE THREAD

**Issue by Kim4444** [apple/swift#58450]
This is due to a "bug" in the Swift installation procedure for Windows 10.  Below, after describing the issue, I have a solution.  I am new at Swift, and other thoughts are welcome!

### Environment
build number: Swift 5.6.1
OS: Windows 10 desktop computer

### Issue Description
On Windows 10, 'swift build' gets error: invalidManifestFormat("<unknown>:0: error: missing required module \'ucrt\'", diagnosticFile: nil)

### Test Case
After an install of Swift on Windows 10, run 'swift build', taken from [Swift - Getting Started](https://www.swift.org/getting-started/), 'Creating a Package'.  That elicits the error above.

### Cause
Some WinSDK files are missing.

### Solution
After installing Swift 5.6.1, do the 4 copy statements on [Swift - Getting Started](https://www.swift.org/getting-started/) > On Windows > Support Files, to eliminate the error.  I pieced this together after reading:  [Trouble getting setup on Windows](https://forums.swift.org/t/trouble-getting-setup-on-windows/53603/2/).  I did actually install Swift before Visual Studio, as described in #58451.

**Comment by grynspan** [comment]
I think #58451 captures the problem (the documentation is unclear on order of operations) a bit better than this issue. Does this issue track a different problem? If not, we can close this one as a duplicate of #58451. If so, would you please clarify a bit? Thanks!

**Comment by Kim4444** [comment]
Thanks for your comments.  My thought in creating this issue was to provide a landing spot for anyone searching for this error:
```
invalidManifestFormat(":0: error: missing required module 'ucrt'", diagnosticFile: nil)
```
which doesn't appear in #58451.   Also, #58451 is all about changing the install process, and I guess it could help the next person getting the above error if they were willing to do an uninstall/reinstall.  But the solution above is just the shortcut for that - to get the next person working quickly.

So because of that does it make sense to not classify it as a duplicate?   (I am new at this.)

Even so, I see now that it makes no sense to keep this issue open, because I solved it myself right within! :)    Perhaps I should have kept the solution out of the initial issue, and then provided the solution immediately afterward, and then closed it myself?

**Comment by grynspan** [comment]
If there's only one thing to do to fix both issues, it seems appropriate to me to mark one or the other as a duplicate. Otherwise one may stay open after the other is closed as "fixed", but it won't track anything actionable. Does that make sense?

**Comment by Kim4444** [comment]
yes, if OK with you, I would prefer the latter, closing this one as 'fixed', and leaving the other.   I am not sure if I have the power, but I will try to close this one.  My hope is that it will save someone some pain, until (if) the other's proposed updates to 'Getting Started' are completed.

**Comment by Kim4444** [comment]
closing.  I am essentially accepting my own solution.
