### ISSUE TITLE
Shouldn't there be a fast path for array mutation?

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#58516]
I was surprised to see getter and setter calls in https://godbolt.org/z/Pfo98qrEo without a fast path that can be run after a uniqueness check.  Overall the codegen looks surprising heavy.  Of course I haven't measured the actual performance; it could be blazing… but my instinct says something must be amiss.  If y'all disagree, feel free to close this!

**Comment by atrick** [comment]
I you add `-O` there's no loop at all. Just a single instruction
`call    memcpy@PLT`

**Comment by dabrahams** [comment]
? That example has -Ounchecked and I see no substantial difference when I use -O.  I'm looking at `output.update(inout [Swift.Int]) -> ()` which is 125 instructions long.  Is godbolt broken or are we interpreting the results differently?

**Comment by dabrahams** [comment]
Ah!  I put the `-O` in the wrong place!  Thanks, sorry, sorry!
