### ISSUE TITLE
Builds fail with both Xcode and bootstrapping enabled

### ISSUE THREAD

**Issue by aenewton** [apple/swift#58692]
**Describe the bug**
When bootstrapping is enabled (the default state) and the `--xcode` build flag is used, the build fails with the following error:

```
clang: error: no such file or directory: '/Users/<my_user>/Developer/swift-project/build/Xcode-RelWithDebInfoAssert/swift-macosx-arm64/lib/RelWithDebInfo/libswiftCompilerModules-bootstrapping1.a'
```

My primary machine is Apple Silicon, but I saw the same error on Intel as well.

**To Reproduce**
1. Build with the following command: 
```
utils/build-script --skip-build-benchmarks \
  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping \
  --xcode
```

...

**Expected behavior**
I expected a successful build with a usable Xcode project

**Environment (please complete the following information):**
 - OS: macOS 12.3.1 
 - Machine: 16-inch MacBook Pro with M1 Pro (16GB Memory)
 - Xcode Version: Xcode 13.3 (13E113)
 - Swift commit: 48208380e33fa021bac429748744a978f6e5145a

**Additional context**
If you build with ninja, the build succeeds.

If you build with Xcode and also disable bootstrapping with `--reconfigure --bootstrapping=off`, the build succeeds.

The issue is only with Xcode *and* bootstrapping.

There are some related threads on Swift forums here:

https://forums.swift.org/t/problems-with-build-script-building-compiler-with-xcode/53477

https://forums.swift.org/t/no-xcode-builds-on-ci/53521

https://forums.swift.org/t/building-swift-compiler-from-source-fails-when-not-using-ninja/54656/8

**Comment by LucianoPAlmeida** [comment]
Also never able to build without `--bootstrapping=off`
But just for reference #40838 this was where bootstrap was enabled for Xcode builds
