### ISSUE TITLE
3 SILOptimizer tests are failing on Ubuntu 20.04 AArch64 

### ISSUE THREAD

**Issue by shahmishal** [apple/swift#58785]
Failed Tests (3):
  Swift(linux-aarch64) :: SILOptimizer/addr_escape_info.sil
  Swift(linux-aarch64) :: SILOptimizer/escape_info.sil
  Swift(linux-aarch64) :: SILOptimizer/ranges.sil

https://ci.swift.org/job/oss-swift-package-ubuntu-20_04-aarch64/440/console
[consoleText-2.txt](https://github.com/apple/swift/files/8662893/consoleText-2.txt)

**Comment by eeckstein** [comment]
rdar://92963081

**Comment by egorzhdan** [comment]
This was fixed by https://github.com/apple/swift/pull/59839.
