### ISSUE TITLE
Archive swift-issues-migration repositories?

### ISSUE THREAD

**Issue by benrimmington** [apple/swift#58895]
Can the [swift-issues-migration][] repositories be archived, so that duplicates aren't shown on the <https://github.com/issues> page by default?

[swift-issues-migration]: <https://github.com/orgs/swift-issues-migration/repositories>

**Comment by shahmishal** [comment]
swift-issues-migration org deleted.

**Comment by daixtrose** [comment]
One question: is the code of the migration tools still available?
