### ISSUE TITLE
Assertion failed: (hasType(node) && "Expected type to have been set!") when opening existential by default

### ISSUE THREAD

**Issue by ahoppen** [apple/swift#58891]
Since https://github.com/apple/swift/pull/41996 the following code completion test case started crashing:

```
$ cat /path/to/test.swift
protocol Frror {}
protocol LocalizedError : Frror {}

func foo(error: Frror) {
  (error as? LocalizedError)#^COMPLETE^#
}
$ ./sourcekitd-test -req=complete -pos=5:29 /path/to/file.swift -- /path/to/file.swift
```

I also noticed that EnableOpenedExistentialTypes now defaults to true when parsing command line arguments but the default in LangOptions.h is still false.

A nicer debugging experience for the above bug can be gained by either
- Changing `EnableOpenedExistentialTypes` in LangOptions.h to true (this is what I think should be done anyway) or
- Adding `InitInvok.getLangOptions().EnableOpenedExistentialTypes = true;` in swift-ide-test.cpp:4267

And then running
```
$ ./swift-ide-test -code-completion -source-filename /path/to/test.swift -code-completion-token COMPLETE
```

rdar://92156002

**Comment by hborla** [comment]
Fixed by https://github.com/apple/swift/pull/59814!
