### ISSUE TITLE
Add support for Xcode 13.3.1

### ISSUE THREAD

**Issue by valentinradu** [apple/swift#58928]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the latest Xcode (13.3.1/13E500a) to build Swift. When calling `utils/build-script` with `SKIP_XCODE_VERSION_CHECK=1` some tests are failing. I'm not sure if this happens on other versions too, but since Xcode 13.3.1 is not officially supported I've reported it as such. Ninja builds and tests are passing without any problem.

**Describe the solution you'd like**
Swift would build and the tests would run when using Xcode 13.3.1!

**Describe alternatives you've considered**
Building using Ninja, which is a bit disruptive.

**Additional context**
None

**Comment by darknoon** [comment]
Xcode 13.4 just dropped, would be nice to support that as well

**Comment by keith** [comment]
https://github.com/apple/swift/pull/58938
