### ISSUE TITLE
Local variables has been released before the end of scope in RELEASE mode.

### ISSUE THREAD

**Issue by RayJiang16** [apple/swift#58929]
**Describe the bug**
Local variables has been released before the end of scope in RELEASE mode.

**To Reproduce**
```swift
enum AnimalType {
    case dog
    case cat
}

protocol Animal: AnyObject {
    var description: String { get }
}

class Dog: Animal {
    var description: String { return "Dog" }
}

class Cat: Animal {
    var description: String { return "Cat" }
}

class Foo {
    weak var animal: Animal?
}

func f1(animalType: AnimalType) {
    let animal: Animal
    switch animalType {
    case .dog:
        animal = Dog()
    case .cat:
        animal = Cat()
    }
    
    let foo = Foo()
    foo.animal = animal
  
    if let a = foo.animal {
        print(a.description) // In DEBUG mode
    } else {
        print("animal has been released") // In RELEASE mode
    }
}

f1(animalType: .dog)
```

**Expected behavior**
Works the same way as DEBUG mode.

**Environment:**
 - OS: macOS 12.1 (21C52)
 - Xcode Version: 13.3.1 (13E500a)
 - Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)

**Additional context**
I add `init` and `deinit` for those class, and find local variable animal has been released right after `let foo = Foo()`
I find some way to let this code work in RELEASE mode.
Add `print(animal)` before end of `f1` scope.
or
Remove switch case, use `let animal: Animal = Dog()`

**Comment by tbkka** [comment]
CC: @atrick @nate-chandler

**Comment by atrick** [comment]
Thank you for reporting this!

This test case is broken with Swift 5.6 but works correctly with Swift 5.7 now that the compiler supports lexical lifetimes.

The 5.6 behavior was legal according to the language rules, but I agree that it was a bug for practical purposes.

**Comment by atrick** [comment]
5.6 workaround: Please use `defer { withExtendedLifetime(animal) {} }` to keep the strong reference alive.
