### ISSUE TITLE
Can’t defer actor-isolated variable access inside Task { }

### ISSUE THREAD

**Issue by StevenMagdy** [apple/swift#58921]
**Describe the bug**
Can’t `defer` actor-isolated variable access inside `Task { }`. To make it work I have to extract the code inside the closure to another function. 

**To Reproduce**
```swift
@MainActor
class A {
  var isLoading: Bool = false

  func startTask1() {
    Task { @MainActor in
      isLoading = true
      defer { isLoading = false } // ❌ Error: Property 'isLoading' isolated to global actor 'MainActor' can not be mutated from a non-isolated context
      print("Doing task")
    }
  }

  // Extracting the logic to a separate function
  func startTask2() {
    Task { await startTask2Impl() } // ✅ OK
  }

  private func startTask2Impl() async { 
    isLoading = true
    defer { isLoading = false } // ✅ OK
    print("Doing task")
  }
}
```

**Expected behavior**
I expect `startTask1` to compile and behave as `startTask2`

**Additional context**
[More](https://forums.swift.org/t/a-bug-cant-defer-actor-isolated-variable-access/50796/19) [examples](https://forums.swift.org/t/a-bug-cant-defer-actor-isolated-variable-access/50796/21)
Related to #41077
Maybe a duplicate of #57673

**Comment by hebdavepaul0** [comment]
This still looks to be an issue with Swift 5.7 in Xcode 14 Beta 1.

**Comment by StevenMagdy** [comment]
cc @rjmccall @DougGregor
