### ISSUE TITLE
Regex literal failing with `unary operator cannot be separated from its operand`

### ISSUE THREAD

**Issue by b8591340** [apple/swift#59341]
The following errors with `'/' is not a prefix unary operator`, `unary operator cannot be separated from its operand`, `Expected expression in list of expressions`.

```swift
let regex = /\(/
```

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Xcode: 14 beta 1

**Additional context**

It works in the Playground, but not in Swift packages with `swift-tools-version:5.7` and the command line with Xcode-beta `—select`ed.

**Comment by hamishknight** [comment]
Bare slash regex syntax `/.../` is [a source breaking change](https://github.com/apple/swift-evolution/blob/main/proposals/0354-regex-literals.md#source-compatibility) and as such requires the compiler flag `-enable-bare-slash-regex` to work for Swift 5.7 (it will then become the default under Swift 6 mode). Xcode will automatically pass this flag for projects when the "Enable Bare Slash Regex Literals" build setting is enabled, however you will need to pass the flag manually in other cases. Note that the extended literal `#/.../#` syntax is available even without `-enable-bare-slash-regex`.
