### ISSUE TITLE
Swift 5.7: incorrect compiler error for `(any P)?` as an enum associated value

### ISSUE THREAD

**Issue by groue** [apple/swift#59392]
**Describe the bug**

The Swift 5.7 compiler won't compile valid code that involves optional existentials `(any P)?` in the associated value of an enum.

**To Reproduce**

1. Compile the following Swift snippet with Xcode 14 beta:

    ```swift
    protocol P { }

    enum E {
        // ❌ Expected parameter name followed by ':'
        case a(() -> (any P)?)
        
        // ❌ Expected parameter name followed by ':'
        case b((any P)?)
    }
    ```

2. See how the compiler fails to compile

**Expected behavior**

The provided code snippet compiles.

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Xcode Version 14.0 beta (14A5228q)

**Comment by AnthonyLatsis** [comment]
Fixed by https://github.com/apple/swift/pull/58950
