### ISSUE TITLE
Solved: Need to approve: Legal documentation must be added, documented and indexed

### ISSUE THREAD

**Issue by miguelgargallo** [apple/swift#59400]
**Is your feature request related to a problem? Please describe.**
Code of Conduct v1.4 was missing, now it is well added, formatted and idexed too.

**Describe the solution you'd like**
Added text from the source, formatting the text, and indexing it.

**Describe alternatives you've considered**
A plain text, but as it is on the #59401 it's a great update.

**Additional context**
No need of smoke test, just changes on a legal document.

**Comment by AnthonyLatsis** [comment]
@miguelgargallo I assume that an update to https://www.swift.org/code-of-conduct/ resolved this issue some time ago? If so, I think we can close your PR as well.
