### ISSUE TITLE
Incorrect warning when casting `any Error` to `AnyHashable`

### ISSUE THREAD

**Issue by stephencelis** [apple/swift#59405]
**Describe the bug**

Swift warns of casting `any Error` to `AnyHashable` when it shouldn't.

**To Reproduce**

Try compiling the following code:

```swift
func isHashable(_ error: Error) -> Bool {
  (error as? AnyHashable) != nil
}
```

Or the following code:

```swift
func isHashable(_ error: Error) -> Bool {
  error is AnyHashable
}
```

Both are given the following warning:

> ⚠️ Cast from 'any Error' to unrelated type 'AnyHashable' always fails

Despite not actually failing:

```swift
struct E: Error, Hashable {}
isHashable(E())  // `true` in either implementation
```

**Expected behavior**

The warning shouldn't appear, as it is incorrect.

**Environment (please complete the following information):**
 - OS: macOS 11
 - Xcode 14 beta 1

**Additional context**

While `any Hashable` may be the way forward here, the existing compiler magic around `AnyHashable` should still work.

**Comment by nandzz** [comment]
Hi @stephencelis , but Error doesn't Inherits From AnyHashable. Futhermore error is a protocol and AnyHashable is a struct. As the warning says. they are unrelated types

Take a look in this code below:

<img width="1032" alt="Screenshot 2022-06-13 at 23 58 34" src="https://user-images.githubusercontent.com/75216897/173452262-9098f7f9-a3bc-4978-98fc-dc2e6a059096.png">

**Comment by stephencelis** [comment]
@nandzz I understand that general case and why it _should_ always fail, but because the compiler treats `AnyHashable` and the `Error` existential in "special" ways, the warning is incorrect.

If the compiler team doesn't feel like the special case for this warning should be handled, they can close it out as a "won't fix." It's easy enough to get around by explicitly boxing in an `Any` first.

**Comment by LucianoPAlmeida** [comment]
I think that since runtime treats `AnyHashable` as special case compiler should be more conservative in emitting this warning because in your example, there is no way to statically know if the concrete type that conforms with `Error` conforms or not with `Hashable` because underlying type is erased. I'll try to put up a fix for it as soon as possible =]
