### ISSUE TITLE
Swift 5.7 tracking fine-grained dependencies in Whole-Module-Optimization mode

### ISSUE THREAD

**Issue by tapthaker** [apple/swift#59407]
**Describe the bug**
Our Swift builds in whole-module-optimization mode are 30% slower than before. This is mainly because swift is tracking incremental information in WMO mode as well.

1. Switch  to Swift 5.6 and execute the following. You should NOT see `<INCREMENTAL_INFORMATION_BLOCK>`
2.  
```lang=bash
echo 'func foo() {}' > a.swift && swiftc -whole-module-optimization -module-name A -c a.swift -emit-module -emit-module-path A.swiftmodule -o a.o && llvm-bcanalyzer -dump A.swiftmodule | grep INCREMENTAL_INFORMATION_BLOCK
```

1. Switch to Swift 5.7 and execute the following. You should see `<INCREMENTAL_INFORMATION_BLOCK>`
2.
```lang=bash
echo 'func foo() {}' > a.swift && swiftc -whole-module-optimization -module-name A -c a.swift -emit-module -emit-module-path A.swiftmodule -o a.o && llvm-bcanalyzer -dump A.swiftmodule | grep INCREMENTAL_INFORMATION_BLOCK
```
...

**Expected behavior**

`INCREMENTAL_INFORMATION_BLOCK>` should not be present

**Environment (please complete the following information):**
 - OS: [e.g. macOS 11.0]: macOS 12.4 Beta 
 - Xcode Version/Tag/Branch: `Xcode.14.0.0.14A5228q.app`

**Comment by CodaFi** [comment]
Are you sure this is all down to the incremental build? Please try disabling this with `-Xfrontend -disable-incremental-imports` and rerun your benchmarks.

**Comment by tapthaker** [comment]
Hey @CodaFi, I seem to be wrong. Disabling incremental imports still results in a 30% regression in WMO mode. We'll investigate this further. Apologies for assuming it was `incremental-imports`
