### ISSUE TITLE
[SwiftPM] `--static-swift-stdlib` is not compatible with `swift test`

### ISSUE THREAD

**Issue by kateinoigakukun** [apple/swift#59447]
**Describe the bug**
SwiftPM's `--static-swift-stdlib` is not compatible with `swift test` since it can't find `XCTest` module 

**To Reproduce**
1. `swift package init --type executable --name StaticExec`
2. `swift test --static-swift-stdlib`

Then we got the following error:
```
Building for debugging...
/tmp/tmp.7UCHKkRKWj/Tests/StaticExecTests/StaticExecTests.swift:1:8: error: no such module 'XCTest'
import XCTest
       ^
[5/8] Emitting module StaticExecTests
error: fatalError
```

**Expected behavior**

Successfully compiled and tested code

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Swift Version: ~`DEVELOPMENT-SNAPSHOT-2022-06-13-a`

**Comment by AnthonyLatsis** [comment]
@shahmishal I was looking if I could delete the `libSwiftPM` label (did such a library even exist?) and this is the only associated issue. Can it be transferred?

**Comment by AnthonyLatsis** [comment]
@kateinoigakukun What happened to this issue? Why was it closed immediately?

**Comment by kateinoigakukun** [comment]
Ah, sorry. I reopened this in swift-package-manager repo: https://github.com/apple/swift-package-manager/issues/5590

**Comment by AnthonyLatsis** [comment]
Thanks for the pointer. Keep in mind that we can transfer issues instead of cloning.

**Comment by AnthonyLatsis** [comment]
@shahmishal ping

**Comment by kateinoigakukun** [comment]
Actually, as far as I remember, I tried to transfer but that operation requires write-permission of the destination repository (and I don't have it).

**Comment by AnthonyLatsis** [comment]
Yeah, true, although it probably makes sense to grant transfer permissions to authors. I usually reach out to someone with write access on both ends when I come across these kinds of issues.
