### ISSUE TITLE
`Date` with `Date.VerbatimFormatStyle` fails to parse string emitted by its own error

### ISSUE THREAD

**Issue by b8591340** [apple/swift#59564]
```swift
let string = "Sat Jun 18 16:10:00 +0000 2022”

var verbatim: Date.VerbatimFormatStyle { 
    .init(format: "\(weekday: .abbreviated) \(month: .abbreviated) \(day: .twoDigits) \(hour: .twoDigits(clock: .twentyFourHour, hourCycle: .zeroBased)):\(minute: .twoDigits):\(second: .twoDigits) \(timeZone: .iso8601(.short)) \(year: .defaultDigits)",
          locale: .init(identifier: "en_UK"), timeZone: .init(secondsFromGMT: .zero)!, calendar: .current)
}

let date = try! Date(string, strategy: verbatim.parseStrategy)
```

This yields the following error.

> Error Domain=NSCocoaErrorDomain Code=2048 "Cannot parse `Sat Jun 18 16:10:00 +0000 2022`. String should adhere to the preferred format of the locale, such as `Sat Jun 18 16:11:15 +0000 2022`." UserInfo={NSDebugDescription=Cannot parse Sat Jun 18 16:10:00 +0000 2022. String should adhere to the preferred format of the locale, such as Sat Jun 18 16:11:15 +0000 2022.}

Swift 5.7 with Xcode 14 beta 1, macOS 12.4.

**Comment by harlanhaskins** [comment]
This is a bug in Foundation, which is not tracked by the Swift project's issue tracker. Can you file a bug for this at feedbackassistant.apple.com?
