### ISSUE TITLE
It's possible to set an isolated property asynchronously

### ISSUE THREAD

**Issue by JJJensen** [apple/swift#59573]
**Describe the bug**
Isolated properties can be set asynchronously using a protocol.

**To Reproduce**
```Swift
actor Act {
    var i = 0
}
let act = Act()

func bad() async {
    await act.i = 666 // Correctly rejected
}

protocol Proto: Actor {
    var i: Int { get set }
}
extension Act: Proto {}

func good() async {
    await (act as any Proto).i = 42 // BUG: Not rejected
    let aIndirect: any Proto = act
    await aIndirect.i = 777 // BUG: Not rejected
}
```

**Expected behavior**
The compiler should reject the "BUG: Not rejected" lines above.

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Xcode Version/Tag/Branch: Public Xcode 14.0 beta (14A5228q) (also Xcode 13.4.1)

**Additional context**
Isolated properties should not be set asynchronously. You have to create an async method to set the property. This avoids misuse like `await obj.prop += 1`. But this bug makes it possible.

**Comment by ktoso** [comment]
We correctly reject this on main
```
/Users/ktoso/code/swift-project/swift/test/Concurrency/actor_isolation_bug.swift:7:7: error: unexpected note produced: mutation of this property is only permitted within the actor
  var i = 0
      ^
/Users/ktoso/code/swift-project/swift/test/Concurrency/actor_isolation_bug.swift:12:3: error: unexpected warning produced: no 'async' operations occur within 'await' expression
  await act.i = 666 // Correctly rejected
  ^
/Users/ktoso/code/swift-project/swift/test/Concurrency/actor_isolation_bug.swift:12:13: error: unexpected error produced: actor-isolated property 'i' can not be mutated from a non-isolated context
  await act.i = 666 // Correctly rejected
            ^
```

I'll add an explicit test for it tho

**Comment by ktoso** [comment]
Confirmed, thanks for reporting -- what breaks it is the explicit  `: Actor` on the protocol, it likely short-circuts in conformance checks somehow. I'll look into this, been digging in conformances and isolation recently anyway.

**Comment by ktoso** [comment]
For tracking rdar://95509917
