### ISSUE TITLE
Array variable which is protected by @MainActor cannnot be updated using index-notation inside Task block.

### ISSUE THREAD

**Issue by fummicc1** [apple/swift#59583]
**Describe the bug**

`Array` variable which is protected by globalactor like `MainActor` cannnot be updated using `index notation` inside `Task` block.

**To Reproduce**

1. Run the follwoing code on Swift 5.6

```swift
import Foundation

struct Test {
    var id: Int
    var text: String
}

class Model {
    @MainActor var list: [Test] = [
        Test(id: 1, text: ""),
        Test(id: 2, text: "")
    ]

    init() {
        Task {
            let updatedList = [
                Test(id: 1, text: "Text1"),
                Test(id: 2, text: "Text2")
            ]
            for updated in updatedList {
                if let i = await self.list.firstIndex(where: { $0.id == updated.id }) {
                    await MainActor.run(body: {
                        self.list[i].text = updated.text
                    })
                }

            }
        }
    }
}
```

2. Check the error output.
```
Actor-isolated property 'list' cannot be passed 'inout' to 'async' function call
```
...

**Expected behavior**

I would like to get no error in the above code, but I am not sure whether it is feasible in the aspect of compiler to write in this way. If it is possible, I would like  you to embrace my expectation in the future release.

**Screenshots**

<img width="1139" alt="スクリーンショット 2022-06-20 14 39 11" src="https://user-images.githubusercontent.com/44002126/174532393-69d02b0a-34bc-4311-917a-091b96530675.png">

**Environment (please complete the following information):**
 - OS: macOS 13 beta (but also macOS12, I think.)
 - Xcode 13.4.1

**Additional context**

In practical case, I can escape this erorr with `updateText` method.

```swift
@MainActor
private func updateText(i: Int, value: String) {
  self.list[i].text = value
}
```

and call `updateText` like

```swift
class Model {
    @MainActor var list: [Test] = [
        Test(id: 1, text: ""),
        Test(id: 2, text: "")
    ]

    init() {
        Task {
            let updatedList = [
                Test(id: 1, text: "Text1"),
                Test(id: 2, text: "Text2")
            ]
            for updated in updatedList {
                if let i = await self.list.firstIndex(where: { $0.id == updated.id }) {
                    await MainActor.run(body: {
                        self.updateText(i: i, value: updated.text) // Changed
                    })
                }
            }
        }
    }

    @MainActor
    private func updateText(i: Int, value: String) {
      self.list[i].text = value
    }
}
```

**Comment by hborla** [comment]
This is fixed by https://github.com/apple/swift/pull/69126
