### ISSUE TITLE
Malformed rewrite rule when building Vexil with Xcode 14 / Swift 5.7

### ISSUE THREAD

**Issue by bok-** [apple/swift#59713]
**Describe the bug**

When building [Vexil](https://github.com/unsignedapps.com/Vexil.git) it fails with:

```
Building for debugging...
&&& Malformed rewrite rule: τ_0_0.[OptionalFlagValue:WrappedFlagValue].[CaseIterable:AllCases].[RandomAccessCollection:Element] => τ_0_0.[OptionalFlagValue:WrappedFlagValue].[CaseIterable] [lhs↓] [rhs↓]
&&& symbol.getKind() != Symbol::Kind::Protocol
```

**To Reproduce**
1. `git clone https://github.com/unsignedapps/Vexil.git`
2. `cd Vexil && swift build`

**Expected behavior**

Builds normally. This works in Xcode 13 / Swift 5.6.

**Environment (please complete the following information):**
 - OS: macOS 12.4 
 - Xcode Version/Tag/Branch: Xcode 14.0 beta 2

**Additional context**
Full build log attached.

[build.txt](https://github.com/apple/swift/files/8986663/build.txt)

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/59557
