### ISSUE TITLE
Infinite recursion in NormalProtocolConformance::finishSignatureConformances()

### ISSUE THREAD

**Issue by dabrahams** [apple/swift#59772]
**Describe the bug**
```
$ swift BitSet.swift
[1]    30669 illegal hardware instruction  swift BitSet.swift
$ 
```

**To Reproduce**

See above; use this file [BitSet.swift.txt](https://github.com/apple/swift/files/9007200/BitSet.swift.txt)

**Expected behavior**
No crash

**Comment by dabrahams** [comment]
```
$ swift --version
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

**Comment by dabrahams** [comment]
Also [this one](https://github.com/apple/swift/files/9007239/BitSet2.swift.txt).  Uncomment the typealias on line 83 to make it compile.

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/70311
