### ISSUE TITLE
Optional existential as closure return value fails to parse

### ISSUE THREAD

**Issue by juri** [apple/swift#59836]
**Describe the bug**
With swiftlang-5.7.0.113.202 clang-1400.0.16.2 as shipped with Xcode 14.0 beta 2, writing an optional existential type as the closure return type causes a `expression failed to parse` error.

**To Reproduce**

Write the following code in swift repl:

```swift
protocol Proto {}
struct S: Proto {}
let a = [1, 2, 3, 4, 5]
a.compactMap { value -> (any Proto)? in
     value > 2 ? S() : nil
}
```

You get the following error:

```
expression failed to parse:
error: repl.swift:4:37: error: consecutive statements on a line must be separated by ';'
a.compactMap { value -> (any Proto)? in
                                    ^
                                    ;

error: repl.swift:4:38: error: expected expression
a.compactMap { value -> (any Proto)? in
                                     ^
```

I believe that should work. You can write it with an explicit `Optional` type:

```swift
protocol Proto {}
struct S: Proto {}
let a = [1, 2, 3, 4, 5]
a.compactMap { value -> Optional<any Proto> in
     value > 2 ? S() : nil
}
```

**Environment (please complete the following information):**
 - OS: macOS 12.4
 - Xcode 14.0 beta 2 (14A5229c)
 - Swift:

   ```
   swift-driver version: 1.55.1 Apple Swift version 5.7 (swiftlang-5.7.0.113.202 clang-1400.0.16.2)
   Target: x86_64-apple-macosx12.0
   ```

**Comment by hborla** [comment]
I believe this was fixed with https://github.com/apple/swift/pull/58951

**Comment by AnthonyLatsis** [comment]
Was able to reproduce this on `main` by reverting the changes in Holly's PR.

**Comment by juri** [comment]
Confirmed, works as expected with `5.7-dev (LLVM eecf02df5133efe, Swift ad06e7d7251311a)`. Thank you!
