### ISSUE TITLE
Result builder autocomplete does not work with `buildPartialBlock`

### ISSUE THREAD

**Issue by stephencelis** [apple/swift#59885]
**Describe the bug**

When in a result builder context, autocomplete does not suggest the new `buildPartialBlock` functions.

**Steps To Reproduce**

1. Define a `@resultBuilder`
2. Type `build` and invoke autocomplete

**Expected behavior**

Both `buildPartialBlock` endpoints should be options.

**Environment (please fill out the following information)**

 - OS: macOS 12
 - Xcode 14 beta 2

**Comment by hamishknight** [comment]
cc @rintaro, does code completion need special handling for this?

**Comment by rintaro** [comment]
Yes, result builder functions are custom. We need to add `buildPartialBlock` entry to https://github.com/apple/swift/blob/main/lib/IDE/CompletionOverrideLookup.cpp#L496-L517
But I realized `buildPartialBlock` is not included in `ResultBuilderBuildFunction`.
@xedin I think `ResultBuilderBuildFunction` is used for diagnostics too, there's no need for `buildPartialBlock` at this point?

**Comment by xedin** [comment]
@rintaro I think this is just an oversight, we need to add `buildPartialBlock` - two versions of it, but I don't think there are any diagnostics that are specific to it at the moment.
