### ISSUE TITLE
Unnecessary overflow check in `_decodeScalar` (UTF-16)

### ISSUE THREAD

**Issue by karwa** [apple/swift#59903]
**Describe the bug**

The standard library function:

```swift
internal func _decodeScalar(
   _ utf16: UnsafeBufferPointer<UInt16>, startingAt i: Int
 ) -> (Unicode.Scalar, scalarLength: Int) {
```

in `stdlib/public/core/UnicodeHelpers.swift`, contains an unnecessary overflow-checked increment. Noticed in https://github.com/apple/swift/pull/59899#discussion_r914399835

Checking in Godbolt, the overflow check does make it to the generated code and there is a small (tiny) code-size improvement when removing it. There may also be a performance improvement if this is in a hot path somewhere, but I haven't measured it.

**Steps To Reproduce**

[Godbolt](https://swift.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AKA7nioFSS%2BsgJ4BlRugDCqWgFcWDEAGYNpJwAZPAZMADlPACNMYhAAJmkAB1QFQnsGVw8vX39k1LsBYNCIlmjYhKtMGwKGIQImYgJMz28/Sur0uoaCIvComPjpBXrG5uy24e7ekrLBgEorVHdiZHYOAFINAEEAeh2Aai2FfZNiQgJGfeRl4kYCWgBPEE2tl5CL4mZafap3BmR9gB9LBoLAiMQNCAvfYwwH7dwEKhcABsIH2cgYCiYVEwACF3FQccRlKh3jF1j5nHIAJKCFEU7CkfaTRohYBbAj7Cj7WkEaFzfYAWgZ%2BwgGLwoMwADpwQYyMzRHLAoxgAQkDzBAL1gB2XHQmH0TkIPDABD7CkAEXhiPpAFZcYC/sgEJhkABrTDoNF4da2i36rlULnmuK4/Zcc0%2BbCW61I5FStB/Tk6vXbGEwvawsmfMS0gBuDTwhgIEDAYDkABUAGIoqV4BTKpjoIQ3VDAJgXCDG01zOYB/aZoHZr75wvF0vl6u1%2BsV4hMOgt4jENsdzBdk0IXv924EZYMUXiyUyxWQx3/F3uz1ommCHxxdc9hbhvtp83a/2v8z7MuVmvx%2BuNs2rbtp23abm%2BqZbOmA4HICw65gwBZnOOP5Tv%2BCizvOtCLsuIFrmBW6vumO57geDAShg0qyqeToXh6Xroryd4PpuT5cC%2BUEwjqH6vERhr7LQqAmJGVoInGvoOrRrr0d66yhlwvo8YOWaCDEI6IWOghimhdYNpgTY4SuoEboRuwHOmcGqTmtCjshWm/tOGFzguwGrhAgkmKZxGYLunwHjpwKupRhl4QoLFMh5T5xBx3EvC8maKGyJxzokiRJYWapsHYyDPNsbxWV8PxOkCILBSexD3gGcJiSi16YtieIEkSJLZhSVK8vSUZMiydhGByXJory/JCiKYrkUe1Hygo5XKkYaqDZqEEBvxYEibGdqSee0lXlyikBsA7gNOgwZtet8ZOLSWCqPsVRKEtREwSpHzqUhRZaahf66YBIVuQRHHQYOlnPQhr0oZOn0zs52GucZj7bj5pFjRRWDHhCxAQGezrbQxN4EMxf1Mux%2BqxZ%2BQYfY530w/hJn3ZxGawfBNkaXZJbk%2BhmEuUuRnU3DD37CRflIxN5UY1Jl440x94E8%2BAYk7xdP8R5a01ciEmY3RO0%2BnEqvyXt2zKUOBUg5pJYOehlNc3hLGmQbQNqcbLPaRDTlYT9naRf9MIC/uTu1oFkpu5gYVgRFQlRTF74vBwCy0Jwtq8N4HBaKQqCcEIZgWMySwrJgIY%2BDwpAEJo0cLG6IC2nEUp%2BAAHHEtpcBo2oAJy2hoPiSE3%2BicJICfFynnC8AoID%2BEXSfR6QcCwEgaAsGl9BkBQEAz3PAymOYBDkaa9wPHwdAfEPECRH3kQhA0TzcLwM9sIIADyDCPH3WAsIYwDiGPpD4Lcth4HmQd95gqhXQIjWAXMksd360DwJEOcxAHiuCwH3AgZwWCcB4AsKgBhgAKAAGp4EwCYG%2BiRGCoN4PwQQsp2BSBkIIRQKh1Dv10FwfQL8QBrwsPoKBQ9IALFQIkGoQ8OCChvkKAAGlQZcqkGDHUFPgLEkR6CCiYMgVYCgFCCjQIIZctBB5VFdDURwUixjeCYUEEIfRSgDCYXkNIAgjF6GsTUaY/RYhMOsHozoIwmhuBaHoNx38BBdEaE4ixLirCeLsa4zxwTZjsUWMsVYegkGYBAePcB8dSCJ2TqnDgqhq7IkFMiSQzIM4EABJvBA29RTp3XkyXAhASB5yYfsVws86AxEaXMXgo8tC9lIGXSQ2opTIiblwbUkhq5NziBoDuyIK5dw4D3DJfdsmD2HoXYuvTwFxF7u/FZ6yx69N/sQVIDhJBAA)

**Comment by dfperry5** [comment]
@karwa  / @lorentey 


Is this bug spoken for? I'm a part of the Swift Mentorship program and would love to use this as my first attempt to contribute to the language? :)

**Comment by karwa** [comment]
It is not spoken for, although it emerged during the PR that the entire function may actually be dead code.

**Comment by dfperry5** [comment]
@karwa  -- does that mean the whole function should just be removed? Removing code is sometimes the best PR possible haha!

**Comment by karwa** [comment]
Yes, I think so. It also isn't public, usableFromInline, or inlinable, so I believe it should be ABI-safe to remove the function.

There's a test which checks the ABI, so if you can delete the function and all tests pass, that'll say for sure. 

ABI compatibility is a big factor when making standard library changes, so it's worthwhile to get some practice checking it.

**Comment by dfperry5** [comment]
@karwa  - awesome! I'll give it a shot! Thanks!

**Comment by dfperry5** [comment]
Opened a PR Here, @karwa  -- waiting on CI results :) Will check in later tonight.
