### ISSUE TITLE
[SymbolGraphGen] swift-symbolgraph-extract support for emitting symbols from `@_export import`s

### ISSUE THREAD

**Issue by franklinsch** [apple/swift#59920]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15921      |
   |Radar             | rdar://problem/89687175         |
   |Original Reporter | @franklinsch      |
   |Type              | Improvement    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Swift-DocC    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   md5: 3bcd4958d4ed4ce5d66606c682cf8647

  </details>

**Issue Description:**

In https://github.com/apple/swift-docc/issues/190, we started exporting symbols that came from `@_exported import` modules when emitting symbol graph files during a Swift build. This ticket tracks adding the same support for the `swift-symbolgraph-extract`, which didn't come for free with https://github.com/apple/swift-docc/issues/190.

**Comment by stevapple** [comment]
Is this going to be resolved? It’s causing some problems building the documentation with https://github.com/apple/swift-docc-plugin, which calls `swift-symbol-extract` through SwiftPM plugin host.
