### ISSUE TITLE
SymbolGraphGen: Unsafe{Mutable?}{Raw?}Pointer members have vanished 

### ISSUE THREAD

**Issue by kelvin13** [apple/swift#59957]
**Describe the bug**
all APIs inherited from `_Pointer` have apparently vanished from standard library symbolgraphs as of `DEVELOPMENT-SNAPSHOT-2022-07-06-a`. many of these APIs are quite important, such as:

* [`UnsafePointer.successor()`](https://swiftinit.org/reference?overload=ss8_PointerPsE9successorxyF)
* [`UnsafePointer.init(bitPattern:)`](https://swiftinit.org/reference?overload=ss8_PointerPsE10bitPatternxSgSu_tcfc)

this only affects APIs inherited from underscored protocols, `@available(*, unavailable)` APIs (such as `SIMD2.+(_:_:)`) are unaffected.

**Steps To Reproduce**
1. generate a symbolgraph with an invocation like:

```
subprocess.run((swift_symbolgraph_extract, 
                '-skip-inherited-docs', 
                '-target', 'x86_64-unknown-linux-gnu', 
                '-output-dir', 'Swift', 
                '-module-name', 'Swift'), 
```

**Expected behavior**

`_Pointer` APIs should be present, as they are in symbolgraphs generated by the april toolchain.

**Comment by kelvin13** [comment]
update: it looks like the regression took place between the 5/31/2022 nightly and the 6/02/2022 nightly

**Comment by kelvin13** [comment]
the date in my last comment was off by a couple of days, 6/2 actually contains the members. they disappeared after 6/2, but reappeared in the 6/20 nightly only. they disappeared again in the 7/06 nightly.

members of underscored protocols are absolutely public API. (arguably, so are the underscored protocols.) aside from the standard library, projects like SwiftNIO also depend on this.

**Comment by QuietMisdreavus** [comment]
Underscored symbols are being filtered out [by language specification](https://docs.swift.org/swift-book/ReferenceManual/LexicalStructure.html#ID412):

> Treat identifiers that begin with an underscore as internal, even if their declaration has the public access-level modifier. This convention lets framework authors mark part of an API that clients must not interact with or depend on, even though some limitation requires the declaration to be public.

APIs that are marked as `@available(*, unavailable)` are hidden because their availability information implies that they are unusable on every platform. These are APIs that are explicitly not meant to be used - are there packages that are deliberately using these unavailable APIs?

**Comment by kelvin13** [comment]
yes, i am aware of TSPL’s prescription regarding underscored symbols, but this simply isn’t realistic to apply as a blanket policy, given how many projects in the ecosystem flaunt this recommendation. for example, it is not really possible to work with SwiftNIO without interacting with `_ChannelInboundHandler` and its members.

`@available(*, unavailable)` is often used expressly for documentation purposes. for example, swift-system vends all of the C `Errno` cases as unconditionally unavailable API, in order to educate users about alternatives to that API. in fact, documentation is the *only* reason those declarations exist, since they cannot actually be referenced by code.

a feature flag to opt-out of this behavior sounds like the correct solution to me. it does not need to be on by default.

**Comment by kelvin13** [comment]
thank you so much!

**Comment by QuietMisdreavus** [comment]
I've posted https://github.com/apple/swift/pull/60096 and https://github.com/apple/swift/pull/60100 to revert the underscored protocol behavior change.
