### ISSUE TITLE
Unicode Regex fails to match using case-insensitive option

### ISSUE THREAD

**Issue by samkrishna** [apple/swift#59953]
**Describe the bug**
Caseless Unicode regexes fail to match Unicode strings with varying cases.

**Steps To Reproduce**

1. Unzip the attached UnicodeRegexes.zip iOS framework project
2. Open the UnicodeRegexesTests.swift test case file
3. Navigate to the testRegexCaselessBugExample test case
4. Run the tests using “Command-U”
5. Wait for the test failure on lines 49 and 50

**Expected behavior**

I expect the case-insensitive regexes for matching "𝛣𝛲𝛢𝛶𝛰" (Greek upper-case) and "𝛽𝜌𝛂𝜐𝜊" (Greek lower-case) spelling out the Greek equivalent characters of the word "bravo" to match (on lines 49 and 50).

**Screenshots**
N/A

**Environment (please fill out the following information)**
 - OS: iOS 16 Beta 3 (Simulator)
 - Xcode Version: Version 14.0 beta 3 (14A5270f)
 - Xcode Developer OS: macOS 12.4 on Intel

**Additional context**

This is related to Apple FB5706701, the Objective-C version of this bug in *NSRegularExpression*. I have included the original Objective-C test code in commented form in the test case.
[UnicodeRegexes.zip](https://github.com/apple/swift/files/9067410/UnicodeRegexes.zip)

**Comment by paiv** [comment]
> "𝛣𝛲𝛢𝛶𝛰" (Greek upper-case)

These are `MATHEMATICAL ITALIC CAPITAL` letters, and Unicode intentionally does not provide case folding for them.

You can match the whole block `1D400 ... 1D7FF`, or specific subranges.

Or use simple greek letters, like ΒΡΑΥΟ, βραυο

**Comment by samkrishna** [comment]
@paiv I just ran the tests with your suggestion and of course you're correct.

Thank you for the Unicode lesson. This was a bug report with an incorrect premise and am closing it now.
