### ISSUE TITLE
`@discardableResult` is ignored when used with `try?`

### ISSUE THREAD

**Issue by StevenMagdy** [apple/swift#59956]
**Describe the bug**
When calling a function declared with `@discardableResult` using `try?`, I receive a warning for the unused return value.

**Steps To Reproduce**
```swift
@discardableResult
func ignoreThis() throws -> String {
  return ""
}

func test() throws {
  try? ignoreThis() // Warning
  try ignoreThis() // OK
}
```

**Environment (please fill out the following information)**
 - Xcode 13.4.1

**Comment by YOCKOW** [comment]
I know how you feel, but this is a duplicate of [SR-3082](https://github.com/apple/swift/issues/45672).

**Comment by StevenMagdy** [comment]
@YOCKOW No worries. I tried searching for a similar issue before opening a new one but I guess I ignored the duplicate because the title is not very clear.
