### ISSUE TITLE
"Failed to produce diagnostic for expression" for SwiftUI View

### ISSUE THREAD

**Issue by dialadahabi** [apple/swift#59991]
**Describe the bug**
The following code produces "Failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project" on the ContentView body method. 

I am aware that the issue is missing braces `.padding()`

```swift
struct ContentView: View {
    var body: some View {
        VStack (alignment: .leading){
            Text("Some text")
                .font(.title)
                .foregroundColor(.black)
            HStack {
                Text("Subheadline 1").font(.subheadline)

                Spacer()

                Text("Subheadline 2").font(.subheadline)
            }
        }
        .padding
    }
}
```
**Screenshot**
<img width="1789" alt="Screen Shot 2022-07-10 at 8 59 49 PM" src="https://user-images.githubusercontent.com/9038865/178156556-31701c7f-9e14-4c9d-bffe-f584c552a333.png">

**Comment by xedin** [comment]
Thank you for reporting, this issue with un-called reference to `padding` is something that we are aware of and it should be fixed by https://github.com/apple/swift/pull/58879

**Comment by xedin** [comment]
Appears to be fixed on `main`:

```
error: type '(EdgeInsets) -> some View' cannot conform to 'View'
        .padding
         ^
 note: only concrete types such as structs, enums and classes can conform to protocols
        .padding
         ^
note: required by static method 'buildExpression' where 'Content' = '(EdgeInsets) -> some View'
        .padding
         ^
```

@ dialadahabi please verify using the latest snapshot of main from swift.org and resolve this issue.

**Comment by dialadahabi** [comment]
@xedin resolved thanks
