### ISSUE TITLE
Accessing a generated var of an actor from an `if let` statement alters the current actor if the result is `nil`

### ISSUE THREAD

**Issue by ptsochantaris** [apple/swift#60002]
**Describe the bug**

If a task on the `@MainActor` accesses a generated `var` of a different actor inside an `if let` statement, and the actor var happens to return an optional nil value, then the code following that access on the original task will continue to run on the thread of the actor instead of carrying on in the `@MainActor`.

If the generated `var` is accessed ahead of the `if let` statement then no such issue occurs, and the subsequent code executes on the `@MainActor` as expected.

I am attaching a very simple Xcode project that reliably reproduces this, but also attaching a screenshot which shows what happens when you run it:

**Steps To Reproduce**

1. Open attached project in Xcode 13.4.1 (or Xcode 14 beta 3)
2. Run the project

**Expected behavior**

The task in the code should run through and print in the console:
```
1 - No result
2 - No result
```
Instead the assertion in the code will trap and only the first line will be printed.

**Screenshots**

<img width="915" alt="Screenshot 2022-07-11 at 19 02 46" src="https://user-images.githubusercontent.com/521581/178328597-9de87b6d-ad69-4f55-96c0-45728c344130.png">

**Environment (please fill out the following information)**

 - OS: macOS. Monterey 12.4
 - Xcode Version 13.4.1 from App Store 

**Additional context**

The issue seems to also occur in the latest Xcode 14.0 betas from what I've tested, hence me submitting this report.

The zipped project file:
[Oscar.zip](https://github.com/apple/swift/files/9086528/Oscar.zip)

**Comment by SRam89** [comment]
Good Evening @ptsochantaris, 

It seems that `let resultInsideIfLet = await MyIsolatedClass.shared.value `was not defined causing the "Thread 2: Assertion failed". 
I've attached a screenshot with the needed corrections and showing your expected results. 
[Screenshot of Corrected Code.pdf](https://github.com/apple/swift/files/9097514/Screenshot.of.Corrected.Code.pdf)

**Comment by ptsochantaris** [comment]
Hi @SRam89 and thank you for your reply, however if you take a second look at the code I am aware of the workaround of placing the `let resultInsideIfLet = await MyIsolatedClass.shared.value` outside the `if let` -- it is, in fact, the first `if` instance in the sample code, which always works as expected.

The second case, with the `await` inlined is the part that fails unexpectedly (both in Swift 5.6 or 5.7)

It's also worth noting that, if you change the code above so that  `MyIsolatedClass.shared.value` returns a non-nil value then the original code will work as well with no other modifications.

However my point is that the original code is valid Swift syntax and compiles fine (see attached project) - which means that either there is some semantic issue which I am not aware of regarding the low-level interaction of actors, or a compiler warning should perhaps be emitted to warn against this, or this is a bug, which I feel is the more likely case - especially given the very specific circumstances under which it occurs (the value must be from an actor, it must be an optional `var`, it must be `nil`, and the `await` must occur inside an `if let`) 

Apologies if I'm perhaps misunderstanding your reply though, I hope this description helps give a better idea of what I believe is broken.

**Comment by ptsochantaris** [comment]
This issue seems to be fixed in Xcode 14.0 beta 5 (14A5294e) - tested on the same device using Xcode 13.1.4 as control. Closing this ticket and many thanks to whoever fixed it!!
