### ISSUE TITLE
contextMenu in NavigationLink not working in the light mode

### ISSUE THREAD

**Issue by seungjun-green** [apple/swift#60066]
**Describe the bug**

If the view for the label of the `NavigationLink`, attached with `contextMenu`, it has no problem in dark mode but, in the light mode, it doesn't show `contextMenu` when it got long pressed.

**Steps To Reproduce**

Here's a sample code(tested on Xcode 13.3):

```
struct ContentView: View {
    var body: some View {
        NavigationView{
            NavigationLink {
                Text("Details View")
            } label: {
                ButtonView()
                    .contextMenu{
                        Button("Tap Me") { print("Tapped!") }
                    }
            }
        }
    }
}


struct ButtonView: View {
    var body: some View {
        Text("dd").foregroundColor(.white)
            .padding().frame(width: 80, height: 80)
            .background(.purple)
    }
}
```

Build the project and try long pressing the ButtonView(). In dark mode it shows contextMenu successfully, but in light mode it does not.

**Expected behavior**
When ButtonView() got pressed it should show `contextMenu` also in light mode.

**Screenshots**
Light Mode:
![Screen Shot 2022-07-15 at 6 12 46 PM](https://user-images.githubusercontent.com/60959924/179193082-5b33b33b-3973-4509-8b98-4642346934a5.png)

Dark Mode(no problem with this screenshot):
![Screen Shot 2022-07-15 at 6 13 28 PM](https://user-images.githubusercontent.com/60959924/179193198-1529d679-fd9b-4b47-a3a3-378abca14dfe.png)

**Environment (please fill out the following information)**
 - OS: [e.g. macOS 12.4]
 - Xcode 13.3

**Additional context**

I tried moving the contextMenu modifier after the label, like this:

```
struct ContentView: View {
    var body: some View {
        NavigationView{
            NavigationLink {
                Text("Details View")
            } label: {
                ButtonView()
            }.contextMenu{
                Button("Tap Me") { print("Tapped!") }
            }
        }
    }
}
```
But this time, app shows `contextMenu` for both cases, but the ButtonView() got blurred when it got long pressed.

![Screen Shot 2022-07-15 at 6 16 47 PM](https://user-images.githubusercontent.com/60959924/179193756-afcab44b-4434-4a92-897b-fa30f4f929ff.png)

![Screen Shot 2022-07-15 at 6 17 44 PM](https://user-images.githubusercontent.com/60959924/179193912-4a059c65-bd42-42c0-98be-5291b07c2c4b.png)

**Comment by LucianoPAlmeida** [comment]
Hey @seungjun-green this space is for tracking issues related to the Swift compiler, language, runtime, and standard library. If you believe this is an Apple Framework issue (in this case `SwiftUI`) you can submit a [Feedback](https://feedbackassistant.apple.com/)
Also, there are many community resources available to you to ask such questions, including StackOverflow, Reddit, Twitter and so on...
With that said, closing this one
