### ISSUE TITLE
Parse failure with `<` after a cast destination type.

### ISSUE THREAD

**Issue by simanerush** [apple/swift#60146]
**Description**
When dealing with cast destination type and a `<` operator after it, the compiler assumes that the generic arguments list is going to follow the `<` and produces an `expected type` error. 

**Steps To Reproduce**
1. Launch Swift.
2. Run `let _ = 1 as Int16 < 7`.
3. Observe the `expected type` error.

**Expected behavior**
There should be no `expected type` error, since `<` in this context is not supposed to be followed by a generic arguments list.

**Environment**
 - OS: macOS 12.4
 - Xcode Version: 13.4

**Additional context**
I fixed issue #43053 which addresses similar problem, but with the`<<` operator.

**Comment by CodaFi** [comment]
This is a fun cross-language disambiguation problem. Consider the (related) classical ambiguous parsing example:

```
f(a<b,c>(d))
```

Is `a<b,c>` meant to be a specialized generic type that is having its initializer invoked with argument `d`, or are a, b, c, and d actually two boolean arguments to `f` that are being compared via the `<` and `>` operators? Bear in mind that both answers are valid parser productions if we parse without retaining a bunch of contextual state (e.g. a symbol table) or performing some amount of unbounded lookahead. 

For some context, Rust has [the exact same problem](https://github.com/rust-lang/rust/issues/22644).

**Comment by tbkka** [comment]
That same Rust thread [describes the C# heuristic](https://github.com/rust-lang/rust/issues/22644#issuecomment-75466424), which makes a lot of sense to me.

**Comment by CodaFi** [comment]
The current Rust-y answer of using lookahead to emit an extremely helpful diagnostic also works here. The C# solution doesn't feel right to me not just because it fails the "some amount of unbounded lookup" test, but because it precludes the language adopting non-type type parameter arguments without some extra disambiguating tokens.

**Comment by simanerush** [comment]
@CodaFi Thank you for this detailed response. I understand the first problem with some ambiguity concerning `<`, but your second message is more concerned with `<<`. One of my currently opened PRs silences the `expected type` diagnostics in that case. Now, I'm wondering if we even need to silence that if for example Rust doesn't do it but emits helpful diagnostics. Can you please take a look at this PR which addresses `<<` issue? #60088
