### ISSUE TITLE
Using the subscript of a dict inside a non-escaping async closure in an actor fails

### ISSUE THREAD

**Issue by FranzBusch** [apple/swift#60302]
**Describe the bug**
When using the subscript of a dictionary inside an `async` method that is non-escaping in an `actor` it produces a compiler error. While calling `.updateValue()` works without problems.

Looking at this code:

```swift
actor Foo {
    var dict = [String: String]()
    func foo() async {
        await withTaskGroup(of: Void.self) { _ in
            dict.updateValue("Bar", forKey: "Foo")
            dict["Foo"] = "Bar" // Actor-isolated property 'dict' cannot be passed 'inout' to 'async' function call
        }
    }
}
```

**Expected behavior**
The above code should compile fine

rdar://97775762

**Comment by JoachimM7** [comment]
It's the same if you use an array... but then you don't have the option to use anything like `updateValue`.

```
actor Foo {
	var arr = [String]()
	func foo() async {
		await withTaskGroup(of: Void.self) { _ in
			self.arr[0] = "Bar" // Actor-isolated property 'arr' cannot be passed 'inout' to 'async' function call
		}
	}
}
```

But in comparison, `append` would work:

```
actor Foo {
	var arr = [String]()
	func foo() async {
		await withTaskGroup(of: Void.self) { _ in
			arr.append("test")
		}
	}
}
```

**Comment by hborla** [comment]
This was fixed by https://github.com/apple/swift/pull/69126
