### ISSUE TITLE
Prefer overloaded witnesses with 'async'-ness matching in protocol conformance

### ISSUE THREAD

**Issue by kateinoigakukun** [apple/swift#60318]
**Describe the bug**

Currently, an async method requirement in a protocol prefers a sync method even if having both sync and async overload.

This would be a follow-up of https://github.com/apple/swift/issues/57476, which allows having overloads that differ only 'async'-ness in protocol requirements.
The test case added in the overload fix PR ensures that compilation succeeds, but both `func foo()` and `func foo() async` in protocol `A` picks `func foo()` in `A2` as witnesses.

**Steps To Reproduce**

Here is the minimum reproducible code, that checks which method is picked as a witness of `func foo() async -> String`. I expect this shouldn't hit the assertion.

```swift
protocol P {
  func foo() async -> String
}

struct S: P {
  func foo() -> String { "sync" }
  func foo() async -> String { "async" }
}

@main
struct Main {
  static func main() async {
    let p: P = S()
    let out = await p.foo()
    assert(out == "async", "await p.foo() calls '\(out)' version")
  }
}
```

**Expected behavior**

Prefer `async`-ness matching implementation when picking witnesses for async method requirements.

**Environment (please fill out the following information)**
 - OS: Ubuntu 20.04.4 LTS
 - Xcode Version/Tag/Branch: DEVELOPMENT-SNAPSHOT-2022-07-25-a

**Additional context**

Related links: https://github.com/apple/swift/issues/57476, https://github.com/apple/swift-evolution/pull/1392

**Comment by kavon** [comment]
rdar://109135488

**Comment by kavon** [comment]
Fixed in https://github.com/apple/swift/pull/65840 on `main`
