### ISSUE TITLE
build-toolchain script fails on M1 Mac with `.../swift-macosx-arm64/bin/swiftc: No such file or directory`

### ISSUE THREAD

**Issue by allevato** [apple/swift#60348]
When running `utils/build-toolchain` on an M1 Mac, the build fails when compiling Swift modules with the following error:

```
FAILED: SwiftCompilerSources/_CompilerRegexParser.o /Users/allevato/Source/Swift/build/buildbot_osx/swift-macosx-arm64/SwiftCompilerSources/_CompilerRegexParser.o
cd /Users/allevato/Source/Swift/swift/SwiftCompilerSources && /Users/allevato/Source/Swift/build/buildbot_osx/swift-macosx-arm64/bin/swiftc -c <additional compiler args...>
/bin/sh: /Users/allevato/Source/Swift/build/buildbot_osx/swift-macosx-arm64/bin/swiftc: No such file or directory
```

Indeed, the only binaries in that directory on my machine are the following:

```shell
$ ls /Users/allevato/Source/Swift/build/buildbot_osx/swift-macosx-arm64/bin/
lldb-check-expect lldb-with-tools
```

Additional discussion at https://forums.swift.org/t/get-the-error-when-building-the-toolchain/58665.

### Steps To Reproduce
1. Run `utils/build-toolchain $TOOLCHAIN_ID` (where `TOOLCHAIN_ID` is some arbitrary name)

### Expected behavior
A toolchain is built.

### Environment
 - OS: macOS 12.4
 - Xcode Version/Tag/Branch: Xcode 13.3; apple/swift `main` branch at HEAD

**Comment by CNKCQ** [comment]
I got the same error

**Comment by keith** [comment]
https://github.com/apple/swift/pull/60624
