### ISSUE TITLE
[main] Regression when awaiting `async let`s that are re-throwing

### ISSUE THREAD

**Issue by FranzBusch** [apple/swift#60351]
**Describe the bug**
The following code compiles perfectly fine on 5.6 and 5.7; however, it is broken on recent `main`.

```swift
func foo() async {
    let stream = AsyncStream<Int>{ _ in }
    async let bar = stream.first { _ in true}

    await bar // error: call can throw, but it is not marked with 'try' and the error is not handled
}
```

**Expected behavior**
The above code should compile on main and should not require a `try` since the call to `first` is re throwing.

rdar://97966043

**Comment by LucianoPAlmeida** [comment]
@FranzBusch This was a regression introduced by https://github.com/apple/swift/pull/41661, sorry for that.
We are working on the fix in https://github.com/apple/swift/pull/60148
