### ISSUE TITLE
Swift 5.7 No type can satisfy both protocol's typealias and associatedtype

### ISSUE THREAD

**Issue by lawmicha** [apple/swift#60395]
**Describe the bug**
The following code compiles on Xcode 13.4.1 and does not compile on Xcode 14.0 beta 4

**Steps To Reproduce**
1. Try to compile 
```swift
protocol AnyModelIdentifierFormat {}

protocol Model: Codable {
    typealias Identifier = String
}

protocol ModelIdentifiable {
    associatedtype IdentifierFormat: AnyModelIdentifierFormat
    associatedtype Identifier: ModelIdentifierProtocol
}

protocol ModelIdentifierProtocol {
}

struct ModelIdentifier<M: Model, F: AnyModelIdentifierFormat>: ModelIdentifierProtocol {
}

func callSite<M: Model>(_ modelType: M.Type,
                        withIdentifier identifier: ModelIdentifier<M, M.IdentifierFormat>) where M: ModelIdentifiable {
    
}

```
2. Error when using Xcode 14 beta 4
```
expression failed to parse:
error: MyPlayground14.playground:19:14: error: no type for 'M.Identifier' can satisfy both 'M.Identifier == String' and 'M.Identifier : ModelIdentifierProtocol'
func callSite<M: Model>(_ modelType: M.Type,
             ^

```

**Expected behavior**
Xcode 14 beta 4 / Swift 5.7 does not introduce compile errors with the above code snippet.

**Screenshots**

**Environment (please fill out the following information)**
 - OS: macOS 12.4
 - Xcode Version/Tag/Branch: Xcode 13.4.1 and Xcode 14 beta 4

**Additional context**
https://github.com/aws-amplify/amplify-ios/pull/2077

**Comment by slavapestov** [comment]
I believe the new behavior is correct. A typealias in a protocol introduces a same-type requirement between any associated type with the same name.

**Comment by lawmicha** [comment]
Hi @slavapestov, thanks for confirming the new behavior is as expected. We've updated our code to fix the problem we were seeing.
