### ISSUE TITLE
Private global actor type can be used to isolated public entities

### ISSUE THREAD

**Issue by nickolas-pohilets** [apple/swift#60420]
Consider the following code:
```swift
@globalActor private final actor PrivateActor {
    static let shared = PrivateActor()
}

public class Foo {
    @PrivateActor public func bar() {}
}
```

It type checks without errors. Global actor annotation is part of the function interface, and escapes into public interface of the module.

**Expected behavior**
Global actor used for isolation should not be less visible than the entity it is isolating. Given code should produce a compilation error.

**Environment (please fill out the following information)**
- Xcode 13.3.1, Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)
- `main` branch, reproducible on https://github.com/apple/swift/commit/a39c78b586155c18fb99e023c5ca42dd6df36145

Radar: rdar://98200658

**Comment by theblixguy** [comment]
Yeah, it looks like we do not check global actors in `TypeCheckAccess` when visiting functions, variables and etc. It should be fairly straightforward to tweak the code to do that.
