### ISSUE TITLE
Missing `any` in -emit-silgen output

### ISSUE THREAD

**Issue by slavapestov** [apple/swift#60434]
```swift
protocol P {
  associatedtype T
}

func foo(_: any P) {}
```

-emit-silgen outputs this:

```swift
sil_stage raw

import Builtin
import Swift
import SwiftShims

protocol P {
  associatedtype T
}

func foo(_: P)

sil [ossa] @main : $@convention(c) (Int32, UnsafeMutablePointer<Optional<UnsafeMutablePointer<Int8>>>) -> Int32 {
...
```

Which doesn't parse back in because of the missing `any`.

**Comment by hborla** [comment]
Ah, printing `any` is currently gated behind `PrintOptions::PrintExplicitAny`, which is only set to `true` for diagnostics and Swift interface printing. I think it's time to print `any` everywhere! I've been procrastinating this because I tried it once and like 300 tests failed 😂

**Comment by AnthonyLatsis** [comment]
@hborla Want me to do this? 😂

**Comment by hborla** [comment]
@AnthonyLatsis that is very nice of you! But don't worry I'm already 178 test files in 🙂
