### ISSUE TITLE
Support Ubuntu 22.04 for Swift 5.7

### ISSUE THREAD

**Issue by shahmishal** [apple/swift#60465]
- [x] Add Docker image for Ubuntu 22.04 on swift-docker repo
- [x] Add Swift CI jobs to build nightly toolchains 
- [x] Update the automation to include Ubuntu 22.04 toolchain
- [ ] Update the website to include links to Ubuntu 22.04

**Comment by shahmishal** [comment]
Currently, the `release/5.7` does not contain all of the Python 3 changes required to support Ubuntu 22.04.

**Comment by neilt** [comment]
Can't wait, we are moving our test servers to 22.04.

**Comment by shahmishal** [comment]
https://github.com/apple/swift-llbuild/pull/838

**Comment by shahmishal** [comment]
https://github.com/apple/swift-package-manager/pull/5743

**Comment by shahmishal** [comment]
https://github.com/apple/indexstore-db/pull/157

**Comment by shahmishal** [comment]
https://github.com/apple/sourcekit-lsp/pull/616

**Comment by shahmishal** [comment]
https://github.com/apple/swift-docc/pull/370

**Comment by shahmishal** [comment]
https://github.com/apple/swift-org-website/pull/126

**Comment by shahmishal** [comment]
Ubuntu 22.04 now available on swift.org for nightly snapshots.
