### ISSUE TITLE
@discardableResult is ignored within the globalActor attribute

### ISSUE THREAD

**Issue by swiftty** [apple/swift#60545]
With this code:

```swift
@MainActor
class Foo {
    @discardableResult
    func bar() -> Int {
        return 10
    }
}

@MainActor
@discardableResult
func baz() -> Bool {
    return true
}

Task {
    await Foo().bar()
    await baz()
    return
}
```

Compiling with Swift 5.7 from Xcode 14.0 beta 4, you see these warnings.

```
Result of call to function returning 'Int' is unused
Result of call to function returning 'Bool' is unused
```

**Expected behavior**
Suppress unused warnings.

**Environment (please fill out the following information)**
 - OS: macOS 12.5
 - Xcode Version/Tag/Branch: Xcode 14.0 beta 4~

**Comment by xedin** [comment]
Should be fixed by https://github.com/apple/swift/pull/60386 . Could you please verify using the latest main or 5.7 branch toolchain? Changes landed about 10 days ago, so main should definitely have it.

**Comment by NachoSoto** [comment]
You beat me by 2 hours 😅

**Comment by swiftty** [comment]
thanks, I confirmed that it was resolved in the latest snapshot `swift-DEVELOPMENT-SNAPSHOT-2022-08-10-a`.

**Comment by kahoot-kbochynski** [comment]
still an issue on XCode Version 15.0 (15A240d). reopen?

**Comment by kahoot-kbochynski** [comment]
still an issue on XCode Version 15.0 (15A240d). reopen?

**Comment by kahoot-kbochynski** [comment]
`struct Bar {
    let value: Int
}

struct Foo {
    let bar: Bar
}
final class Demo {

    let someBarProducer: SomeBarProducer

    init(someBarProducer: SomeBarProducer) {
        self.someBarProducer = someBarProducer
    }

    func handleFooBars(_ foos: [Foo]) {
        Task { @MainActor in
            await withTaskGroup(of: Void.self) { group in
                for foo in foos {
                    group.addTask {
                        try? await self.someBarProducer.handleFoo(foo)
                    }
                }
                await group.waitForAll()
            }
        }
    }
}

final class SomeBarProducer {

    @discardableResult
    @MainActor
    func handleFoo(_ foo: Foo) async throws -> Bar {
        try Task.checkCancellation()
        return foo.bar
    }
}`
Please check this one

**Comment by AnthonyLatsis** [comment]
This is not unrelated to concurrency. I opened #71870.
