### ISSUE TITLE
Source compatibility suite: Line-sdk-ios-swift failing to build after llvm-project branch update

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#60577]
**Describe the bug**
`line-sdk-ios-swift` is failing to build after updating the revision of the llvm-project used to build swift within the source compatibility suite.

```swift
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/System/Library/Frameworks/SafariServices.framework/Headers/SFAuthenticationSession.h:17:28: error: domain argument does not refer to global constant
typedef NS_ENUM(NSInteger, SFAuthenticationError) {
                           ^
jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/line-sdk-ios-swift/LineSDK/LineSDK/Login/LoginProcess.swift:24:8: error: could not build Objective-C module 'SafariServices'
import SafariServices
```

**Steps To Reproduce**
1.) Build swift using the `main` branch
2.) Attempt to build `line-sdk-ios-swift` using revision `d8bb2bc`

Expected behavior
The package builds without errors.

**Environment (please fill out the following information)**
swift-main-source-compat-suite
swift-main-source-compat-suite-debug

**Additional context**
This is a result of the recent update to swift in which we target the llvm-project branch `stable/20220421` 
https://github.com/apple/swift-source-compat-suite/pull/698

Failing job: https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/53/

**Comment by justice-adams-apple** [comment]
This also affects ACHNBrowserUI

**Comment by hyp** [comment]
Fixed in https://github.com/apple/llvm-project/pull/5183
Updated source compatibility suite: https://github.com/apple/swift-source-compat-suite/pull/704
