### ISSUE TITLE
Source compatibility suite: Kickstarter-ReactiveExtensions failing to build

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#60598]
**Describe the bug**
ReactiveExtensions is failing to build with 5.0

```
Prepare build
error: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
Build Preparation
The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
```

This is because we now use swift-driver which doesn't integrate with the legacy build system. The correct approach is for the project to be updated to use the newest build system.

**Steps To Reproduce**
1.) Build swift using the main branch
2.) Attempt to build Kickstarter-ReactiveExtensions using revision aa994f0921dca1965ae537fe77c2edc798eef230
...

**Expected behavior**
The package builds without errors.

**Environment (please fill out the following information)**
swift-main-source-compat-suite
swift-main-source-compat-suite-debug

**Additional context**
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/57/artifact/swift-source-compat-suite/XFAIL_Kickstarter-ReactiveExtensions-ReactiveExtensions.xcodeproj_5.0_BuildXcodeProjectScheme_ReactiveExtensions-iOS_generic-platform-iOS.log

**Comment by justice-adams-apple** [comment]
I will reach out to the Kickstarter-ReactiveExtensions owner and request a source update. Will report back once I hear anything from them

**Comment by AnthonyLatsis** [comment]
I assume this is resolved because `Kickstarter-ReactiveExtensions` is still in the suite and has been green recently.
