### ISSUE TITLE
Incorrect diagnostic when attempting to extend `any P`

### ISSUE THREAD

**Issue by bjhomer** [apple/swift#60595]
**Describe the bug**
When you attempt to write `extension any P`, the compiler suggests that you should try extending `any P` instead, which is not very useful. Then the fix-it inserts `P` instead of `any P`, which is the opposite of what the error message suggested.

```
protocol P {}

extension any P {
    static var foo: String { "foo" }
}
```

Compiler Output:
```
error: extension of type 'any P' must be declared as an extension of 'any P'
extension any P {
^         ~~~~~

note: did you mean to extend 'any P' instead?
extension any P {
^         ~~~~~
          P
```

**Steps To Reproduce**
1. Try to compile the above code
2. Note that the error message tries to tell you to do something you're already doing, and which is not supported.

**Expected behavior**
I'd love to be able to actually extend the existential box with its own functionality. But until that's supported, the error should be something more like this:

```
error: extension of type 'any P' not supported
extension any P {
^         ~~~~~

note: did you mean to extend 'P' instead?
extension any P {
^         ~~~~~
          P
```

**Screenshots**
N/A

**Environment (please fill out the following information)**
 - OS: macOS 13.0 Beta (22A5321d)
 - Xcode Version/Tag/Branch: Version 14.0 beta 5 (14A5294e)

**Additional context**
N/A

**Comment by LucianoPAlmeida** [comment]
@hborla this looks like just needs a tailored diagnostic message, so my guess it would be good to label as a starter bug?

**Comment by dfperry5** [comment]
@hborla / @LucianoPAlmeida  Is this something I could tackle as part of the Swift Mentorship program?

**Comment by LucianoPAlmeida** [comment]
> @hborla / @LucianoPAlmeida Is this something I could tackle as part of the Swift Mentorship program?

@dfperry5 Sure! Feel free to assign yourself to it =]

**Comment by cbjeukendrup** [comment]
Oops, it looks like things crossed each other! I was already working on a PR but had not seen the last two comments (I had to work offline today...). @dfperry5 I'm so sorry!

**Comment by dfperry5** [comment]
No problem @cbjeukendrup -- Just jealous you got to it before me!
