### ISSUE TITLE
Swift 5.7 segmentation fault during silgen

### ISSUE THREAD

**Issue by stjernegard** [apple/swift#60723]
**Describe the bug**
When using Swift 5.7, the compiler will crash when trying to compile anything containing a function like the one below.
```Swift
func test(arg: Never) async { } 
```

The same happens with any other enum with no cases.

This can also be seen here: https://swiftfiddle.com/jw3n746lkfgwxmpdqh3xqltmui

**Environment**
 - Xcode 14.0 beta 5
 - swift-driver version: 1.62.3 Apple Swift version 5.7 (swiftlang-5.7.0.123.8 clang-1400.0.29.50) 
    Target: arm64-apple-macosx13.0

**Comment by theblixguy** [comment]
It doesn’t crash on `main` so I guess it got fixed recently.
