### ISSUE TITLE
Improve error message for type mismatch between `any P` and `(any P)?`

### ISSUE THREAD

**Issue by hborla** [apple/swift#60730]
If you try to pass a value of type `(any P)?` to an argument of type `any P`, Swift should produce an error telling you to unwrap the optional. Instead, it tells you that `(any P)?` doesn’t conform to `P`, which is confusing, and the user probably meant to unwrap the argument anyway.

```swift
protocol P {}

struct S: P {}

func takesP(_: any P) {}

func passOptional(value: (any P)?) {
  takesP(value) // error: Argument type '(any P)?' does not conform to expected type 'P'

  takesP(value ?? S()) // okay
  takesP(value!) // okay
}
```

The constraint system currently applies the `MissingConformance` fix when solving for  the `takesP(value)` expression. Instead, it should identify that the wrapped type of the argument matches the parameter type, and apply the `ForceOptional` fix.

This is also tracked by rdar://94037733

**Comment by hborla** [comment]
cc @dfperry5 this is a good constraint system starter bug if you're interested!

**Comment by dfperry5** [comment]
@hborla  - I am so interested and am happy to take it on!

**Comment by dfperry5** [comment]
Opened PR here: https://github.com/apple/swift/pull/61191
