### ISSUE TITLE
Autolinks for Swift evolution proposal identifiers (SE-*)

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#60747]
Today, Swift Jira issue identifiers (example: SR-1) are [automatically turned into links](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources). It would be great to extend this functionality to Swift evolution proposals (example: SE-1).

**Comment by benrimmington** [comment]
This feature was also [requested][] for the forums.

[requested]: <https://forums.swift.org/t/in-any-forum-post-is-there-anyway-configure-the-forum-software-to-automatically-make-swift-evolution-se-nnnn-into-tooltip-showing-its-full-title-and-link-to-go-to-the-ses-page/55641>

**Comment by shahmishal** [comment]
Updated to support `SE-` in apple/swift repo. 

SE-<num> will point to https://apple.github.io/swift-evolution/#?proposal=SE-<num>

Thanks @AnthonyLatsis @benrimmington!

**Comment by AnthonyLatsis** [comment]
Thank you so much @shahmishal! We use four-digit identifiers for evolution proposals; could we also add any missing leading zeros so that e.g. SE-1 and SE-01 both appear as SE-0001 in the search query?

> SE- will point to https://apple.github.io/swift-evolution/#?proposal=SE-

Is this as accurate as we can get?

**Comment by shahmishal** [comment]
Not sure if this is supported by GitHub auto linking feature, I could be wrong.

**Comment by AnthonyLatsis** [comment]
Looks like it: the documentation only mentions a <num> variable, no scripting. Pity.

**Comment by AnthonyLatsis** [comment]
We need support for `https://apple.github.io/swift-evolution/SE-*` URL paths to make this work.

**Comment by benrimmington** [comment]
@shahmishal Please could the autolink setting be changed to:

+ **Numeric**
  Numeric autolinks only match `0-9`.

I think the setting is currently:

- **Alphanumeric**
  Alphanumeric autolinks match `A-Z`, `0-9`, and `-`. They are not case sensitive.

For example, it matches the "glessard/se-pointer-family-initialization" branch name (in commit 2689b6044bb7d519c18892d95211c2dd794e30c5).

**Comment by AnthonyLatsis** [comment]
@shahmishal ping

**Comment by shahmishal** [comment]
This is fixed now.
