### ISSUE TITLE
Generic signature compiler error when using `typealias`

### ISSUE THREAD

**Issue by igor-makarov** [apple/swift#60741]
The following example code does not compile in 5.7.  
I believe this is a compiler regression since the `typealias` refers to a concrete type that isn't generic.

```swift
public protocol P {}

extension P {
    public typealias Aliased = Int
}

public struct S<O: P>: Hashable {
    internal var aliasedAccessor: O.Aliased {
        fatalError()
    }
}

public struct ComplicatedStruct<C, ID> where C: Collection, ID: Hashable {
    public init(_ data: C, id: KeyPath<C.Element, ID>) {
        fatalError()
    }
}

extension ComplicatedStruct {
    public init<O: P>(collection: C, objectType: O.Type)
    where C.Element == S<O>, ID == O.Aliased {
        self.init(collection, id: \.aliasedAccessor) // error: key path value type 'Int' cannot be converted to contextual type 'ID'
    }
}
```

It compiled correctly in 5.6 and was used in [CoreStore](https://github.com/JohnEstropia/CoreStore/blob/develop/Sources/ForEach%2BSwiftUI.swift#L62) library. 

[Compiler Explorer, Swift 5.6](https://swift.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:swift,selection:(endColumn:1,endLineNumber:25,positionColumn:1,positionLineNumber:25,selectionStartColumn:1,selectionStartLineNumber:25,startColumn:1,startLineNumber:25),source:'public+protocol+P+%7B%7D%0A%0Aextension+P+%7B%0A++++public+typealias+Aliased+%3D+Int%0A%7D%0A%0Apublic+struct+S%3CO:+P%3E:+Hashable+%7B%0A++++internal+var+aliasedAccessor:+O.Aliased+%7B%0A++++++++fatalError()%0A++++%7D%0A%7D%0A%0Apublic+struct+ComplicatedStruct%3CC,+ID%3E+where+C:+Collection,+ID:+Hashable+%7B%0A++++public+init(_+data:+C,+id:+KeyPath%3CC.Element,+ID%3E)+%7B%0A++++++++fatalError()%0A++++%7D%0A%7D%0A%0Aextension+ComplicatedStruct+%7B%0A++++public+init%3CO:+P%3E(collection:+C,+objectType:+O.Type)%0A++++where+C.Element+%3D%3D+S%3CO%3E,+ID+%3D%3D+O.Aliased+%7B%0A++++++++self.init(collection,+id:+%5C.aliasedAccessor)+//+error:+key+path+value+type+!'Int!'+cannot+be+converted+to+contextual+type+!'ID!'%0A++++%7D%0A%7D%0A'),l:'5',n:'0',o:'Swift+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:swift56,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:swift,libs:!(),options:'',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+swiftc+5.6+(Swift,+Editor+%231)',t:'0')),header:(),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) - Compiles correctly

[Compiler Explorer, Swift 5.7](https://swift.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:swift,selection:(endColumn:1,endLineNumber:25,positionColumn:1,positionLineNumber:25,selectionStartColumn:1,selectionStartLineNumber:25,startColumn:1,startLineNumber:25),source:'public+protocol+P+%7B%7D%0A%0Aextension+P+%7B%0A++++public+typealias+Aliased+%3D+Int%0A%7D%0A%0Apublic+struct+S%3CO:+P%3E:+Hashable+%7B%0A++++internal+var+aliasedAccessor:+O.Aliased+%7B%0A++++++++fatalError()%0A++++%7D%0A%7D%0A%0Apublic+struct+ComplicatedStruct%3CC,+ID%3E+where+C:+Collection,+ID:+Hashable+%7B%0A++++public+init(_+data:+C,+id:+KeyPath%3CC.Element,+ID%3E)+%7B%0A++++++++fatalError()%0A++++%7D%0A%7D%0A%0Aextension+ComplicatedStruct+%7B%0A++++public+init%3CO:+P%3E(collection:+C,+objectType:+O.Type)%0A++++where+C.Element+%3D%3D+S%3CO%3E,+ID+%3D%3D+O.Aliased+%7B%0A++++++++self.init(collection,+id:+%5C.aliasedAccessor)+//+error:+key+path+value+type+!'Int!'+cannot+be+converted+to+contextual+type+!'ID!'%0A++++%7D%0A%7D%0A'),l:'5',n:'0',o:'Swift+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:swift57nightly,compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:swift,libs:!(),options:'',source:1,stdinPanelShown:'1',tree:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+swiftc+5.7+(nightly)+(Swift,+Editor+%231)',t:'0')),header:(),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) - Errors

**Comment by igor-makarov** [comment]
@slavapestov is this related to the requirement machine?

**Comment by AnthonyLatsis** [comment]
Reduced:

```swift
protocol P {
//  typealias Alias = Int // works
}
extension P {
  typealias Alias = Int // doesn't work
}

struct S<T, U: P> {
  func f() where T == U.Alias {
    let _: T = 0
  }
}
```

**Comment by igor-makarov** [comment]
Thanks @AnthonyLatsis!

**Comment by slavapestov** [comment]
Yep, type aliases in protocol extensions cannot be referenced from where clauses.

**Comment by igor-makarov** [comment]
It would seem rather odd to the end user.  
This syntax is definitely referring to a concrete type, and yet it's not allowed.

To me, it seems just as puzzling as the associated type limitations on protocols used to feel before 5.7.

I understand that there's a technical reason for the limitation, but I was hoping it could be lifted to avoid 'punishing' the end user with hard-to-understand error messages.

**Comment by slavapestov** [comment]
@igor-makarov I understand it seems like an arbitrary restriction since it used to work before. If I figure out a feasible way to remove it in the future I definitely will.
