### ISSUE TITLE
5.7 regression, closure not accepted when function with same signature is

### ISSUE THREAD

**Issue by keith** [apple/swift#60806]
With this code:

```swift
struct Foo<T> {
    init(_: (T) -> Void) {}
}

protocol Bar {}

enum Baz: Bar {
    case someCase(Int)
}

let _: Foo<Bar> = Foo<Bar> { (a: Bar) -> Void in
    switch a {
    case let .someCase(value) as Baz:
        print(value)
    default:
        break
    }
}
```

Compiling with Swift 5.6 works fine. With Swift 5.7 (Xcode 14b6) I get:

```
% swiftc bar.swift
bar.swift:11:19: error: type of expression is ambiguous without more context
let _: Foo<Bar> = Foo<Bar> { (a: Bar) -> Void in
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

With Swift main @ https://github.com/apple/swift/commit/5bfef4fc4bfa6e424384a39533ceea3744a613cc I get:

```
/tmp/bar.swift:13:15: error: type 'any Bar' has no member 'someCase'
    case let .someCase(value) as Baz:
             ~^~~~~~~~
```

Which appears to hint at the issue. Changing the closure to a function with the same signature sidesteps the issue:

```swift
struct Foo<T> {
    init(_: (T) -> Void) {}
}

protocol Bar {}

enum Baz: Bar {
    case someCase(Int)
}

func b(a: Bar) -> Void {
    switch a {
    case let .someCase(value) as Baz:
        print(value)
    default:
        break
    }
}

let _: Foo<Bar> = Foo<Bar>(b)
```

**Comment by LucianoPAlmeida** [comment]
This looks fixed on main: See https://godbolt.org/z/va5Ya5ccb
Can you please verify and close? Thanks!

**Comment by keith** [comment]
So the warning is improved, but I guess I wouldn't say it's fixed unless it's expected that it still doesn't compile, but a function with the same signature and contents does compile? https://godbolt.org/z/qGTEdYWjz

**Comment by LucianoPAlmeida** [comment]
Oh I see, just misunderstood the original case.

**Comment by keith** [comment]
I updated the title and removed the DiagnosticsQol label since really the core issue seems to be the regression that previously you could use a closure, but now that doesn't work but using a function does
