### ISSUE TITLE
Double Decimal calculations are wrong

### ISSUE THREAD

**Issue by krpatelit** [apple/swift#60822]
**Problem **
Mathematical operation on Double value with decimal points are not accurate

**Steps to reproduce **

`

    func checkDoublePrecision() {
    
    var doubleValue: Double = 1.00
   
    print("Start: \(doubleValue)")

    while doubleValue >= 0.00 {

        print(doubleValue)

        doubleValue -= 0.01

    }

    print("finish: \(doubleValue)")
}

checkDoublePrecision()
`

Above code generate below output 

`
Start: 1.0

1.0

0.99

0.98

0.97

0.96

0.95

0.94

0.9299999999999999

0.9199999999999999

0.9099999999999999
0.8999999999999999
0.8899999999999999
0.8799999999999999
0.8699999999999999
0.8599999999999999
0.8499999999999999
0.8399999999999999
0.8299999999999998
0.8199999999999998
0.8099999999999998
0.7999999999999998
0.7899999999999998
0.7799999999999998
0.7699999999999998
0.7599999999999998
0.7499999999999998
0.7399999999999998
0.7299999999999998
0.7199999999999998
0.7099999999999997
0.6999999999999997
0.6899999999999997
0.6799999999999997
0.6699999999999997
0.6599999999999997
0.6499999999999997
0.6399999999999997
0.6299999999999997
0.6199999999999997
0.6099999999999997
0.5999999999999996
0.5899999999999996
0.5799999999999996
0.5699999999999996
0.5599999999999996
0.5499999999999996
0.5399999999999996
0.5299999999999996
0.5199999999999996
0.5099999999999996
0.49999999999999956
0.48999999999999955
0.47999999999999954
0.46999999999999953
0.4599999999999995
0.4499999999999995
0.4399999999999995
0.4299999999999995
0.4199999999999995
0.4099999999999995
0.39999999999999947
0.38999999999999946
0.37999999999999945
0.36999999999999944
0.35999999999999943
0.3499999999999994
0.3399999999999994
0.3299999999999994
0.3199999999999994
0.3099999999999994
0.2999999999999994
0.28999999999999937
0.27999999999999936
0.26999999999999935
0.25999999999999934
0.24999999999999933
0.23999999999999932
0.22999999999999932
0.2199999999999993
0.2099999999999993
0.1999999999999993
0.18999999999999928
0.17999999999999927
0.16999999999999926
0.15999999999999925
0.14999999999999925
0.13999999999999924
0.12999999999999923
0.11999999999999923
0.10999999999999924
0.09999999999999924
0.08999999999999925
0.07999999999999925
0.06999999999999926
0.059999999999999255
0.04999999999999925
0.03999999999999925
0.02999999999999925
0.019999999999999248
0.009999999999999247
finish: -7.528699885739343e-16
`

Problem: 0.94 - 0.01  = 0.9299999999999999
Problem: 0.009999999999999247 - 0.01  = -7.528699885739343e-16

**Expected behavior**
.`Start: 1.0
1.0
0.99
0.98
0.97
0.96
0.95
0.94
0.93
0.94
.
.
0.01
finish: 0.00
`

**Screenshots**

**Environment (please fill out the following information)**
 - OS: macOS 12.2, Xcode: 13.2.1, Swift: 5.0
 - Xcode Version/Tag/Branch:

**Additional context**

**Comment by tbkka** [comment]
This all looks correct to me.  Swift Double is a _binary_ floating-point format, and so `0.01` cannot be exactly represented.  This means that repeated subtraction should be expected to differ from the results you would get computing the same series in decimal.

Please read:  [What Every Computer Scientist Should Know About Floating Point](https://docs.oracle.com/cd/E19957-01/800-7895/800-7895.pdf)

**Comment by krpatelit** [comment]
Hey Tim,

Thanks for your reply on my issue.
In that case could you help me how can we achieve this logic where we want
to deduct 0.01 amount and need a decimal precise result.

Regards
Kiran

**Comment by tbkka** [comment]
Use integers.
```
var a = 100  // Really 1.00
a -= 001   // Really - 0.01
```
Wrap this up in a `MyNumber` struct type to make it easier to use (and to hide the code that converts these to strings).

**Comment by krpatelit** [comment]
Hi Tim,

Thank you very much for the quick response.
That is surprising for me how that works.  Just curious to know, is it the
same for Objective-C also ?

**Comment by tbkka** [comment]
Double works the same way in every major programming language.  (Because the hardware implementations all follow IEEE 754 / ISO 60559.)
