### ISSUE TITLE
@discardableResult is ignored in global actor context (Xcode 14 only)

### ISSUE THREAD

**Issue by seanmrich** [apple/swift#60863]
A function annotated with a global actor ignores its `@discardableResult` attribute.

Consider the following:
```swift
@MainActor
struct UIStruct {
    @discardableResult
    func discardable() -> Int { 0 }
}

@MainActor
func uiFunction() {
    UIStruct().discardable()  // Warning: Result of call to function returning 'Int' is unused
}
```

In Xcode 13.4.1, this code compiles without warning. Xcode 14 beta 6 incorrectly warns that the result of the function is unused. In both versions of the compiler, removing `@MainActor` from the struct and function eliminates the warning.

Tested on macOS 12.5.1
Build setting `Strict Concurrency Setting` set to `Minimal`

**Comment by LucianoPAlmeida** [comment]
Duplicated from https://github.com/apple/swift/issues/60276 and resolved by https://github.com/apple/swift/pull/60324
Closing this, thanks @seanmrich!

**Comment by seanmrich** [comment]
Sorry for the dupe. Thanks for the quick action!
