### ISSUE TITLE
A switch statement can refer and use a property that defined after the switch block.

### ISSUE THREAD

**Issue by es-kumagai** [apple/swift#60872]
**Describe the bug**
A switch statement can refer and use a property that defined after the switch block. In this time, the value referred from the property seems to be zero whether the property is initialized or not. 

**Steps To Reproduce**
1. Use a property undeclared yet in a switch block.
2. Declare the property after the switch block. In this time, there is no need to initialize the property.

```swift
let value = 10

switch value {    
default:
   print("Default: ", x)
}

let x: Int
```

**Expected behavior**
When the undeclared property is referenced, I'd like to report an error means "the symbol cannot be found in scope" in compile.

**Environment (please fill out the following information)**
 - OS: macOS Monterey 12.5.1 (21G83)
 - Xcode: Version 13.4.1 (13F100)
 - Device: Mac Studio (M1 Max)

**Additional context**
This problem may induce the following undetectable code error.

```swift
let location = (x: 5, y: 0)

switch location {
    
case (x, 0):
    print("The location is on the x-axis and the x is ", x)
    
default:
    print("The location is not on the x-axis.")
}

// ...

let x: Int
```

This code was written with the expectation of the following behavior:
> If a `location` passed to switch keyword is on the x-axis, take the `x` value and print it. Otherwise, report that the `location` is not on the x-axis.

However, writing `let` keyword was forgotten in `case (x, 0)`, it couldn't get the `x` value from `location`. In this time, since no errors are reported, the programmer may not aware of this mistake.

**Comment by xwu** [comment]
All top-level code behaves this way; it's got nothing to do with the `switch` statement:  
https://twitter.com/twostraws/status/1276590212844597248

Whether intentionally designed or not, it would be source-breaking to change this behavior. Place your code inside a function and you will see the expected error.

**Comment by es-kumagai** [comment]
That's true ...! I did not know this behavior. I actually had to check it too, certainly, it had nothing to do with the `switch` statement at all. Thank you for telling me.
