### ISSUE TITLE
Incorrect "duplicate key" warnings when using `#line` as key in dictionary literals

### ISSUE THREAD

**Issue by fwcd** [apple/swift#60873]
**Describe the bug**
The latest trunk toolchain (incorrectly) reports a duplicate dictionary key warning when using `#line` on different lines (a pattern [commonly used by `swift-syntax` tests](https://github.com/apple/swift-syntax/blob/114e16a7fc057a3aa85cff4ad1f4be8e143db240/Tests/SwiftSyntaxBuilderTest/IntegerLiteralTests.swift#L7-L16)). For example:

```swift
let x = [
  #line: "a",
  #line: "b",
]
print(x)
```

compiled with

```
Apple Swift version 5.8-dev (LLVM 03bd949eeee4761, Swift 2c40a850df6f409)
Target: arm64-apple-macosx12.0
```

produces

```swift
dict-line.swift:2:3: warning: dictionary literal of type '[Int : String]' has duplicate entries for #line literal key
  #line: "a",
  ^
dict-line.swift:2:3: note: duplicate key declared here
  #line: "a",
  ^~~~~~~~~~~
            
dict-line.swift:3:3: note: duplicate key declared here
  #line: "b",
  ^~~~~~~~~~~
            
[3: "b", 2: "a"]
```

**Steps To Reproduce**
1. Compile the program above with `Apple Swift version 5.8-dev (LLVM 03bd949eeee4761, Swift 2c40a850df6f409)` (August 29, 2022 snapshot)

**Expected behavior**

The same behavior as on Swift 5.6:

```
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: arm64-apple-macosx12.0
```

```swift
[3: "b", 2: "a"]
```

**Environment (please fill out the following information)**
 - OS: macOS 12.5.1
 - Xcode Version/Tag/Branch: Apple Swift version 5.8-dev (LLVM 03bd949eeee4761, Swift 2c40a850df6f409)

**Comment by theblixguy** [comment]
cc @LucianoPAlmeida

**Comment by LucianoPAlmeida** [comment]
Ah I miss that, will fix it! Thanks for reporting @fwcd
