### ISSUE TITLE
include/swift/AST/DiagnosticEngine.h:993: Assertion `!ActiveDiagnostic && "Already have an active diagnostic"' failed

### ISSUE THREAD

**Issue by kelvin13** [apple/swift#60954]
> this issue was [copied over from the vscode-swift](https://github.com/swift-server/vscode-swift/issues/399) repository. 

**Describe the bug**

custom operators crash the extension if it has not also indexed the file containing the operator definitions.
this is often the case, because the extension cannot consistently locate sibling files if in a nested Packages/ editable package.

example: 

```swift 
enum MaskedVersion
{
    func ?= (pattern:MaskedVersion?, version:Self)
    {
        pattern ?= .init(version)
    }

    init?<S>(_ string:S) where S:StringProtocol
    {
    }
}
```

**To Reproduce**

open the attached project in vscode

**Expected behavior**

the extension should not crash

**Environment**

 - swift: DEVELOPMENT-SNAPSHOT-2022-08-18-a
 - Visual Studio Code version: 1.70.2
 - vscode-swift version: 0.7.0

there is a `.devcontainer` in the attached project

[sourcekit-lsp-crash.zip](https://github.com/swift-server/vscode-swift/files/9419230/sourcekit-lsp-crash.zip)

**Comment by theblixguy** [comment]
Probably missing a `flush()` somewhere. The active diagnostic is `unwrap_with_default_value`.

cc @xedin
