### ISSUE TITLE
Bug issues in xcode

### ISSUE THREAD

**Issue by Ero2002** [apple/swift#61068]
**Describe the bug**

**Steps To Reproduce**
1.
2.
...

**Expected behavior**

**Screenshots**

**Environment (please fill out the following information)**
 - OS: [e.g. macOS 11.0]
 - Xcode Version/Tag/Branch:

**Additional context**

**Comment by Ero2002** [comment]
var body: some View {
        
        NavigationView{
            Form{
              
                Section{
                    Picker("Units" ,selection: $Unit){
                        ForEach(units , id: \.self){
                            Text($0 , format: .number)
                        }
                    }
                    .pickerStyle(.segmented)
                }header: {
                    Text("From:")
                }
                Section{
                    Picker("Units", selection: $Unit){
                        ForEach(units , id: \.self){
                            Text($0, format: .number)
                        }
                    }
                }
            }
        }
            
    }

**Comment by AnthonyLatsis** [comment]
Closing in favor of #61069 (resubmission).
