### ISSUE TITLE
Distributed computed properties are not marked as throwing

### ISSUE THREAD

**Issue by akbashev** [apple/swift#61070]
**Describe the bug**
When trying to make `distributed` computed property inside distributed actor—property is not marked as throwing outside the actor. If you won't add `try` or `throws`—compiler could hang forever, adding `try` leads to a warning: `No calls to throwing functions occur within 'try' expression`

**Steps To Reproduce**
1. Add some distributed computed property to a distributed actor (see screenshot applied).
2. Access this property outside. It will suggest it's async, but no mentions about `try`.
3. If a function, which calls this property is not marked as throwing—compiler will hang forever.
4. If you add `throw` to a function and `try` to a property—`No calls to throwing functions occur within 'try' expression` will appear.

**Expected behavior**
Distributed computed property should be marked as throwing, same as distributed functions (because of nature of Distributed Actors).

**Screenshots**
Compiler will hang if it's not is marked with `try`:
<img width="1072" alt="Screenshot 2022-09-13 at 12 58 52" src="https://user-images.githubusercontent.com/5507330/189884556-58e6d7f4-975d-4288-a958-14dc07a025d4.png">
Build will succeed if everything marked, but warning appears:
<img width="1072" alt="Screenshot 2022-09-13 at 12 58 37" src="https://user-images.githubusercontent.com/5507330/189884693-b62b1837-cc85-48cc-bcba-c993fbca519f.png">

**Environment**
 - OS: iOS 16, macOS 13
 - Xcode Version/Tag/Branch: Xcode 14 RC1 | 14A309, Xcode 14 Beta 6 | 14A5294g

**Comment by ktoso** [comment]
Thanks, pretty suspicious since I think we cover these with tests... will look into it, thanks!

**Comment by ktoso** [comment]
rdar://99864733

**Comment by ktoso** [comment]
rdar://102061790

**Comment by ktoso** [comment]
And... done :)

**Comment by akbashev** [comment]
@ktoso Thx! :)
