### ISSUE TITLE
Missing isolation check within closure passed as event handler

### ISSUE THREAD

**Issue by mstyura** [apple/swift#61163]
**Describe the bug**
Isolation checker does not raise error when actor isolated state is accesses from event handler closures.

**Steps To Reproduce**
1. Compile snipped of code below:
```swift
import Foundation
import Combine

actor MyActor {
  private var state = 0
  private var subscribtion: AnyCancellable?

  func subscribe() {
    subscribtion = NotificationCenter.default.publisher(for: .NSCalendarDayChanged).sink { [self] _ in
      self.state += 1
    }
  }
}

actor MyActor2 {
  private var state = 0
  private var subscribtion: Any?

  func subscribe() {
    subscribtion = NotificationCenter.default.addObserver(forName: .NSCalendarDayChanged, object: nil, queue: nil) { [self] _ in
      self.state += 1
    }
  }
}
```
...

**Expected behavior**
An closure can not be directly executed within actor context, so compiler should raise an error accessing isolated state from closure.

**Screenshots**

**Environment (please fill out the following information)**
 - OS: MacOS 12.6
 - Xcode 14.0 (14A309):

**Additional context**
It might be due to the fact that closures in signatures are not currently marked as `@Sendable` and compiler assumes no context change happen compared to event subscription side which is inside actor. Maybe compiler should be less optimistic regarding `@escaping` closures by default or maybe there should be another compiler setting which will turn on pessimistic mode for `@escaping` closures treating them as `@Sendable` automatically.

**Comment by hborla** [comment]
>It might be due to the fact that closures in signatures are not currently marked as @Sendable 

Yes, this is an issue with the `NotificationCenter.addObserver` APIs. This isn't a Swift compiler issue, though the `addObserver` closure does have a `@Sendable` annotation in recent SDKs according to https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver.
