### ISSUE TITLE
Cannot create MutableArray and immutable array variable together

### ISSUE THREAD

**Issue by AiziChen** [apple/swift#61229]
**Describe the bug**
I have these simple code here:
```swift
let arr = [1, 2, 3]

arr[0] = 10

print(arr)
```
but it compile fail:
```shell
main.swift:3:4: error: cannot assign through subscript: 'arr' is a 'let' constant
arr[0] = 10
~~~^
main.swift:1:1: note: change 'let' to 'var' to make it mutable
let arr = [1, 2, 3]
^~~
var
```

**Steps To Reproduce**
- use command `swift main.swift` to run it

**Expected behavior**
Array use `let` keyword may only cannot change the variable, but can change array's content.
Is there a way to change array's content but cannot change array variable?

**Screenshots**

**Environment (please fill out the following information)**
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0

**Comment by tbkka** [comment]
This is the expected behavior for Swift arrays:  A `var` array is mutable; a `let` array is not mutable.  Swift standard library collections are value types, so there is no reason to distinguish between "changing the variable" and "changing the array's content".
