### ISSUE TITLE
Offer fix-it when platform name in an availability attribute or query is close but not quite valid

### ISSUE THREAD

**Issue by tshortli** [apple/swift#61237]
With https://github.com/apple/swift/pull/61234 we now offer a fix-it when the case of a platform name specified in an availability attribute or query is incorrect. We could go further by diagnosing near misses using edit distance.

rdar://100241896

**Comment by LucianoPAlmeida** [comment]
This looks interesting! But not sure the label new feature is correct here. To me still looks like a DiagnosticQol. @tshortli Does it makes sense?

**Comment by tshortli** [comment]
> This looks interesting! But not sure the label new feature is correct here. To me still looks like a DiagnosticQol. @tshortli Does it makes sense?

Yup, fixed. It didn't feel correct to label this as a bug when I created the issue but now I know better.
