### ISSUE TITLE
Isolated static property can satisfy nonisolated protocol requirement 

### ISSUE THREAD

**Issue by mbrandonw** [apple/swift#61300]
**Describe the bug**

It is possible to make an isolated static property satisfy a protocol requirement that is not isolated:

```swift
struct A {}
extension A: P {
  @MainActor static let value = 42 // ✅
}
```

This compiles without any warnings even though the following two variations do have the warning I would expect:

```swift
struct A {}
extension A: P {
  @MainActor static var value: Int { 42 } // ⚠️
  @MainActor static var value = 42 // ⚠️
}
```
> ⚠️ Main actor-isolated static property 'value' cannot be used to satisfy nonisolated protocol requirement

This allows you to access the value synchronously without isolating to the main actor:

```swift
Task.detached {
  _ = A.value
  _ = (A.self as any P.Type).value
}
```

This should be a compiler error since the detached task is not operating in the main actor, yet we are accessing a `@MainActor` property.

This problem occurs for any global actor, not just `@MainActor`.

**Steps To Reproduce**
Run the above code in Swift to show that there are no warnings.

**Expected behavior**
There should be a warning on the line of the `static let` that says an isolated thing cannot satisfy a nonisolated requirement:

> ⚠️ Main actor-isolated static property 'value' cannot be used to satisfy nonisolated protocol requirement

**Environment (please fill out the following information)**
 - OS: macOS 12.5.1 (21G83)
 - Xcode Version/Tag/Branch: Version 14.0 (14A309), Swift 5.7

**Comment by hborla** [comment]
This is fixed by https://github.com/apple/swift/pull/69607
