### ISSUE TITLE
False error: Global actor 'MyActor'-isolated property 'state' can not be mutated from global actor 'MyActor'

### ISSUE THREAD

**Issue by mstyura** [apple/swift#61327]
**Describe the bug**
Isolation check gives false error

**Steps To Reproduce**
1. Compile snippet:
```
@globalActor
public struct MyActor {
  private actor ActorImpl { }

  public static let shared: some Actor = ActorImpl()
}

@MyActor
final class MyClass {
  private var state = 0
}

extension MyClass {
  nonisolated func mutate() {
    Task { @MyActor in
      defer {
        self.state = 1 // False error: Global actor 'MyActor'-isolated property 'state' can not be mutated from global actor 'MyActor'
      }
      self.state = 2 // OK
    }
  }
}
```
...

**Expected behavior**
Code is compiled without errors

**Environment (please fill out the following information)**
 - OS: MacOS 12.6
 - Xcode 14.0

**Comment by theblixguy** [comment]
I think this is fixed on `main` by https://github.com/apple/swift/pull/60688 - can you verify using the latest development snapshot from swift.org?

**Comment by mstyura** [comment]
Verified on version `Swift Development Snapshot 2022-09-24 (a)` and the issue is fixed. Thanks a lot!
