### ISSUE TITLE
Replace `init` delegations in `Mirror` with calls to `Builtin.unreachable()` when reflection is disabled

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#61326]
[These](https://github.com/apple/swift/blob/9159f8772d9f891ef788bebf720c4d5b7cd29d9e/stdlib/public/core/Mirror.swift#L486) initializer delegations, which ought to have been `Builtin.unreachable()` calls, were used to [work around](https://github.com/apple/swift/pull/39674#discussion_r725664337) an issue that was fixed a while ago: #57622.

**Comment by jakedves** [comment]
Hey, could I get assigned to this issue for my first contribution? Thanks

**Comment by AnthonyLatsis** [comment]
Sure!
