### ISSUE TITLE
[interop] subscript on C++ map type is not usable because of mutability

### ISSUE THREAD

**Issue by hyp** [apple/swift#61337]
**Describe the bug**
It's impossible to use the subscript operator on a C++ map.

**Steps To Reproduce**
C++ header:
```
#include <map>

using MapTy = std::map<int, int>;

inline MapTy getMap() { return {}; }
```
Swift code:
```
import CxxTest

func test() {
    var map = getMap();
    let y: CInt = 1
    let x = map[y]
}
```

Error reported:

```
error: cannot assign through subscript: 'map' is immutable
    let x = map[y]
            ~~~^
```

**Expected behavior**
This should compile.

**Comment by ktoso** [comment]
For reference: rdar://100529571

**Comment by hyp** [comment]
https://github.com/apple/swift/pull/61385

**Comment by hyp** [comment]
Confirmed as fixed by https://github.com/apple/swift/pull/61385! Thanks @egorzhdan
