### ISSUE TITLE
For loop with tuple unpacking and invalid member fails to report correct error

### ISSUE THREAD

**Issue by Stiivi** [apple/swift#61363]
**Describe the bug**
The compiler fails with:

```
error.swift:2:1: error: failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the project
```

**Steps To Reproduce**

The following code is offensive:

```swift
var d: [Int:String] = [:]
for (_, s) in d.items { }
```

**Expected behavior**
The compiler should complain about `d` not having member `items` as in the following example:

```swift
var d: [Int:String] = [:]
for item in d.items { }
```

Correctly reported error:

```
error2.swift:2:15: error: value of type '[Int : String]' has no member 'items'
for item in d.items { }
            ~ ^~~~~
```

**Environment (please fill out the following information)**
 - OS: 12.6 (21G115)
 - Swift version:

```
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
```

**Comment by LucianoPAlmeida** [comment]
This should be fixed on main @Stiivi Can you verify with the latest snapshot and close? Thanks

**Comment by Stiivi** [comment]
Indeed with `swift-DEVELOPMENT-SNAPSHOT-2022-09-27-a` I got:

```
/tmp/error.swift:2:17: error: value of type '[Int : String]' has no member 'items'
for (_, s) in d.items { }
              ~ ^~~~~
```

... as expected.

Thank you!
