### ISSUE TITLE
Actor isolation not respected or warned when conforming to a delegate from an extension

### ISSUE THREAD

**Issue by jayhickey** [apple/swift#61370]
**Describe the bug**

Actor isolation is not respected or warned when conforming to a delegate from an extension on an `@MainActor` class. For example, the below code compiles without warnings or errors:

```swift
protocol MyDelegate {
  func doThing()
}

@MainActor
class MyClass {
  var myCounter = 0
}

extension MyClass: MyDelegate {
  func doThing() {
    print("Is on main: \(Thread.isMainThread)") // prints 'false'
    myCounter += 1
  }
}

var v: MyDelegate?
Task { @MainActor in
  v = MyClass()
}

Task.detached { 
  sleep(1)
  v?.doThing()
}
```

If I move the conformance up within the type definition scope, I get a "Main actor-isolated instance method 'doThing()' cannot be used to satisfy nonisolated protocol requirement" warning. Explicitly marking the extension as `@MainActor` also causes the same warning to surface, but it's not clear to me why that isn't implicitly happening.

**Steps To Reproduce**

Run the above swift code an notice it executes without any warnings or errors.

**Expected behavior**

Expect the following warning on the `doThing()` declaration:

> ⚠️ Main actor-isolated static property 'value' cannot be used to satisfy nonisolated protocol requirement

**Screenshots**

**Environment (please fill out the following information)**
- OS: macOS 12.5.1 (21G83)
- Xcode Version/Tag/Branch: Version 14.0 (14A309), Swift 5.7

**Additional context**

See [this conversation](https://forums.swift.org/t/actor-isolation-delegates-in-extensions/60571/3) in the Swift forums for more discussion.

**Comment by jayhickey** [comment]
Possibly related to #61300

**Comment by hborla** [comment]
The warning in extensions was hidden under `-strict-concurrency=complete`. I've made the diagnostic more discoverable in https://github.com/apple/swift/pull/70153
