### ISSUE TITLE
Compiler crashes with forced typecasts

### ISSUE THREAD

**Issue by za-creature** [apple/swift#61394]
I come from the land of ducks, so I'm likely using a bad pattern here. That being said, the compiler sent me here (eventually... while https://www.swift.org/contributing/#reporting-bugs mentions github issues, it doesn't link here) so I'm filing this as a bug because while I have no expectations, a compiler crash is a compiler crash:
```
failed to produce diagnostic for expression; please submit a bug report and include the project
```

Basically I'm trying to create a generic fixed-size ring buffer that stores ordered `Element`s (sensor readings), crashes when the input is not monotonic, and `log(n)` searches through them on demand.
Since the elements themselves are not necessarily `Comparable`, I do this by adding a mapper parameter to the constructor that is expected to convert them into a comparable `Index`.

However, if the elements _are_ comparable, there's no need to map them to anything else, so a default identity mapper could be used instead. This is a degenerate case as the `Index` generic is no longer distinct from `Element` and can be omitted from the type signature, which is a possible cause for the compiler rejecting a direct `as` cast even though that particular constructor should only be available when Element is in fact Comparable. Forcing the cast crashes the compiler, likely for the same reason it's not picking it up in the first place.

**Steps To Reproduce**
```swift
import CoreMotion
import CoreLocation


struct SortedRingBuffer<Element, Index> where Index: Comparable {
    // a ring buffer for monotonous events, used to store the
    // most recent `maxSize` sensor readings; readings must be
    // directly comparable, or must provide a mapper that will
    // return comparable results
    typealias Mapper = (Element) -> Index
    private let size: Int
    private let mapper: Mapper
    init(_ maxSize: Int, usingMapper: @escaping Mapper) {
        size = maxSize
        mapper = usingMapper
    }
    init(_ maxSize: Int) where Element: Comparable {
        self.init(maxSize) {val in val as! Index} // throws 'Element is not convertible to Index' without as!
    }

    // implementation omitted; this implements binary search on
    // a private vector of elements via append(item: Element)
    // and closest(to: Index) -> Element
}

var motionBuffer = SortedRingBuffer(10) {(item: CMLogItem) in item.timestamp}
var locationBuffer = SortedRingBuffer(10) {(item: CLLocation) in item.timestamp.timeIntervalSince1970}
var integerBuffer = SortedRingBuffer<Int>(10) // this crashes the compiler
print("noop")

```

**Environment**
 - Mac OS 12.5 (21G72)
 - Xcode 13.4.1 (13F100)

**Additional context**
Major thumbs up for inferring the types from the closure signature of the first two declarations. As a related curiosity, is there any formal proof for Swift's Turing-completeness on types out yet?

**Edit**
This works:
```swift
var integerBuffer = SortedRingBuffer<Int, Int>(10)
```

**Comment by LucianoPAlmeida** [comment]
I cannot repro in Xcode 14, can you verify there as well and close if that is fixed?

**Comment by za-creature** [comment]
Confirmed: ```Generic type 'SortedRingBuffer' specialized with too few type parameters (got 1, but expected 2)```

**Comment by LucianoPAlmeida** [comment]
Awesome, thanks for verify :)
