### ISSUE TITLE
Open source builds do not support MacCatalyst target

### ISSUE THREAD

**Issue by mikepinkerton** [apple/swift#61418]
The open source toolchain distributions do not have the appropriate libraries to support the MacCatalyst target. 

For example, trying to build a catalyst app using the 5.7 release toolchain downloaded from swift.org results in:

```
ld64.lld: error: ../../third_party/swift-toolchain/usr/lib/swift/macosx/libswiftCompatibilityConcurrency.a(CompatibilityConcurrency.cpp.o) has platform macOS, which is different from target platform macCatalyst
```

The above is an excerpt from Chromium's catalyst buildbot: https://logs.chromium.org/logs/chromium/buildbucket/cr-buildbucket/8801593085733033281/+/u/compile/raw_io.output_text_failure_summary_

**Environment (please fill out the following information)**
 - OS:  all
 - Xcode Version/Tag/Branch: Xcode14

**Comment by etcwilde** [comment]
I'm a little confused by how this ever worked, even before the concurrency/compat libraries.
We don't ship catalyst swiftmodules or zippered libraries in the public toolchains.
There's not really a reason we can't, but I'm not sure how this is a new regression.

**Comment by mikepinkerton** [comment]
Thank you!!!!
