### ISSUE TITLE
Swift compiler can't determine the type of a closure set in a ternary operator

### ISSUE THREAD

**Issue by michaeldwilliams** [apple/swift#61436]
**Describe the bug**
When assigning a property to a closure using a ternary operator, the compiler complains that the "Type of expression is ambiguous without more context", even when the type is explicitly set.

**Steps To Reproduce**

```
       var onTapChange: (@MainActor () -> Void)?

        let action: (() -> Void)? = { [weak self] in
            guard let self = self else { return }
            self.delegate?.doSomething()
        }

        onTapChange = options.count < 2 ? nil : action      <--- Type of expression is ambiguous without more context
```

**Expected behavior**
The compiler should be satisfied because all of the types are explicitly declared

**Screenshots**
N/A

**Environment (please fill out the following information)**
 - OS: MacOS 12.6
 - Xcode Version/Tag/Branch: Xcode 14.1 beta 3

**Additional context**
Above is an attempt to be more explicit with the types. Our previous code, which has no issues in 14.0, creates and sets the closure inline in the ternary operator.

```
       var onTapChange: (@MainActor () -> Void)?

        onTapChange = options.count < 2 ? nil : { [weak self] in      <--- Type of expression is ambiguous without more context
            guard let self = self else { return }
            self.delegate?.doSomething()
        } 
```

**Comment by AnthonyLatsis** [comment]
Reduced: 
```swift
let x: @MainActor () -> Void

let y: () -> Void = {}

x = true ? y : y
```
