### ISSUE TITLE
Extensions to protocol typealias types compile but can't be accessed

### ISSUE THREAD

**Issue by daniel-hall** [apple/swift#61450]
**Describe the bug**

If I declare a typealias for a concrete type in a protocol, e.g.

```
struct A { }

protocol P {
  typealias Element = A
}
```

and then I write an extension based on that typealias on a conforming type, e.g.:

```
struct Conforming: P { }

extension Conforming.Element { // This should be identical to `extension A`
  var success: Bool { true }
}

```

The compiler allows it. But trying to access the extension property will fail:

```
print(Conforming.Element().success) //Compiler error:  "Value of type 'Conforming.Element' (aka 'A') has no member 'success'"

```
If I declare the extension directly on the type (not through the typealias), e.g.

```
extension A {
  var success: Bool { true }
}
```

Then the same print statement (accessing type A through the protocol typealias) will succeed

Declaring the typealias directly on the type allows the extension through the typealias to work:

```
struct Conforming {
  typealias Element = A
}

extension Conforming.Element { 
  var success: Bool { true }
}

print(Conforming.Element().success) //  "true"
```

It only seems to fail on the requirement of writing an extension that refers to a typealias declared by a protocol.

**Environment (please fill out the following information)**
 - OS: macOS 12.6
 - Xcode Version/Tag/Branch: Version 14.0 (14A309)

**Additional context**

Ultimately what I want to accomplish is something like this (just a convenience really)

```
protocol SettingsProvider { 
  typealias SettingsConfiguration = Configuration<Self>
}

struct Configuration<T> { }

struct ConcreteType: SettingsProvider { }

// I want to be able to do this
extension ConcreteType.Settings {
  var someProperty: String
}

// Instead of this equivalent that seems much less intuitive to me
extension Configuration<ConcreteType> {
  var someProperty: String
}
```

[Swift Forums thread here](https://forums.swift.org/t/mysterious-failure-of-extensions-declared-on-typealiases-of-protocols-any-good-workaround/60653)

**Comment by slavapestov** [comment]
This is now diagnosed on main:

```
q.swift:9:1: error: extension of type 'Conforming.Element' (aka 'A') must be declared as an extension of 'A'
extension Conforming.Element { // This should be identical to `extension A`
^         ~~~~~~~~~~~~~~~~~~
q.swift:9:1: note: did you mean to extend 'A' instead?
extension Conforming.Element { // This should be identical to `extension A`
^         ~~~~~~~~~~~~~~~~~~
          A
```

Fix was https://github.com/apple/swift/pull/60364
