### ISSUE TITLE
Marking a method as unavailable in tvOS Extensions should allow me to use APIs unsafe for extensions

### ISSUE THREAD

**Issue by KaiOelfke** [apple/swift#61541]
**Describe the bug**

The issue https://github.com/apple/swift/issues/43834 for iOSApplicationExtension was already fixed. But for tvOSApplicationExtension this issue still exists. This can be reproduced with the sample code below in a multiplatform app with Xcode 14.1.0 beta 3. When compiling for iOS this builds, but for tvOS there's the error: `'someProperty' is unavailable in application extensions for tvOS`.

I didn't test `macOSApplicationExtension`, `watchOSApplicationExtension` and `macCatalystApplicationExtension`, but it should have the same behavior. Of course UIApplication has to be replaced with some other unavailable API like NSApplication depending on the platform. The sample is for iOS and tvOS only.

```swift
import SwiftUI
import UIKit

struct Helper {

    @available(iOSApplicationExtension, unavailable)
    @available(tvOSApplicationExtension, unavailable)
    var someProperty: Bool {
        // some code that can't be used in an app extension
        UIApplication.shared.canOpenURL(URL(string: "https://www.apple.com")!)
    }
}

@main
struct MySampleApp: App {

    init() {
        print(Helper().someProperty)
    }

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
```

**Steps To Reproduce**
1. Create a new project using the Xcode 14 multiplatform app template
2. Remove macOS as destination and add tvOS
3. Copy the sample code to the app entry point file
4. Build for iOS
5. Build for tvOS

**Expected behavior**
`Helper().someProperty` should be accessible in the main app target of tvOS. It should behave like building for iOS.

**Environment (please fill out the following information)**
 - OS: macOS 12.5.1
 - Xcode Version/Tag/Branch: 14.1.0 beta 3

**Additional context**

**Comment by tshortli** [comment]
This was fixed by https://github.com/apple/swift/pull/60006
