### ISSUE TITLE
`@available` doesn’t affect literal initialization

### ISSUE THREAD

**Issue by davdroman** [apple/swift#61564]
**Describe the bug**
When a literal initializer is marked with an availability annotation, it's seemingly ignored by the compiler at the point of use, unless the initializer is used explicitly.

**Steps To Reproduce**

```swift
struct Foo {
    let bar: String
}

@available(*, deprecated)
extension Foo: ExpressibleByStringLiteral {
    init(stringLiteral value: StringLiteralType) {
        self.bar = value
    }
}

let a: Foo = Foo(stringLiteral: "") // warning: 'init(stringLiteral:)' is deprecated
let b: Foo = "" // no warning
```

**Expected behavior**
Both assignments should cause a deprecation warning.

Note: every other availability status (e.g. `unavailable`) is also ignored.

**Screenshots**

<img width="960" alt="Screenshot 2022-10-13 at 11 29 21" src="https://user-images.githubusercontent.com/2538074/195573480-5413d8b0-596a-41f1-adea-deff49736e8d.png">

**Comment by greenthings** [comment]
What I understand is that you deprecated stringLiteral the way which initializes the bar.

But, why neither "a" nor "b" gives a warning and only "a" gives a warning?

If this is correct understanding, you need to read the documentation.

In the swift/Literals.md, you can find below.

The ExpressibleByStringLiteral Protocol

/// A type that can be initialized with a string literal.
///
/// The `String` and `StaticString` types conform to the
/// `ExpressibleByStringLiteral` protocol. You can initialize a variable or
/// constant of either of these types using a string literal of any length.
///
///     let picnicGuest = "Deserving porcupine"
///

So, Even if you deprecated it, It can be initialized with a string literal like "", "a", "b" and so on.

I hope it will help you.

**Comment by greenthings** [comment]
Reference) 
https://github.com/apple/swift/blob/main/docs/Literals.md

**Comment by davdroman** [comment]
Thank you for such a quick turnaround @LucianoPAlmeida! 👏
