### ISSUE TITLE
keyword "some" will be inferred as "any" in Protocol extension function

### ISSUE THREAD

**Issue by miku1958** [apple/swift#61591]
**Describe the bug**
keyword "some" will be inferred as "any" in Protocol extension function

**Steps To Reproduce**
1. using keyword "some" in a Protocol extension function
2. using this function in Generic function
```swift
import SwiftUI

protocol Ability { }

extension Ability {
	func image() -> some View {
		Image("").resizable()
	}
}
struct MainAbility: Ability { }

let ability: Ability = MainAbility()
HStack {
	ability.image()
}
```

**Expected behavior**
Compiler can build successfully.

**Screenshots**
<img width="794" alt="image" src="https://user-images.githubusercontent.com/24806909/196036369-a0336bda-398f-4ed6-bffd-cb27ee24f392.png">

**Environment (please fill out the following information)**
 - OS: [e.g. macOS 12.6]
 - Xcode 14.1 beta 3 (14B5033e)

**Comment by slavapestov** [comment]
This is expected behavior. The type of 'ability' is 'any Ability', which is a type-erased existential. Calling a protocol extension method that returns an opaque return type on an existential erases the opaque return type to the existential, because there is no way to represent the result type statically in this case.

Consider this code:

```swift
protocol P: Equatable {}

extension P {
  func foo() -> some P { return this }
}

struct S1: P {}
struct S2: P {}

let s1: any P = S1()
let s2: any P = S2()
let b: Bool = ...
let foo = (b ? s1 : s2).foo()

// what is the type of 'foo'?
```

**Comment by miku1958** [comment]
But in my case, there is no Association between the return type and the protocol itself.

It seems to me that the behavior of the above code and the following code should be equivalent
```
protocol Ability { }

extension Ability {
}

func image(ability: Ability) -> some View {
	Image("").resizable()
}
struct MainAbility: Ability { }

let ability: Ability = MainAbility()
HStack {
	image(ability: ability)
}
```
