### ISSUE TITLE
[Source compatibility suite] exercism-swift fails to build tests using swift package

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61614]
**Describe the bug**
The source compatibility suite project [exercism-swift](https://github.com/exercism/swift) is failing to build when `--build-tests` is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout [exercism-swift @ 3df5e4](https://github.com/exercism/swift/commit/3df5e4ab83a9ab47228a46da7263e09a2a2b0b90)
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
error: filename "LinuxMain.swift" used twice: '/exercism-swift/exercises/accumulate/Tests/LinuxMain.swift' and '/exercism-swift/exercises/acronym/Tests/LinuxMain.swift'note: filenames are used to distinguish private declarations with the same name
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
```
Apple Swift version 5.8-dev (LLVM d90179316c5e50b, Swift 39059555891a358)
```

**Comment by AnthonyLatsis** [comment]
@justice-adams-apple Is this resolved?

**Comment by AnthonyLatsis** [comment]
> This appears to be a source level issue

@justice-adams-apple I think issues like this one that are related to project updates rather than compiler regressions can be tracked in the compatibility suite repo.
