### ISSUE TITLE
[Source compatibility suite] SwiftLint fails to build tests with legacy commits using swift package

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61616]
**Describe the bug**
https://github.com/realm/SwiftLint/commit/60f98ec50d74c6e6aa7c527493d844960653f3a6 is failing to build when --build-tests is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout https://github.com/nodes-ios/Serpent/commit/61d72cd2fbe8a0e9ab69878eb585a99eb15859cc
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
SwiftLint/Tests/SwiftLintFrameworkTests/IntegrationTests.swift:48:32: error: value of type 'Bool' has no member '_getBuiltinLogicValue'
            let isASCII = true._getBuiltinLogicValue()
                          ~~~~ ^~~~~~~~~~~~~~~~~~~~~
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
```
Apple Swift version 5.8-dev (LLVM d90179316c5e50b, Swift 39059555891a358)
```

This appears to be a source error, and is fixed with https://github.com/realm/SwiftLint/commit/b8296cb09a707aac8f5a3e77f70512901a862943 in response to https://github.com/apple/swift/pull/21451

We should update the source Revision for swiftLint-Legacy in the source compatibility suite. In the meantime, I will Xfail the project

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed and has passed since.
