### ISSUE TITLE
[Source compatibility suite] Serpent fails to build tests using swift package

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61615]
**Describe the bug**
The source compatibility suite project https://github.com/nodes-ios/Serpent/commit/61d72cd2fbe8a0e9ab69878eb585a99eb15859cc is failing to build when --build-tests is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout https://github.com/nodes-ios/Serpent/commit/61d72cd2fbe8a0e9ab69878eb585a99eb15859cc
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
Serpent/Serpent/SerpentTests/Tests/AlamofireExtensionTests.swift:11:8: error: no such module 'Alamofire'
import Alamofire
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
```
Apple Swift version 5.8-dev (LLVM d90179316c5e50b, Swift 39059555891a358)
```

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed and has passed since.
