### ISSUE TITLE
[Source compatibility suite] swift-system fails to build tests using swift package 

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61617]
**Describe the bug**
The source compatibility suite project https://github.com/apple/swift-system/commit/0627d28e6ae514940c6ee061acfd36a3c231b87f is failing to build when `--build-tests` is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout https://github.com/apple/swift-system/commit/0627d28e6ae514940c6ee061acfd36a3c231b87f 
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
swift-system/Tests/SystemTests/MockingTest.swift:22:5: error: cannot find 'MockingDriver' in scope
    MockingDriver.withMockingEnabled { driver in
    ^~~~~~~~~~~~~
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
```
Apple Swift version 5.8-dev (LLVM d90179316c5e50b, Swift 39059555891a358)
```

**Comment by justice-adams-apple** [comment]
This error only occurs when building the Release build config of the project

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed and has passed since.
