### ISSUE TITLE
False positive "Code after 'return' will never be executed" of code after `#if canImport(Network) ... #endif`

### ISSUE THREAD

**Issue by dnadoba** [apple/swift#61621]
**Describe the bug**
The following produces a warning
```swift
func foo() -> Int {
    #if canImport(Network)
    return 1
    #endif
    return 2 // warning: Code after 'return' will never be executed
}
```
but it should not as the `return 2` will be executed on non Darwin platforms.

**Steps To Reproduce**
compile the above code on macOS

**Expected behavior**
no warning.

**Environment (please fill out the following information)**
 - OS: macOS 13.0 (22A371)
 - Xcode Version/Tag/Branch: Version 14.0 beta 6 (14A5294g)

**Comment by tbkka** [comment]
Have you tried `#else`?

**Comment by dnadoba** [comment]
It doesn't produce a warning with `#else`. My reasoning was that the `#else` branch is now "dead code" on macOS as well. I though it should either produce a warning in both cases or in none. But I now think this is more of a language design question and not a bug. Closing this one now as it probably works as intended. Sorry, probably shouldn't report issues after a long day 😅
