### ISSUE TITLE
Actor isolation error incorrectly triggered in defer statements

### ISSUE THREAD

**Issue by StarLard** [apple/swift#61629]
**Describe the bug**
Attempting to mutate an actor-isolated property from within a defer statement isolated to the same actor incorrectly triggers an actor-isolation violation. For example, the following code generates an error:
```swift
@MainActor
var someVaue = 0

Task { @MainActor in
    someVaue = 1 // Okay; no warnings or errors
}

Task { @MainActor in
    defer {
        someVaue = 1 // Sad; error: "Main actor-isolated property 'someVaue' can not be mutated from the main actor"
    }
    print("Hello World")
}
```

**Steps To Reproduce**
1. Isolate a value to an actor
2. Attempt to modify said value from defer statement within task isolated to the same actor
3. Compiler generates warning

**Expected behavior**
The property can be mutated without error

**Screenshots**
<details><summary>Error in Playground</summary>

![Screen Shot 2022-10-18 at 5 36 44 PM](https://user-images.githubusercontent.com/13044247/196570539-21e67384-bcad-49e4-8834-0cda57e4b4e9.png)

</details>

<details><summary>Error in iOS Project</summary>

![Screen Shot 2022-10-18 at 5 47 03 PM](https://user-images.githubusercontent.com/13044247/196571641-700116f7-56b8-46fb-93b2-ec6869244893.png)

</details>

**Environment (please fill out the following information)**
 - OS: macOS 12.6
 - Xcode Version/Tag/Branch: 14.0.1

**Comment by AnthonyLatsis** [comment]
Apparently fixed on `main`.
