### ISSUE TITLE
[Source compatibility suite] vapor_service fails to build tests using swift package

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61624]
**Describe the bug**
The source compatibility suite project https://github.com/vapor/service/commit/281a70b69783891900be31a9e70051b6fe19e146c is failing to build when --build-tests is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout https://github.com/vapor/service/commit/281a70b69783891900be31a9e70051b6fe19e146
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
/Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/vapor_service/Tests/ServiceTests/Utilities.swift:20:17: error: constructing an object of class type 'Self' with a metatype value must use a 'required' initializer
        return .init()
                ^
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/90/artifact/swift-source-compat-suite/XFAIL_vapor_service_4.2_BuildSwiftPackage.log

**Comment by justice-adams-apple** [comment]
For now I will xfail the project on the compat suite

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed.
