### ISSUE TITLE
[Source compatibility suite] Nimble fails to build tests using swift package

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61625]
**Describe the bug**
The source compatibility suite project https://github.com/Quick/Nimble/commit/eea5843b34beb559dd51cf004953f75028e47add is failing to build when `--build-tests` is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout https://github.com/Quick/Nimble/commit/eea5843b34beb559dd51cf004953f75028e47add
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
error: link command failed with exit code 1 (use -v to see invocation)
duplicate symbol '_NDR_record' in:
    /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Nimble/.build/x86_64-apple-macosx/release/CwlPreconditionTesting.build/CwlBadInstructionException.swift.o
    /Users/ec2-user/jenkins/workspace/swift-PR-source-compat-suite-test-macOS/swift-source-compat-suite/project_cache/Nimble/.build/x86_64-apple-macosx/release/CwlPreconditionTesting.build/CwlCatchBadInstruction.swift.o
ld: 1 duplicate symbol for architecture x86_64
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/90/artifact/swift-source-compat-suite/XFAIL_Nimble_5.0_BuildSwiftPackage.log

**Comment by justice-adams-apple** [comment]
For now I will xfail the project on the compat suite

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed.
