### ISSUE TITLE
[Source compatibility suite] swift-cluster-membership fails to build tests using swift package

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#61622]
**Describe the bug**
The source compatibility suite project https://github.com/apple/swift-cluster-membership/commit/e9619146a1198253c587f6f34c0869d3a98b0c76 is failing to build when --build-tests is passed to the invocation used to build the swift package.

**Steps To Reproduce**
1. Checkout https://github.com/apple/swift-cluster-membership/commit/e9619146a1198253c587f6f34c0869d3a98b0c76
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
error: link command failed with exit code 1 (use -v to see invocation)
Undefined symbols for architecture x86_64:
  "(extension in XCTest):__C.XCTestCase.addTeardownBlock(() async throws -> ()) -> ()", referenced from:
      SWIMNIOExampleTests.BaseClusteredXCTestCase.setUp() -> () in BaseXCTestCases.swift.o
      @objc SWIMNIOExampleTests.BaseClusteredXCTestCase.setUp() -> () in BaseXCTestCases.swift.o
ld: symbol(s) not found for architecture x86_64
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
```
Apple Swift version 5.8-dev (LLVM d90179316c5e50b, Swift 39059555891a358)
```

https://ci.swift.org/job/swift-PR-source-compat-suite-test-macOS/90/artifact/swift-source-compat-suite/XFAIL_swift-cluster-membership_5.0_BuildSwiftPackage.log

**Comment by justice-adams-apple** [comment]
For now I will xfail the project on the compat suite

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed and has passed since.
