### ISSUE TITLE
Sendability of Globals is not checked in Task's closure

### ISSUE THREAD

**Issue by jcasc** [apple/swift#61688]
**Describe the bug**
No warning is emitted when a closure passed to a Task references a mutable global variable.

**Steps To Reproduce**

    class Cat {
        var name = "Tom"
    }

    class Globals {
        var cat = Cat()
    }
    
    let glob = Globals()
    
    func one () {
        Task {glob.cat.name="Max"} // Expected Warning about some nonSendable moving into a different concurrency domain
    }

**Expected behavior**
I excpected a warning along the lines of

> Capture of 'glob' with non-sendable type 'Globals' in a `@Sendable` closure

No such warning is emitted.

**Environment**
 - OS: MacOS 12.6 (Intel), Xcode 14.0.1
 - Xcode Version/Tag/Branch: 14.0.1

**Additional context**
Normally, with `-warn-concurrency` enabled, Swift/Xcode warns about non-sendables crossing concurrency domains.

**Comment by hborla** [comment]
This is fixed by SE-0412, which is enabled under `-strict-concurrency=complete` in Swift 5.10.
