### ISSUE TITLE
Runtime: enum type descriptor returns enum tag for nested enum value in single case payload (release-only)

### ISSUE THREAD

**Issue by stephencelis** [apple/swift#61708]
**Describe the bug**

Given the following nested enums:

```swift
public enum E1 {
  case c1(E2)
}

public enum E2 {
  case c1(Bool)
  case c2(Bool)
  case c3(Any)
}
```

Using the runtime to inspect the enum "tag" of `E1.c1(.c2(true))` should result in returning `0` to match the index of its only case, `c1`.

And it does...in debug configurations.

In release configurations it returns `1` instead, which reflects the _nested_ tag, `E2.c2(true)`.

**Steps To Reproduce**

I'm using @Azoy's [Echo](https://github.com/Azoy/Echo) for ease of access to the Swift runtime metadata. In particular I am using @ole's [PR fork](https://github.com/Azoy/Echo/pull/71), which adds support for release builds.

1. Clone https://github.com/stephencelis/EnumRuntimeBug
2. `cd EnumRuntimeBug`
3. Run this code:

    https://github.com/stephencelis/EnumRuntimeBug/blob/01e5ee9ee92594930df8040da8c4b4e1eebc3c94/Sources/EnumRuntimeBug/main.swift#L1-L21

    And compare in debug/release:

    ```sh
    $ swift run -c debug EnumRuntimeBug
    tag 0
    $ swift run -c release EnumRuntimeBug
    tag 1
    Trace/BPT trap: 5
    ```

**Expected behavior**

Both debug and release should evaluate the same enum tag and print `tag 0`.

**Screenshots**

**Environment (please fill out the following information)**
 - OS: macOS 12
 - Xcode Version/Tag/Branch: 14.1 (Swift 5.7)

**Comment by ole** [comment]
@stephencelis Looks like you have a copy/paste error in your bug description:

> ```
> $ swift run -c debug EnumRuntimeBug
> tag 0
> $ swift run -c debug EnumRuntimeBug
> tag 1
> Trace/BPT trap: 5
> ```

I'm guessing the second `swift run` line should be `-c release`, right? (If you fix it above, I'll edit this comment accordingly.)

**Comment by stephencelis** [comment]
@ole Ah yup! Thanks and done!

**Comment by tbkka** [comment]
CC: @drexin @aschwaighofer

**Comment by Azoy** [comment]
https://github.com/apple/swift/pull/61966

**Comment by drexin** [comment]
Fixed in https://github.com/apple/swift/pull/61966
