### ISSUE TITLE
WKWebView 使用系统播放器AVPlayerViewController，全屏弹出在iOS16crash

### ISSUE THREAD

**Issue by AndyZZhz** [apple/swift#61739]
WKWebView 使用系统播放器AVPlayerViewController，全屏弹出在iOS16crash

**Comment by LucianoPAlmeida** [comment]
Hey @AndyZZhz this space is for tracking issues related to the Swift compiler, language, runtime, and standard library. There are many community resources available to you to ask questions like this, including StackOverflow, Reddit and so on... If you believe this is an iOS16 issue you can submit a [Feedback](https://feedbackassistant.apple.com/)

So closing this =]

**Comment by AnthonyLatsis** [comment]
You mention a crash: if you believe this is a compiler issue, not a framework one, please report a new issue according to the [guidelines](https://www.swift.org/contributing/#reporting-bugs), in English.
