### ISSUE TITLE
Progressview is hidden in the list when it is scrolled

### ISSUE THREAD

**Issue by jaikrishna-zuper** [apple/swift#61743]
Run the below code, you can see the progressview, Scroll the list to bottom and come back to top, you cannot see the progress View. I have this issue in iOS 16, it may occur in the other platform too.

```
@main
struct SampleApp: App {
    var body: some Scene {
        WindowGroup {
            
            List {
                ProgressView()
                       ForEach(0..<50, id: \.self) {
                           Text("\($0)")
                       }.id(UUID().uuidString)
            }
        }
    }
}

```

**Comment by LucianoPAlmeida** [comment]
Hey @jaikrishna-zuper this space is for tracking issues related to the Swift compiler, language, runtime, and standard library. There are many community resources available to you to ask questions like this, including StackOverflow, Reddit and so on... If you believe this is an Apple Framework issue (in this case SwiftUI issue) you can submit a [Feedback](https://feedbackassistant.apple.com/)

With that said, closing this
