### ISSUE TITLE
Extension keyboard not working with IOS 16

### ISSUE THREAD

**Issue by UnityNinja** [apple/swift#61968]
**Describe the bug**
I have a basic keyboard extension that was working with IOS 15 before updating my phone to IOS 16.1 .

The keyboard has a WKWebView that renders a basic HTML page with some text in it (code sample below)

When running on the simulator with IOS 16 everything loads perfectly.

The problem appears when I'm trying to run the application on an actual device, there I am stuck in a white screen (WKWebView loads, but the content is not loading) and a lot of errors ( log : https://pastebin.com/jC62Mwgd ). NOTE: the log was taken from a test run of the keyboard in 'Notes' application

`func makeViewConfiguration() -> WKWebViewConfiguration  {
        let configuration = WKWebViewConfiguration()
        let dropSharedWorkersScript = WKUserScript(source: "delete window.SharedWorker;", injectionTime:
WKUserScriptInjectionTime.atDocumentStart, forMainFrameOnly: false)
        configuration.userContentController.addUserScript(dropSharedWorkersScript)
        return configuration
    }
 override func viewDidLoad() {
        super.viewDidLoad()
        popup = UIView()
        popup.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        webView = WKWebView(frame: CGRect(x:100, y:100, width:100, height:350), configuration: makeViewConfiguration())
        webView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        webView.frame = CGRect(origin: CGPoint.zero, size: popup.frame.size)
        webView.backgroundColor = UIColor.white
        webView.uiDelegate = self

        let contentController = webView.configuration.userContentController
        contentController.add(self, name: "toggleMessageHandler")

        popup.addSubview(webView)

        
        webView.loadHTMLString("<html><body><p>Hello!</p></body></html>", baseURL: nil)
        
        popup.backgroundColor = UIColor.cyan;
       
        self.view.addSubview(popup)
       
    }`

Already tried but nothing changed:
- to disable shared workers
- to enable RequestOpenAccess,
- to enable AllowArbitraryLoads

**Expected behavior**
The keyboard must work as it is working on iOS 14 to iOS 15.6 versions.

**Environment**
 - OS: macOS Monterey version 12.6
 - Xcode Version:  Version 14.0.1 (14A400)

**Comment by tbkka** [comment]
Issues developing macOS or iOS applications should be sent to Apple's Feedback Assistant.  This forum is only for issues specifically related to the Swift compiler and runtime.  There's nothing in here that obviously looks like a Swift compiler or runtime bug.  (If you find anything that does make it look like a Swift compiler or runtime bug, please feel free to re-open this bug.)

**Comment by AnthonyLatsis** [comment]
[Apple's Feedback Assistant](https://feedbackassistant.apple.com/)
