### ISSUE TITLE
GettingStarted.md contains out-of-date CMake version

### ISSUE THREAD

**Issue by aenewton** [apple/swift#62023]
**Describe the bug**
The GettingStarted guide is out of date regarding which CMake version is required. 

**Steps To Reproduce**
Repro details are in this thread: https://forums.swift.org/t/unable-to-integrate-xcode-with-ninja/61350/2

I was running 3.21.x, and the docs state you need 3.19.6 or higher, so I thought I was in the clear, but the "unknown arguments specified" made me suspect the version. I upgraded to the latest (3.24.3) and now the build succeeded. I'm not sure exactly which version should be the minimum, but 3.19.6 is now too low.

**Environment (please fill out the following information)**
M1 Pro MacBook Pro
macOS 13.0 (22A380)
Xcode Version 14.1 (14B47b)
xcode-select -p = /Applications/Xcode.app/Contents/Developer

**Comment by tbkka** [comment]
CC: @etcwilde

**Comment by etcwilde** [comment]
So, there is a bug in CMake. I think it's around code signing causing the compiler detection to fail when using the Xcode generator, resulting in it failing to set the compiler related variables. This percolates down into LLVM, which has some checks. IIRC, we don't actually support building with Xcode, only using it for source editing. To build, use the Ninja generator and that should work.

**Comment by AnthonyLatsis** [comment]
If this is indeed a CMake bug, then it seems to reproduce only on macOS 13 for some reason. `--xcode` was recently repurposed to only generate the projects, it doesn’t do a full-fledged build anymore.
