### ISSUE TITLE
`@MainActor` annotation on `didSet` does nothing (neither in runtime or compile time)

### ISSUE THREAD

**Issue by mstyura** [apple/swift#62114]
**Describe the bug**
Compile the following snippet:
```
// extra compiler flags: -warn-concurrency -enable-actor-data-race-checks
import Foundation

final class MyClass {
    var state: Int = 0 {
        @MainActor
        didSet {
            // Not the thread is not main even so @MainActor annotated
            print("didSet thread: \(Thread.current)")
        }
    }
}

func run() async {
    _ = await Task {
        let c = MyClass()
        c.state = 10
        print("Did finish")
    }.result
}

await run()
```

**Steps To Reproduce**
1. Compile attached snipped of code;
2. Run application with  `SWIFT_UNEXPECTED_EXECUTOR_LOG_LEVEL=2`

**Actual behavior**
No compile time warnings generated, application is crashed in runtime with `SWIFT_UNEXPECTED_EXECUTOR_LOG_LEVEL=2`

**Expected behavior**
Either compiler produces compiler error/warning on setting property from wrong actor or in runtime `didSet` is dispatched to main actor,

**Environment (please fill out the following information)**
 - Xcode Version/Tag/Branch: XCode 14.1/Swift 5.7

**Comment by hborla** [comment]
Property observers cannot have different actor isolation from the enclosing property. This is diagnosed by https://github.com/apple/swift/pull/69369
