### ISSUE TITLE
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'clang_rt.cc_kext_i386_osx' from project 'CompilerRT') warning: None of the architectures in ARCHS (i386) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, i386, x86_64). (in target 'clang_rt.cc_kext_i386_osx' from project 'CompilerRT')

### ISSUE THREAD

**Issue by MikePendo** [apple/swift#62205]
**Description**
Build failed on runing 
`utils/build-script --release --swift-darwin-supported-archs "$(uname -m)" --Xcode`

**Steps to reproduce**
Following the instruction from here: [How to Set Up an Edit-Build-Test-Debug Loop](https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md)
Wanted to generated Xcode projects to look at the code but have encounter the following error:
```
error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture. (in target 'clang_rt.cc_kext_i386_osx' from project 'CompilerRT')
warning: None of the architectures in ARCHS (i386) are valid. Consider setting ARCHS to $(ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, i386, x86_64). (in target 'clang_rt.cc_kext_i386_osx' from project 'CompilerRT')
```
So I have changed the arch of the target clang_rt.cc_kext_i386_osx to arm64 and x86_64
and got the following:
`Xcode-ReleaseAssert/llvm-macosx-x86_64/tools/clang/runtime/compiler-rt-bins/build/clang_rt.cc_kext_i386_osx.build/Release/Objects-normal/arm64/powisf2.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'clang_rt.cc_kext_i386_osx' from project 'CompilerRT')`

**Expected behavior**
Successfully build, and Xcode projects created 

**Environment**
- Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
  Target: x86_64-apple-macosx12.0
- Xcode 13.4 Build version 13F17a

Similar issue was found [here](https://forums.swift.org/t/error-running-build-script-no-architectures-to-compile-for/31050/9) and marked as resolved
Can u please suggest what configs should I change to build the projects

**Comment by AnthonyLatsis** [comment]
`--xcode` broke on Friday due to what seems like an LLVM change; we're currently looking into it.

**Comment by AnthonyLatsis** [comment]
@MikePendo Can you provide the swift branch and revision?

**Comment by MikePendo** [comment]
main branch,
```
103b4a89c22 (HEAD -> main, origin/main, origin/HEAD) [Parse] Restore a couple of StructureMarkerRAII (#62193)
1ab30513019 Merge pull request #62199 from apple/shahmishal/resilient_debug_value.sil
d2ebcf3bdd9 Disable resilient_debug_value.sil
```

**Comment by MikePendo** [comment]
Quick question, so what steps should I do to compile it, should I start everything from scratch?

**Comment by AnthonyLatsis** [comment]
Not everything, just checkout the sources again (remember, you *have* to use `update-checkout` for that), then generate the projects from scratch. To generate from scratch, either pass `--clean` to your `build-script` invocation, or delete the `build/Xcode-*` directory before generating. Other instructions remain the same.

**Comment by MikePendo** [comment]
@AnthonyLatsis 
Please tell me if I need to open a new issue after running `update-checkout` and 
```
utils/build-script --skip-build-benchmarks \
   --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping --clean
```
I am seeing the following errors

```
CMake Error in lib/ASTGen/CMakeLists.txt:
  Imported target "SwiftSyntax::SwiftBasicFormat" includes non-existent path

    "/location/Desktop/SwiftCompiler/build/Xcode-ReleaseAssert/earlyswiftsyntax-macosx-x86_64/lib/swift/host"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
after running :
`utils/build-script --release --swift-darwin-supported-archs "$(uname -m)" --Xcode`
I dont see that folder get generated `/lib/swift/host`, any ideas?

Also in the docs they mention:
`Add the generated Xcode projects or Swift packages that are relevant to your tasks to your workspace. All the Xcode projects can be found among the build artifacts under build/Xcode-DebugAssert`
I think it should be run with `--debug` flag (for better consistency), I got the error in both cases

**Comment by AnthonyLatsis** [comment]
@MikePendo Are you positive this was a clean build that failed? If so, then yes, please open a new issue. And sorry for the breakages, it looks like the ongoing migration of the parser to Swift is causing disturbances.

**Comment by AnthonyLatsis** [comment]
As for `DebugAssert`, that’s a typo, thanks for spotting it!

**Comment by AnthonyLatsis** [comment]
@MikePendo Ah, I misinterpreted your reply. So it's the Ninja build that's failing for you, not Xcode project generation?

**Comment by whiteio** [comment]
Was a new issue opened for this? I'm also running into the same problem when doing a clean build.

**Comment by AnthonyLatsis** [comment]
> Was a new issue opened for this? I'm also running into the same problem when doing a clean build.

No, please do.

**Comment by MikePendo** [comment]
sorry I forgot to open.
@whiteio if you open can please link the new open issue here so we could follow

**Comment by AnthonyLatsis** [comment]
> ```
> CMake Error in lib/ASTGen/CMakeLists.txt:
>   Imported target "SwiftSyntax::SwiftBasicFormat" includes non-existent path
> 
>     "/location/Desktop/SwiftCompiler/build/Xcode-ReleaseAssert/earlyswiftsyntax-macosx-x86_64/lib/swift/host"
> 
>   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
> 
>   * The path was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and references files it does not
>   provide.
> ```

This error is tracked in #62645, no need to open a new one.
