### ISSUE TITLE
LLDB missing variables in certain case

### ISSUE THREAD

**Issue by Alkaid-10** [apple/swift#62241]
For some certain swift code, like：

```swift
// Dog.swift
class Dog: NSObject {
  var wang : Bool?
}
// main.swift

let wang = Dog().wang ?? false
if wang { //Break here
  print("this line is never reached") // <--
}
```

When we debug and stop at the `Break here` line, the debugger doesn't show the value of `wang`.

There are also some details behavior:

1. If we use that `wang` variable later (except the `if` expression), like `print(wang)`. The issue disappears
2. If we define class `Dog` inside the same file `main.swift` (not another file `Dog.swift`. The issue disappears

We have tried to find out reasons and have one guess: During SIL Canonical stage, the Swift compiler may probably do some optimizations to such unused variables, which leads to the loss of debug value. For example:

```
%30 = load %8 : $*Bool, loc "/Users/ccc/Desktop/PHITest/PHITest/ViewController.swift":18:27, scope 2 // users: %89, %31, %33
%33 = struct_extract %30 : $Bool, #Bool._value, loc "/Users/ccc/Desktop/PHITest/PHITest/ViewController.swift":20:9, scope 3 // user: %34
```

This SIL might be optimized as:

```
%31 = load %30 : $*Builtin.Int1, loc "/Users/ccc/Desktop/PHITest/PHITest/ViewController.swift":18:27, scope 2 // user: %33
```

Maybe this process leads to the loss of debug value of `wang` which cause the missing display of value of `wang` in LLDB?

**Steps to reproduce**

The demo which can trigger this bug is attached in this PHITest.zip file.

By setting breakpoints at `if(wang)` in ViewController.swift and debug this project you can see the lldb debugger doesn't show the value of `wang`. 

[PHITest.zip](https://github.com/apple/swift/files/10080323/PHITest.zip)

**Expected behavior**

The LLDB debugger should show the value of `wang`, which should be `false`.

**Environment**
- Swift compiler version info: Swift 5.7
- Xcode version info: Xcode 14.0/14.1
- Deployment target:  iOS15+ (reproducible in lower firmware as well)

**Comment by LucianoPAlmeida** [comment]
The code as it shows will never reach this print line because wang is always `false` I couldn't repro this and lldb shows correct values. Are you building in release mode or debug mode?

**Comment by Alkaid-10** [comment]
> The code as it shows will never reach this print line because wang is always `false` I couldn't repro this and lldb shows correct values. Are you building in release mode or debug mode?

Try adding breakpoint at `if(wang)` statement? I found this bug by setting breakpoint at this line.

**Comment by LucianoPAlmeida** [comment]
![Screenshot 2022-11-24 at 22 46 48](https://user-images.githubusercontent.com/8292651/203884166-e54961a5-31fc-49c9-81c5-3c42d459334e.png)

Interesting fact, this was repro only in local function scope. And `Dog`'s definition didn't need to be in other file.
`swift-healthcheck` did produce error trying to load _StringProcessing module
<summary>
Output of swift-healthcheck
<details>
SwiftASTContextForExpressions::LogConfiguration() --     -I/Users/lucianoalmeida/Library/Developer/Xcode/DerivedData/swiftc-exwdrbeowpjeixazhrkfwlickbzm/Build/Intermediates.noindex/swiftc.build/Debug/swiftc.build/DerivedSources
SwiftASTContextForExpressions::LogConfiguration() --     -DDEBUG=1
SwiftASTContextForExpressions::LoadOneModule() -- Missing Swift module or Clang module found for "_StringProcessing", "imported" via SwiftDWARFImporterDelegate. Hint: Register Swift modules with the linker using -add_ast_path.
</details>
</summary>

**Comment by dreampiggy** [comment]
I use the same test project, and use `log enable lldb`, the `_StringProcessing` module exists, so I don't think related to that issue. It mostlly related to the compiler side SILGen optimization.

```
== [UserExpression::Evaluate] Parsing expression wang ==
 SwiftUserExpression::ScanContext()
   [SUE::SC] Compilation unit is swift
 DWARF location description kind: Memory
 DWARF location description kind: Memory
   [SUE::SC] Containing class name: PHITest.ViewController
 Parsing the following code:

extension $__lldb_context {
  @LLDBDebuggerFunction @available(iOS 16.0, *)
  final func $__lldb_wrapped_expr_1(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
    
do {
/*__LLDB_USER_START__*/
wang
/*__LLDB_USER_END__*/
} catch (let __lldb_tmp_error) {
  var $__lldb_error_result = __lldb_tmp_error
}

  }
}
@LLDBDebuggerFunction @available(iOS 16.0, *)
func $__lldb_expr(_ $__lldb_arg : UnsafeMutablePointer<Any>) {
  do {
    $__lldb_injected_self.$__lldb_wrapped_expr_1(
      $__lldb_arg
    )
  }
}

 SwiftASTContextForExpressions::LoadOneModule() -- Importing module _StringProcessing
 SwiftASTContextForExpressions::operator()() -- Loading linked library "swift_StringProcessing".
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module _StringProcessing from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/_StringProcessing.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module _Concurrency
 SwiftASTContextForExpressions::operator()() -- Loading linked library "swift_Concurrency".
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module _Concurrency from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/_Concurrency.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module Swift
 SwiftASTContextForExpressions::operator()() -- Loading linked library "swiftCore".
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module Swift from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/Swift.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module PHITest
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module PHITest from {kind = Serialized Swift AST, filename = "PHITest";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module UIKit
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module UIKit from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/UIKit.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module UIKit
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module UIKit from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/UIKit.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module _StringProcessing
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module _StringProcessing from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/_StringProcessing.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module _Concurrency
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module _Concurrency from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/_Concurrency.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 SwiftASTContextForExpressions::LoadOneModule() -- Importing module SwiftOnoneSupport
 SwiftASTContextForExpressions::LoadOneModule() -- Imported module SwiftOnoneSupport from {kind = Serialized Swift AST, filename = "/Applications/Xcode-14.0.0.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.0.sdk/usr/lib/swift/SwiftOnoneSupport.swiftmodule/arm64-apple-ios-simulator.swiftinterface";}
 DWARF location description kind: Memory
 Made global type alias for $__lldb_context (0x430e3bf68) in context (0x44c181a00):
(typealias implicit "$__lldb_context" type='ViewController')

 DWARF location description kind: Memory
 Adding injected self: type (0x430e3bf68) context(0x44c181a00) is: (class_type decl=PHITest.(file).ViewController)

 [SwiftASTManipulator::AddExternalVariables] Injected variable (var_decl implicit range=[<EXPR>:17:62 - line:17:62] "$__lldb_injected_self" type='ViewController' interface type='ViewController' access=public readImpl=stored writeImpl=stored readWriteImpl=stored)

 [LLDBExprNameLookup::lookupOverrides(7)] Searching for $__lldb_context
 [LLDBExprNameLookup::lookupAdditions (7)] Searching for $__lldb_context
 [LLDBExprNameLookup::lookupOverrides(8)] Searching for $__lldb_context
 [LLDBExprNameLookup::lookupAdditions (8)] Searching for $__lldb_context
 [LLDBExprNameLookup::lookupOverrides(9)] Searching for UnsafeMutablePointer
 [LLDBExprNameLookup::lookupAdditions (9)] Searching for UnsafeMutablePointer
 [LLDBExprNameLookup::lookupOverrides(10)] Searching for UnsafeMutablePointer
 [LLDBExprNameLookup::lookupAdditions (10)] Searching for UnsafeMutablePointer
 [LLDBExprNameLookup::lookupOverrides(11)] Searching for wang
 [LLDBExprNameLookup::lookupAdditions (11)] Searching for wang
 [LLDBExprNameLookup::lookupOverrides(12)] Searching for wang
 [LLDBExprNameLookup::lookupAdditions (12)] Searching for wang
 [LLDBExprNameLookup::lookupOverrides(13)] Searching for $__lldb_injected_self
 [LLDBExprNameLookup::lookupAdditions (13)] Searching for $__lldb_injected_self
error: expression failed to parse:
error: <EXPR>:8:1: error: cannot find 'wang' in scope
wang
^~~~

```

**Comment by LucianoPAlmeida** [comment]
> It's mostly related to the compiler side SILGen optimization ? Maybe the dwarf info generated by compiler is wrong.

It would be surprising if it was since we are seeing this issue in debug mode. Although some mandatory SIL passes runs in that case, but I'm no expert so it could be...

Here are some interesting thing I was able to narrow down from this issue:
It looks like is related to operator `??`, in fact to if m is a result of a call to any generic function 
```swift
@inline(never)
func hole<T>(_ : T) {}

class A {
  var m : Bool? = true
}

func unwrap<T>(_ optional: T?, _ defaultValue: @autoclosure () throws -> T)
    rethrows -> T {
  switch optional {
  case .some(let value):
    return value
  case .none:
    return try defaultValue()
  }
}

// main.swift
func testFn() {
  let m = unwrap(A().m, false)
  if m { // error: no variable named 'm' found in this frame
    hole("this line is never reached")
  }
}

func testFn1() {
  let m: Bool 
  m = unwrap(A().m, false)
  if m { // OK
    hole("this line is never reached") 
  }
}

testFn()
testFn1()
```
Also ok if `unwrap` is not-generic or we define a non-generic `??` operator specialization for `Bool`.
So lldb compiler seems to be having trouble with getting information from generic context, but from that point on wasn't able to debug further. 

> Maybe the dwarf info generated by compiler is wrong.

I'm not familiar enough with lldb to affirm anything, so it is possible. But my guess is that the error `error: expression failed to parse` is something that indicates an issue with lldb compiler because logs aren't even able to show a type checked AST for lookup the variable, because something is failing when trying to parse source in context, so no sure how could that be related to missing/wrong debug info, but again not an expert in lldb or anything...

cc @adrian-prantl  @augusto2112

**Comment by augusto2112** [comment]
Thank you for the report and for the investigation everyone.

I've reduced this to the following example:

```
func f() {
    let wang = Optional<Bool>.none ?? false
    if wang {
      print("wang")
    }
}
f()
```

It does look like the compiler is dropping debug info for `wang`, there's no mentions of `wang` in the `dwarfdump` output for the example, but if we add a usage of `wang` after the if statement (like `print(wang)`), then it shows up as:

```
0x00000055:     DW_TAG_subprogram
                  DW_AT_low_pc	(0x0000000100003d0c)
                  DW_AT_high_pc	(0x0000000100003eb0)
                  DW_AT_frame_base	(DW_OP_reg29 W29)
                  DW_AT_linkage_name	("$s1t1fyyF")
                  DW_AT_name	("f")
                  DW_AT_decl_file	("/tmp/t.swift")
                  DW_AT_decl_line	(1)
                  DW_AT_type	(0x0000017e "$sytD")
                  DW_AT_external	(true)

0x00000072:       DW_TAG_lexical_block
                    DW_AT_low_pc	(0x0000000100003d18)
                    DW_AT_high_pc	(0x0000000100003eb0)

0x0000007f:         DW_TAG_variable
                      DW_AT_location	(DW_OP_fbreg -8)
                      DW_AT_name	("wang")
                      DW_AT_decl_file	("/tmp/t.swift")
                      DW_AT_decl_line	(2)
                      DW_AT_type	(0x00000193 "const Swift::Bool")
```

**Comment by Alkaid-10** [comment]
I have tied to skip some function like `deleteAllDebugUses` and the result didn't changed.
I found one comment in the `swift/Documentaion/docs/SIL.rst`, it saids that:
`Debug information is generally associated with allocations (alloc_stack or
alloc_box) by having a Decl node attached to the allocation with a SILLocation.
For declarations that have no allocation we have explicit instructions for
doing this.  This is used by 'let' declarations, which bind a value to a name
and for var decls who are promoted into registers.  The decl they refer to is
attached to the instruction with a SILLocation.`
So I have a new guess, maybe it is because swift never create a debug_value for this type of variable?

**Comment by Alkaid-10** [comment]
I have found a related commit: https://github.com/apple/swift/commit/875d1114b04a835c96b92c63071d9045e453362c from a great author @atrick. In this commit he said that he was fixing CanonicalizeInstruction to correctly preserve debug info at both -Onone and -O. Maybe this bug is triggered because of this debug_info miss and will be fixed by apple in the future @atrick ? I have tested on both -Onone and -O mode and found out that in Viewcontroller.sil we still miss the debug_value "wang". >_<

**Comment by atrick** [comment]
Thanks for debugging and reducing!

I'm not sure of the status of LLVM's "debug fragmants" feature. Regardless, I don't think we want to rely on that feature for debug (Onone) builds.

The split-loads pass "lowers" the load of Bool into a load of Bool._value. We need to run this pass at Onone to avoid breaking source. We can't move the debug_value to the new load because it's the wrong type, and only a "fragment" of the original value.

As a very crude hack, we could simply move the debug_value from the loaded value to its address. I'm afraid in some cases that could report an incorrect debug value.

A better hack is probably the one I outlined in the FIXME. Keep both the original and the new lowered load but "hide" the original one from the exclusivity checker.

I can try to implement that very soon, like next week. If someone else wants to go for it, I can review it.

**Comment by atrick** [comment]
I do think the createDebugFragments fix should be enabled at -O. It might work with the current LLVM. But someone who works on debug info would need to test and debug it. @adrian-prantl

**Comment by Alkaid-10** [comment]
> 

Thanks for your great advice, it does help a lot! However I still have a small question about "the exclusivity checker": How can we hide a load address, is there any flag telling whether is a SIL instruction valid or not? Besides, what is an exclusivity checker and how does it works(Therefore I can find a way to avoid the original load from being checked)? Thanks again for your great advice！

**Comment by atrick** [comment]
The exclusivity checker verifies that the same variable is not accessed at the same time that it is being modified using a different name (for example via closure captures). People expect to be able to access two fields of the same struct simultaneously though:
`foo(&s.a, &s.b)`
Initially, that looks illegal to the checker. Diagnosing that correctly as valid code requires load splitting.
The way that we hide the original load from the checker is by wrapping it in an unsafe access scope
```
%access = begin_access [unsafe] %adr
load %access
end_access %access
```

**Comment by adrian-prantl** [comment]
> I do think the createDebugFragments fix should be enabled at -O. It might work with the current LLVM. But someone who works on debug info would need to test and debug it. @adrian-prantl

The only known issue with the system that I am aware if is the one mentioned in

**Comment by Alkaid-10** [comment]
Thanks to @atrick 's advice, I have successfully fixed this problem in my swift, now it can successfully show the missing debug value. 
Now the result in lldb is:
<img width="836" alt="修复结果" src="https://user-images.githubusercontent.com/53359190/207799396-b0d93c9a-2fa8-4099-9439-0ea3158b78dc.png">

I will do more security check before a formal submit to make sure it is a safe modification.
Is it necessary to submit this commit @atrick ? Since this is just a hack, I don't know if this bug will disappear in the future since I knew from the comment that there will be a big change in the code inside splitAggregateLoad().

**Comment by atrick** [comment]
Here's a PR the fix I suggested. It needed to be extended to handle general problem, and there were a lot of difficult details to handle.

PR: https://github.com/apple/swift/pull/62672

**Comment by atrick** [comment]
Reopening because the fix was reverted.
