### ISSUE TITLE
Incorrect swift syntax in Grenerics.rst#default-implementations

### ISSUE THREAD

**Issue by yamagranat** [apple/swift#62254]
**Description**

https://github.com/apple/swift/blob/main/docs/Generics.rst#default-implementations
shows example of protocol providing default implemntations:
```swift
protocol Numeric {  
  func +(lhs : Self, rhs : Self) -> Self  
  func -(lhs : Self, rhs : Self) -> Self { return lhs + -rhs }  
  func +(x : Self) -> Self { return x }  
  func -(x : Self) -> Self  
}
```
but it's not actual implementation of such functionality.
I suppose that the following is better because it shows actual Swift syntax:
```swift
protocol Numeric {
  func +(lhs : Self, rhs : Self) -> Self
  func -(x : Self) -> Self
}
extension Numeric {
  func -(lhs : Self, rhs : Self) -> Self { return lhs + -rhs }
  func +(x : Self) -> Self { return x }
}
```

**Steps to reproduce**

**Expected behavior**

**Environment**
- Swift compiler version info 
- Xcode version info 
- Deployment target:

**Comment by AnthonyLatsis** [comment]
Duplicate of #62255
