### ISSUE TITLE
Initializer autocompletion leaves out async keyword from async closure members

### ISSUE THREAD

**Issue by Jnosh** [apple/swift#62274]
**Description**

For the following example type:

```swift
struct Foo {
    private let bar: () async -> Void
}
```

autocompletion for the initializer produces the following, dropping async from the closure type:

```swift
init(bar: @escaping () -> Void) {
    self.bar = bar
}
```

**Environment**
- swift-driver version: 1.62.15
- Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
- Xcode 14.1 (14B47b)
- Deployment target: macOS 13

**Comment by AnthonyLatsis** [comment]
@nkcsgexi Does this sound like a good first time issue?

**Comment by nkcsgexi** [comment]
Yeah, I think it's a reasonable starter bug.

**Comment by greenthings** [comment]
Can i join in?

**Comment by AnthonyLatsis** [comment]
No need to ask!

**Comment by Kyle-Ye** [comment]
> * swift-driver version: 1.62.15
> * Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
> * Xcode 14.1 (14B47b)
> * Deployment target: macOS 13

Could not reproduce it with the same env.

```swift
struct Foo {
    // Autocompletion result: ⌘ click on Foo and choose "Generate Memberwise Initializer"
    internal init(bar: @escaping () async -> Void) {
        self.bar = bar
    }

    private let bar: () async -> Void
}
```

**Comment by Jnosh** [comment]
I can confirm that "Generate Memberwise Initializer" produces the correct result. Seems the generated initializer depends on how it is generated.

I encountered the issue when typing `init` below the member in the struct, at which point Xcode presents an autocomplete option `init(bar: @escaping () -> Void) {...}` which creates async-less initializer.

<img width="431" alt="autocomplete" src="https://user-images.githubusercontent.com/3801202/205711835-23f7108b-1c1f-4c70-a8cc-aaae7f2cfbe4.png">

**Comment by Kyle-Ye** [comment]
> I can confirm that "Generate Memberwise Initializer" produces the correct result. Seems the generated initializer depends on how it is generated.
> 
> I encountered the issue when typing `init` below the member in the struct, at which point Xcode presents an autocomplete option `init(bar: @escaping () -> Void) {...}` which creates async-less initializer.
> 
> <img alt="autocomplete" width="431" src="https://user-images.githubusercontent.com/3801202/205711835-23f7108b-1c1f-4c70-a8cc-aaae7f2cfbe4.png">

I believe this was either a bug in Xcode or a bug in SourceKit LSP.

But try to “Generate Memberwise Initializer” in VSCode via vscode-swift plugin (Which uses SourceKit LSP for the language server) gives the same correct completion.

So I think it is more likely to be a bug in Xcode snippets system. (Need a experienced one in SourceKit to conform is)

**Comment by AnthonyLatsis** [comment]
> I encountered the issue when typing `init` below the member in the struct

That’s a helpful detail, thank you. This is a code completion issue then.

**Comment by AnthonyLatsis** [comment]
Interesting, I thought we had our own completions for memberwise initializers. Odd for Xcode to implement a feature that ought to belong in the arsenal of our source tooling.
