### ISSUE TITLE
Global Actor conformed to public NSObject cannot be found. 

### ISSUE THREAD

**Issue by Cartisim** [apple/swift#62370]
**Description**
I have an interesting issue, When I create a global actor

```
@objc @globalActor public final actor MyActor {
    static public let shared = MyActor()
    private init(){}
}
```
and Conform it to a class that inherits NSObject

```
@MyActor
public final class MyClass: NSObject {

    @objc public var propertyOne: SomeType

    @objc func functionOne() async {
        // Some Logic
    }

}
```

I then use xcode build to generate an XCFramework

When I import the Module the swift compiler is all kinds of unhappy in regards to this actor

inside of MyModule.swiftmodule/arm64-apple-ios.private.swiftinterface I keep getting the error.
No type named 'MyActor' in module 'MyModule' on a variety of properties and functions that are public and are available in Objective-C via @objc func or @objc var/let.

**Steps to reproduce**
1. Create an XCode Project
2. Write a final public class that conforms to NSObject
3. Write a global public actor that conforms to Objective-C
4. Conform the public class to the Global Actor
5. Write a couple methods and properties
6. Run a build script that generates an XCFramewo
[MyExample.zip](https://github.com/apple/swift/files/10143467/MyExample.zip)
rk
7. Import the framework into an iOS project
8. Try and build the project

**Expected behavior**
I would expect a clean build and the Global Actor to be found, but rather I get an error
`No type named 'MyActor' in module 'MyModule' `

Swift compiler: 5.7.1
Xcode version: 14.1

**Environment**
- Swift compiler version info swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51) Target: arm64-apple-macosx13.0
- Xcode version info Xcode 14.1 Build version 14B47b
- Deployment target: iOS 13/14
- 
Here is an example of the bug
[MyExample.zip](https://github.com/apple/swift/files/10143468/MyExample.zip)

**Comment by tshortli** [comment]
This is fixed in Swift 5.8. It was addressed by https://github.com/apple/swift/pull/61421
