### ISSUE TITLE
MainActor isolation is not ensured in a particular case

### ISSUE THREAD

**Issue by PoltoraIvana** [apple/swift#62394]
**Description**
MainActor isolation is not ensured in a particular case

**Steps to reproduce**
See the code:

```swift
import UIKit

final class ThreadCheckViewController: UIViewController {
  private let presenter: SomePresenter = Presenter()
  
  override func viewDidLoad() {
    super.viewDidLoad()
    Task.detached {
      await self.presenter.doSomethingOnMain()
    }
  }
}


@MainActor
protocol SomePresenter: AnyObject {
  func doSomethingOnMain() async // ------> method is annotated as async
}

final class Presenter: SomePresenter {
  func doSomethingOnMain() { // ------> even though method is sync and not async, it satisfies the protocol 
    guard Thread.isMainThread else {
      preconditionFailure() // ------> this is called, crashing
    }
    print("On main")
  }
}
```

**Expected behavior**
I would expect that either:
- the code does not compile, since method in a class does not really satisfy the requirement (is sync instead of async), or
- it is called on MainActor.

**Environment**
- Swift compiler version info: swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
- Xcode version info: Xcode 14.0, Build version 14A309
- Deployment target: tested with both iOS 16 as a deployment target and iOS 13

**Comment by AnthonyLatsis** [comment]
cc @ktoso

**Comment by hborla** [comment]
I provided an analysis of the same problem in https://github.com/apple/swift/issues/68487

The type checking behavior here is fine; the issue appears to be a miscompile where the witness thunk for the async protocol requirement does not hop to the isolation domain of the synchronous method before calling it.
