### ISSUE TITLE
Compiler is extremely slow to compile simple closure

### ISSUE THREAD

**Issue by Zollerboy1** [apple/swift#62390]
**Description**
While trying today's advent of code task as fast as possible (yes, I was slightly frustated), I encountered a weird bug in the compiler that causes it to compile extremely slowly. The simplest example that still exhibits this behaviour is a simple swift file of 11 lines that causes swiftc to run for over 2 minutes.

**Steps to reproduce**
Create a swift file with the following contents:

```swift
extension Sequence where Element: Numeric {
    public func sum() -> Element {
        self.reduce(0, +)
    }
}

let foo: [(Int, Int, Int, Int)] = []

print(foo.map { a, b, c, d in
    return ((a <= c && b >= d) || (c <= a && d >= b)) ? 1 : 0
}.sum())
```

Try to build it with swiftc.

**Expected behavior**
I expect the compiler to compile such a single file in a matter of a few milliseconds.

**Environment**
- **Swift version:**
  swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.2 clang-1400.0.29.51)
  Target: x86_64-apple-macosx13.0
- **Xcode version (Shouldn't really matter, as this happens on linux using Swift 5.7 as well)**
  Xcode 14.1
  Build version 14B47
- **Deployment Target**
  macOS Ventura 13.0

**Comment by xedin** [comment]
Interesting.

**Comment by xedin** [comment]
I wonder if in first example solver attempts one of the operator disjuctions before unpacking tuple, maybe we can improve performance here by special casing this in `resolveClosure`
