### ISSUE TITLE
Error when adding swift to Windows 10 

### ISSUE THREAD

**Issue by egkagka** [apple/swift#62419]
Dears,

I tried to install swift to windows 10 laptop but I experienced the following issue although I meet all the requirements as listed on https://www.swift.org/getting-started/

The error when I tried to run a simple command (print("Hello") is:
**<module-includes>:1:10: note: in file included from <module-includes>:1:
#include "AssertionReporting.h"
         ^
C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\shims/AssertionReporting.h:16:10: note: in file included from C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\shims/AssertionReporting.h:16:
#include "SwiftStdint.h"
         ^
C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\shims/SwiftStdint.h:28:10: error: 'stdint.h' file not found
#include <stdint.h>
         ^
<unknown>:0: error: could not build C module 'SwiftShims'**

Please note that swift is successfully installed (checked using 'swift --version' at cmd) & added to path.

Thank you everyone very much in advance,
Eva

**Comment by Joannis** [comment]
Running into the same issue as well. I assume you haven't found a solution right @egkagka ?

**Comment by Joannis** [comment]
Funny thing is that VSCode seems to recognise stdint.h, and points me to the right location inside MSVC. But it's not being linked against by Swift itself. I think it'll be a small change to fix this.

**Comment by ggthg** [comment]
I had the same issue. I uninstalled Swift and installed "Desktop development with C++" using "Visual Studio Installer" then reinstalled Swift. It worked for me.

![image](https://user-images.githubusercontent.com/84884512/214480700-38b895a1-c182-4675-bfda-a17d47a2fdff.png)

**Comment by egkagka** [comment]
> Running into the same issue as well. I assume you haven't found a solution right @egkagka ?

Not yet, although I tried the same procedure using a different laptop and there was no problem, so I have no clue what it may be. 
Sorry for the late response, haven't noticed your comment

**Comment by egkagka** [comment]
> I had the same issue. I uninstalled Swift and installed "Desktop development with C++" using "Visual Studio Installer" then reinstalled Swift. It worked for me.
> 
> ![image](https://user-images.githubusercontent.com/84884512/214480700-38b895a1-c182-4675-bfda-a17d47a2fdff.png)

Thank you very much! 
I'll try it as soon as possible and hopefully the issue will be fixed
Once again, thank you!

**Comment by compnerd** [comment]
The install order is likely the thing or you have multiple versions of Visual Studio installed.  If you have more than one version of Visual Studio installed, please use the x64 native developer command prompt and that should resolve the issue.

**Comment by Kyle-Ye** [comment]
> The install order is likely the thing or you have multiple versions of Visual Studio installed. If you have more than one version of Visual Studio installed, please use the x64 native developer command prompt and that should resolve the issue.

Running `swift build` in `x64 native developer command prompt` fix the problem. But what can we do if we want to use it in VSCode or other termianl.(I actually only have one Visual Studio installed. And in case I do something wrong, I just uninstalled everything and install VS 2019 again to confirm it.)

**Comment by compnerd** [comment]
With the 2023-03-27 development snapshot this should no longer be an issue, we no longer need to modify Visual Studio.
