### ISSUE TITLE
[Source compatibility suite] BricBrac fails to build tests using swift package on Linux

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#62438]
**Describe the bug**
The source compatibility suite project https://github.com/glimpseio/BricBrac/commit/92447f2c02b62c373f60d8e76e684a645fcd570a is failing to build when `--build-tests` is passed to the invocation used to build the swift package on Linux.

**Steps To Reproduce**
1. Checkout https://github.com/glimpseio/BricBrac/commit/92447f2c02b62c373f60d8e76e684a645fcd570a
2. Run `xcrun swift build --build-tests -Xswiftc -enable-testing`

The output will contain
```
/build/swift-source-compat-suite/project_cache/BricBrac/Tests/LinuxMain.swift:5:28: error: type 'BricBracTests' has no member 'allTests'
    testCase(BricBracTests.allTests),
```

**Expected behavior**
Expecting the project to build correctly

**Environment (please fill out the following information)**
```
Apple Swift version 5.8-dev (LLVM 6060385d2e829e0, Swift dc033557ccaed64)
Target: x86_64-apple-macosx10.15.4
```

https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/77/artifact/build/swift-source-compat-suite/FAIL_BricBrac_5.3_BuildSwiftPackage.log

**Comment by justice-adams-apple** [comment]
Xfailed project on linux here: https://github.com/apple/swift-source-compat-suite/pull/748

**Comment by AnthonyLatsis** [comment]
The project is no longer XFAILed.
