### ISSUE TITLE
Print is broken on Windows

### ISSUE THREAD

**Issue by broken-bytes** [apple/swift#62554]
**Description**
`print` does not work as intended on Windows.  Running print with anything other than the default terminator results in corrupted terminal output.

**Update:**
The issue is related to the modern Virtual Terminal mode in Windows. When not using the virtual Terminal Mode, it works as intended. See https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
Some commands to yield correct results, while others do not. Using some of the commands incorrectly (e.g. omitting an escape character) works while it should not.

I will dig deeper into this and keep the ticket updated.

**Steps to reproduce**

- Create a new Swift Package Project
- Define an executable target
- Run multiple prints with `terminator` set to `""`
- No matter what has been written previously, the cursor will always start at 0, thus every print overrides the previous

**Example:** 

```swift
public static func main() -> Void {
  print("This is Text A", terminator: "")
  print("This is Text B", terminator: "")
}
```

**Expected behavior**
The prints should get appended and the cursor should begin where the last print ended. This is the case for macOS. 

Output from previous example on macOS:
`This is Text AThis is Text B`

Output from previous example on Windows:
`This is Text B`

**Environment**
macOS:
- Builtin Xcode 14 Compiler
- macOS 12.6.1

Windows:
- Swift Compiler Dev Snapshot 5.8
- Windows 11 latest
- Powershell/CMD

I will test if this behaviour is the same on the release stream. I will update the ticket then.

**Update**: 
Also present on 5.7.1 release

**Comment by broken-bytes** [comment]
So what I found out so far:


The Windows doc state at some point that coloured output would need the escape sequence /r. Using that results in the issue I mentioned. Omitting it does the trick. As the docs state it, I will have to investigate further if this is just an issue with Swift + Virtual Terminal, or if this also happens in C++ + Virtual Terminal. If this is the case it would be a documentation issue.

I will test the very same procedure with C++ today and will update.

**Comment by compnerd** [comment]
This is not a bug, it is working as intended.  Unlike Unix, Windows requires CR+LF to actually proceed to the next line.  The default terminator is `\r\n` which will demonstrate the desired behaviour.

**Comment by compnerd** [comment]
```
>type \tmp\print.swift
print("This is Text A", terminator: "")
print("This is Text B", terminator: "")
>swiftc -o \tmp\print.exe -emit-executable \tmp\print.swift
   Creating library \tmp\print.lib and object \tmp\print.exp
>\tmp\print.exe
This is Text AThis is Text B
```

**Comment by broken-bytes** [comment]
Yes this does indeed work. 

I didn't realise in the first place that the issue is not the print itself but the print when using virtual console.
Using regular prints in a normal environment do work. 

I will probably create a sample repo in the next couple days to showcase the issue. It's a little hard to explain what's going on without more code and a proper setup.

Overall, I do think it's a Microsoft Documentation mistake

**Comment by compnerd** [comment]
@broken-bytes can this be closed?

**Comment by broken-bytes** [comment]
Yes it can be closed, it seems to be an issue with Windows itself, which isn't Swift's fault
