### ISSUE TITLE
rebranch, Windows: build fails with MSVC internal compiler error

### ISSUE THREAD

**Issue by eeckstein** [apple/swift#62633]
See https://ci-external.swift.org/view/all/job/oss-swift-r-windows-x86_64-vs2019/1648/

```
C:\Users\swift-ci\jenkins\workspace\oss-swift-r-windows-x86_64-vs2019\swift\lib\StaticMirror\ObjectFileContext.cpp(561) : fatal error C1001: Internal compiler error.
(compiler file 'd:\a01\_work\3\s\src\vctools\Compiler\Utc\src\p2\main.c', line 213)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com/ 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x69
  cl!RaiseException()+0x69
  cl!InvokeCompilerPassW()+0x11c5af
  cl!InvokeCompilerPassW()+0x17aa3b
```

**Comment by eeckstein** [comment]
@compnerd Any idea how to proceed with that?

**Comment by shahmishal** [comment]
Are we able to resolve this issue by updating to VS2022?

**Comment by compnerd** [comment]
Okay, it seems to be related to a type construction:

```c++
auto context = new reflection::ReflectionContext<External<NoObjCInterop<RuntimeTarget<4>>>>(nullptr);
```

**Comment by compnerd** [comment]
> Are we able to resolve this issue by updating to VS2022?

Yes, I believe that VS2022 just happens to not hit the issue.

**Comment by compnerd** [comment]
Ah so, doing a bit of sleuthing (thanks @al45tair!).

```cmd
> git merge-base github/main HEAD
cc70677303ad05ddf45358173785fe9ae7d3582a
```

This allows us to do the following:
```cmd
> git diff cc70677303ad05ddf45358173785fe9ae7d3582a..
```

This immediately shows what is likely the cause of this - the language mode was changed from C++14 to C++17, which has semantic changes.  I believe that `TaggedUnion` is no longer correct and will need to be adjusted.

**Comment by al45tair** [comment]
Talking to some folks here, and looking at the code, we think the code is correct (both for `TaggedUnion` and `TypeLookUpOrError`) and that this is just an MSVC bug. @compnerd tells me that updating to VS2022 did fix it, which is good. If we can't do that, then I _suspect_ that adding some extra constructors to `TaggedUnion` _might_ allow us to work around the problem, though they aren't actually needed.

**Comment by compnerd** [comment]
This has been fixed thanks to @al45tair.
