### ISSUE TITLE
Emit a warning when type parameters are shadowed.

### ISSUE THREAD

**Issue by hborla** [apple/swift#62767]
This code does not produce any diagnostics: 

```swift
struct S<T> {
  func f<T>(_: T) {}
}
```

Then, confusing errors are produced when the above code is called incorrectly:

```swift
S().f(1) // error: Generic parameter 'T' could not be inferred
```

This is fundamentally because the type parameter `T` is shadowed in `func f`. Usually, programmers do this by accident - they meant for the inner `T` to match the outer `T`. The compiler should emit a warning when type parameters are shadowed like this, with two notes for possible fixes:
* A note to remove the shadowed type parameter with a corresponding fix-it.
* A note to rename the shadowed type parameter.

**Comment by jumhyn-duolingo** [comment]
Is there ever a legitimate case for this shadowing? I.e., do we need a silencing mechanism here, or would it be fine to always require a rename?

**Comment by airspeedswift** [comment]
I can only think of bad reasons e.g. coming up with different letters or names for the type parameters is annoying

**Comment by hborla** [comment]
> Is there ever a legitimate case for this shadowing?

I have never seen one. There are other issues with shadowing too; for example, shadowed type parameters are busted in Swift interfaces because there's no way to qualify a reference to the outer type parameter in case it shows up in the shadowed scope, e.g. when printing fully qualified nested types with shadowed generic parameters:

```swift
struct Outer<T: P> {
  struct Inner<T> {
    func f() -> Inner<T> {}
  }
}
``` 

The fully qualified result of `f` is `Outer<T>.Inner<T>`, but in that context, the first `T` is wrong because it references the shadowed `T` without any conformance requirement, resulting in a bogus error when a module from its Swift interface.

**Comment by dfperry5** [comment]
Has anyone taken this on? Or is it OK if I give it a shot?

**Comment by hborla** [comment]
@dfperry5 go for it!

**Comment by dfperry5** [comment]
I've been moving slow - but planning on diving into this this week!
