### ISSUE TITLE
Unable compile swift-5.7.1-release on m1 macbook pro

### ISSUE THREAD

**Issue by badguy123** [apple/swift#62824]
### Description
I want compile swift-5.7.1-release on my m1 ,but there are many error
> Xcode: Version 14.0 (14A309)
> OS: 12.6

My command:
`utils/update-checkout --clone --tag swift-5.7.1-RELEASE`

and

`SKIP_XCODE_VERSION_CHECK=1 utils/build-script --skip-build-benchmarks  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)"  --sccache --release --swift-disable-dead-stripping`

**output :**
note: skipping Xcode version check
[utils/build-script] NOTE: Using toolchain default
Ensuring the sccache server is running...
+ /usr/local/bin/sccache --show-stats
+ /usr/libexec/PlistBuddy -c 'Print :SupportedTargets:macosx:Archs' /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/SDKSettings.plist
+ mkdir -p /Users/c/Desktop/llvm/swift571/build/Ninja-ReleaseAssert
--- Building earlyswiftdriver ---
+ /Users/c/Desktop/llvm/swift571/swift-driver/Utilities/build-script-helper.py build --package-path /Users/c/Desktop/llvm/swift571/swift-driver --build-path /Users/c/Desktop/llvm/swift571/build/Ninja-ReleaseAssert/earlyswiftdriver-macosx-arm64 --configuration release --toolchain /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr --ninja-bin /usr/local/bin/ninja --cmake-bin /usr/local/bin/cmake --local_compiler_build
Building Swift Driver dependency: llbuild
Building Swift Driver dependency: Swift System
Building Swift Driver dependency: TSC
Building Swift Driver dependency: Argument Parser
Building Swift Driver dependency: Yams
Building Swift Driver for target: arm64-apple-macosx10.15
b'[1/5][ 20%][0.376s] Linking Swift executable bin/swift-help\n[2/5][ 40%][0.994s] Linking Swift shared library lib/libSwiftDriver.dylib\nFAILED: lib/libSwiftDriver.dylib Sources/SwiftDriver/CMakeFiles/SwiftDriver.dir/ExplicitModuleBuilds/ClangVersionedDependencyResolution.swift.o Sources/SwiftDriver/CMakeFiles/SwiftDriver.dir/ExplicitModuleBuilds/ExplicitDependencyBuildPlanner.swift.o
...
dependencies/yams/lib/libCYaml.a && :\nerror: link command failed with exit code 1 (use -v to see invocation)\nld: warning: ignoring file dependencies/yams/lib/libCYaml.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64\nld: warning: ignoring file lib/libCSwiftScan.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64\nUndefined symbols for architecture arm64:\n  "_yaml_document_end_event_initialize", referenced from:\n      _$s4Yams7EmitterC9serialize4nodeyAA4NodeO_tKF in libYams.a(Emitter.swift.o)\n  "_yaml_document_start_event_initialize", referenced from:\n      _$s4Yams7EmitterC9serialize4nodeyAA4NodeO_tKF in libYams.a(Emitter.swift.o)\n  "_yaml_emitter_delete", referenced from:\n      _$s4Yams7EmitterCfd in libYams.a(Emitter.swift.o)\n      _$s4Yams7EmitterCfD in libYams.a(Emitter.swift.o)\n  "_yaml_emitter_emit", referenced from:\n      _$s4Yams7EmitterC4openyyKF in libYams.a(Emitter.swift.o)\n      _$s4Yams7EmitterC9serialize4nodeyAA4NodeO_tKF in libYams.a(Emitter.swift.o)\n      _$s4Yams7EmitterC5closeyyKF in libYams.a(Emitter.swift.o)\n      _$s4Yams7EmitterC15serializeScalar33_ED6AA6759560A6062E809BF7E6589292LLyyAA4NodeO0D0VKF in libYams.a(Emitter.swift.o)\n      _$s4Yams7EmitterC17serializeSequence33_ED6AA6759560A6062E809BF7E6589292LLyyAA4NodeO0D0VKF in libYams.a(Emitter.swift.o)\n      _$s4Yams7EmitterC16serializeMapping33_ED6AA6759560A6062E809BF7E6589292LLyyAA4NodeO0D0VKF in libYams.a(Emitter.swift.o)\n  "_yaml_emitter_initialize", referenced from:\n      _$s4Yams7EmitterC9canonical6indent5width12allowUnicode9lineBreak13explicitStart0J3End7version8sortKeys13sequenceStyle07mappingQ0ACSb_S2iSbAC04LineI0OS2bSi5major_Si5minortSgSbAA4NodeO8SequenceV0Q0OAU7MappingVAXOtcfc in libYams.a(Emitter.swift.o)\n  "_yaml_emitter_set_break",
...
ERROR: command terminated with a non-zero exit status 1, aborting

**It seems that yams problem, so i modify the cmakelists.txt, add CMAKE_OSX_ARCHITECTURES:**
`set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64")`

**recompile still error**
...
-- Build files have been written to: /Users/c/Desktop/llvm/swift571/build/Ninja-ReleaseAssert/swift-macosx-arm64
+ popd
~/Desktop/llvm/swift571/swift-swift-5.7.1-RELEASE
+ /usr/local/bin/cmake --build /Users/c/Desktop/llvm/swift571/build/Ninja-ReleaseAssert/swift-macosx-arm64 -- -j10 all swift-test-stdlib-macosx-arm64
ninja: error: 'stdlib/swift-test-stdlib-macosx-x86_64', needed by 'stdlib/CMakeFiles/swift-test-stdlib', missing and no known rule to make it
ERROR: command terminated with a non-zero exit status 1, aborting

**How can i compile swift5.7.1 on my m1 mavbook pro ? Thanks.**

**Comment by buttaface** [comment]
There is currently no (public?) macOS arm64 CI, so there may be problems like this. Don't set `CMAKE_OSX_ARCHITECTURES`, that should be automatically detected.

That said, presumably you're setting the one in `swift/CMakeLists.txt`, which should have no effect on your first build error when building earlyswiftdriver, so there's something wrong either with your build or description of it. Try `rm -rf build/Ninja-ReleaseAssert` and start over with no modifications to the source: can you reproduce the first error? Because the modification you tried should have had no effect on the earlyswiftdriver.

**Comment by badguy123** [comment]
@buttaface  swift-5.7.1-release only support xcode12.3-13.3, so i need set SKIP_XCODE_VERSION_CHECK=1, 

```
error: using unsupported Xcode version:

Xcode 14.0
Build version 14A309

Install one of:
12.3 (12C33)
12.4 (12D4e)
12.5 (12E262)
13.0 beta (13A5154h)
13.0 beta 4 (13A5201i)
13.0 (13A233)
13.1 RC 1 (13A1030d)
13.2 beta (13C5066c)
13.2.1 (13C100)
13.3 (13E113)
Or set 'SKIP_XCODE_VERSION_CHECK=1' in the environment
```

if i no modifications to the source ,the first error is yams: 
>  building for macOS-arm64 but attempting to link with file built for macOS-x86_64

and

> Undefined symbols for architecture arm64:\n "_yaml_document_end_event_initialize", referenced from:\n _$s4Yams7EmitterC9serialize4nodeyAA4NodeO_tKF in libYams.a(Emitter.swift.o)
...

**I didn't change the source code the first time, seems "$(uname -m)" is Invalid for yams, so i add CMAKE_OSX_ARCHITECTURES to yams CMakeLists.txt, but still error**

**Comment by buttaface** [comment]
OK, I misunderstood, makes sense if you modified the Yams CMake configuration instead.

First off, update to the 5.7.2 patch release, which will have more fixes. Second, clean out the build directory again and add the `--verbose` flag to your `build-script` command, which will tell you exactly how CMake is being configured for Yams: maybe there was some mistake in [how the early Swift driver was doing so back then](https://github.com/apple/swift-driver/blob/swift-5.7.1-RELEASE/Utilities/build-script-helper.py#L520).

**Comment by badguy123** [comment]
Ok, I will try it

**Comment by badguy123** [comment]
@buttaface I download swift 5.7.3 and compile ,but the mistakes are the same, i find `dependencies/yams/lib/libCYaml.a`

```
➜  lib lipo -info ./libYams.a
Non-fat file: ./libYams.a is architecture: arm64
➜  lib lipo -info ./libCYaml.a
Non-fat file: ./libCYaml.a is architecture: x86_64
```
is `libCYaml.a building for macOS-arm64 but attempting to link with file built for macOS-x86_64` ?,how to fix it ?,add `set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64")` to yams CMakeLists.txt it seems that not work.

**Comment by buttaface** [comment]
Since one Swift static archive is being built correctly for arm64 and only the other C static archive is being built incorrectly for x86_64, my guess is that you have some other x86_64-centric clang installed that the CMake config is automatically picking up. Do you have another brew clang set up in x86_64 emulation mode or something?

That's why I said to run the build-script in verbose mode, to get info like what clang it's picking up or running. Unless you post that verbose output here, we can't figure it out.

**Comment by badguy123** [comment]
@buttaface You are great! 👍  finally i successfully compiled swift, very thanks.
build-script use `/usr/local/bin/cmake`, but is x86_64 arch, i have reconnected the symbol, i use a dual architecture cmake,it works ❤️ ❤️ ❤️
