### ISSUE TITLE
Void-returning @differentiable function crashes compiler

### ISSUE THREAD

**Issue by hamishknight** [apple/swift#62923]
The following crashes in SILGen:

```swift
import _Differentiation

func foo(_ fn: @differentiable(reverse) (Float) -> Void) {}
```

**Comment by asl** [comment]
So, the reason here is `Void` (aka empty tuple) type is assumed to be differentiable with tangent space being empty tuple as well.

Looks like we'd need to additionally check and disallow void result type if there are no inouts.

Tagging @rxwei @dan-zheng  @BradLarson

**Comment by rxwei** [comment]
Yeah that sounds about right. @asl

**Comment by asl** [comment]
@rxwei Thanks for cross-checking! It tried to imagine other corner cases related to `Void` but failed to find any so far :)
