### ISSUE TITLE
SceneKit feature addition 

### ISSUE THREAD

**Issue by VSofficial** [apple/swift#62941]
**Motivation**

SceneKit is a project with less focus within Swift, improvements in it will enhance game development within Xcode. I guess apple themself consider evolution of SceneKit as private efforts 

**Solution**

Taking inspiration from third party open-source frameworks of game development and considering improvements

**Alternatives considered**

Since it's a fresh request for the SceneKit, have to make a document within this thread with [ what's provided in it, what's missing in it, what features are useful to game developers, how much Metal and SceneKit development is different or same]

**Comment by LucianoPAlmeida** [comment]
Hi,
Looks like this a feature request to a specific Apple framework, and not an issue related to a component of the open source toolchain (compiler, stdlib, lldb, SourceKit etc.). Bug reports or feedback for Apple closed source frameworks can be reported through [feedbackassistant.apple.com](https://feedbackassistant.apple.com/).

**Comment by VSofficial** [comment]
Does Libraries of Swift not exclusively opensource? Like SceneKit, SwiftUI are greater part of swift development
