### ISSUE TITLE
Missing authorization header in nightly version. Tag: swift-DEVELOPMENT-SNAPSHOT-2023-01-08-a

### ISSUE THREAD

**Issue by dorsJfrog** [apple/swift#62942]
**Description**
Resolve package is not working. Followed after requests and found missing 'authorization' header on nightly version.
compared between swift version 5.7.2 which is latest version to Swift version 5.8-dev (LLVM d0e30b7f831ad7b, Swift f72816e547e3a9f)
Tag: swift-DEVELOPMENT-SNAPSHOT-2023-01-08-a

**Latest release resolve the package successfully and the request headers are:**
```
accept : application/vnd.swift.registry.v1+json
accept-encoding : deflate, gzip, br, zstd
accept-language : en
authorization : Basic xxxxxxxxxxx
connection : keep-alive
host : 10.1.23.25:55019
user-agent : SwiftPackageManager/5.7.1
```
This is the curl that the client is sending:
```
curl '<my-regisrty-url>/test/swifttest'  -H 'accept-encoding: deflate, gzip, br, zstd' -H 'user-agent: SwiftPackageManager/5.7.1' -H 'authorization: Basic xxxxxxxxxxx' -H 'accept: application/vnd.swift.registry.v1+json' -H 'connection: keep-alive' -H 'accept-language: en' --compressed --insecure
```

**in nightly version the Request headers are:**
```
accept : application/vnd.swift.registry.v1+json
accept-encoding : deflate, gzip, br, zstd
accept-language : en
connection : keep-alive
host : 10.1.23.25:55019
user-agent : SwiftPackageManager/5.8.0-dev 
```
This is the curl that the client is sending:
```
curl '<my-regisrty-url>/test/swifttest' -H 'accept-encoding: deflate, gzip, br, zstd' -H 'accept: application/vnd.swift.registry.v1+json' -H 'user-agent: SwiftPackageManager/5.8.0-dev' -H 'connection: keep-alive' -H 'accept-language: en' --compressed --insecure
```
You can see that the different is that in nightly version the **authorization** header is missing.
Also the command is stuck and doesn't return error

**Steps to reproduce**
1. Create swift package
2. Set package configuration to point on registry.
3. Set Package.swift to resolve some package from registry.
4. Run 'swift package resolve' to resolve packages.

**Expected behavior**
I expect the resolve package to work.
Also if it doesn't work, to return some error and to not stack.

**Comment by yim-lee** [comment]
@dorsJfrog Please file dependency resolution related issue in https://github.com/apple/swift-package-manager

The issue you are experiencing is likely due to [SE-0378](https://github.com/apple/swift-evolution/blob/main/proposals/0378-package-registry-auth.md) and the recently [merged implementation](https://github.com/apple/swift-package-manager/pull/6027).

Please try updating the user-level `registries.json` by adding the `authentication` block. For example:

```json
{
  "registries": {
    "[default]": {
      "url": "https://example-registry.com"
    }
  },
  "authentication": {
    "example-registry.com": {
      "type": "basic"
    }
  },
  "version": 1
}
```

**Comment by yim-lee** [comment]
cc @tomerd

**Comment by dorsJfrog** [comment]
@yim-lee 
Thanks for replying!

**Comment by AnthonyLatsis** [comment]
Duplicate of https://github.com/apple/swift-package-manager/issues/4358

@yim-lee Can you transfer this issue to the package manager repo?

**Comment by yim-lee** [comment]
I do not have write access to this repo. @shahmishal @tomerd Can either of you do the transfer please?
