### ISSUE TITLE
UnsafeRawBufferPointer is missing the fast _custom* Collection customisation points [was: ByteBufferView.contains doesn't produce optimal code]

### ISSUE THREAD

**Issue by weissi** [apple/swift#62964]
### Expected behavior

`ByteBufferView.contains` uses the special `Collection` hook to find elements quickly. Given that we only have bytes in there, this should be very quick.

### Actual behavior

This Swift code

```
            if self.buffer.readableBytesView.contains(UInt8(ascii: "B")) {
                which = UInt8(ascii: "B")
            }
```

produces the following core loop

```
0x0000000100105a50         cbz        x9, loc_100105acc

0x0000000100105a54         cbz        x8, loc_100105a80

0x0000000100105a58         ldrb       w10, [x9], #0x1
0x0000000100105a5c         sub        x8, x8, #0x1
0x0000000100105a60         cmp        w10, #0x42
0x0000000100105a64         b.ne       loc_100105a50
```

<img width="536" alt="Screenshot 2023-01-10 at 4 55 09 pm" src="https://user-images.githubusercontent.com/624238/211613832-846d8698-cc1f-45dd-90be-df024fb855f3.png">

So we see 3 conditional jumps:

1. `cbz        x9, loc_100105acc` (branch on zero for x9)
2. `cbz        x8, loc_100105a80` (branch on zero for x8)
3. `b.ne       loc_100105a50` (compare if we found the `B` (0x42))

Ideally this would be vectorised a bit but even without, we shouldn't have 2 `cbz`s, one is enough.

**Comment by weissi** [comment]
Thanks @Lukasa, I'm transferring this from `apple/swift-nio` to `apple/swift` because it's a stdlib issue.

**Comment by tbkka** [comment]
CC: @lorentey

**Comment by tbkka** [comment]
CC: @glessard
