### ISSUE TITLE
Build error: use of undeclared identifier 'RECORD_SOURCE_FILE_CONTENTS'

### ISSUE THREAD

**Issue by valeriyvan** [apple/swift#63028]
**Description**

Build fails with errors:

```
/Users/***/swift/lib/Frontend/SerializedDiagnosticConsumer.cpp:253:20: error: use of undeclared identifier 'RECORD_SOURCE_FILE_CONTENTS'
  Record.push_back(RECORD_SOURCE_FILE_CONTENTS);
                   ^
/Users/***/swift/lib/Frontend/SerializedDiagnosticConsumer.cpp:274:26: error: use of undeclared identifier 'RECORD_SOURCE_FILE_CONTENTS'
      State->Abbrevs.get(RECORD_SOURCE_FILE_CONTENTS),
                         ^
/Users/***/swift/lib/Frontend/SerializedDiagnosticConsumer.cpp:451:7: error: use of undeclared identifier 'RECORD_SOURCE_FILE_CONTENTS'
      RECORD_SOURCE_FILE_CONTENTS, "SourceFileContents", Stream, Record);
      ^
/Users/***/swift/lib/Frontend/SerializedDiagnosticConsumer.cpp:510:31: error: use of undeclared identifier 'RECORD_SOURCE_FILE_CONTENTS'
  Abbrev->Add(BitCodeAbbrevOp(RECORD_SOURCE_FILE_CONTENTS));
                              ^
/Users/***/swift/lib/Frontend/SerializedDiagnosticConsumer.cpp:515:15: error: use of undeclared identifier 'RECORD_SOURCE_FILE_CONTENTS'
  Abbrevs.set(RECORD_SOURCE_FILE_CONTENTS,
              ^
5 errors generated.
```

**Steps to reproduce**

clone with `utils/update-checkout --clone-with-ssh`

build with `utils/build-script --skip-build-benchmarks \
  --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "$(uname -m)" \
  --sccache --release-debuginfo --swift-disable-dead-stripping --bootstrapping=off`

**Expected behavior**

Expect build succeed.

**Environment**
- Swift compiler version info 
```
swiftc -version                            
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```
- Xcode version info 
```
xcodebuild -version
Xcode 14.2
Build version 14C18
```
- Deployment target: arm64-apple-macosx13.0

**Comment by valeriyvan** [comment]
cc: @DougGregor

**Comment by kateinoigakukun** [comment]
@valeriyvan I had the same build failure before. Please ensure that your llvm-project has bd7ca1394fe05d35aeda5996949452aaf6e7779a commit. If not, run `utils/update-checkout` again to fetch the latest LLVM changes :)

**Comment by valeriyvan** [comment]
I have ran `utils/update-checkout` multiple times with no effect. But indeed the problem was with `llvm-project` repo. I have deleted it completely, then run `utils/update-checkout` again which fetched `llvm-project`. After this build runs as expected.
