### ISSUE TITLE
Unexpected `"cannot assign to property: 'self' is immutable"` error in extension of `AnyObject`-constrained protocol

### ISSUE THREAD

**Issue by calda** [apple/swift#63112]
**Description**

Mutating method on extension of `AnyObject`-constrained protocol results in unexpected `"cannot assign to property: 'self' is immutable"` error.

**Steps to reproduce**

Attempt to build the following code in Swift 5.7 ([playground](https://swiftfiddle.com/6bfgfh4eyvbubfyxwr7odryqw4)):

```swift
class MyClass: MyProtocol {
  var property: String = ""
}

protocol ProtocolSettable {
  var property: String { get set }
}

protocol MyProtocol: AnyObject, ProtocolSettable {

}

extension MyProtocol {
  func updateProperty() {
    // 🛑 "cannot assign to property: 'self' is immutable"
    property = "test"
  }
}
```

It fails to compile with this error:

```
/main.swift:15:5: error: cannot assign to property: 'self' is immutable
    property = "test"
```

**Expected behavior**

Since `MyProtocol` is guaranteed to be a class, I expect this to compile.

**Comment by LucianoPAlmeida** [comment]
This is indeed a bug, interesting that `protocol ProtocolSettable: AnyObject` (we can even remove AnyObject ) makes it works. My guess is that is assuming `ProtocolSettable` as base for property.

Simplified a bit
```swift
protocol P {
  var a: String { get set }
}
protocol P1: P {}

extension P {
  func mut() {
    a = "test" // error: cannot assign to property: 'self' is immutable
  }
}
```

**Comment by AnthonyLatsis** [comment]
@LucianoPAlmeida I think the compiler is correct to complain about your example. The setter of a protocol requirement is considered mutating by default.

**Comment by AnthonyLatsis** [comment]
I agree this error makes no sense for a class-constrained `Self` though.

**Comment by LucianoPAlmeida** [comment]
> @LucianoPAlmeida I think the compiler is correct to complain about your example. As in the case of a `struct`, the setter of a protocol or protocol extension member is considered `mutating` by default.

Ah yeah, I simplified incorrectly. Just fixed

**Comment by jasonbobier** [comment]
Has there been any movement on this? I just ran into it.

**Comment by ktoso** [comment]
I don't think there was any movement here recently.
This would need a small swift evolution proposal, but implementation wise it's not much -- distributed actors actually do this in a sneaky way by omitting the check preventing normal language from doing this. So it would be quite nice to open up this ability in general.

See: 
-  https://github.com/apple/swift/pull/38998 -- how distributed does this
- https://forums.swift.org/t/allow-self-x-in-class-convenience-initializers/15924

Adding radar to track though rdar://82264746

**Comment by jasonbobier** [comment]
Thanks! This really seems more like a bug than a feature since the reference does allow mutation.

**Comment by Hanh-hub** [comment]
add AnyObject in the protocol will fix the bug
After I add AnyObject it complied. 
protocol ErrorHandling: AnyObject {
    var errorMessage: String { get set }
    var showError: Bool { get set }
    func handleError(_ error: Error)
}

extension ErrorHandling {
    func handleError(_ error: Error) {
        if let error = error as? LocalizedError {
            errorMessage = error.errorDescription ?? "An unexpected error occurred."
        } else {
            errorMessage = error.localizedDescription
        }
        showError = true
    }
}

**Comment by slavapestov** [comment]
This behaves correctly. Consider the following implementation:

```swift
protocol P {
  init(x: Int)
  var property: Int { get set }
}

extension P {
  var property: Int {
    get { return 3 }
    set { self = Self(x: newValue) }
  }
}

protocol Q: P, AnyObject {}

class C: Q {
  let x: Int

  required init(x: Int) {
    self.x = x
  }
}

extension Q {
  func f() {
    self.property = 10
  }
}

let c = C(x: 0)
c.f() // this would actually replace `c` with a new instance, hence it's rejected
print(c.x) // this should print 10
```

If you want to avoid this, either make the base protocol AnyObject-constrained, or declare a nonmutating setter requirement:

```
var property: Int { get nonmutating set }
```

This will prevent the setter from being implemented by replacing `self`.

@ktoso If distributed actors relies on this, then it's incorrect. It should also use a nonmutating setter.
