### ISSUE TITLE
TaskGroups `waitForAll` changed behaviour in recent 5.8 toolchains

### ISSUE THREAD

**Issue by FranzBusch** [apple/swift#63147]
**Description**
With recent 5.8 toolchains `waitForAll` does not re throw the first observed error anymore it rather just silently returns.

**Steps to reproduce**
The following code behaves different in 5.7 and recent 5.8 snapshots

```swift
@main
struct Foo {
    static func main() async throws {
        do {
            try await withThrowingTaskGroup(of: Void.self) { group in
                group.addTask {
                    throw CancellationError()
                }

                group.addTask {}

                do {
                    try await group.waitForAll()
                } catch {
                    print("Got error", error)
                    throw error
                }
            }
        } catch {
            print(error)
        }
    }
}

// 5.7 prints
Got error CancellationError()
CancellationError()
Program ended with exit code: 0

// 5.8 Dev snapshot 2023-01-19 prints
Program ended with exit code: 0
```

**Expected behavior**
The behaviour shouldn't have changed.

**Environment**
- Swift compiler version: Dev snapshot 2023-01-19

rdar://104507347

**Comment by ktoso** [comment]
Hmmm thanks for the report -- we have a double bug here actually!

This was implemented wrong before:

```
   /// Wait for all of the group's remaining tasks to complete.
  @_alwaysEmitIntoClient
  public mutating func waitForAll() async throws {
    while let _ = try await next() { }
  }
```

so I 'fixed' it, by delegating to same impl as discarding task group, but with a flag... that didn't quite do the right thing -- the bug you observed.

BUT. We actually should instead fix the impl to keep the promise about _wait until all have finished_ AND throw the first error, as a discarding task group does (and the "throw first" is also the existing semantics -- but it was missing the wait all here).

I'll submit a fix to have it corrected from both wrong versions of this.
