### ISSUE TITLE
Cannot modify actor property from `withCheckedContinuation` closure when using subscript

### ISSUE THREAD

**Issue by vincentisambart** [apple/swift#63156]
**Description**

In an actor's isolated methods, modifying one of the actor's properties (for example a `Dictionary`) from a closure passed to `withCheckedContinuation` works fine when modifying using a mutating method but gives a compiler error when using `subscript`.

**Steps to reproduce**

In a closure passed to `withCheckedContinuation` in an actor's isolated method, you can modify one of the actor's properties without compiler error. For example the following code compiles fine.

```swift
actor BuildsFine {
    private var container: [Int: CheckedContinuation<Void, Never>] = [:]
    func wait() async {
        await withCheckedContinuation { continuation in
            container.updateValue(continuation, forKey: 1)
        }
    }
}
```

However, the compiler won't let you do the modification when using `subscript` instead, as in the following code.

```swift
actor ShouldBuildFineButDoesNot {
    private var container: [Int: CheckedContinuation<Void, Never>] = [:]
    func wait() async {
        await withCheckedContinuation { continuation in
            container[1] = continuation
        }
    }
}
```

```
test.swift:5:13: error: actor-isolated property 'container' cannot be passed 'inout' to 'async' function call
            container[1] = continuation
            ^
test.swift:2:17: note: property declared here
    private var container: [Int: CheckedContinuation<Void, Never>] = [:]
                ^
```

Asking [on the Swift forums](https://forums.swift.org/t/modifying-actor-property-in-closure-passed-to-withcheckedcontinuation/62678) I was told that whatever the correct one is, either both or none should give a compiler error, so I filed this issue (my understanding is that both building without error is the correct behavior).

**Expected behavior**

I'm expecting the following code modifying the property to build without error, as happens when using `updateValue()`.

```swift
actor ShouldBuildFineButDoesNot {
    private var container: [Int: CheckedContinuation<Void, Never>] = [:]
    func wait() async {
        await withCheckedContinuation { continuation in
            container[1] = continuation
        }
    }
}
```

**Environment**
- swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
- Xcode 14.2 - Build version 14C18
- Deployment target: macOS 13.0

**Comment by hborla** [comment]
I believe this is fixed with https://github.com/apple/swift/pull/69126
