### ISSUE TITLE
Using key path literals as functions defeats @MainActor checks

### ISSUE THREAD

**Issue by ole** [apple/swift#63189]
**Description**

Using a key path literal as a function argument circumvents the compiler's global actor checks.

As described in [Hobbyist Software, Five ways to break Swift Concurrency (2022-11-10](https://blog.hobbyistsoftware.com/2022/11/five-ways-to-break-swift-concurrency/) and briefly discussed in https://forums.swift.org/t/suggestion-runtime-warnings-in-debug-builds-if-mainactor-methods-vars-are-called-from-background-threads/61537/11

**Steps to reproduce**

A reproducible example is in the blog post linked above. Here's another reduced one:

```swift
struct S {
    @MainActor var mainActorIsolated: Int {
        return 0
    }
}

func nonIsolated() {
    let array = [S()]

    // Correct diagnostic
    // error: Main actor-isolated property 'mainActorIsolated' can not be referenced from a non-isolated context
    let mapped1 = array.map { $0.mainActorIsolated }
    
    // No error! Should not compile!
    let mapped2 = array.map(\.mainActorIsolated)
}
```

The line `let mapped2 = array.map(\.mainActorIsolated)` compiles without warnings in Swift 5.7.2, but it shouldn't. If you run this with `-enable-actor-data-race-checks`, you get the correct runtime diagnostic (data race detected).

**Expected behavior**

The line `let mapped2 = array.map(\.mainActorIsolated)` should not compile.

**Environment**

- macOS 13.1
- swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51) Target: arm64-apple-macosx13.0
- Xcode 14.2 Build version 14C18
- Deployment target: macOS 13.1

**Additional info**

This bug seems to be specific to global actor checks. It also happens with custom global actors, not just with `@MainActor`. But you get a correct compiler error when you try to access a "normal" actor property in this way ("Cannot form key path to actor-isolated property").

**Comment by hborla** [comment]
This was fixed by https://github.com/apple/swift/pull/70329

```
warning: cannot form key path to main actor-isolated property 'mainActorIsolated'; this is an error in Swift 6
    let mapped2 = array.map(\.mainActorIsolated)
                              ^
```
