### ISSUE TITLE
Code coverage reports a line as being covered when it isn't.

### ISSUE THREAD

**Issue by jasonbobier** [apple/swift#63194]
**Description**
With code coverage, lines that aren’t executed after a throw still have their hit count incremented.

**Steps to reproduce**
1. Open the sample project
2. Run testExample() unit test
3. Notice in Throws.swift that the commented line shows 3 hits instead of 1

**Expected behavior**
The commented line should show 1 hit

**Environment**
- Swift compiler version info: swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0

- Xcode version info: Version 14.2 (14C18)
- Deployment target: macOS 13.1

Also reported as: FB7656633

[CoverageBug.zip](https://github.com/apple/swift/files/10492831/CoverageBug.zip)

**Comment by hamishknight** [comment]
This is a known issue, unfortunately. Code coverage currently does not take error handling control flow into account.

**Comment by jasonbobier** [comment]
Yow... that's pretty tough for those of us that use try/catch a lot.

**Comment by jasonbobier** [comment]
This still exists in Xcode Version 15.0 beta (15A5160n).

**Comment by jasonbobier** [comment]
This still exists in Xcode Version 15.0.1 (15A507)
