### ISSUE TITLE
AutoDiff produces SIL that cannot be read back

### ISSUE THREAD

**Issue by asl** [apple/swift#63234]
This is a spin-off from https://github.com/apple/swift/issues/63207 to track the underlying issue. Currently autodiff produces SIL that cannot be parsed back. The reason is internal types that are never serialized as they are created in the artificial module.

Example SIL file is attached. Trying to parse it yields:
```
playground.sil:108:17: error: cannot find type '_AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0' in scope
  %14 = struct $_AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0 (%10 : $@callee_guaranteed (@inout F<Double, Double>) -> S<Double, Double>) // user: %16
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
playground.sil:117:136: error: cannot find type '_AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0' in scope
sil private @$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tFTJpSpSr : $@convention(thin) (F<Double, Double>, @owned _AD__$s10playground5testAyyF1aL_5input10PlayGround1FVyS2dGAE1SVyS2dG_tF_bb0__PB__src_0_wrt_0) -> S<Double, Double> {
                                                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

[playground.sil.txt](https://github.com/apple/swift/files/10509937/playground.sil.txt)

Tagging @BradLarson @rxwei @dan-zheng

**Comment by rxwei** [comment]
The synthesized type decls are not in the primary source file but a synthesized file unit. That might be where the problem lies.

**Comment by asl** [comment]
Yes, exactly. They are not produced in SIL, not exposed in the modules / libraries. Was there any particular case why they are there?

**Comment by rxwei** [comment]
I responded to #63207 on this topic.  However, it might be worth trying to fix the problem by printing decls in the synthesized file units when printing SIL.

**Comment by asl** [comment]
@rxwei Yes. I'm having a patch for SIL emission :) Though, it won't solve #63207 as these types are not available from e.g. modules.

**Comment by rxwei** [comment]
Yeah, pretty sure we are running into the same problems as macros here.

**Comment by asl** [comment]
@rxwei It turns out that `_AD_`* types are non-resilent (`@frozen` is always added), but at the same time might be internal therefore generated SIL does not pass verifier :)
