### ISSUE TITLE
UIDeviceOrientationDidChangeNotification's call point did changed

### ISSUE THREAD

**Issue by ipf-shkim** [apple/swift#63230]
**Description**

UIDeviceOrientationDidChangeNotification's call point did changed 
when I updated iPad's version to iPadOS 16 from iPadOS 14.3

**Steps to reproduce**
- iPadOS 14
    - UIDeviceOrientationDidChangeNotification call after change the orientation

- iPadOS 16
    - UIDeviceOrientationDidChangeNotification call right before the orientation change

**Expected behavior**
as the notification's name is UIDeviceOrientation**DidChange**Notification, I expect the call point should be after change the orientation

**Comment by LucianoPAlmeida** [comment]
Hi,
Looks like this an issue of a specific Apple framework, and not an issue related to a component of the open source toolchain (compiler, stdlib, lldb, SourceKit etc.). Bug reports or feedback for Apple closed source frameworks can be reported through [feedbackassistant.apple.com](https://feedbackassistant.apple.com/).
