### ISSUE TITLE
Windows toolchain - swiftToCxx directory missing 

### ISSUE THREAD

**Issue by litewrap** [apple/swift#63446]
**Description**
 swiftToCxx directory is missing  in the Swift Windows toolchain

**Steps to reproduce**

```
Directory: C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\lib\swift


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          2/3/2023   9:09 AM                migrator
d-----          2/3/2023   9:09 AM                pm

```

**Expected behavior**

\usr\lib\swift must include the swiftToCxx directory  and the content include the following header files:
_SwiftCxxInteroperability.h
_SwiftStdlibCxxOverlay.h

**Comment by AnthonyLatsis** [comment]
Please include the Swift version.

**Comment by hyp** [comment]
@compnerd do you by any chance know why `/usr/lib/swift` doesn't include a lot of things on Windows?

**Comment by compnerd** [comment]
@hyp the answer is two folds:
1. Separation between toolchain and SDK.

 The content in the toolchain should be target agnostic.

2. People add things without testing on windows.

There is an explicit list of things that are packaged for distribution.  That lives in the installer sources at [sdk-amd64](https://github.com/apple/swift-installer-scripts/blob/main/platforms/Windows/sdk-amd64.wxs) and [runtime-amd64](https://github.com/apple/swift-installer-scripts/blob/main/platforms/Windows/runtime-amd64.wxs) for X64, with variants for X86, ARM64, and ARMv7.

**Comment by litewrap** [comment]
> 

All Swift versions, including the 5.8 and latest snapshot

**Comment by hyp** [comment]
@compnerd let me know if you'll be able to look at this. I will assign it to you for now, but feel free to send it back to me if you think you won't have bandwidth.
