### ISSUE TITLE
Conflicting arguments to generic parameter 'Content' ('<<hole>>' vs. '<<hole>>' vs. '<<hole>>' …

### ISSUE THREAD

**Issue by JetForMe** [apple/swift#63450]
**Description**

I get a set of these errors with the attached project:

```
…/Exorcist/Exorcist/ContentView.swift:21:3 Conflicting arguments to generic parameter 'Content' ('<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>')

…/Exorcist/Exorcist/ContentView.swift:32:4 Conflicting arguments to generic parameter 'Columns' ('<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>')

…/Exorcist/Exorcist/ContentView.swift:139:4 Conflicting arguments to generic parameter 'Self' ('VStack<<<hole>>>' vs. 'VStack<<<hole>>>' vs. 'VStack<<<hole>>>' vs. 'VStack<<<hole>>>' vs. 'VStack<<<hole>>>' vs. 'VStack<<<hole>>>' vs. 'VStack<<<hole>>>' vs. 'VStack<<<hole>>>')

…/Exorcist/Exorcist/ContentView.swift:139:4 Conflicting arguments to generic parameter 'M' ('<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>' vs. '<<hole>>')
```

**Steps to reproduce**

Build the attached project with Xcode 14.2 and Swift 5.8 development snapshot 2023-02-01.

**Expected behavior**

Expected useful diagnostics.

**Environment**

$ /Library/Developer/Toolchains/swift-5.8-DEVELOPMENT-SNAPSHOT-2023-02-01-a.xctoolchain/usr/bin/swiftc -version
Apple Swift version 5.8-dev (LLVM 44d4f9d4b49845f, Swift 74ab40be0d09183)
Target: arm64-apple-macosx13.0

$ xcodebuild -version
Xcode 14.2
Build version 14C18

- Deployment target: macOS 13.1

[Exorcist holes.zip](https://github.com/apple/swift/files/10660471/Exorcist.holes.zip)

**Comment by tkafka** [comment]
Just ran into this in a simple view using SwiftUI Chart - the same code as here was previously inlined inside another view, where it worked fine, but once I extracted the chart, I can't get rid of the `<<hole>>` compiler errors.

Xcode Version 14.3 (14E222b), Swift 5.8, no special compile flags.

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/876717/233950493-435cd729-0bc4-409d-b717-d2c13c50eb2f.png">

**Comment by xedin** [comment]
Actual diagnostic here is `Cannot convert value of type 'BoolComparator' to expected argument type 'KeyPathComparator<ProcessFile>'`
