### ISSUE TITLE
Incorrect SIMD operation results: simd_orient returns 0 for some inputs where it shouldn't

### ISSUE THREAD

**Issue by kunitsyn** [apple/swift#63571]
**Description**
simd_orient returns 0 where it shouldn't, on swift 5.7.1.

With three non-aligned points a, b & c on the XZ plane, represented as 3D double-precision SIMD vectors, and a point p = (0, -10, 0) which is clearly outside of the XZ plane, simd_orient returns 0.

**Steps to reproduce**
```
% swift repl
Welcome to Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51).
Type :help for assistance.
  1> import simd
  2> let a = simd_double3(1, 0, 0); let b = simd_double3(0, 0, -1); let c = simd_double3(-1, 0, 1)
a: simd_double3 = (1.000000e+00, 0.000000e+00, 0.000000e+00)
b: simd_double3 = (0.000000e+00, 0.000000e+00, -1.000000e+00)
c: simd_double3 = (-1.000000e+00, 0.000000e+00, 1.000000e+00)
  3> let p = simd_double3(0, -10, 0)
p: simd_double3 = (0.000000e+00, -1.000000e+01, 0.000000e+00)
  4> simd_dot(c - p, simd_cross(a - p, b - p))
$R0: Double = 30
  5> simd_orient(a, b, c, p)
$R1: Double = 0
```

This happens on macos Darwin 22.2.0, Intel i5-1038NG7 CPU. In the comment to simd_orient declaration, it says that _"Positively oriented" is equivalent to the vectors (a-d, b-d, c-d) following the "right hand rule", or to the dot product of c-d with the the cross product of a-d and b-d being positive._ Repeating this exact calculation, `simd_dot(c - p, simd_cross(a - p, b - p))`, correctly gives a positive answer, but simd_orient does not.

**Expected behavior**
simd_orient returns something positive with these inputs.

**Environment**
- Swift compiler version info: `swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0`
- Deployment target: macos Darwin 22.2.0, Intel i5-1038NG7 CPU

**Comment by JanWillemBrands** [comment]
I can confirm that Playgrounds gives the same result. However, if you change to simd_float3 both expressions return the same result.

`import simd

let a = simd_float3( 1.0,  0.0,  0.0)
let b = simd_float3( 0.0,  0.0, -1.0)
let c = simd_float3(-1.0,  0.0,  1.0)

let p = simd_float3( 0.0, -1.0,  0.0)

print(simd_dot(c - p, simd_cross(a - p, b - p)))
print(simd_orient(a, b, c, p))
`

**Comment by xedin** [comment]
cc @stephentyrone

**Comment by stephentyrone** [comment]
`simd_orient` isn't provided by Swift, rather by the <simd/simd.h> headers in the SDK, and needs to be tracked via Feedback Assistant.

**Comment by JanWillemBrands** [comment]
simd_orient gives different results for Float and Double in a trivial example...

```
import simd

let af = simd_float3(1, 0, 0)
let bf = simd_float3(0, 1, 0)
let cf = simd_float3(0, 0, 1)
let df = simd_float3(5, 5, 5)

print(simd_orient(af, bf, cf, df)) // prints -14.0

let ad = simd_double3(1, 0, 0)
let bd = simd_double3(0, 1, 0)
let cd = simd_double3(0, 0, 1)
let dd = simd_double3(5, 5, 5)

print(simd_orient(ad, bd, cd, dd)) // prints 1.0

```

**Comment by JanWillemBrands** [comment]
Copied into a Feedback assistant report (@kunitsyn I hope you don't mind?)

https://feedbackassistant.apple.com/feedback/12015022

**Comment by stephentyrone** [comment]
This is a bug in the simd/geometry.h header, which you can workaround as follows:
```
import simd

func simd_orient_workaround(
  _ a: simd_double3,
  _ b: simd_double3,
  _ c: simd_double3,
  _ d: simd_double3
) -> Double {
  let buf = simd_double4x3(a,b,c,d)
  return withUnsafePointer(to: buf) {
    $0.withMemoryRebound(to: Double.self, capacity: 16) {
      _simd_orient_pd3($0)
    }
  }
}
```

**Comment by stephentyrone** [comment]
The simd.h bug is fixed in the macOS 14 / iOS 17 / etc SDKs. It's purely a header change, so simply recompiling with the new SDKs will result in code that runs correctly on older OSes as well.
