### ISSUE TITLE
[Collect Data] Windows pull request failure unrelated to the changes

### ISSUE THREAD

**Issue by shahmishal** [apple/swift#63596]
This issue will be used to collect information about the Windows platform testing. Please add the information here if you see any failures on your pull request unrelated to the changes.

**Comment by Rajveer100** [comment]
Well, in my recent PR #63567 the smoke-tests passed for macOS and Linux platform, while failing for the windows platform, maybe this info might be helpful!

**Comment by shahmishal** [comment]
> Well, in my recent PR #63567 the smoke-tests passed for macOS and Linux platform, while failing for the windows platform, maybe this info might be helpful!

Thanks @Rajveer100 
```
Failed Tests (10):
  Swift(windows-x86_64) :: DebugInfo/alloc_stack_arg.swift
  Swift(windows-x86_64) :: DebugInfo/archetype.swift
  Swift(windows-x86_64) :: DebugInfo/inlined-generics.swift
  Swift(windows-x86_64) :: IRGen/closure.swift
  Swift(windows-x86_64) :: IRGen/generic_tuples.swift
  Swift(windows-x86_64) :: IRGen/opaque_result_type_debug.swift
  Swift(windows-x86_64) :: IRGen/struct_resilience.swift
  Swift(windows-x86_64) :: IRGen/synthesized_conformance.swift
  Swift(windows-x86_64) :: SILGen/protocol_with_superclass.swift
  Swift(windows-x86_64) :: SILGen/protocol_with_superclass_where_clause.swift
```

cc: @compnerd

**Comment by Rajveer100** [comment]
#63574

**Comment by shahmishal** [comment]
> #63574

Test failures: 
```
Failed Tests (4):
  Swift(windows-x86_64) :: DebugInfo/dynamic_layout.swift
  Swift(windows-x86_64) :: IRGen/big_types_corner_cases.swift
  Swift(windows-x86_64) :: IRGen/closure.swift
  Swift(windows-x86_64) :: SILGen/vtable_thunks_reabstraction.swift
```

**Comment by compnerd** [comment]
The original PR that introduced it actually did fail on Windows, we would've caught it then.

**Comment by ktoso** [comment]
This isn't about windows but about two PRs "racing" and thus ending up with broken main:

- https://github.com/apple/swift/pull/66119 added a test that checked a diagnostic
- And at the same time this commit was landed: https://github.com/apple/swift/commit/47206732f590d416da154a702524a86bf8f3494d

CI tested those independently and both passed.

Once they got merged into main, the changed diagnostic from (2) caused the new test in (1) to fail on a typo.

This was resolved in: https://github.com/apple/swift/pull/66138

Technically merge queues prevent such issues, but would add even more potential wait time to merge changes.

Some "middle ground" would be amazing to find but I don't think something automated exists for this yet.

**Comment by shahmishal** [comment]
This can be closed now. The swift repo now requires Windows testing before merging PR.
