### ISSUE TITLE
Unable to use -Xfrontend -debug-constraints

### ISSUE THREAD

**Issue by Jomy10** [apple/swift#63709]
**Description**

When using swift test or swift build and passing the option, swift gives an error: Missing value -c <configuration>

**Steps to reproduce**

```
✗ swift test -c debug -Xfrontend -debug-constraints
error: Missing value for '-c <configuration>'
Help:  -c <configuration>  Build with configuration
Usage: swift test <options>
  See 'test -help' for more information.
```

**Expected behavior**

run with the command

**Environment**
- Swift compiler version info 
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0

- Xcode version info 
- Deployment target: 
Xcode 14.2
Build version 14C18

**Comment by hamishknight** [comment]
I believe you have to do `swift test -c debug -Xswiftc -Xfrontend -Xswiftc -debug-constraints` in order to tell SwiftPM to pass the `-Xfrontend` arguments to the Swift driver.

**Comment by hamishknight** [comment]
Closing, feel free to reopen if the above does not work for you.
