### ISSUE TITLE
can't show diagnostics for multi view 

### ISSUE THREAD

**Issue by sambhaskins** [apple/swift#63721]
import SwiftUI

@main
struct MW_ExampleApp: App {
    let persistanceController = PersistenceController.shared

    var body: some Scene {
        WindowGroup {
            ContentView()
                .environment(\.managedObjectContext,
                              persistanceController.container.viewContext)
        }
        
        WindowGroup("Example", for: Example.ID.self) { $exampleID in
            if let exampleID {
                let example = try? persistanceController.container.viewContext.fetch(
                    Example.fetchRequest(forID: exampleID)
                ).first {
                    DetailView(example: example)
                        .environment(\.managedObjectContext, persistanceController.container.viewContext)
                }
            } else {
                Text("No Example Found")
                    .foregroundColor(.secondary)
            }
        }
    }
}

**Comment by sambhaskins** [comment]
posted previously

**Comment by AnthonyLatsis** [comment]
> posted previously

@sambhaskins Do you have a link?
