### ISSUE TITLE
Unicode.Scalar.Properties.isEmoji returns false for Unicode 15 emoji

### ISSUE THREAD

**Issue by samhenrigold** [apple/swift#63754]
**Description**

**Steps to reproduce**
```swift
let scalars: [Unicode.Scalar] = ["😎", "🩵", "💙", "🪼", "$", "A"]
for s in scalars {
    print(s, "-->", s.properties.isEmoji)
}
```

**Expected behavior**
The [isEmoji](https://developer.apple.com/documentation/swift/unicode/scalar/properties-swift.struct/isemoji) properties of Unicode 15.0 emoji (in this case, the teal heart and jellyfish) should return true. Instead, they return false.

<img width="703" alt="Screenshot 2023-02-17 at 1 34 11 PM" src="https://user-images.githubusercontent.com/49251320/219753683-53b7dfc2-ac57-4d86-a87f-6c34e847af26.png">

**Environment**
- Swift compiler version info
```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```
- Xcode version info:
```
Xcode 14.2
Build version 14C18
```
- Playgrounds version info used in this test: `Version 4.2.1 (1726.28)`
- Deployment target: iOS 16.4 DP1

**Comment by tbkka** [comment]
CC: @Azoy

**Comment by Azoy** [comment]
The stdlib hasn't been updated to support Unicode 15's data.

**Comment by jonghyun-kim** [comment]
Xcode 14.3 RC2 (Swift 5.8) still returns false.

> The stdlib hasn't been updated to support Unicode 15's data.

Is there any update or plan?
