### ISSUE TITLE
Disambiguation of function ref using coercion to non-matching type produces unhelpful error

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#63834]
```swift
func foo(int: Int, string: String) {}
func foo(int: Int, string: Bool) {}

let a = foo(int:string:) as (Int, Int) -> Void // error: type of expression is ambiguous without more context
```

We ought to point out the mismatch and show the candidates, similar to how the ambiguity is handled in the absence of a coercion.

**Comment by LucianoPAlmeida** [comment]
It looks like `AllowFunctionTypeMismatch::diagnoseForAmbiguity` just don't know how to handle `CoerceExpr` as source of ambiguity.

**Comment by LucianoPAlmeida** [comment]
Actually it simply don't handle ambiguity for `function argument` it only does for `ApplyArgToParam`.

**Comment by AnthonyLatsis** [comment]
Reopening for these cases:

```swift
let _ = foo(int:string:) as (Int) -> Void
let _ = foo(int:string:) as Int
```

**Comment by LucianoPAlmeida** [comment]
Thank you.
