### ISSUE TITLE
Ambiguous expansion of macro `SWIFT_ENUM` in generated headers

### ISSUE THREAD

**Issue by devioustree** [apple/swift#63837]
When using frameworks compiled with pre-5.8 compilers it can be trivial to have conflicting definitions of the `SWIFT_ENUM` macro in the generated Swift header. I believe this is a similar issue to https://github.com/apple/swift/pull/63338

My guess is that the new `ClangMacros.def` introduced in https://github.com/apple/swift/pull/59072 has accidentally omitted a space: https://github.com/apple/swift/blob/75f53a9b1923e891985734ea6ac6f4cae4d91603/include/swift/PrintAsClang/ClangMacros.def#L178

`_name: _type` used to be `_name : _type` (note the space before `:`)

**Comment by AnthonyLatsis** [comment]
cc @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
Nice catch! I've opened https://github.com/apple/swift/pull/63902 to fix this.
