### ISSUE TITLE
[Source compatibility suite] swift compiler hanging when attempting to build swift-nio in release

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#63846]
**Describe the bug**
swift-nio is failing to build its release configuration and timing out during the build process. The build appears to be hanging when attempting to compile

From the build logs you can see 
```
swift-frontend -frontend -c /source-compat/project_cache/swift-nio/Tests/NIOPosixTests/AcceptBackoffHandlerTest+XCTest.swift <ARGS>
```
Note that this timeout only occurs when building the tests for 5.0 in release config (not debug). This only occurs on main and not on 5.8 or 5.7

**Expected behavior**
Expecting the project to build correctly

**Environment**
```
Apple Swift version 5.9-dev (LLVM 726983520b3cae8, Swift ecb864c1598e81a)
Target: arm64-apple-macosx13.0
```
https://ci.swift.org/job/swift-main-source-compat-suite/341/artifact/swift-source-compat-suite/XFAIL_swift-nio_5.0_BuildSwiftPackage.log

**Comment by eeckstein** [comment]
Fixed: https://github.com/apple/swift/pull/63890
