### ISSUE TITLE
Swift allows & calls `@available(*, unavailable) deinit`

### ISSUE THREAD

**Issue by weissi** [apple/swift#63854]
For classes, Swift should probably make `@available(*, unavailable) deinit { ... }` illegal syntax because it's impossible to uphold the unavailability.

For `@noncopyable` types, I think it [should make the user call a `consume`ing and `forget`ful function](https://forums.swift.org/t/se-0390-noncopyable-structs-and-enums/63258/58).

```swift
class Foo {
    @available(*, unavailable)
    deinit {
        print("Isn't it ironic.")
    }
}

func foo() {
    _ = Foo()
}

foo()
```

```bash
$ swift test.swift
Isn't it ironic.
```

rdar://106409012

**Comment by tshortli** [comment]
Addressed for 5.9 with #64844. Note that the PR does not address `@noncopyable`, types, though since I think the proposed behavior would need to be incorporated into an accepted Swift evolution proposal before it is implemented.
