### ISSUE TITLE
[5.8] Collection literal inferred as Any when function type argument is Any

### ISSUE THREAD

**Issue by keith** [apple/swift#63982]
With this code:

```swift
func asJSON(_ a: [String: Any]) { print(a) }

asJSON([
    "a": [
        "b": "c",
        "d": [
            "e": "f",
        ],
    ],
])
```

Swift 5.8 from Xcode 14.3 beta 2 warns that the collection is inferred as Any:

```
foo.swift:4:10: warning: heterogeneous collection literal could only be inferred to '[String : Any]'; add explicit type annotation if this is intentional
    "a": [
         ^
```

In this case I'm surprised to see this warning since the function it's being passed to explicitly takes `[String: Any]`, so it being inferred as Any seems expected and I don't think needs a warning

**Comment by xedin** [comment]
The type of dictionary is inferred to `[String: Any]` before it's converted to the parameter type. The warning has been made more aggressive by https://github.com/apple/swift/pull/60323. cc @AnthonyLatsis

**Comment by xedin** [comment]
I'm not sure how I feel about this myself, on one side this seems reasonable because collection is indeed heterogeneous but on other other hand we could consider parameter to be an explicit type annotation as well.

**Comment by keith** [comment]
> on other other hand we could consider parameter to be an explicit type annotation as well

yea that's what I was expecting

**Comment by AnthonyLatsis** [comment]
After looking at https://github.com/apple/swift/commit/1d21b4e, which introduced this diagnostic, I think I might have misinterpreted its purpose. I agree with Keith that whether the literal has a defaulted type should not matter if it gets type-erased anyway. On its turn, an erasure expression implies the presence of an explicit type annotation somewhere.

**Comment by xedin** [comment]
Should the changes be reverted then, @AnthonyLatsis?

**Comment by AnthonyLatsis** [comment]
Yes, I will see if there is anything useful worth keeping while there’s still time until 5.9 converges. Do you want me to fully revert it for upcoming 5.8 patches now?

**Comment by xedin** [comment]
Let’s revert on main and 5.9.

**Comment by AnthonyLatsis** [comment]
@lattner Do you remember why you added this diagnostic (https://github.com/apple/swift/commit/1d21b4e)? Is it to avoid semantic source breaks caused by potential improvements to the type join?

**Comment by lattner** [comment]
no recollection sorry
