### ISSUE TITLE
Improve out-of-place binding diagnostic to reflect whether the binding was written as 'var' or 'let'

### ISSUE THREAD

**Issue by hamishknight** [apple/swift#63993]
For the following:

```swift
func bar(_ x: Int) -> Int { x }
if case bar(let x) = 0 {} // error: 'var' binding pattern cannot appear in an expression
```

we should say `'let' binding pattern` instead of `'var' binding pattern`.

**Comment by Rajveer100** [comment]
Regarding the binding pattern type, should we probably add a new case for `let` according to this file's `switch`:

```
switch (kind) {
  case PatternKind::Paren:
    return OS << "parenthesized pattern";
  case PatternKind::Tuple:
    return OS << "tuple pattern";
  case PatternKind::Named:
    return OS << "pattern variable binding";
  case PatternKind::Any:
    return OS << "'_' pattern";
  case PatternKind::Typed:
    return OS << "pattern type annotation";
  case PatternKind::Is:
    return OS << "prefix 'is' pattern";
  case PatternKind::Expr:
    return OS << "expression pattern";
  case PatternKind::Binding:
    return OS << "'var' binding pattern"; <-----------
  case PatternKind::EnumElement:
    return OS << "enum case matching pattern";
  case PatternKind::OptionalSome:
    return OS << "optional .Some matching pattern";
  case PatternKind::Bool:
    return OS << "bool matching pattern";
  }
```

**Comment by Rajveer100** [comment]
@hamishknight

**Comment by hamishknight** [comment]
Yes, in that `case` you should be able to cast to `BindingPattern` and check for `isLet()` to customize it

**Comment by Rajveer100** [comment]
Hey @hamishknight,

What would be the right/safe way to `cast`?

**Comment by Rajveer100** [comment]
Thanks @hamishknight, while I grind through, would ask further queries!

**Comment by Rajveer100** [comment]
@hamishknight
Which file would be the right place to add this new `enum`?

**Comment by hamishknight** [comment]
Yes, Pattern.h is good

**Comment by Rajveer100** [comment]
What would be the `Underlying Type` for the `enum`, would it possibly be `uint8_t`?

**Comment by Rajveer100** [comment]
Also, the function prototype would be this way I suppose:

```
DescriptivePatternKind getDescriptiveKind(PatternKind kind) const { }
```

**Comment by hamishknight** [comment]
Yes, `uint8_t` is good, and the prototype would be:

```
DescriptivePatternKind getDescriptiveKind() const;
```

As this will be a method on `Pattern`, it doesn't need the extra parameter, you can call `getKind()` instead, following the same pattern as `Decl::getDescriptiveKind`.

**Comment by Rajveer100** [comment]
Following error in 'DiagnosticsSema.def':

`use of undeclared identifier 'DescriptivePatternKind'`

**Comment by hamishknight** [comment]
> Following error in 'DiagnosticsSema.def':
>
> `use of undeclared identifier 'DescriptivePatternKind'`

This should be fixed once you update `DiagnosticArgument` to use `DescriptivePatternKind` instead of `PatternKind` (in particular, it needs forward declaring in DiagnosticEngine.h).


> Also, is this switch case fine?

Yes, that's great, and yes you'll need to fill in the rest of the cases. You can define a `TRIVIAL_KIND` macro similar to `Decl::getDescriptiveKind` to make it easier to map the rest of the cases if you want.

**Comment by Rajveer100** [comment]
Sounds great!

**Comment by Rajveer100** [comment]
I am opened a pull request, so you can appropriately review the changes!
