### ISSUE TITLE
stdlib gets rebuild multiple times in `build-script -r -T` configuration

### ISSUE THREAD

**Issue by xedin** [apple/swift#64007]
I see stdlib related warnings while building:

 - The compiler itself
 - Under `--- Building tests for swift ---`
 - Under `--- Running tests for swift --- --- check-swift-only_early_swiftdriver-macosx-arm64 ---`
 - Under `--- check-swift-validation-macosx-arm64 ---`

Happens with recent `main` branch.

**Comment by xedin** [comment]
cc @shahmishal

**Comment by shahmishal** [comment]
@edymtt Would you be able to look into this issue?

**Comment by justice-adams-apple** [comment]
Couldn't reproduce, agreed with @xedin  to close this, feel free to reopoen if seen again
