### ISSUE TITLE
modern async/await concurrency for CoreData

### ISSUE THREAD

**Issue by smenor** [apple/swift#64183]
**Motivation**
Almost every nontrivial app can benefit from an object-oriented database that can synchronise bi-directionally to some external API

CoreData exists and could naturally fill that role but it has several underlying design issues which make it difficult to work with in a modern multi-threaded environment

Developers currently have to manually manage faulting, synchronisation between contexts, and so on.

**Solution**
Passing CoreData managed objects around between contexts should Just Work™ naturally and as expected.

**Alternatives considered**

There are a number of third party ORMs and OO databases and those are fine or we could build something like that in-house ( and have to waste time re-solving the same problems everyone else already had to ) but this is such a basic and fundamental thing that it should be part of the language

If you were being even more ambitious, this could be « make `CoreData` not suck » with nice convenience systems to allow for ORM storage of arbitrary objects with arbitrary queries and a nice / easy to use and painless system for robustly managing migrations and serialisation/de-serialisation

Going a step further, steal the idea behind C#'s LINQ and give developers some semantic sugar to naturally do concurrent database queries locally or remotely with SQL-like commands in code ( that would probably be the most Swift thing to do because the language is a veritable best-of other languages )

**Comment by tshortli** [comment]
Please use https://feedbackassistant.apple.com to file bugs and request enhancements to the frameworks in Apple's SDKs.
