### ISSUE TITLE
Local rename fails if refactoring `if let file` when `file` is not declared

### ISSUE THREAD

**Issue by ahoppen** [apple/swift#64264]
The following new test case fails with `error: value decl ''file'' has no declaration location`. If the variable is renamed to anything but `file`, it works. The same issue happens if the variable is named `line` so I believe the problem here is that `file` is resolving to the `file` macro.

```swift
func test() {
    // RUN: %sourcekitd-test -req=refactoring.rename.local -pos=%(line + 1):12 %s -- %s
    if let file {}
}

```

**Comment by bnbarham** [comment]
https://github.com/apple/swift/pull/64298
