### ISSUE TITLE
(lib/IDE) @_documentation attribute always crashes sourcekit-lsp

### ISSUE THREAD

**Issue by kelvin13** [apple/swift#64309]
using the `@_documentation` attribute always crashes sourcekit-lsp on the 5.8 branch.

```swift
@_documentation(visibility: public)
enum E
{
}
```

both `@_documentation(visibility:)` and `@_documentation(metadata:)` are affected, as well as both quoted and un-quoted metadata forms.

it appears to trip this assertion in [`lib/IDE/SyntaxModel.cpp`](https://github.com/apple/swift/blob/main/lib/IDE/SyntaxModel.cpp#L1346-L1353):

```
sourcekit-lsp: /home/build-user/swift/lib/IDE/SyntaxModel.cpp:1343: auto (anonymous namespace)::ModelASTWalker::handleAttrRanges(ArrayRef<(anonymous namespace)::ModelASTWalker::DeclAttributeAndRange>)::(anonymous class)::operator()(swift::SourceRange) const: Assertion `(TokenNodes.empty() || SM.isBeforeInBuffer(AttrRange.End, TokenNodes.front().Range.getStart())) && "AttrRange doesn't align with any TokenNode?"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

this happens on `swift-5.8-DEVELOPMENT-SNAPSHOT-2023-02-23-a`.

```
$ swift --version
Swift version 5.8-dev (LLVM 44d4f9d4b49845f, Swift b9562e1a860ec0b)
Target: x86_64-unknown-linux-gnu
```

**Comment by QuietMisdreavus** [comment]
I opened https://github.com/apple/swift/pull/64326 which fixes a crash, though it's not the same assertion as your message. I'm building a Linux toolchain on that PR; if it succeeds, would you be willing to test it out for me?

**Comment by kelvin13** [comment]
if it is an Amazon Linux 2 toolchain, yes!

**Comment by QuietMisdreavus** [comment]
Looks like Swift CI builds an Ubuntu toolchain on its Linux builder. 😕 Still, the archive is here: https://download.swift.org/tmp/pull-request/64326/384/ubuntu2004/PR-ubuntu2004.tar.gz

**Comment by kelvin13** [comment]
just verified the `@_documentation` attribute is no longer crashing sourcekit-lsp on the 5.8 release. thanks Victoria!
