### ISSUE TITLE
Type-Check Fails to Finish in a Reasonable Time

### ISSUE THREAD

**Issue by thekief** [apple/swift#64333]
I am currently trying to build an iOS app with a toolchain based on the 5.8 branch. 
The app compiled fine with Swift 5.7 but now fails due to the type-checking. 
I extracted following snippet to show case the problem:

```swift
import Combine
import SwiftUI

class LoginViewModel: ObservableObject, LoginDelegate {
    enum State {
        case a
        case b
        case c
        case d
    }
    
    @Published var state: State
    @Published var showAccountActivationView = false
    ... 
```

```swift
import SwiftUI

struct LoginView: View {
    @ObservedObject var viewModel: LoginViewModel
    
    var body: some View {
        Group {
            if viewModel.showAccountActivationView {
                <do some stuff on the viewModel>
            } else if viewModel.state == .a {
                <do some stuff on the viewModel>
            } else if viewModel.state == .b {
                <do some stuff on the viewModel>
            } else if viewModel.state == .c {
                <do some stuff on the viewModel>
            } else if viewModel.state == .d {
                <do some stuff on the viewModel>
            }
        }
    ...
```

If I try to compile the files containing these snippets I get following error:

```
<path>/LoginView.swift:6:25: error: the compiler is unable to type-check this expression in reasonable time; 
try breaking up the expression into distinct sub-expressions
    var body: some View {
```

Removing one of the conditions instructions seems to make it compile fine.
Any ideas what could be possibly causing a regression there?

**Comment by xedin** [comment]
It looks like actual problem is with the expressions inside of `if` conditions because I cannot reproduce it with just `if/else` chain:

```swift

import SwiftUI

struct MyTest : View {
  enum State {
    case a
    case b
    case c
    case d
  }

  var state: State

  var body: some View {
    Group {
      if true {
        EmptyView()
      } else if state == .a {
        EmptyView()
      } else if (state == .b) {
        EmptyView()
      } else if (state == .c) {
        EmptyView()
      } else if (state == .d) {
        EmptyView()
      }
    }
  }
}
```

This type-checks just fine with 5.7 and 5.8.

If you are using operators in the if/else conditions it's possible that there were some new overloads that got added in 5.8 that contribute to slow down.

Any way you can share a complete example? You can use Feedback Assistant to report and attach the project.

**Comment by thekief** [comment]
I will try to provide a minimal viable example as soon as possible.

> It looks like actual problem is with the expressions inside of ...

This was my first guess as well but after removing everything inside it still failed.
At one point I just had the condition as in my initial report and it still failed.

Somehow it seems to be linked solely to the checks.

**Comment by xedin** [comment]
@thekief What happens if you use `switch` instead? Also what 5.8 toolchain are you using?

**Comment by thekief** [comment]
That is some black magic stuff you suggested there.
I moved the enum checks into an `else` and tested them there with a `switch` and it seems to work.
I will run some tests after getting some sleep.

As for the toolchain, I am using the **release/5.8** branch and the current commit I built upon is **c4a0c8e1**

**Comment by xedin** [comment]
I've expected as much because `switch` inside of an else is a separate transformation and it doesn't use `==` which is heavily overloaded. 

Here is a reduction which is much closer to yours:

```
import Combine
import SwiftUI

class MyModel: ObservableObject {
  enum State {
    case a
    case b
    case c
    case d
  }

  @Published var state: State = .a
  @Published var showAccountActivationView = false
}

struct MyTest : View {
  @ObservedObject var viewModel: MyModel

  var body: some View {
    Group {
      if viewModel.showAccountActivationView {
        EmptyView()
      } else if viewModel.state == .a {
        EmptyView()
      } else if viewModel.state == .b {
        EmptyView()
      } else if viewModel.state == .c {
        EmptyView()
      } else if viewModel.state == .d {
        EmptyView()
      }
    }
  }
}
```

I'm also curious whether this reduction type-checks for you on main or not?

**Comment by thekief** [comment]
I will try to build against `main` over the weekend.
Currently we do not have plenty build machines so I can build toolchains only over the weekend.

**Comment by xedin** [comment]
No worries! Regardless I'd suggest you switch to use `switch` where possible that should improve your build type in general.

**Comment by thekief** [comment]
btw, reading throught the documentation I noticed that the underscore is also available in switch tuples:
Would you happen to know if following snippet

```swift
...
switch(viewModel.showAccountActivationView, viewModel.state){
    case (true, _):
        <do stuff>
    case (false, .a):
        <do other stuff>
    ...
```

would be preferable to this snippet?

```swift
...
if viewModel.showAccountActivationView {
    <do stuff>
} else {
    switch( viewModel.state){
    case .a:
        <do more stuff>
    case .b:
        <do other stuff>
    ...
...
```

Atleast from the information provided so far, I would consider it superior as it should not use, atleast I hope so, the overloaded version of `==` .

**Comment by xedin** [comment]
It's up to you, I like the version with if/switch better.

**Comment by xedin** [comment]
@thekief Btw, what version of Xcode are you using with your custom build compiler?

**Comment by thekief** [comment]
I am using following Xcode version with the custom build:

```
Xcode 14.2
Build version 14C18
```

**Comment by xedin** [comment]
It makes sense that I cannot reproduce the problem! SwiftUI shipped with 14.2 doesn't have `buildExpression` yet so it cannot take advantage of all the performance changes compiler introduced in 5.8 (For more details see https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192/9). 

I bet if you did this in your project:

```
extension ViewBuilder {
  public static func buildExpression<T>(_ e: T) -> T { e }
}
```

Your original code would type-check as well, but you should update the Xcode when possible.

**Comment by thekief** [comment]
Thank you for the detailed information. 
I will look into it.

**Comment by santiagoaloi** [comment]
I had a similar situation when having a complex expression with a lot of nested conditions or method call. I thnk  the compiler is struggling to resolve that.

Have you tried simplifying  the expression?...  as you noted. In your case, removing one of the conditionals from the if-else chain seems to resolve the issue.

**Comment by IsaacBreen** [comment]
Same here. My example:

```swift
import SwiftUI

struct X: Identifiable {
    var id: ObjectIdentifier
    let y: String
}

struct ContentView: View {
    var body: some View {
        let xs: [X] = []
        ForEach(xs, id: \.id) { x in
            if false && x.y == "blah" {
                let z = x.y == "blah";
                if false {}
                HStack {
                    Text(x.y)
                }
            }
        }
    }
}
```


But throwing `if false {}`  in there makes it work 🥳

```swift
import SwiftUI

struct X: Identifiable {
    var id: ObjectIdentifier
    let y: String
}

struct ContentView: View {
    var body: some View {
        let xs: [X] = []
        ForEach(xs, id: \.id) { x in
            if false && x.y == "blah" {
                let z = x.y == "blah";
                if false {}
                HStack {
                    Text(x.y)
                }
            }
        }
    }
}
```


Just to be safe, I'm going to add `if false {}` between every line in my code from now on.

I've been Swift user for all of three hours, so I'm assuming this isn't just a rare or esoteric bug. Or perhaps I'm just really unlucky! 🥲

**Comment by thekief** [comment]
The workaround with the switch solved it for me. Sadly I haven't been able to restest it with a proper Swift 5.8 setup.

If there is anything related to this, feel free to re-open it.

**Comment by peacedudes** [comment]
The root cause of this may reproducible with:
      let x = 0 + 0 + 0 + 0 + "0" 

expression failed to parse:
error: repl.swift:1:10: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
 let x = 0 + 0 + 0 + 0 + "0" 
         ^~~~~~~~~~~~~~~~~~~
 

- - - bonus details - - -
It's curious to start with 0 + "0" and see reasonable compiler warnings become progressively less helpful as another term is added. The errors I'm seeing in latest playground seem surprisingly more helpful than I remember, and go like this.
(1)
expression failed to parse:
error: Untitled Page.xcplaygroundpage:4:11: error: binary operator '+' cannot be applied to operands of type 'Int' and 'String'
let x = 0 + "0"
        ~ ^ ~~~

Untitled Page.xcplaygroundpage:4:11: note: overloads for '+' exist with these partially matching parameter lists: (Int, Int), (String, String)
let x = 0 + "0"
          ^

(2, 3)
expression failed to parse:
error: Untitled Page.xcplaygroundpage:4:15: error: operator function '+' requires that 'RunLoop.SchedulerTimeType.Stride' conform to 'Sequence'
let x = 0 + 0 + "0"
              ^

Swift.RangeReplaceableCollection:3:35: note: where 'Other' = 'RunLoop.SchedulerTimeType.Stride'
    @inlinable public static func + <Other>(lhs: Other, rhs: Self) -> Self where Other : Sequence, Self.Element == Other.Element
                                  ^

(4)
xpression failed to parse:
error: Untitled Page.xcplaygroundpage:4:9: error: the compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
let x = 0 + 0 + 0 + 0 + "0"
        ^~~~~~~~~~~~~~~~~~~

This is easy to try and fun to play around with.  I think the one who fixes this age old grief should feel very pleased with what they've done.
