### ISSUE TITLE
The build fails because TransferRepresentationBuilder cannot infer type 

### ISSUE THREAD

**Issue by miku1958** [apple/swift#64345]
**Description**
TransferRepresentationBuilder does not work.

**Steps to reproduce**
This code can't be built
```swift
import CoreTransferable

@available(macOS 13.0, *)
struct Proxy: Transferable {
    static var transferRepresentation: some TransferRepresentation {
        FileRepresentation(exportedContentType: .mpeg4Movie) { (item: Proxy) -> SentTransferredFile in
            let fileURL = URL(filePath: "")
            return SentTransferredFile(fileURL)
        }.visibility(.all)
    }
}
```
These some error if I add ".visibility(.all)"
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/24806909/224875029-303efe8b-2abd-47ed-a083-f8b39e5e0ccd.png">

I have to change the above code to this so the complier can work
```swift
import CoreTransferable

@available(macOS 13.0, *)
struct Proxy: Transferable {
    static var transferRepresentation: some TransferRepresentation {
        let fileRepresentation = FileRepresentation(exportedContentType: .mpeg4Movie) { (item: Proxy) -> SentTransferredFile in
            let fileURL = URL(filePath: "")
            return SentTransferredFile(fileURL)
        }

        return fileRepresentation.visibility(.all)
    }
}
```
**Expected behavior**
TransferRepresentationBuilder can work

**Environment**
- Swift compiler version info 5.7.2
- Xcode version info Xcode 14.2
- Deployment target: macOS 13.2.1

**Comment by AnthonyLatsis** [comment]
This repository accepts issues with the programming language itself or the standard library. `CoreTransferable` is a closed-source framework, so this issue is best reported using Apple‘s feedback assistant.
