### ISSUE TITLE
Memory Leak for WKWebView:evaluateJavaScript:completionHandler

### ISSUE THREAD

**Issue by paulayurie** [apple/swift#64857]
Memory leaks (Malloc 32 Bytes x 4) when calling WKWebView.evaluateJavaScript passing a completion handler. 

Code example: 

```Swift
extension ViewController: WKNavigationDelegate {
    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        webView.evaluateJavaScript("document.documentElement.scrollHeight", completionHandler: { (height, error) in
            self.webViewHeightConstraint?.constant = height as! CGFloat
        })
    }
}

```
On the memory graph it is possible to see that it is on JavaScriptCore.

Tested on iOS 16.2 and 16.0.1.

![Screenshot 2023-02-23 at 10 56 37](https://user-images.githubusercontent.com/16544129/229486215-438f079e-b6de-4a18-b7e1-a6684c8149ac.png)

[<rdar://problem/105986674>](<rdar://problem/105986674>)

**Comment by AnthonyLatsis** [comment]
The screenshot suggests this is an issue with a proprietary C++ framework, not the Swift compiler or standard library. Please report it using the feedback assistant.
