### ISSUE TITLE
Runtime crash in AnyKeyPath.debugDescription when using @dynamicMemberLookup

### ISSUE THREAD

**Issue by mbrandonw** [apple/swift#64865]
**Description**

The following code defines a wrapper struct around a value and uses `@dynamicMemberLookup` to expose access to the underlying value:

```swift
@dynamicMemberLookup
struct Wrapper<Value> {
  let value: Value
  subscript<OtherValue>(dynamicMember keyPath: KeyPath<Value, OtherValue>) -> OtherValue {
    self.value[keyPath: keyPath]
  }
}
```

In Swift 5.8, if we try to access a key path's `debugDescription` on `Wrapper` that goes through the dynamic member, we get a runtime crash:

```swift
let kp = \Wrapper<String>.count
print(kp.debugDescription)  // 🛑 Bad access
```

**Steps to reproduce**

Run the above code in any Swift environment.

**Expected behavior**

It should print out something like `"\Wrapper<String>.count"`.

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
- Xcode 14.3, Build version 14E222b
- Deployment target: iOS 16.4

**Comment by mbrandonw** [comment]
Hi @benpious, I saw you pitched and implemented [SE-0369](https://github.com/apple/swift-evolution/blob/a7942ebc63da3f0da6fc54eac25d5d4f49125a96/proposals/0369-add-customdebugdescription-conformance-to-anykeypath.md) so thought you might be interested in this edge case that we ran into.

**Comment by benpious** [comment]
Thanks for tagging me @mbrandonw. I'll try to find time to look at this. 

Idk if this is the forum for it, but I'm curious what folks think the correct behavior is here. I don't have context on why this happens, but I suspect that the result of the most basic fix would be that it looks something like this: `\Wrapper<String>.subscript(dynamicMember: KeyPath<String, OtherValue>)`, when the ideal would probably be to have it look like this: `\Wrapper<String>.count` or `\Wrapper<String>.count (@dynamicMemberLookup)`. `\Wrapper<String>.count` is more true to the original SE: "we should try to emit roughly what it looked like in the source file" but it may be useful to the reader to indicate that it's sourced through dynamic member lookup, assume that is technically possible to achieve. 

Based on the fact that this is crashing we may have to settle for something suboptimal, in the worst case it might just be a memory address, which would probably be just as useless to you as a crash b/c it wouldn't be deterministic and test output from your library would be flaky as a result.

**Comment by mbrandonw** [comment]
Hi @benpious, yeah we personally would love to see the key path printed as `\Wrapper<String>.count` with no dynamic member annotation since the user of some library code may not even be aware of such a detail.

**Comment by benpious** [comment]
I looked into this, and it doesn't crash on the latest main, thanks to a [commit](https://github.com/apple/swift/commit/91dcf8d2987d2ab81accd3b090500e5f42c1a7da) from @mikeash. The output is currently `Wrapped<String>.subscript(dynamicMember: <unknown>)`. 

It has nothing to do with dynamicMemberLookup, it turns out, any generic subscript currently causes this to happen. 

I think a good solution to this probably starts with solving the general problem of printing the actual value of the args of the subscript (convert from `\[Int].subscript(Int)` to `\[Int].subscript(0)`, for example) and then a special case that looks for this specific pattern and then stitches the types together.

**Comment by AnthonyLatsis** [comment]
Thanks for pinpointing the fix! Now that the crash is gone, should a new issue be opened to track output improvements?

**Comment by mbrandonw** [comment]
Hi @AnthonyLatsis, just thing, done here https://github.com/apple/swift/issues/65996. I wasn't sure if it should be "feature" or "bug".
