### ISSUE TITLE
`if let` binding of a non-optional doesn't raise a compilation error in result builders

### ISSUE THREAD

**Issue by valentinradu** [apple/swift#65008]
**Description**
Normally, if we bind a non-optional using `if let`, the compiler will protest (i.e. `Initializer for conditional binding must have Optional type, not 'X').
However, when doing the same in a result builder, the compiler is silent.

**Steps to reproduce**

Given the following simple result builder:
```swift
@resultBuilder
struct StringBuilder {
    static func buildBlock(_ components: String...) -> String {
        String(components.joined(separator: ","))
    }
    static func buildOptional(_ component: String?) -> String {
        component ?? ""
    }
}

struct StringWrapper {
    private let _value: String
    init(@StringBuilder _  builder: () -> String) {
        _value = builder()
    }
}
```

Trying to bind a non-optional will compile just fine, possibly leading to confusion and unexpected results:

```swift
let nonOptional: Int = 0
StringWrapper {
    // compiler should complain
    if let nonOptional = nonOptional {
        String(nonOptional)
    }
}
```

**Expected behavior**
The compiler should complain when trying to bind a non-optional in a result builder.

**Environment**
- swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51), Target: arm64-apple-macosx13.0
- Xcode 14.2, Build version 14C18
- N/A

**Comment by keith** [comment]
Can you test with Swift 5.8? We noticed some of these are fixed and warn now

**Comment by xedin** [comment]
Indeed, this has been fixed in 5.8 as outlined by https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192

**Comment by valentinradu** [comment]
Yes, it was fixed 🎉. I've just tested. Sorry for the noise, I haven't found a reference mentioning it.

**Comment by xedin** [comment]
No worries!
