### ISSUE TITLE
Failed to produce diagnostic for expression (adding up tuples)

### ISSUE THREAD

**Issue by SimplyDanny** [apple/swift#65216]
**Description**

Given a file `tuples.swift` with the content

```swift
let a = (1, 2) + (3, 4)
```

the Swift compiler reports

```
tuples:1:16: error: failed to produce diagnostic for expression
let a = (1, 2) + (3, 4)
               ^
```
when running `swift tuples.swift`.

The same error can be seen in Xcode and Swift Playgrounds as well.

**Environment**

- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
  Target: arm64-apple-macosx13.0
- Xcode 14.3
  Build version 14E222b

**Comment by AnthonyLatsis** [comment]
Diagnosed fine on the main branch: `binary operator '+' cannot be applied to two '(Int, Int)' operands`. 

@xedin Any ideas what fixed this? I couldn’t find a regression test.

**Comment by xedin** [comment]
Most likely https://github.com/apple/swift/pull/64143

**Comment by AnthonyLatsis** [comment]
> Most likely #64143

Not that one, I checked. Let’s close it as is.
