### ISSUE TITLE
Crash with thin generic function member

### ISSUE THREAD

**Issue by JackYoustra** [apple/swift#65280]
**Description**
A thin struct with generic input and output types will not compile.

**Steps to reproduce**
```swift
struct Interpose<T, U> {
    let targetFunction: @convention(thin) (T) -> U
}

// works
// struct Interpose {
//     let targetFunction: @convention(thin) () -> ()
// }

let interposeKeychain = Interpose(targetFunction: add)

func add() { }
```
See godbolt of 5.7 (https://gcc.godbolt.org/z/EfxxdqMqd) and nightly (https://gcc.godbolt.org/z/Y6xMMKo8c).

**Expected behavior**
Shouldn't crash. Maybe an error would be acceptable, but it shouldn't crash.

**Environment**
It's on the godbolt swift versions and on xcode 14E222b.

**Comment by AnthonyLatsis** [comment]
Duplicate of #56452
