### ISSUE TITLE
"-disallow-use-new-driver" unnecessarily set

### ISSUE THREAD

**Issue by thekief** [apple/swift#65461]
**Description**

Using the 5.8 release causes issues regarding the driver choice when experimenting with a toolchain build from https://github.com/apple/swift/commit/f9611bc8e745b1b9a98d494236adb6d6c739fe97.

Previous to the release, everything seemed to work in regards to the driver selection. A most noteable detail is that we updated to the newest Xcode version around the same time, potentially being the root cause for this issue.

Trying to build a project with the Github version, yields following error:

``` 
Invalid manifest (compiled with: ["/Library/Developer/Toolchains/swift-LOCAL-2023-03-31-a.xctoolchain/usr/bin/swiftc", "-vfsoverlay", "/var/folders/jh/vhc853k541j16db9k_0klvr40000gn/T/TemporaryDirectory.x5UWZ6/vfs.yaml", "-L", "/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-target", "arm64-apple-macos12.0", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk", "-swift-version", "5", "-I", "/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageCore.framework/Versions/A/Frameworks/SwiftPM.framework/SharedSupport/ManifestAPI", "-sdk", "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk", "-package-description-version", "5.3.0", "-Xfrontend", "-serialize-diagnostics-path", "-Xfrontend", "/Users/test/Library/Caches/org.swift.swiftpm/manifests/ManifestLoading/toast-swift.dia", "/Users/test/Library/Developer/Xcode/DerivedData/Test-bnglvjhsuerwyxamkapehgevsujg/SourcePackages/checkouts/toast-swift/Package.swift", "-disallow-use-new-driver", "-o", "/var/folders/jh/vhc853k541j16db9k_0klvr40000gn/T/TemporaryDirectory.sZSseI/toast-swift-manifest"])
<unknown>:0: warning: legacy driver is now deprecated; consider avoiding specifying '-disallow-use-new-driver'
<unknown>:0: error: unable to execute command: <unknown>
```

**Steps to reproduce**

- build an iOS toolchain based on https://github.com/apple/swift/commit/f9611bc8e745b1b9a98d494236adb6d6c739fe97
- try to compile an iOS project

**Expected behavior**

The build succeeds

**Environment**
- Swift compiler version info: 5.8-f9611bc8
- Xcode version info: 14.3 (14E222b)
- Deployment target: n/a

**Comment by thekief** [comment]
The issue is not further reproducible.

**Comment by dreampiggy** [comment]
Anyone faced this issue on Swift Package Manager and Xcode integration with custom xctoolchain ?
Swift 5.9

![image](https://github.com/apple/swift/assets/6919743/a7b13a3f-16d3-48ac-8911-adff244f75af)

**Comment by thekief** [comment]
I had something similar going on right now with a new version @dreampiggy too. In my case it resolved itself by cleaning the cache/project. You might also want to remove the local dependency cache that can be found here:

- `~/Library/Caches/org.swift.swiftpm`
- `~/Library/Developer/Xcode/DerivedData/<PROJECT>_<ID>`
- `~/Library/Caches/org.swift.swiftpm`

**Comment by dreampiggy** [comment]
Does not help.

You can use the open-source App: https://github.com/Dimillian/IceCubesApp

Run:

```
xcodebuild clean build -scheme IceCubesApp -configuration Release -destination generic/platform=iOS -toolchain my.toolchain.bundle.id
```
```

**Comment by dreampiggy** [comment]
Need I submit a new issue to apple/swift ?

Isn't SwiftPM and Xcodebuild on Apple platform should be inside the compiler compatible test case ?

**Comment by thekief** [comment]
Alright, that makes it a somewhat uncharted territory for me. I also opened this issue https://github.com/apple/swift-driver/issues/1349 where @artemcm made some comments. Maybe he has some insight.

**Comment by krypt-lx** [comment]
I just got this exception warning trying to archive mac os cli app using bazel
