### ISSUE TITLE
Invalid type parameter in getReducedType()

### ISSUE THREAD

**Issue by asl** [apple/swift#65487]
Consider the following patch that switches off derivative function type cache:
```diff
diff --git a/lib/SIL/IR/SILFunctionType.cpp b/lib/SIL/IR/SILFunctionType.cpp
index d361a27f7d9..2b0b5a3aff7 100644
--- a/lib/SIL/IR/SILFunctionType.cpp
+++ b/lib/SIL/IR/SILFunctionType.cpp
@@ -883,7 +883,7 @@ CanSILFunctionType SILFunctionType::getAutoDiffDerivativeFunctionType(
   auto insertion =
       ctx.SILAutoDiffDerivativeFunctions.try_emplace(key, CanSILFunctionType());
   auto &cachedResult = insertion.first->getSecond();
-  if (!insertion.second)
+  if (0 && !insertion.second)
     return cachedResult;

   SILFunctionType *constrainedOriginalFnTy =
```

Then `AutoDiff/SILOptimizer/semantic_member_accessors_sil.swift` fails with:
```
Invalid type parameter in getReducedType()
Original type: τ_0_0.TangentVector
Simplified term: τ_0_0.[Differentiable:TangentVector]
Longest valid prefix: τ_0_0
Prefix type: τ_0_0

Requirement machine for <τ_0_0, τ_0_1>
Rewrite system: {
}
}
Property map: {
}
Conformance paths: {
}
Please submit a bug report (https://swift.org/contributing/#reporting-bugs) and include the crash backtrace.
Stack dump:
```

So it seems that `getReducedType()` behavior somehow changes. I double checked and input types seems to be same on the first and subsequent invocations

**Comment by asl** [comment]
Tagging @slavapestov @BradLarson

**Comment by slavapestov** [comment]
> Requirement machine for <τ_0_0, τ_0_1>

This generic signature does not have a `τ_0_0: Differentiable` requirement, so indeed the type parameter `τ_0_0.TangentVector` is not valid in this generic signature. The bug is upstream. Perhaps there's some kind of problem with the caching logic where generic signatures are getting mixed up?

**Comment by asl** [comment]
Right. Somehow the generic signature might be lost on the subsequent calls.

**Comment by asl** [comment]
@slavapestov Things are a bit more interesting here. Here is bit of SIL in question:
```llvm
  %14 = partial_apply [callee_guaranteed] %13<T>() : $@convention(thin) <τ_0_0 where τ_0_0 : Differentiable> (@inout Generic<τ_0_0>, @in_guaranteed τ_0_0) -> () // user: %15
  %15 = convert_function %14 : $@callee_guaranteed (@inout Generic<T>, @in_guaranteed T) -> () to $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@inout Generic<τ_0_0>, @in_guaranteed τ_0_1) -> () for <T, T> //
user: %16
  %16 = differentiable_function [parameters 0 1] [results 0] %15 : $@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@inout Generic<τ_0_0>, @in_guaranteed τ_0_1) -> () for <T, T> // user: %17
```

And indeed we're trying to calculate derivative type for substituted type:
```
(sil_function_type type=@callee_guaranteed @substituted <τ_0_0, τ_0_1> (@inout Generic<τ_0_0>, @in_guaranteed τ_0_1) -> () for <T, T>
  (input=bound_generic_struct_type decl=null.(file).Generic@/Users/asl/Projects/swift-project/swift/test/AutoDiff/SILOptimizer/semantic_member_accessors_sil.swift:21:8
    (generic_type_param_type depth=0 index=0))
  (input=generic_type_param_type depth=0 index=1)
  (substitution_map generic_signature=<τ_0_0, τ_0_1>
    (substitution τ_0_0 -> T)
    (substitution τ_0_1 -> T))
  (substitution_map generic_signature=<nullptr>))
```

Looks like `getConstrainedAutoDiffOriginalFunctionType` does not know what to do with pattern substitutions and without invocation generic signature is not adding any `Differentiability` constraints at all. However `getTangentParameterConventionForOriginalResult` / `getTangentParameterConvention` seem to use pattern substitutions.

**Comment by asl** [comment]
Ah yes, and things are working with caching enabled because we do not consider pattern substitutions as part of the key.
