### ISSUE TITLE
Actor boundary warning when conforms to a protocol that has non-isolated internal properties of public types

### ISSUE THREAD

**Issue by b1ackturtle** [apple/swift#65493]
**Description**
I am getting warning when I build the following code with `-warn-concurrency` flag.

```swift
@MainActor
protocol MyProtocol {
    nonisolated var value: Value { get }
}

public struct Value {}

struct MyStruct: MyProtocol {
    let value = Value()
}
```

> warning: non-sendable type 'Value' in conformance of main actor-isolated property 'value' to protocol requirement cannot cross actor boundary

**Steps to reproduce**
1. Copy the above code into a file named `test.swift`.
2. Run `swift -warn-concurrency test.swift`.

**Expected behavior**
The code should not produce a warning if it is legal code.

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
- Target: arm64-apple-macosx13.0
- Xcode 14.3, Build version 14E222b 

**Additional context**
When the access modifier of `Value` is internal, I am not getting the warning.

**Comment by hborla** [comment]
This is correct behavior; because `Value` is `public`, the conformance to `Sendable` has to be explicit. The correct fix is to mark `Value` as `Sendable`:

```
@MainActor
protocol MyProtocol {
  nonisolated var value: Value { get }
}

public struct Value: Sendable {}

struct MyStruct: MyProtocol {
  let value = Value()
}
```
