### ISSUE TITLE
Regression of type inference in `@resultBuilder`

### ISSUE THREAD

**Issue by elmetal** [apple/swift#65782]
**Description**
I'm getting an error when building the following code with Swift 5.8.
This error does not occur in Swift 5.7.

```swift
protocol P {}
struct MyP: P { let elements: [any P] }

@resultBuilder struct MyBuilder {
    static func buildBlock(_ components: any P...) -> some P {
        MyP(elements: components)
    }

    static func buildExpression(_ expression: any P) -> P {
        expression
    }

    static func buildEither(first component: any P) -> P {
        component
    }

    static func buildEither(second component: any P) -> P {
        component
    }
}

extension Int: P {}

struct Generic<T: Equatable, Value: P>: P {
    var state: State
    let value: (State) -> Value

    init(state: State,
         @MyBuilder value: @escaping (State) -> Value) {
        self.state = state
        self.value = value
    }

    enum State: Equatable {
        case a(T)
    }
}

func p() -> some P {
    Generic(state: .a(123)) { state in // Type of expression is ambiguous without more context
        switch state {
        case .a:
            MyP(elements: [2])
        }
    }
}
```

**Steps to reproduce**
1. Copy the above code into a file named `reproduce.swift`.
2. Run `swift reproduce.swift`.

**Environment**
- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
- Target: arm64-apple-macosx13.0
- Xcode 14.3, Build version 14E222b

**Comment by xedin** [comment]
There are changes to result builder inference which prohibit some of the patterns that result in exponential behavior in the solver, code in the description is one of the examples where there is a bi-directional inference between body of the result builder and its enclosing context. Please see https://forums.swift.org/t/improved-result-builder-implementation-in-swift-5-8/63192/14 for more details, section "Partially resolved closure parameters used in the result builder body" is of particular interest.
