### ISSUE TITLE
Strideable conformance with ExpressibleByIntegerLiteral results in incorrect range iteration

### ISSUE THREAD

**Issue by mohurwitzmusic** [apple/swift#65846]
When creating a custom Swift type that conforms to both `ExpressibleByIntegerLiteral` and `Strideable`, unexpected behavior occurs when using the range operators to iterate over a sequence of these custom types. 

In the provided code snippet, a `ByteWrapper` struct is defined that conforms to both `ExpressibleByIntegerLiteral` and `Strideable`, and it encapsulates a `UInt8` value. An enumeration `Wrapped` is also created to wrap instances of `ByteWrapper`. When a range from 0 to 15 is mapped to `Wrapped<ByteWrapper>` instances, the expected result is an array with 16 elements.

However, the actual result is an array with only 15 elements. The iteration appears to stop prematurely, not including the last value of the range. This behavior is inconsistent with the standard usage of range operators in Swift, which should include all elements from the start to the end of the range (for half-open range) or through the end of the range (for closed range). 

This issue indicates a potential problem in the interaction between `Strideable` conformance, `ExpressibleByIntegerLiteral`, and range iteration in Swift.

```
import Foundation

public struct ByteWrapper: ExpressibleByIntegerLiteral, Strideable {
    public typealias IntegerLiteralType = Int
    public typealias Stride = Int

    public var value: UInt8

    public init(integerLiteral value: IntegerLiteralType) {
        self.value = UInt8(Swift.min(Swift.max(value, 0), 15))
    }

    public func advanced(by n: Stride) -> ByteWrapper {
        let next = Int(self.value) + n
        return ByteWrapper(integerLiteral: Swift.min(Swift.max(next, 0), 15))
    }

    public func distance(to other: ByteWrapper) -> Stride {
        Int(self.value).distance(to: Int(other.value))
    }
}

enum Wrapped<T> {
    case none
    case value(T)
}

let values: [Wrapped<ByteWrapper>] = (0..<16).map { Wrapped.value($0) }
assert(values.count == 16) // 15
```

The issue seems to be limited to half-open ranges. When the same Strideable type ByteWrapper is used with a closed range, it behaves as expected, correctly generating an array of 16 elements. This leads to the conclusion that the discrepancy lies somewhere in how half-open ranges handle strideable types. Here's an example demonstrating this:

```
let closedRangeValues: [Wrapped<ByteWrapper>] = (0...15).map { Wrapped.value($0) }
assert(closedRangeValues.count == 16) // This assertion passes, demonstrating that closed ranges work as expected.
```

**Comment by AnthonyLatsis** [comment]
Assuming this is the predecessor of #65877, please consider editing your issue if you find better ways to express/demonstrate the problem rather than reporting a new one.

**Comment by AnthonyLatsis** [comment]
Duplicate of #65877
