### ISSUE TITLE
ForwardTrailingClosures is not source compatible with calls to `View.sheet(isPresented:onDismiss:content:)`

### ISSUE THREAD

**Issue by jqsilver** [apple/swift#65921]
**Description**
The Swift proposal "[Forward-scan matching for trailing closures](https://github.com/apple/swift-evolution/blob/main/proposals/0286-forward-scan-trailing-closures.md)" explicitly states that its implementation includes a heuristic that will allow for calls to SwiftUI's `View.sheet` method to continue to compile. 

> For the `View.sheet(isPresented:onDismiss:content:)` API, this means that onDismiss, which has a default argument, will be skipped in the forward match so that the unlabeled trailing closure will match content:, allowing this code to continue to compile correctly.

However, when I enable ForwardTrailingClosures in Swift 5.8, the example call does not continue to compile correctly. 

**Steps to reproduce**
Using Xcode 14.3, I've created a new iOS App project with SwiftUI. [ForwardScanCompatibilityRepro.zip](https://github.com/apple/swift/files/11480742/ForwardScanCompatibilityRepro.zip)
 I modified the `ContentView` to look like this:

```Swift
import SwiftUI

struct ContentView: View {
  @State private var isShowingSheet = false

  var body: some View {
    VStack {
      showButton
        .sheet(isPresented: $isShowingSheet) {
          Text("Hello")
        }
    }.padding()
  }

  var showButton: some View {
    Button("Show Sheet") {
      isShowingSheet.toggle()
    }
  }
}
```

This code compiles and runs just fine, but when I add `-enable-upcoming-feature ForwardTrailingClosures` to "Other Swift Flags" it no longer compiles. The error message states `Missing argument for parameter 'content' in call`. 

If you modify the call to include the `content:` parameter then the code compiles. 

```Swift
        .sheet(isPresented: $isShowingSheet, content: {
          Text("Hello")
        })
```

**Expected behavior**

`sheet(isPresented: $isPresented) { Text("Hello") }` should compile with Swift 5.8 and `-enable-upcoming-feature ForwardTrailingClosures`. 

**Environment**
- Swift version info swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
- Xcode version info Xcode 14.3 Build version 14E222b
- Deployment target: iOS 16.4

**Comment by AnthonyLatsis** [comment]
Shorter example:
```swift
do {
  @State var flag = false

  let _ = Color.black.sheet(isPresented: $flag) {
    Color.black
  }
}
```

cc @DougGregor

**Comment by jqsilver** [comment]
I've created a simpler repro that doesn't rely on SwiftUI:

1. create a new swift package using `swift package init --type=executable`
2. update main.swift:

```
// The Swift Programming Language
// https://docs.swift.org/swift-book

func example(onStart: ((String) -> Void)? = nil, onEnd: (String) -> Void) {
  onStart?("Started")
  onEnd("Ended")
}

example { result in
  print(result)
}
```

3. enable ForwardTrailingClosures in Package.swift
```
// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "ForwardScanRepro2",
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .executableTarget(
            name: "ForwardScanRepro2",
            path: "Sources",
            swiftSettings: [
              .enableUpcomingFeature("ForwardTrailingClosures")
            ]),
    ]
)
```

[ForwardScanRepro2.zip](https://github.com/apple/swift/files/11490297/ForwardScanRepro2.zip)

**Comment by AnthonyLatsis** [comment]
@xedin You may want to note this down. I don’t know how close we are to Swift 6, but it appears the heuristic in question is one of the reasons the proposal got accepted.

**Comment by jqsilver** [comment]
FYI, it looks like this issue still reproduces in 5.10.

**Comment by calda** [comment]
Here's a fix: https://github.com/apple/swift/pull/71709
