### ISSUE TITLE
Swift 5.8 bumps Coverage Mapping version from 5 to 6 without using the corresponding format

### ISSUE THREAD

**Issue by bachand** [apple/swift#65964]
**Description**

Swift 5.8 bumps the coverage mapping version to 6 from version 5 without adding the CWD / compilation directory as the first item of the file list. The LLVM code coverage mapping format [documentation](https://llvm.org/docs/CoverageMappingFormat.html#llvm-ir-representation) explains the difference between versions 5 and 6:

> There is one difference between versions 6 and 5:
>- The first entry in the filename list is the compilation directory. When the filename is relative, the compilation directory is combined with the relative path to get an absolute path. This can reduce size by omitting the duplicate prefix in filenames.

We have confirmed this by parsing the `__LLVM_COV,__llvm_covmap` section of the binary compiled by the Swift 5.8 compiler shipped Xcode 14.3.

We can compare the [Swift IRGen that writes the coverage filenames](https://github.com/apple/swift/blob/release/5.8/lib/IRGen/GenCoverage.cpp#L86-L99) to similar [code in Apple's fork of llvm-project](https://github.com/apple/llvm-project/blob/swift/release/5.8/clang/lib/CodeGen/CoverageMappingGen.cpp#L1680-L1694). The latter code in llvm-project correctly inserts the CWD as the first item in the list (specifically see L1684).

The fact that the filenames are written in the format of version 5 with version 6 specified in the header breaks downstream tools like `llvm-cov` that [parse code coverage data](https://github.com/apple/llvm-project/blob/f0fb631dd1a3a2988b23ba5057cd9106713cd0b4/llvm/lib/ProfileData/Coverage/CoverageMappingReader.cpp#L151-L181), breaking the generation of coverage reports.

We have also confirmed that the Swift 5.7 compiler shipped in Xcode 14.2 encodes version 5, which correctly matches the format of the filenames.

**Steps to reproduce**

1. Download [code_coverage.zip](https://github.com/apple/swift/files/11492915/code_coverage.zip)
2. `cd` into the uncompressed `code_coverage/` directory
3. Run `./build_and_test.sh` and see the error message from `llvm-cov`

<img width="496" alt="Screenshot 2023-05-16 at 4 52 27 PM" src="https://github.com/apple/swift/assets/1791049/8388a97f-ce27-4a13-8cd8-88f7d50cf05e">

In the screenshot above we can see that the first filename (Test.swift) is being interpreted as the CWD and is being prefixed to the second filename (Lib.swift).

**Expected behavior**

`llvm-cov` generates the report with no error message. This can be seen by running the same steps as above with Xcode 14.2.

**Environment**

- Swift compiler version info
```
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
```

- Xcode version info 
```
Xcode 14.3
Build version 14E222b
```

- Deployment target: n/a

cc: @qyang-nj who has been investigating with me

**Comment by AnthonyLatsis** [comment]
cc @hamishknight

**Comment by tbkka** [comment]
CC: @aschwaighofer

**Comment by hamishknight** [comment]
Looks like our format version is automatically set to whatever the latest version LLVM has. We ought to have a static_assert or something to make sure we update the emission when the version gets bumped, to avoid silently breaking things like this. It should be noted that this issue only affects cases where the file name is written as a relative path, which only affects cases where you're using `-coverage-prefix-map`, as otherwise we currently always make the path absolute when writing the coverage data.

**Comment by qyang-nj** [comment]
@hamishknight Thanks for the info. Yes! We found it's [this commit](https://github.com/apple/llvm-project/commit/5fbd1a333aa1a0b70903d036b98ea56c51ae5224#diff-302b7ed5318dca59934a7c8aaadc452fc65f4859685cd9839bdf9a878d390393) bumped the version in LLVM. This commit has been in Swift 5.7 release. However, we didn't see this problem until Swift 5.8 with Xcode 14.3 release.

We built sample code with Swift 5.7.2 compiler came with Xcode 14.2, the CoverageMapping version is 5 (encoded as 4). We also built a swift compiler directly from `swift-5.7.2-RELEASE`  open source, but the version is 6. We're wondering what caused this discrepancy? Do you have any insights? Thanks!

**Comment by hamishknight** [comment]
> We built sample code with Swift 5.7.2 compiler came with Xcode 14.2, the CoverageMapping version is 5 (encoded as 4). We also built a swift compiler directly from swift-5.7.2-RELEASE open source, but the version is 6. We're wondering what caused this discrepancy? Do you have any insights? Thanks!

I can confirm that does indeed appear to be the case. Unfortunately I can't comment on the reason behind the discrepancy, but it is indeed unfortunate.

**Comment by hamishknight** [comment]
This should be fixed in Xcode 15 beta 3

**Comment by qyang-nj** [comment]
Yes. I confirmed it's fixed in Xcode15 beta 3. Thank you!
