### ISSUE TITLE
Error message about converting keypaths is "backward"

### ISSUE THREAD

**Issue by KeithBauerANZ** [apple/swift#65965]
**Description**
Error says 

> key path value type 'ReferenceWritableKeyPath<S, String>' cannot be converted to contextual type 'WritableKeyPath<S, String>'

but it should say

> key path value type 'WritableKeyPath<S, String>' cannot be converted to contextual type 'ReferenceWritableKeyPath<S, String>'

**Steps to reproduce**
```swift
struct S {
    var s: String = ""
}

func go<A, B>(_ keypath: ReferenceWritableKeyPath<A, B>, on: A) {}

var v = S()
go(\.s, on: v)
```

```
swiftc keypath-error.swift
```

**Environment**
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

**Comment by AnthonyLatsis** [comment]
Slightly shorter:
```swift
struct S {
  var s: String
}

func go(_: ReferenceWritableKeyPath<S, String>) {}
go(\.s)
```

Reproduces with Swift 5.9-dev (c1d5118c21d).

**Comment by xedin** [comment]
cc @amritpan

**Comment by arjunivor** [comment]
I'd like to help on this. Any idea where the error message is located? Also, is anyone else working on this?

**Comment by arjunivor** [comment]
Think I found [it](https://github.com/apple/swift/blob/d685c1c67d39360d55738b272f809b757531eafe/include/swift/AST/DiagnosticsSema.def#L671). It wouldn't be as simple as switching %0 and %1 around would it? or would that affect every error of this type? 

note: i'm new to contributing in general, any help would be appreciated.

**Comment by tbkka** [comment]
Hint:  search the code for `expr_smart_keypath_value_covert_to_contextual_type` to see where this message is actually used.

**Comment by arjunivor** [comment]
[CSFix.h](https://github.com/apple/swift/blob/d685c1c67d39360d55738b272f809b757531eafe/include/swift/Sema/CSFix.h#L791-L792) has `Type getFromType() const { return LHS; }
  Type getToType() const { return RHS; }`, switching those (LHS/RHS) around might also result in other problems.

**Comment by AnthonyLatsis** [comment]
> It wouldn't be as simple as switching %0 and %1 around would it

Those are just template string parameters; placeholders, if you will. The error message is "backward" because someone made a mistake and whatever *argument* is designated to the first parameter ought to have been designated to the second, and vice versa.

**Comment by arjunivor** [comment]
> [CSFix.h](https://github.com/apple/swift/blob/d685c1c67d39360d55738b272f809b757531eafe/include/swift/Sema/CSFix.h#L791-L792) has `Type getFromType() const { return LHS; } Type getToType() const { return RHS; }`, switching those (LHS/RHS) around might also result in other problems.

would this suggestion work? for switching the arguments around

**Comment by AnthonyLatsis** [comment]
> [here](https://github.com/apple/swift/blob/d685c1c67d39360d55738b272f809b757531eafe/lib/Sema/CSDiagnostics.cpp#L2484) and [here](https://github.com/apple/swift/blob/d685c1c67d39360d55738b272f809b757531eafe/lib/Sema/CSDiagnostics.cpp#L7403). 

Do we already know which one of these two call sites is responsible for the bad substitution?
