### ISSUE TITLE
`AsyncSequence` does not specify `Element` as primary associated type

### ISSUE THREAD

**Issue by purpleblues** [apple/swift#66097]
**Description**

`AsyncSequence` does not specify `Element` as primary associated type.

**Steps to reproduce**

N/A

**Expected behavior**

`AsyncSequence` protocol specifies `Element` as primary associated type like below.

```Swift
public protocol AsyncSequence<Element> { 
    associatedtype Element where Self.Element == Self.Iterator.Element
}
```

**Environment**

- swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0
- Xcode 14.3
Build version 14E222b

**Comment by AnthonyLatsis** [comment]
@purpleblues Why did you close this?

**Comment by purpleblues** [comment]
I didn't know that this was deferred to a future proposal (https://github.com/apple/swift-evolution/blob/main/proposals/0358-primary-associated-types-in-stdlib.md#alternatives-considered)
