### ISSUE TITLE
git clone --mirror fails

### ISSUE THREAD

**Issue by xiota** [apple/swift#66168]
**Description**

I am unable to clone this repository with `git clone --mirror`.  Upon running the command, I see the following output:
```
Cloning into bare repository 'swift.git'...
```
Followed by no output or network activity for a long time.  Then the following error:
```
error: RPC failed; HTTP 408 curl 18 HTTP/2 stream 7 was reset
fatal: expected 'packfile'
```

`git clone` and `git clone --bare` appear to work as expected.

`git` works as expected on a fork of the repository with the "Copy the main branch only" option unchecked.  (Potential solution, replace repository with a fresh fork.)

**Steps to reproduce**

Run: `git clone --mirror https://github.com/apple/swift.git`

**Expected behavior**

`git` should clone the repository.

Note: Same issue with different repository: https://github.com/apple/llvm-project/issues/6919

**Comment by finagolfin** [comment]
I recently saw a similar issue with pushing a large branch to my Swift fork on github, which was fixed for me by [enlarging git's `http.postBuffer`](https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning), maybe that will work for you too.

**Comment by tbkka** [comment]
This is an issue with `git` and/or Github servers and/or your network connection, not with the swift project per se.

**Comment by xiota** [comment]
Of numerous GitHub repositories, many owned by Apple, I encountered this issue with only these two repositories, both owned by Apple, when using the `--mirror` flag.  This has been reproduced on my personal machine and two build servers outside my control, on three separate networks.  This makes `git` configuration and network connection issues unlikely.

Some GitHub server or configuration issue related to these specific repositories is likely.  However, since the repositories are owned by Apple, I would expect Apple developers or representatives would be interested in fixing the problem, contacting GitHub, if necessary, to resolve the issue.  Do you really prefer an outsider contacting GitHub directly about issues with your repositories, potentially disrupting your company's activities in the process?
