### ISSUE TITLE
When I use the ASWebAuthenticationSession to login, how can I open the login page in fullscreen mode?

### ISSUE THREAD

**Issue by bettersun** [apple/swift#66207]
Now when I use the ASWebAuthenticationSession to login, ASWebAuthenticationSession.start() will open a login webpage in a small model window.

But I want to open the login page in fullscreen mode? 

What should I set for this ?

**Comment by AnthonyLatsis** [comment]
This repository contains the Swift compiler and Standard Library. Questions about using closed-source Apple frameworks (`UIKit`, `SwiftUI`, `AuthenticationServices`, etc.) are best asked on the [developer forums](https://developer.apple.com/forums/tags/authenticationservices) or Q&A spaces like StackOverflow.
