### ISSUE TITLE
The diagnostic prompt for "??" will not automatically remove the whitespace on the left-hand side.

### ISSUE THREAD

**Issue by CrazyFanFan** [apple/swift#66206]
**Description**

This may not be a bug, but it is certainly not user-friendly. 

The diagnostic message for the "??" operator suggests removing the "??" and the default value on the right if the left-hand side is not optional, but it does not automatically fix or remove any leading whitespace on the left-hand side of the "??".

```swift
let foo = "foo"
print("Foo value is \(foo ?? "empty-value")")
```
Automatically fix using diagnostic information.

```swift
let foo = "foo"
print("Foo value is \(foo )")
                         ^~~~~~ A space will be kept here.
```

**Expected behavior**

The expected result of the automatic fix is as follows:

```swift
let foo = "foo"
print("Foo value is \(foo)")
```

**Environment**
- Swift compiler version info 
> swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
> Target: arm64-apple-macosx13.0
- Xcode version info 
> Xcode 14.3.1
> Build version 14E300b
- Deployment target: 
> iOS 11.0

**Comment by Reckoner1710** [comment]
@CrazyFanFan  Hey man, you working on this? Sorry this is my first time contributing to something, so just confirming.

**Comment by CrazyFanFan** [comment]
@Reckoner1710  Yes, I am trying to fix this issue. Interestingly, this is my first time attempting to contribute to Swift, and many aspects of it are unfamiliar to me.

**Comment by Reckoner1710** [comment]
@CrazyFanFan  cool mahn, go ahead then. Will work on some other issue :)

**Comment by arkumari2000** [comment]
If no one is working on this issue actively, I would like to pick this up as my first issue in this repo for contribution. @CrazyFanFan please let me know if you are working on this.
Thanks.

**Comment by CrazyFanFan** [comment]
@arkumari2000 Yes, I'm trying to fix this issue and this is the Pull Request: https://github.com/CrazyFanFan/swift/commit/62fdefa987e2321ff83dc30338a04c03e41cb86a. I'm waiting for a review and if you have any better solutions, please feel free to discuss it with me.
