### ISSUE TITLE
CommandLine.arguments and CommandLine.argc should be deprecated and replaced with immutable equivalents.

### ISSUE THREAD

**Issue by Lukasa** [apple/swift#66213]
CommandLine.arguments and CommandLine.argc are both declared `static var`. This is a real footgun: they're unsafe to use in a concurrency context because they may be mutated from any thread at any time. There's no real value in these being mutable so I think it is largely an oversight. We should consider deprecating these and replacing them with thread-safe equivalents.

**Comment by grynspan** [comment]
I wonder if we could maybe get away with just removing the setters? Hopefully nobody's relying on them…

**Comment by Nau56** [comment]
import Foundation

let commandLineArguments = CommandLine.arguments

// Access command-line arguments as an array of strings
for argument in commandLineArguments {
    print("Argument: \(argument)")
}

// Access the number of command-line arguments
let argumentCount = CommandLine.argc
print("Argument count: \(argumentCount)")

**Comment by grynspan** [comment]
Note `argc` is immutable. A workaround:

```swift
let commandLineArgs: [String] = UnsafeBufferPointer<UnsafeMutablePointer<CChar>?>(
  start: CommandLine.unsafeArgv,
  count: Int(CommandLine.argc)
).lazy
  .compactMap { $0 }
  .compactMap { String(validatingUTF8: $0) }
```

**Comment by stevapple** [comment]
> I wonder if we could maybe get away with just removing the setters? Hopefully nobody's relying on them…

I don't think this can get through before Swift 6. Also, we cannot change it directly because of ABI stability.

**Comment by grynspan** [comment]
We could add an equivalent method (the method-ness can be used to indicate that the value is recomputed on each use?)

```swift
extension CommandLine {
  /// Get the command-line arguments passed to this process.
  ///
  /// - Returns: An array of command-line arguments.
  public static func arguments() -> [String] {
    UnsafeBufferPointer(start: unsafeArgv, count: Int(argc)).lazy
      .compactMap { $0 }
      .compactMap { String(validatingUTF8: $0) }
  }
}
```

We can trivially make such a thing back-deployable or transparent so that it can be used in older Darwin releases too.

**Comment by gwynne** [comment]
See also #69658

**Comment by dnadoba** [comment]
`ProcessInfo.processInfo.arguments` from Foundation is the current best workaround

**Comment by dnadoba** [comment]
This is actually already fixed by https://github.com/apple/swift/pull/72258

**Comment by grynspan** [comment]
Based on @tshortli's comment [here](https://github.com/apple/swift/pull/72258#issuecomment-1993505899), it sounds like there may be more work to do?

**Comment by tshortli** [comment]
I fixed the availability checker problems I was describing in the comments you linked to.

**Comment by grynspan** [comment]
Awesome :)
