### ISSUE TITLE
Recent Swift nightly toolchains crash compiling GRDB

### ISSUE THREAD

**Issue by mattwhiteside** [apple/swift#66240]
**Description**
When compiling an Xcode project that depends on the [GRDB package](https://github.com/groue/GRDB.swift/tree/v6.14.0)

The compiler crashes with the following assertion:

Assertion failed: (CastInst::castIsValid(opc, C, Ty) && "Invalid constantexpr cast!"), function getCast, file Constants.cpp, line 1951

**Steps to reproduce**

1. Create an Xcode project and add a dependency on the GRDB package, v6.14.0.
2. After the packages have been resolved, try to compile the 'GRDB-package' target.

**Expected behavior**

Compiles successfully.

**Environment**
- Swift compiler version: Swift Development Snapshot 2023-05-30 (a)
- Xcode version: 14.3.1, build 14E300b
- Deployment target: macOS 13.3

Thanks.  Let me know if any more info is needed.

Here's the rest of the stack trace:

4.	While evaluating request IRGenRequest(IR Generation for file "/Users/<redacted>/Library/Developer/Xcode/DerivedData/<redacted>/SourcePackages/checkouts/GRDB.swift/GRDB/QueryInterface/SQL/SQLRelation.swift")
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  swift-frontend           0x0000000104f735d4 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
1  swift-frontend           0x0000000104f72978 llvm::sys::RunSignalHandlers() + 112
2  swift-frontend           0x0000000104f73c14 SignalHandler(int) + 304
3  libsystem_platform.dylib 0x000000019ce46a24 _sigtramp + 56
4  libsystem_pthread.dylib  0x000000019ce17c28 pthread_kill + 288
5  libsystem_c.dylib        0x000000019cd25ae8 abort + 180
6  libsystem_c.dylib        0x000000019cd24e44 err + 0
7  swift-frontend           0x000000010617e974 llvm::ConstantExpr::getCast(unsigned int, llvm::Constant*, llvm::Type*, bool) (.cold.3) + 0
8  swift-frontend           0x0000000104bd8cf8 llvm::ConstantExpr::getCast(unsigned int, llvm::Constant*, llvm::Type*, bool) + 472
9  swift-frontend           0x0000000104454384 llvm::IRBuilderBase::CreateCast(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&) + 216
10 swift-frontend           0x00000001005fd7ec swift::irgen::emitScatterBits(swift::irgen::IRGenModule&, swift::irgen::IRBuilder&, llvm::APInt, llvm::Value*, unsigned int) + 160
11 swift-frontend           0x000000010057af04 swift::irgen::EnumPayload::emitScatterBits(swift::irgen::IRGenModule&, swift::irgen::IRBuilder&, llvm::APInt const&, llvm::Value*) + 784
12 swift-frontend           0x000000010057a950 swift::irgen::EnumPayload::insertValue(swift::irgen::IRGenModule&, swift::irgen::IRBuilder&, llvm::Value*, unsigned int) + 112
13 swift-frontend           0x000000010063ced4 swift::irgen::ScalarPairTypeInfo<(anonymous namespace)::FuncTypeInfo, swift::irgen::ReferenceTypeInfo>::packIntoEnumPayload(swift::irgen::IRGenModule&, swift::irgen::IRBuilder&, swift::irgen::EnumPayload&, swift::irgen::Explosion&, unsigned int) const + 84
14 swift-frontend           0x0000000100607b40 (anonymous namespace)::MultiPayloadEnumImplStrategy::emitValueInjection(swift::irgen::IRGenModule&, swift::irgen::IRBuilder&, swift::EnumElementDecl*, swift::irgen::Explosion&, swift::irgen::Explosion&) const + 208
15 swift-frontend           0x00000001005cd920 swift::irgen::emitConstantValue(swift::irgen::IRGenModule&, swift::SILValue, bool) + 592
16 swift-frontend           0x00000001005e3bb4 swift::irgen::IRGenModule::getGlobalInitValue(swift::SILGlobalVariable*, llvm::Type*, swift::irgen::Alignment) + 372
17 swift-frontend           0x00000001005e3358 swift::irgen::IRGenModule::getAddrOfSILGlobalVariable(swift::SILGlobalVariable*, swift::irgen::TypeInfo const&, swift::ForDefinition_t) + 1436
18 swift-frontend           0x000000010064e990 swift::irgen::IRGenModule::emitSILGlobalVariable(swift::SILGlobalVariable*) + 172
19 swift-frontend           0x00000001005dc7e8 swift::irgen::IRGenerator::emitGlobalTopLevel(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>> const&) + 624
20 swift-frontend           0x00000001006e256c swift::IRGenRequest::evaluate(swift::Evaluator&, swift::IRGenDescriptor) const + 1620
21 swift-frontend           0x00000001007300ac swift::GeneratedModule swift::SimpleRequest<swift::IRGenRequest, swift::GeneratedModule (swift::IRGenDescriptor), (swift::RequestFlags)9>::callDerived<0ul>(swift::Evaluator&, std::__1::integer_sequence<unsigned long, 0ul>) const + 208
22 swift-frontend           0x00000001006f1118 llvm::Expected<swift::IRGenRequest::OutputType> swift::Evaluator::getResultUncached<swift::IRGenRequest>(swift::IRGenRequest const&) + 364
23 swift-frontend           0x00000001006e469c swift::performIRGeneration(swift::FileUnit*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::StringRef, llvm::GlobalVariable**) + 212
24 swift-frontend           0x00000001002bf908 performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*) + 1664
25 swift-frontend           0x00000001002becbc swift::performCompileStepsPostSema(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 568
26 swift-frontend           0x00000001002cdeac withSemanticAnalysis(swift::CompilerInstance&, swift::FrontendObserver*, llvm::function_ref<bool (swift::CompilerInstance&)>, bool) + 160
27 swift-frontend           0x00000001002c179c performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 724
28 swift-frontend           0x00000001002c0730 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2456
29 swift-frontend           0x000000010010aec8 swift::mainEntry(int, char const**) + 2144
30 dyld                     0x000000019cabff28 start + 2236

**Comment by hamishknight** [comment]
Should be fixed by https://github.com/apple/swift/pull/66238

**Comment by hamishknight** [comment]
Please verify using the next available nightly toolchain

**Comment by mattwhiteside** [comment]
Built a local toolchain and it's fixed.  Thanks.
