### ISSUE TITLE
Move only structs no longer work in release mode.

### ISSUE THREAD

**Issue by TeamPuzel** [apple/swift#66299]
I recently opened a different issue: https://github.com/apple/swift/issues/66047

It's fixed now so I closed it, however now compiling with `swift run -c release` results in an unresponsive server (yet no errors from the os). It worked before so I'm not sure what the problem is.

Swift package: [Server.zip](https://github.com/apple/swift/files/11636151/Server.zip)

**Comment by gottesmm** [comment]
@TeamPuzel I just tried this locally with ToT and it works. (I was able to curl localhost:3000 and get back Hello World). Can you try with ToT once this lands https://github.com/apple/swift/pull/66505. If you don't want to build yourself, I would wait a few days and we should get a new snapshot. (I tested and your project hits the issue I am fixing in the aforementioned PR)
