### ISSUE TITLE
Compiler crash when inferring generic parameter type from a parameter pack (again)

### ISSUE THREAD

**Issue by natecook1000** [apple/swift#66661]
This is nearly the same code as #66660 (only the `where` clause is different), but yields a different crash:

```swift
protocol GenericComponent<Param> {
  associatedtype Param
}

struct Generic<Param>: GenericComponent {}

func convert<G1: GenericComponent, each C>(_ x: G1) -> Generic<(repeat each C)>
  where repeat G1.Param == (String, each C)
{
  Generic()
}
```

Error (and [stack dump](https://github.com/apple/swift/files/11752727/stackdump.txt)):

```
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 578.
```

**Comment by natecook1000** [comment]
Reproduced with `swift-DEVELOPMENT-SNAPSHOT-2023-06-07-a.xctoolchain`.

**Comment by AnthonyLatsis** [comment]
This no longer crashes.

**Comment by GeorgeElsham** [comment]
Although closely related issue #66660 compiles now for me, this code won't. Not sure if it's a regression. As you highlight the above commit fixing both issues, when only this one still fails to compile for me, I suspect there may be a regression here in this case.

Environment:
Xcode: Version 15.0 beta 8 (15A5229m)
Swift (`xcrun swift -version`): swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1) , Target: arm64-apple-macosx13.0

**Comment by vanvoorden** [comment]
@AnthonyLatsis I saw a similar error in https://github.com/apple/swift/issues/71258.
