### ISSUE TITLE
Support special characters (such as: ࿚)

### ISSUE THREAD

**Issue by AbnerPei** [apple/swift#66758]
In our App ࿚ is contained in a user nickname, display (App Store search) is shown in the diagram below:
![IMG_5198](https://github.com/apple/swift/assets/11939807/ddd36d5a-f69e-4e65-bfcf-fbed6ef92327)

**Comment by tbkka** [comment]
This repository is for the open-source, cross-platform Swift compiler and language implementation.  For issues with iOS, SwiftUI, or other Apple-specific technologies, please use Apple's feedback assistant:  feedbackassistant.apple.com

**Comment by AbnerPei** [comment]
In case I'm not clear, the APP Store search bar screenshot is just an example of Apple's own App issues! If you run the following code, you will see that the last character is garbled（The Demo effect is shown below）!
```
        let lable = UILabel(frame: CGRect(x: 20, y: 150, width: 200, height: 40))
        lable.text = "❥橘月₅̶₂̶₀̶࿚"
        view.addSubview(lable)
```
<img width="358" alt="image" src="https://github.com/apple/swift/assets/11939807/9b2aecc1-76a0-4a24-ac0d-903a6b7cd60d">

So，I want you to deal with this problem, not for me to give feedback。
Thanks very much ！

**Comment by tbkka** [comment]
No one here can help with this:  This is an issue with Apple's UIKit and text rendering APIs, not with the Swift compiler or language.  You can use the feedback assistant to make sure the appropriate people inside of Apple are aware of this issue.
