### ISSUE TITLE
Crash when attempting to capture more associated values than are available

### ISSUE THREAD

**Issue by ChrisLawther** [apple/swift#66863]
**Description**
After modifying a type, I was inadvertently left with a `guard case let` that was attempting to capture more associated values than the type now had. This results in the compiler crashing.

**Steps to reproduce**
Start a new Swift package and replace the code with:

    public struct CompilerCrasher {
        enum Thing {
            case one
            case other(Int)
        }

        let things: [Thing] = [
            .one,
            .one,
            .other(7)
        ]

        func causeCrash() {
            let values = things.compactMap { thing -> Int? in
                // The capture group is expecting two associated values, but there is only one.
                guard case let .other(_, value) = thing else { return nil }

                return value
            }
        }
    }

**Expected behavior**
An error message reporting the mismatch between the expected quantity and available quantity of associated values.

**Environment**
- Swift compiler version info `swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100) Target: arm64-apple-macosx13.0`
- Xcode version info: `Xcode 14.3 Build version 14E222b`
- Deployment target: Any? Wasn't constrained by default `Package.swift`

**Output from the crash:**

    Stack dump:
    0.  Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/chris/Desktop/CompilerCrasher/Sources/CompilerCrasher/CompilerCrasher.swift -emit-dependencies-path /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/Objects-normal/arm64/CompilerCrasher.d -emit-reference-dependencies-path /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/Objects-normal/arm64/CompilerCrasher.swiftdeps -serialize-diagnostics-path /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/Objects-normal/arm64/CompilerCrasher.dia -target arm64-apple-ios11.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -I /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Products/Debug-iphoneos -I /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -F /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Products/Debug-iphoneos -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk/Developer/Library/Frameworks -no-color-diagnostics -enable-testing -g -module-cache-path /Users/chris/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D SWIFT_PACKAGE -D DEBUG -D Xcode -serialize-debugging-options -empty-abi-descriptor -Xcc -working-directory -Xcc /Users/chris/Desktop/CompilerCrasher -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -ivfsstatcache -Xcc /Users/chris/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos16.4-20E238-.sdkstatcache -Xcc -I/Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/swift-overrides.hmap -Xcc -I/Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Products/Debug-iphoneos/include -Xcc -I/Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/DerivedSources-normal/arm64 -Xcc -I/Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/DerivedSources/arm64 -Xcc -I/Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG=1 -module-name CompilerCrasher -frontend-parseable-output -disable-clang-spi -target-sdk-version 16.4 -target-sdk-name iphoneos16.4 -parse-as-library -o /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Build/Intermediates.noindex/CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/Objects-normal/arm64/CompilerCrasher.o -index-unit-output-path /CompilerCrasher.build/Debug-iphoneos/CompilerCrasher.build/Objects-normal/arm64/CompilerCrasher.o -index-store-path /Users/chris/Library/Developer/Xcode/DerivedData/CompilerCrasher-hkamqqyccsmvqlewzsnzlkinpmcd/Index.noindex/DataStore -index-system-modules
    1.  Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
    2.  Compiling with the current language version
    3.  While evaluating request ASTLoweringRequest(Lowering AST to SIL for file "/Users/chris/Desktop/CompilerCrasher/Sources/CompilerCrasher/CompilerCrasher.swift")
    4.  While silgen emitFunction SIL function "@$s15CompilerCrasherAAV10causeCrashyyF".
     for 'causeCrash()' (at /Users/chris/Desktop/CompilerCrasher/Sources/CompilerCrasher/CompilerCrasher.swift:13:5)
    Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
    0  swift-frontend           0x00000001059d7300 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 56
    1  swift-frontend           0x00000001059d62e4 llvm::sys::RunSignalHandlers() + 112
    2  swift-frontend           0x00000001059d7910 SignalHandler(int) + 344
    3  libsystem_platform.dylib 0x00000001a895aa84 _sigtramp + 56
    4  swift-frontend           0x0000000100ef36b0 swift::Lowering::SILGenFunction::emitApplyExpr(swift::ApplyExpr*, swift::Lowering::SGFContext) + 252
    5  swift-frontend           0x0000000100f5bcb4 swift::Lowering::SILGenFunction::emitExprInto(swift::Expr*, swift::Lowering::Initialization*, llvm::Optional<swift::SILLocation>) + 136
    6  swift-frontend           0x0000000100f46a28 swift::Lowering::SILGenFunction::emitPatternBinding(swift::PatternBindingDecl*, unsigned int)::$_0::operator()(swift::Expr*, swift::VarDecl*, bool, std::__1::unique_ptr<swift::Lowering::Initialization, std::__1::default_delete<swift::Lowering::Initialization> >&) const + 436
    7  swift-frontend           0x0000000100f46448 swift::Lowering::SILGenFunction::emitPatternBinding(swift::PatternBindingDecl*, unsigned int) + 1992
    8  swift-frontend           0x0000000100ee5948 swift::ASTVisitor<swift::Lowering::SILGenFunction, void, void, void, void, void, void>::visit(swift::Decl*) + 148
    9  swift-frontend           0x0000000100fd68a0 swift::ASTVisitor<(anonymous namespace)::StmtEmitter, void, void, void, void, void, void>::visit(swift::Stmt*) + 3280
    10 swift-frontend           0x0000000100f87028 swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 728
    11 swift-frontend           0x0000000100ee1ea0 swift::Lowering::SILGenModule::emitFunctionDefinition(swift::SILDeclRef, swift::SILFunction*) + 7208
    12 swift-frontend           0x0000000100ee37cc emitOrDelayFunction(swift::Lowering::SILGenModule&, swift::SILDeclRef) + 164
    13 swift-frontend           0x0000000100ee0264 swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 320
    14 swift-frontend           0x0000000100fe2c04 (anonymous namespace)::SILGenType::emitType() + 460
    15 swift-frontend           0x0000000100ee4ff4 swift::ASTVisitor<swift::Lowering::SILGenModule, void, void, void, void, void, void>::visit(swift::Decl*) + 88
    16 swift-frontend           0x0000000100ee63c4 swift::ASTLoweringRequest::evaluate(swift::Evaluator&, swift::ASTLoweringDescriptor) const + 2664
    17 swift-frontend           0x0000000100fd581c swift::SimpleRequest<swift::ASTLoweringRequest, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> > (swift::ASTLoweringDescriptor), (swift::RequestFlags)9>::evaluateRequest(swift::ASTLoweringRequest const&, swift::Evaluator&) + 204
    18 swift-frontend           0x0000000100eea1b0 llvm::Expected<swift::ASTLoweringRequest::OutputType> swift::Evaluator::getResultUncached<swift::ASTLoweringRequest>(swift::ASTLoweringRequest const&) + 604
    19 swift-frontend           0x00000001008c84e0 performCompile(swift::CompilerInstance&, int&, swift::FrontendObserver*) + 1792
    20 swift-frontend           0x00000001008c6944 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 4308
    21 swift-frontend           0x000000010088b68c swift::mainEntry(int, char const**) + 4116
    22 dyld                     0x00000001a85d3f28 start + 2236

**Comment by hamishknight** [comment]
The crash was fixed by b5e9bbb68dd879cd9bbe85c54e1b7218a0db67b7, we still have additional diagnostic work to produce the correct error message though, which I'm tracking in #65062. On main we currently produce the following, which is wrong:

```swift
error: type of expression is ambiguous without a type annotation [type_of_expression_is_ambiguous]
        let values = things.compactMap { thing -> Int? in
                     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
