### ISSUE TITLE
SourceKit expression type request returns optional type for expression that is not optional

### ISSUE THREAD

**Issue by skrtks** [apple/swift#66882]
**Description**
When requesting expression types for the following Swift snippet, I would expect the type of `foo` to be `String`, not `String?`:

```
let foo: String = "Hey"

let bar: String? = foo // `foo` should be of type `String` not `String?`
```

I looked into why this might be happening and found that SourceKit is taking the type of the `InjectIntoOptionalExpr` that surrounds the actual expression in the assignment. It could be that this is the expected behaviour, but since SourceKit is used in an IDE context, I would not expect the type of the injected expression.

If this is not the expected behaviour, I'm willing to implement a fix. 

**Steps to reproduce**
Running `source.request.expression.type` on the above code snippet produces the following output: 

```
<ExpressionTypes>
(16, 21): String
(40, 41): String?
</ExpressionTypes>

```
**Environment**
- Swift compiler version info:
    swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
- Xcode version info: Version 14.2 (14C18)
- Deployment target: arm64-apple-macosx13.0

**Comment by AnthonyLatsis** [comment]
cc @nkcsgexi

**Comment by hamishknight** [comment]
Tracking this internally as rdar://111462279

**Comment by hamishknight** [comment]
This is indeed unexpected, we ought to ignore implicit expressions, similar to cursor info. We're tracking this internally as rdar://111462279, we'd be more than happy for you to submit a fix for it though

**Comment by skrtks** [comment]
Great, I'll work on a fix 👍🏼
