### ISSUE TITLE
Freestanding Expression macro code that uses `try` fails to compile with 'Errors thrown from here are not handled' when used in a throwing closure

### ISSUE THREAD

**Issue by liamnichols** [apple/swift#67102]
**Description**

When using freestanding expression macros, if the macro generates code that uses the `try` keyword in the returned expression, the following compile error is produced when the macro is used inside a throwing closure:

> Errors thrown from here are not handled

**Steps to reproduce**

- Download the following sample project: [ThrowingInFreestandingMacroReproProj.zip](https://github.com/apple/swift/files/11941756/ThrowingInFreestandingMacroReproProj.zip)
- Build the ThrowingInFreestandingMacroReproProjClient target
- See _Errors thrown from here are not handled_ compile error

<img width="1704" alt="Screenshot 2023-07-04 at 01 00 26" src="https://github.com/apple/swift/assets/482871/21c922a9-aadb-4394-a0ee-32c2cb611161">

**Expected behavior**

The project should compile successfully because errors thrown from inside the closure are in fact handled.

**Environment**

```
$ swiftc -version
swift-driver version: 1.82.2 Apple Swift version 5.9 (swiftlang-5.9.0.114.10 clang-1500.0.29.1)
Target: arm64-apple-macosx13.0

$ xcodebuild -version
Xcode 15.0
Build version 15A5161b
```

**Comment by DougGregor** [comment]
Closures infer their throwing-ness based on the presence of `try` in the source code. Because macro expansion occurs after type checking, the closure is inferred to be non-throwing. This is the expected behavior for the system.

**Comment by liamnichols** [comment]
> Because macro expansion occurs after type checking, the closure is inferred to be non-throwing.

Thanks for explaining this @DougGregor. Does this mean that use of throwing functions inside an expression macro is not supported then? I can't quite wrap my head around how you would write on that supports this, but maybe that's because you can't?

**Comment by hydrixos** [comment]
It would be great if this issue could be re-considered. The current handling leads to an error message when using an`#expect(try …)` macro in Swift Testing within a closure:

```
import Testing

class Foo {
	init() {
	}
	
	func doSomething() throws -> Bool {
		throw TestError("Error")
	}
}

struct FooTest {
	@Test func throwingClosure() async throws {
		let foo = Foo()
		
		try Self.perform {
			#expect(try foo.doSomething())
		}
	}
	
	static func perform(_ block: () throws -> Void) throws {
		try block()
	}
}
```

In this case an "Errors thrown from here are not handled" is emitted. While using the same `#export(try …)` macro directly from a throwing function works. 

If this can't be easily fixed, it would be already very helpful if the error message would hint on the throwing closure (because it takes quite time to understand the context…
