### ISSUE TITLE
Duplicate -rpath Frameworks build Warnings Xcode 15 Beta 3 

### ISSUE THREAD

**Issue by rnantes** [apple/swift#67147]
Getting the following errors in Xcode 15 beta 3 when building swift package using the Vapor Framework Hello World Example Project. I get the same errors using the Swift 5.9 Development toolchain. I did not get these errors in Xcode 15 beta 2.

`Duplicate -rpath "/Users/Library/Developer Xcode/DerivedData/hello-hftziduwikmqzpcqvnyyxbsykcb Build/Products/Debug/PackageFrameworks ignored`

`Duplicate -rpath '@loader_path/../Frameworks' ignored`

`Could not associate debug note to atom _OBJC_LABEL PROTOCOL_$_OS_sec_protocol_metadata`

<img width="2096" alt="Screenshot-xcode-15-beta-3-vapor-errors" src="https://github.com/apple/swift/assets/9631562/858f3867-5a2e-4c0c-8a4a-7aef26ed1367">

**Comment by gongzhang** [comment]
Same here and confirm this is new in Xcode 15 beta 3. 

https://developer.apple.com/forums/thread/733317

I can reproduce this issue by replacing Vapor with almost any other packages.

**Comment by twof** [comment]
Also seeing this. You can reproduce by simply creating a macro package and trying to build it. I'll try downgrading to Xcode 15 beta 2 for the time being.

**Comment by jnozzi** [comment]
Can repro on beta 4 as well. Both on an older codebase with ObjC/Swift mix and frameworks/submodules/etc, and on a new SwiftUI app with only pure Swift packages.

**Comment by rnantes** [comment]
Seems to be resolved on Xcode 15 beta 5

**Comment by jnozzi** [comment]
Confirmed for me as well. 👏👏👏
