### ISSUE TITLE
std::vector<std::string> fails to conform to CxxRandomAccessCollection

### ISSUE THREAD

**Issue by hyp** [apple/swift#67410]
As reported here: https://forums.swift.org/t/c-interop-for-in-loop-requires-std-1-vector-element-to-conform-to-sequence/66232

Reproducer:
https://github.com/Sajjon/CxxRandomAccessCollectionNotWorking

**Comment by hyp** [comment]
over to @egorzhdan

**Comment by Sajjon** [comment]
Btw it works to call a method returning `std::string` so using string alone is not an issue, and `std::vector<int>` is not an issue, just the combination of `vector<string>` fails to compile.

**Comment by moretromain** [comment]
I'm facing the same issue, not only with std::string, but even with builtin char/int types:

On the C++ side, I do a few typedefs:
`
using CharArray     = std::vector<char>;
using UCharArray    = std::vector<unsigned char>;
using I8Array       = std::vector<int8_t>;
using U8Array       = std::vector<uint8_t>;
using I16Array      = std::vector<int16_t>;
using U16Array      = std::vector<uint16_t>;
using I32Array      = std::vector<int32_t>;
using U32Array      = std::vector<uint32_t>;
using I64Array      = std::vector<int64_t>;
using U64Array      = std::vector<uint64_t>;
`
On the Swift side, for each of those, a simple function:
`
    public static func i8ArrayTest(_ data: I8Array) -> [Int8] {
        let ret = Array<Int8>(data)
        return ret
    }
`

The results are interesting:
- int, int32_t and uint32_t are working as expected
- all other types are not working (error: doesn't conform to Sequence or CxxConvertibleToCollection)


Furthermore, if I keep only the two that work (int32_t and uint32_t), I get a link error a bit later, with multiply defined symbols:
`<unknown>:0: error: multiple definitions of symbol '$sSo1soiySiSo3stdO3__1O0020___wrap_iter__udAAdDaV_AGtFTO'
<unknown>:0: error: multiple definitions of symbol '$sSo2eeoiySbSo3stdO3__1O0020___wrap_iter__udAAdDaV_AGtFTO'
<unknown>:0: error: multiple definitions of symbol '$sSo3stdO3__1O0020___wrap_iter__udAAdDaV9successorAFyF'
<unknown>:0: error: multiple definitions of symbol '$sSo3stdO3__1O0020___wrap_iter__udAAdDaV2peoiyyAFz_SitFZ'`

Swift 5.9 / Xcode 15 Beta 4, same issue when compiling from Xcode, or by invoking swiftc directly
