### ISSUE TITLE
The buildEither(first:) and buildEither(second:) function in ResultBuilder is designed for what situation

### ISSUE THREAD

**Issue by Gavin96** [apple/swift#67426]
**Background**

As mentioned in proposal 0289 (https://github.com/apple/swift-evolution/blob/main/proposals/0289-result-builders.md): 
**buildEither(first: Component) -> Component and buildEither(second: Component) -> Component are used to build partial results when a selection statement produces a different result from different paths. When a result builder provides these methods, the transformed function can include if statements with an else statement as well as switch statements.**

We could define the buildEither(first: ) && buildEither(second:) in one struct annotated by @ResultBuilder.
For example:

```swift
@resultBuilder
struct DemoBuilder {
    static func buildBlock(_ parts: String...) -> String {
        parts.map{"* " + $0 + " #"}.joined(separator: " ")
    }

    static func buildExpression(_ num: Int) -> String {
      print("pass buildE 1");
      return String(num);
    }

    static func buildExpression(_ name: String) -> String {
      print("pass buildE 2");
      return name;
    }

    static func buildEither(first component: String) -> String {
      return component;
    }

    static func buildEither(second component: String) -> String {
      return component;
    }
}

var tmp = false

@DemoBuilder
func buildString() -> String {
  if tmp {
    1
  } else {
    2
  }
}

print(buildString())
```
In above codes, we define these two buildEither function to produce different results from different paths.

**My Attempts**
However, since buildEither(first:) && buildEither(second:) are functions, we could do more than just return its function input's parameter in its function body, we could add something more just like:
```swift
@resultBuilder
struct DemoBuilder {
    static func buildBlock(_ parts: String...) -> String {
        parts.map{"* " + $0 + " #"}.joined(separator: " ")
    }

    static func buildExpression(_ num: Int) -> String {
      print("pass buildE 1");
      return String(num);
    }

    static func buildExpression(_ name: String) -> String {
      print("pass buildE 2");
      return name;
    }

    static func buildEither(first component: String) -> String {
      return "pass first: " + component;
    }

    static func buildEither(second component: String) -> String {
      return "pass second: " + component;
    }
}

var tmp = false

@DemoBuilder
func buildString() -> String {
  if tmp {
    1
  } else {
    2
  }
}

print(buildString())
```
By adding the "pass first" and "pass second" information,  the buildEither execution process could be shown explicitly.

**Question**
There are few samples about the buildEither I could find in the internet. My question is whether these two functions are only designed for producing a different result from different paths, and function definitions are always:
```
buildEither(first: Component) -> Component {
    return first;
}
buildEither(second: Component) -> Component {
    return second;
}
```
Or, there are any other situation in swiftUI where we could not just simply return first or second.

**Comment by xedin** [comment]
Bodies of these functions are not limited to just return of the “component”, they are intended to help API implements to affect if/else and switch execution, you can add any logic you want as soon as  `buildEither` produces `Component` type.

**Comment by Gavin96** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到您的信息。

**Comment by AnthonyLatsis** [comment]
It looks like you are asking a question and not requesting a feature, so I’m going to adjust the labels and close the issue (you can still comment). Next time, please consider asking questions about Swift using the [forums](https://forums.swift.org) rather than GitHub Issues. The forums have a wider audience and a special category for this purpose, making you more likely to get a timely and comprehensive answer.
