### ISSUE TITLE
[StdLib] Incorrect results from `String.hasPrefix` and `hasSuffix`

### ISSUE THREAD

**Issue by natecook1000** [apple/swift#67427]
[As reported on the Swift forums](https://forums.swift.org/t/why-is-regex-slower-than-using-a-bunch-of-string-contains/66247/26), `String.hasPrefix` and `String.hasSuffix` sometimes have an incorrect result:

```swift
"\r\n".hasPrefix("\r")      // true
"\r\n".hasPrefix("\r"[...]) // false

"\r\n".hasSuffix("\n")      // true
"\r\n".hasSuffix("\n"[...]) // false
```

All four of these calls should return `false`, since those methods should be matching at the character level, not at the Unicode scalar level. The problem is in the `String`-specific overloads for `hasPrefix` and `hasSuffix` in [StringLegacy.swift](https://github.com/apple/swift/blob/main/stdlib/public/core/StringLegacy.swift#L123-L151), which don't validate that the string passed as a parameter ends on a character boundary (when both strings are known to be NFC). The calls that pass a substring go to the `StringProtocol`-based overload, instead, which calls through to the `Sequence` method `starts(with:)`.

**Environment**
- Swift `main` branch

**Comment by nishithshah2211** [comment]
@natecook1000 I'd like to attempt fixing this if you or anyone else is not already working on it.

**Comment by nishithshah2211** [comment]
Just to add another observation for this buggy behavior:

```swift
"\r\n".count // returns 1 - because \r\n is an extended grapheme cluster 
"hello\r\n".count // 6 
"\r\nhello\r\n".count // 7

"\r\nhello\r\n".hasPrefix("\r") // returns true, but it should be false since \r\n is an extended grapheme cluster and \r is not to be considered independent of the following \n

```

**Comment by nishithshah2211** [comment]
More puzzling and likely related behavior:

```swift
let s1 = "\r\n" + "cafe" + "\u{301}" + "\r\n"
let s2 = "\r\n" + "cafe" + "\r\n"

s1.count // returns 6
s2.count // returns 6

s1.hasPrefix("\r") // returns false
s2.hasPrefix("\r") // returns true
```

It seems related to the same above behavior, but let me know if this should be filed as a separate bug.
