### ISSUE TITLE
Document lifetime of closures used to create `Task`s

### ISSUE THREAD

**Issue by karwa** [apple/swift#67452]
**Description**

Joe:

> As a general rule, it is rarely necessary or helpful to use weak captures in a Task closure, since tasks already don't form permanent references to their context; like any other function, they will retain the values they use only for as long as the code executing needs them, and when the task ends, it will release any remaining local state.

https://forums.swift.org/t/unexpected-memory-leak-when-using-task-in-a-closure-causes/66272/6

Me:

> To be fair, the documentation for the Task type does not mention this, nor does the documentation for any of the Task initialisers (where those closures are provided).
>
> In other contexts, if you initialise a type by providing an `@escaping` closure, the assumption is that the closure's lifetime will match that of the initialised value (e.g. the value will save the closure as a stored property). If in this case the lifetime of the closure is truly independent of the lifetime of the created Task handle, then that fact should be a documented guarantee. Otherwise, developers should assume that it is an implementation detail and not rely on it, IMO.

We should add appropriate documentation to the `Task` type to inform users how long their `@escaping` closures will live for.

Current documentation: https://developer.apple.com/documentation/swift/task#creating-a-task

**Comment by ktoso** [comment]
While wording of the rationale could be expressed nicer I agree it's worth documenting this explicitly :-)

PRs welcome, or we'll get to it sometime 👍

**Comment by ktoso** [comment]
rdar://112653483

**Comment by karwa** [comment]
Yeah sorry it's a bit lazily written. It's hot and humid today 🥵

Hopefully it's still clear enough.
