### ISSUE TITLE
missing c++ interop components in toolchain build for Windows

### ISSUE THREAD

**Issue by compnerd** [apple/swift#67462]
Building the latest 5.9 snapshot fails to package due to missing files.

https://dev.azure.com/compnerd/swift-build/_build/results?buildId=61846&view=logs&j=3d6d6336-35c7-5975-2a77-9c4cad333d2b&t=abe84523-3dab-5ac8-8c4b-5a986786345c

```
##[error]platforms\Windows\sdk-amd64.wxs(449,0): Error WIX0103: Cannot find the File file 'D:\a\1/windows-sdk-amd64/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\lib\swift\windows\x86_64\libcxxshim.h'. The following paths were checked: D:\a\1/windows-sdk-amd64/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\lib\swift\windows\x86_64\libcxxshim.h
##[error]platforms\Windows\sdk-amd64.wxs(453,0): Error WIX0103: Cannot find the File file 'D:\a\1/windows-sdk-amd64/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\lib\swift\windows\x86_64\libcxxshim.modulemap'. The following paths were checked: D:\a\1/windows-sdk-amd64/Library/Developer/Platforms/Windows.platform/Developer/SDKs/Windows.sdk\usr\lib\swift\windows\x86_64\libcxxshim.modulemap
```

We are failing to install `libcxxshim.h` and `libcxxshim.modulemap`.

**Comment by hyp** [comment]
@compnerd is that something you're going to be fixing for 5.9?

**Comment by compnerd** [comment]
I think that we should fix this for 5.9.  If you can get it fixed before I can that would be great - but this is blocking the Windows releases on 5.9 :-(.

**Comment by hyp** [comment]
Cc @egorzhdan do you know what's going wrong here?

**Comment by hyp** [comment]
@compnerd why do we need them to be under `x86_64\libcxxshim.modulemap`? they should be just in windows I believe. What kind of check is looking for these files?

**Comment by compnerd** [comment]
The installer places them at `x86_64`, I couldn't really tell you why that path over the architecture agnostic one (I suspect that it is where it is on the other platforms as well).

https://github.com/apple/swift-installer-scripts/blob/release/5.9/platforms/Windows/sdk-amd64.wxs#L447-L455

**Comment by hyp** [comment]
We need:

```
- windows/ibcxxshim.h
- windows/libcxxshim.modulemap
- windows/libcxxstdlibshim.h
```

to match what we do for linux . On linux we don't put them under x86_64.

**Comment by compnerd** [comment]
Oh!  I think I know whats happening.  https://github.com/apple/swift-installer-scripts/pull/213 was not merged into release/5.9!

**Comment by compnerd** [comment]
It seems that we aren't packaging `libcxxstdlibshims.h` on windows, is that supposed to be distributed as well?

**Comment by egorzhdan** [comment]
> It seems that we aren't packaging libcxxstdlibshims.h on windows, is that supposed to be distributed as well?

Yes, we'll need that on Windows to get the `swiftCxxStdlib` module (the overlay for the C++ stdlib) working.

**Comment by compnerd** [comment]
Okay, the last bit for this is up and waiting for CI before I merge the changes.  This gets part of the problem resolved I think.

**Comment by compnerd** [comment]
The 5.9 issue stands here still.

**Comment by compnerd** [comment]
5.9 packaging for this component is done.  There is still CxxStdlib to package up, but that requires a bit more preparation.
