### ISSUE TITLE
Process.run() fails to execute command completely

### ISSUE THREAD

**Issue by CrazyFanFan** [apple/swift#67509]
**Description**

When using the Process.run() method to execute a command, the command fails to execute completely and the program terminates prematurely. The issue is observed when executing the following Swift code:
```swift
print("enter")
let task = try Process.run(URL(fileURLWithPath: "/usr/bin/script"), arguments: "-aq /dev/null bash -c ls".components(separatedBy: " ")) { process in
    print(process.terminationStatus)
}

task.waitUntilExit()
print("leave")
```
The expected behavior is that the ls command should be executed successfully and the program should print "enter", the termination status of the process, and "leave" in the console.

**Steps to reproduce**

1. Copy the above Swift code into a main.swift.
2. Call `swift main.swift`
3. Observe that the program terminates prematurely after printing "enter" and the termination status of the process.

**Expected behavior**

The ls command should be executed successfully and the program should print "enter", the termination status of the process, and "leave" in the console.

**Note:**

The issue appears to be related to the use of the /usr/bin/script command with the -aq options. Removing these options or using a different command appears to resolve the issue.

**Environment**
- Swift compiler version info 
> swift-driver version: 1.85 Apple Swift version 5.9 (swiftlang-5.9.0.120.7 clang-1500.0.34.3)
> Target: arm64-apple-macosx14.0
- Xcode version info 
> Build version 15A5195m
- Deployment target: 
> 14.0 Beta (23A5286i)

**Comment by AnthonyLatsis** [comment]
I think this should be transferred to [swift-foundation](https://github.com/apple/swift-foundation).

**Comment by CrazyFanFan** [comment]
@AnthonyLatsis Thank you for your suggestion. I have moved this issue to https://github.com/apple/swift-corelibs-foundation/issues/4803.

**Comment by AnthonyLatsis** [comment]
`swift-corelibs-foundation` is the Foundation for non-Apple platforms, but I guess it’s fine.

Please try [transferring](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) the issue next time (or ask us) instead of cloning. This way we can avoid polluting the issue database.

**Comment by CrazyFanFan** [comment]
> `swift-corelibs-foundation` is the Foundation for non-Apple platforms, but I guess it’s fine.
> 
> Please try [transferring](https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository) the issue next time (or ask us) instead of cloning. This way we can avoid polluting the issue database.

I learned something new today, thanks!
