### ISSUE TITLE
Fix-Its should be phrased as imperative actions rather than questions

### ISSUE THREAD

**Issue by tristanlabelle** [apple/swift#67510]
Swift phrases quick fixes as questions:

![image](https://github.com/apple/sourcekit-lsp/assets/2314287/01d6ec76-42f5-4621-9d28-7ad857895584)

This is inconsistent with other extensions and code actions, which are phrased as imperative verbs:

<img width="308" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/32300a89-d264-4029-af8c-cd873fa31c31">
<img width="355" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/15693d87-33ab-4d40-a250-4041bdd2e806">
<img width="360" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/052544f4-d94d-4aeb-a772-c7badfe5329d">
<img width="347" alt="image" src="https://github.com/apple/sourcekit-lsp/assets/2314287/052b49d8-f4a9-4f65-a847-fb62e0f6c2f9">

**Comment by tristanlabelle** [comment]
Sounds good, thank you! Other messages here start with a capital letter but `sourcekit-lsp` could make that conversion if `swift-syntax` has other clients with other expectations.

**Comment by hborla** [comment]
@nishithshah2211's interested in taking a look at this!

**Comment by XaurDesu** [comment]
Should we make a list of messages worded like this? I could maybe try and rewrite a few of them

**Comment by XaurDesu** [comment]
Actually now that i think about it, where are this messages defined, anyways?

**Comment by xedin** [comment]
All of the diagnostic messages are located in https://github.com/apple/swift/tree/main/include/swift/AST in various `Diagnostics*.def` files split into one file per compiler phase e.g. Parser, Sema, SIL as well as Common. There is an easy way to find out identifier of the diagnostic: add `-Xfrontend -debug-diagnostic-names` flag in your compiler invocation and use the identifier produced in braces to grep in the def files.

**Comment by vickipetrova** [comment]
Is there any work remaining on this issue -- I can see it's still open but there's a merged PR? I'm just looking for a simple first issue to tackle :)

**Comment by tristanlabelle** [comment]
You're welcome to review other scenarios but I just verified that the specific bug I was reporting here was fixed, although now there are two different-named actions that will do the same.

![image](https://github.com/apple/swift/assets/2314287/47c9a8c1-c777-4901-af5b-18ae90750ee1)
