### ISSUE TITLE
private declarations in extension are inaccessible to the original type declaration in a particular case

### ISSUE THREAD

**Issue by horiz0n-zero** [apple/swift#67564]
**Description** 
private Properties / Methods / Functions in a Class / Struct extension is accessible only in the file where it's declared.
If you declare a class A with a method that read private static property declared in an extension, compiler will reach the following warning: 'x' is inaccessible due to 'private' protection level. Only in the case where the extension and the class declaration are in different files.

**Steps to reproduce**
This code works and compile well:
<img width="1480" alt="Capture d’écran 2023-07-27 à 14 15 29" src="https://github.com/apple/swift/assets/20483430/6c4d033c-e445-4e76-b9b5-809b86da5b3f">

This code will not work, because code are separated
fileA.swift:
<img width="1480" alt="Capture d’écran 2023-07-27 à 14 30 12" src="https://github.com/apple/swift/assets/20483430/f86215f8-a5e9-4e7d-b5dd-749c0528eced">

fileB.swift:
<img width="1480" alt="Capture d’écran 2023-07-27 à 14 30 32" src="https://github.com/apple/swift/assets/20483430/799d8dfb-59c7-490f-b751-1962c738d9ec">

**Expected behavior**
The object should have access to it's own private properties / functions / methods ... from extension

**Environment**
- Swift compiler version info :
swift-driver version: 1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
Target: x86_64-apple-macosx13.0
- Xcode version info :
Xcode 14.3
Build version 14E222b
- Deployment target: 
16.1.1

In my project, i've got a custom run script phase that generate a lot of static data, if i cannot use the private keyword somewhere were, much else declarations lose the private keyword :/

**Comment by AnthonyLatsis** [comment]
This behavior is expected and [documented](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol#Access-Levels). If you have ideas on how to improve the access control model to suit your use case, please consider starting a discussion thread on the Swift forums. It may well be worth reading through old related threads before you do — this topic was almost certainly discussed multiple times in the past.
