### ISSUE TITLE
Why does Swift use the let keyword instead of the final keyword

### ISSUE THREAD

**Issue by Silentdoer** [apple/swift#67646]
let and var keywords don't seem to be the same part of speech.
Can the var keyword be replaced with let mut keywords ?

**Comment by RemiBardon** [comment]
I think this question fits best in <https://forums.swift.org>. Also, I suppose the subject has already been discussed many times.

**Comment by grynspan** [comment]
Thanks for asking! Both `let` and `var` have long histories of use in programming languages to signal an immutable or mutable value, respectively. `let` ultimately has its origins in algebra and mathematical proofs, while `var` is used in other C-like languages such as JavaScript and Go.

If you have more questions, I'd also recommend asking on the Swift forums.
