### ISSUE TITLE
[cxx-interop] Build swiftCxxStdlib on Windows

### ISSUE THREAD

**Issue by egorzhdan** [apple/swift#67649]
The Swift overlay for the C++ standard library consists of two modules: `swiftCxx` and `swiftCxxStdlib`.

✅ Cxx is built and tested on Windows.
❌ CxxStdlib is not currently enabled on Windows. That means that the conversion mechanism between `std::string` and `Swift.String` is not available on Windows, as well as other `std::string` ergonomics features such as the conformance to Equatable, Hashable, etc

**Comment by egorzhdan** [comment]
cc @compnerd

**Comment by hyp** [comment]
This should be fixed for 5.9.

**Comment by egorzhdan** [comment]
This was fixed by @compnerd in https://github.com/apple/swift/pull/67899.
