### ISSUE TITLE
consume operator applied to a global var of a Copyable type produces an incorrect error message

### ISSUE THREAD

**Issue by DmT021** [apple/swift#67755]
**Description**

The compiler produces a poor error message when the `consume` operator is applied to a global Copyable variable.

**Steps to reproduce**

At the top-level of main.swift:
```
let a = "a"
let b = consume a // 'consume' applied to value that the compiler does not support. This is a compiler bug. Please file a bug with a small example of the bug
```

**Expected behavior**

The error should say something similar to what it says for non-copyable types: `Cannot consume noncopyable stored property 'a' that is global`.

**Environment**
- Swift compiler version info swift-driver version: 1.87 Apple Swift version 5.9 (swiftlang-5.9.0.124.4 clang-1500.0.38.1)
- Xcode version info 15A5209g
- Deployment target:

**Comment by glessard** [comment]
The same issue is tracked by rdar://112561671

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/68031

**Comment by gottesmm** [comment]
This is fixed on main in the above mentioned PR.
