### ISSUE TITLE
Cross module compilation results in DESERIALIZATION FAILURE

### ISSUE THREAD

**Issue by BlueAnt-Q** [apple/swift#67823]
**Description**

Compiling the attached minimal project crashes the compiler with a DESERIALIZATION FAILURE
"While finishing conformance for protocol conformance to 'PersistentModel' (in module 'SwiftData')"

The app project references the initializer of a model object in a framework module at the point of failure.

If the model object is moved into the app project the compilation succeeds.

**App Module**
```swift
struct PreviewData {
    static func load() {
        let collection = GameCollection()
    }
}
```

**Framework Module**
```swift
@Model
public final class GameCollection {
    public var name: String
    
    public init() {}
}
```

**Steps to reproduce**

Build the project in Xcode or from the command line.

**Environment**

swiftc --version
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.2 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0

xcodebuild -version
Xcode 15.0
Build version 15A5219j

[DeserializationError.zip](https://github.com/apple/swift/files/12303325/DeserializationError.zip)

**Comment by DaveakX** [comment]
Do you by any chance have a string based enum in GameCollection ?  I've seen the same error with the latest beta and the workaround was to switch back to what was required in the first betas, switching to just storing a string and having a transient property deal with the enum get/set.

**Comment by BlueAnt-Q** [comment]
The actual GameCollection class has several properties that have all been adjusted to conform to the current beta sharp edges. The code shown above & in the attached minimal project has only a single String property.

**Comment by BlueAnt-Q** [comment]
The issue seems to be isolated to the serialization of `init`.

I created a static method to invoke the initializer & things seem to work as expected when calling the method from another module.

In GameCollection.swift:

```swift
public static func create() -> GameCollection {
    GameCollection()
}
```

**Comment by patterueldev** [comment]
> The issue seems to be isolated to the serialization of `init`.
> 
> I created a static method to invoke the initializer & things seem to work as expected when calling the method from another module.
> 
> In GameCollection.swift:
> 
> ```swift
> public static func create() -> GameCollection {
>     GameCollection()
> }
> ```

I don't know if my comment is relevant, but this worked in my project.
I'm so stressed why I can't suddenly build my app, and I reduced my test files to minimal until I got to a point where I identified that the culprit behind my package not building is because of the instantiation of my model e.g.
`Category(name: "Sports")`
where `@Model class category { ... }`

But thanks to you, I somehow was managed to salvage my code, I thought I have to completely give up SwiftData. I guess I'll settle with this until the guys at swift actually fixes this, if this is actually an issue and they are on the roadmap to fix it.

**Comment by rkhamilton** [comment]
I also ran into this same compiler crash in my project. I had defined my ModelObjects in a package, and attempted to use them in another package. I get the same DESERIALIZATION FAILURE.

Thank you for identifying the workaround to use a public static func wrapper for the initializer. This allowed me to keep moving forward with my project as well.

This crash appeared for me in Xcode 15 beta 6, and is still present in beta 7. I've sent in feedback FB13038974, but also wanted to pile on here.

**Comment by cianiandreadev** [comment]
Thank you guys. Same issues here (iOS 17 beta 6 & 7).

I have my persistency layer in a Swift Package and same serialization problem when using it in main apps (both Mac, iOS and Watch OS).

Nice to know that at least I'm not alone! 😆

**Comment by BlueAnt-Q** [comment]
Fixed in:
```sh
% swiftc --version
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0

% xcodebuild -version
Xcode 15.0
Build version 15A240d
```

**Comment by up4154** [comment]
> Fixed in:
> 
> ```shell
> % swiftc --version
> swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
> Target: arm64-apple-macosx14.0
> 
> % xcodebuild -version
> Xcode 15.0
> Build version 15A240d
> ```

hey i have the same version but still facing the same issue
