### ISSUE TITLE
[c++ interop] Tests: stop passing _LIBCPP_DISABLE_AVAILABILITY for llvm/17 aligned Swift rebranch

### ISSUE THREAD

**Issue by hyp** [apple/swift#67841]
Some tests need _LIBCPP_DISABLE_AVAILABILITY to be able to use libc++ from older SDKs on CI.

**Comment by naknut** [comment]
Hi again @hyp . I created #72006 a few weeks ago but Ive yet to hear from you, @zoecarver or @egorzhdan . I totally understand if all of you are busy but wanted to send a little reminder anyway.
