### ISSUE TITLE
Compiler crash with for...in statement involving parameter packs

### ISSUE THREAD

**Issue by xAlien95** [apple/swift#67906]
**Description**
Given

```swift
struct Variadic<each T>: Sequence {
  typealias Element = Int
  typealias Iterator = [Int].Iterator

  consuming func makeIterator() -> Iterator {
    fatalError()
  }
}

func foo<each T>(_: repeat each T) -> Variadic<repeat each T> {
  .init()
}
```

the following code is causing a compiler crash, with the error message `Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 578` ([Full output/stack dump](https://github.com/apple/swift/files/12326962/stack.dump.txt)),

```swift
for a in foo {
  print(a)
}
```

and the following one shows the error message `Assertion failed: ((!replacement || replacement->hasError() || gp->isParameterPack() == replacement->is<PackType>()) && "replacement for pack parameter must be a pack type"), function operator(), file SubstitutionMap.cpp, line 237`.

```swift
for a in foo() {
  print(a)
}
```

**Steps to reproduce**
Build the script with the latest Swift development snapshot.

**Expected behavior**
The compiler shouldn't crash.

**Environment**
- Swift compiler version info: `swift-DEVELOPMENT-SNAPSHOT-2023-08-09-a.xctoolchain`, Apple Swift version 5.9-dev (LLVM `79013835e88ccd5`, Swift `cda0fd4c84d72a9`)
- Xcode version info: Xcode 14.2, Build version 14C18
- Deployment target: macOS 12.6.8 (21G725)

**Additional context**
The script compiles if you use an intermediate variable:

```swift
let s = foo()

for a in s {
  print(a)
}
```

**Comment by AnthonyLatsis** [comment]
These are two separate bugs. We should open a second issue one for either of them.

Reduced test case for crash 1:
```swift
struct S<each T> {}
func foo<each T>(_: S<repeat each T>) {}
for _ in foo {}
```

Reduced test case for crash 2:
```swift
protocol P {}
struct S<each T>: P {}
func test<T: P>(_: T) {}
test(S())
```

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/70797

**Comment by vanvoorden** [comment]
@slavapestov I saw a similar error in https://github.com/apple/swift/issues/71258.
