### ISSUE TITLE
Impossible to check if value is an optional

### ISSUE THREAD

**Issue by ulazdins-afs** [apple/swift#67934]
**Description**

Type casting `someValue as? Optional<Any>` always succeeds but it should fail if `someValue` is not optional.

**Steps to reproduce**

```swift
class CastingTestCase: XCTestCase {
    func isOptional(value: Any) -> Bool {
        // 👇 shows Warning: "Conditional cast from 'Any' to 'Optional<Any>' always succeeds"
        if let optionalValue = value as? Optional<Any> {
            print("Hello, I'm an Optional Any: \(optionalValue ?? "")")
            return true
        }
        
        return false
    }
    
    func testOptional() {
        let value: Any = Optional<String>.some("Hello")
        
        XCTAssertEqual(isOptional(value: value), true) // ✅ succeeds
    }
    
    func testNotOptional() {
        let value: Any = "Hello"
        
        XCTAssertEqual(isOptional(value: value), false) // ❌ fails
    }
}
```

**Expected behavior**

The expected behavior would be for both tests to succeed. 

It seems like `someValue as? Optional<Any>` takes `someValue` and wraps with optional instead of checking the actual type of `someValue`. That feels like wrong behavior

**Environment**
```
swiftc -version
swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
Target: arm64-apple-macosx13.0

xcodebuild -version
Xcode 14.3.1
Build version 14E300c
```

**Comment by tbkka** [comment]
This is the correct behavior.  The `as?` operator can be thought of as a "try to convert" operation.  In this case, any value can be converted to `Optional<Any>` by wrapping it first in an `Any` container and then wrapping the result in an `Optional<>` box.

Please read https://github.com/apple/swift/blob/main/docs/DynamicCasting.md for a more detailed technical description of how casting works in Swift.

**Comment by tbkka** [comment]
@hborla - Do we have a document explaining the operation of the `as` operator?   I think of it as an explicit type checker constraint, but that may be over-simplifying.

**Comment by hborla** [comment]
I don't know of any technical specification or dedicated document explaining the `as` operator. `as` is a static coercion, so it's not different from providing a type annotation. What's happening here is that `originalValue as Optional<Any>` will promote `originalValue` with type `Any` to `Optional<Any>`. Since the cast happens at compile time, there's no information that the underlying type of `Any` is another optional, so at runtime you end up with two levels of optionality.

**Comment by ulazdins-afs** [comment]
Thank you for responses :)

I still find the behavior slightly confusing, but it is what it is
