### ISSUE TITLE
Fix SILCombine of convert_escape_to_no_escape ( differentiable_function for OSSA

### ISSUE THREAD

**Issue by meg-gupta** [apple/swift#67992]
The following test fails ownership verification : 

```
// RUN: %target-sil-opt -enable-sil-verify-all %s -sil-combine -sil-combine-canonicalize=false

// SILCombine tests for differentiation-related instructions.

sil_stage canonical

import Swift
import _Differentiation

sil [ossa] @test_convert_escape_to_noescape : $@convention(thin) (@owned @callee_guaranteed (Float) -> Float) -> () {
bb0(%0 : @owned $@callee_guaranteed (Float) -> Float):
  %diff_fn = differentiable_function [parameters 0] [results 0] %0 : $@callee_guaranteed (Float) -> Float
  %1 = convert_escape_to_noescape %diff_fn : $@differentiable(reverse) @callee_guaranteed (Float) -> Float to $@noescape @differentiable(reverse) @callee_guaranteed (Float) -> Float
  %3 = apply undef(%1) : $@convention(thin) (@guaranteed @differentiable(reverse) @noescape @callee_guaranteed (Float) -> Float) -> ()
  destroy_value %1 : $@noescape @differentiable(reverse) @callee_guaranteed (Float) -> Float
  destroy_value %diff_fn : $@differentiable(reverse) @callee_guaranteed (Float) -> Float
  return undef : $()
}

```

**Comment by meg-gupta** [comment]
@asl I hit this issue while working on unrelated OSSA changes. I have created a small repro which I added in the description.

**Comment by meg-gupta** [comment]
I think the issue is that the old differentiable_function is not rauw'ed away and since it is consuming we end up with ownership verification errors. There maybe instances where the old differentiable_function instruction cannot be raw'ed (when we have non-debug_value non-destroy_value users).

**Comment by asl** [comment]
@meg-gupta Interestingly enough, the fix already contained in https://github.com/apple/swift/pull/65605 where we're only doing the optimization when the value has single use (so we will transform differentiable `function_refs`, but not owned pointers).

I will think about how to generalize the transformation
