### ISSUE TITLE
Unable to mutate non-copyable struct in deinit

### ISSUE THREAD

**Issue by karwa** [apple/swift#68115]
**Description**

This fails to compile:

```swift
struct Test: ~Copyable {
    
  mutating func clear() {}

  deinit {
    clear() // error: cannot use mutating member on immutable value: 'self' is immutable
  }
}
```

This seems incongruous with the fact that it is allowed to call mutating members in a method which consumes the struct:

```swift
struct Test: ~Copyable {
  mutating func clear() {}
}

func demo(_ x: consuming Test) {
    x.clear()  // OK
}
```

Surely `deinit` is a sort of "final consumer" of the struct's data and should be allowed to call mutating methods. This is also suggested by the fact that we can end a value's lifetime explicitly using:

```
_ = consume x
```

**Expected behavior**

Expect `deinit` to be able to call mutating methods in a noncopyable struct.

**Environment**

Swift version 5.9-dev (LLVM fd38736063c15cd, Swift a533c63d783f5b8)
Target: x86_64-unknown-linux-gnu

**Comment by karwa** [comment]
Ugh this is actually in the proposal, so it's "working as intended" :(

**Comment by tbkka** [comment]
If you think there are things that were prohibited in SE-390 that should be allowed, please start a thread on forums.swift.org and let's talk about it!

When we wrote SE-390, we deliberately disallowed anything we weren't sure was safe.  As people use this and we learn more about this area, we expect to make this more permissive.  So please let us know how we can improve this area!
