### ISSUE TITLE
The 'consume' operator does not end the lifetime of copyable types

### ISSUE THREAD

**Issue by atrick** [apple/swift#68128]
See https://forums.swift.org/t/should-deinit-be-called-after-explicit-consume-of-reference-type/66920

[consumereference.swift.txt](https://github.com/apple/swift/files/12432702/consumereference.swift.txt)
```
class Object {
    deinit { print("deinit object") }
}

struct Noncopyable: ~Copyable {
    deinit { print("deinit noncopyable") }
}

func testDeinitAfterConsume() {
    do {
        let object = Object()
        print("before consume")
        _ = consume object
        print("after consume")
    }
    
    print()
    
    do {
        let noncopyable = Noncopyable()
        print("before consume")
        _ = consume noncopyable
        print("after consume")
    }
}

testDeinitAfterConsume()
```

The `consume` operator ends the variable's lifetime. The following behavior is incorrect and reflects the fact that the operator is not fully implemented. 
```
before consume
after consume
deinit object
```

**Comment by atrick** [comment]
rdar://114395689 ([GH:#68128] [move-only] The 'consume' operator does not end the lifetime of copyable types)

**Comment by glessard** [comment]
The same issue was reported as https://github.com/apple/swift/issues/68122

**Comment by atrick** [comment]
duplicate: https://github.com/apple/swift/issues/68122

**Comment by gottesmm** [comment]
rdar://113142446

**Comment by nate-chandler** [comment]
Fixed by https://github.com/apple/swift/pull/74109 .
Regression test added in https://github.com/apple/swift/pull/74140 .
