### ISSUE TITLE
Misleading error about operator argument precedence when referencing function in comparison

### ISSUE THREAD

**Issue by Tunous** [apple/swift#68206]
**Description**

I incorrectly referenced a function accepting a type that is used on right hand side of `||` operator in following code sample:

```swift
func a(string: String) -> Bool {
    return b || string == "a"
}

func b(param: String) -> Bool {
    return true
}
```

Swift displayed an error message about operator precedence which is misleading and doesn't point at the actual problem. The shown message is:
```
error: repl.swift:2:17: error: operator argument #2 must precede operator argument #1
    return b || string == "a"
           ~~~~~^~~~~~~~~~~~~
           string == "a"
```

Additionally Xcode suggested fix-it which changed body of the function to invalid:
```swift
return string == ""b
```

**Steps to reproduce**

Enter above sample code in swift repl or any project.

**Expected behavior**

I would expect to see error message similar to following:
```
error: repl.swift:2:12: error: cannot convert value of type '(String) -> Bool' to expected argument type 'Bool'
    return b || true
           ^
````

Which is displayed for this sample code:
```swift
func a(string: String) -> Bool {
    return b || true
}

func b(param: String) -> Bool {
    return true
}
```

**Environment**
- Swift compiler version info 
```
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0
```
- Xcode version info
```
Xcode 15.0
Build version 15A5229h
```
- Deployment target: iOS 17.0

**Comment by AnthonyLatsis** [comment]
@xedin Did you also fix the issue with the fix-it?

**Comment by AnthonyLatsis** [comment]
I can confirm the improvement with the godbolt nightly snapshot.
