### ISSUE TITLE
[cxx-interop] C++ stdlib overlay should provide extensions for `std::u32string`

### ISSUE THREAD

**Issue by egorzhdan** [apple/swift#68211]
The Swift overlay for the C++ standard library provides a few extensions for `std::string` and `std::u16string` for better ergonomics.

These are implemented in https://github.com/apple/swift/blob/main/stdlib/public/Cxx/std/String.swift (plus a small shims header: https://github.com/apple/swift/blob/main/stdlib/public/Cxx/cxxshim/libcxxstdlibshim.h)

The overlay should also provide similar support for `std::u32string`.

**Comment by egorzhdan** [comment]
@CrazyFanFan sure, please feel free to try to tackle this!

**Comment by CrazyFanFan** [comment]
@egorzhdan Hi, I attempted to run the test command: `./swift/utils/run-test --build-dir ./build/Ninja-RelWithDebInfoAssert/swift-macosx-arm64 ./swift/test/Interop.`

There are some cases that did not pass the tests, and it seems that the test cases are unable to access the API I added. Did I miss any parameters? Can you provide me with some suggestions?

Partial error log:
```log
/Users/.../swift/test/Interop/Cxx/stdlib/overlay/std-string-overlay.swift:349:20: error: value of type 'std.u32string' (aka 'std.__1.basic_string<Scalar, char_traits<Scalar>, allocator<Scalar>>') has no member 'description'
  expectEqual(cxx1.description, "")
              ~~~~ ^~~~~~~~~~~

--

********************
********************
Failed Tests (1):
  Swift(macosx-arm64) :: Interop/Cxx/stdlib/overlay/std-string-overlay.swift


Testing Time: 139.06s
  Unsupported      :  31
  Passed           : 501
  Expectedly Failed:   7
  Failed           :   1

```

**Comment by CrazyFanFan** [comment]
I see the newly added API in the build artifact: 
***lib/swift/macosx/CxxStdlib.swiftmodule/arm64-apple-macos.swiftinterface***. 

It is highly likely that there was an issue with the way I invoked the test command.
