### ISSUE TITLE
Certain deinit's on ~Copyable types fail to compile

### ISSUE THREAD

**Issue by rvsrvs** [apple/swift#68328]
**Description**

The following code fails to compile using Xcode 15b8:
```
struct Example: ~Copyable {
    private var failureString: String { "Goodbye." }
    deinit { fatalError("FATAL ERROR: \(failureString)") }
}
```
It produces the error:

    Usage of a noncopyable type that compiler can't verify. This is a compiler bug. Please file a bug with a small example of the bug

**Steps to reproduce**

Cut and paste the above struct into a playground and observe the compiler error

**Expected behavior**

It should compile and, when run, the deinit should cause a fatal error to occur with the correct error message.

**Environment**
- Swift Version: swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.106 clang-1500.0.40.1)
Target: arm64-apple-macosx13.0  
- Xcode Version: Xcode 15.0, Build version 15A5229m 
- Deployment target:  all

**Comment by gottesmm** [comment]
PrunedLiveness does not understand something here. It isn't a move checker bug:

```
frame #15: 0x0000000100a69aa4 swift-frontend`swift::siloptimizer::MoveOnlyObjectChecker::check(llvm::SmallSetVector<swift::MarkUnresolvedNonCopyableValueInst*, 32u>&) at MoveOnlyObjectCheckerUtils.cpp:621:25 [opt]
   618 	
   619 	    // Step 1. Compute liveness.
   620 	    if (!canonicalizer.computeLiveness()) {
-> 621 	      diagnosticEmitter.emitCheckerDoesntUnderstandDiagnostic(markedValue);
   622 	      LLVM_DEBUG(
   623 	          llvm::dbgs()
   624 	          << "Emitted checker doesnt understand diagnostic! Exiting early!\n");
(lldb)
```

@atrick

**Comment by nate-chandler** [comment]
Fixed by https://github.com/apple/swift/pull/68342 .

Tracked internally as rdar://115185992 .
