### ISSUE TITLE
Add a custom `@_spi` kind to expose `BumpPtrAllocator` from SwiftSyntax to ASTGen.

### ISSUE THREAD

**Issue by ahoppen** [apple/swift#68351]
Mark `BumpPtrAllocator` as `@_spi(BumpPtrAllocator)` and change `@_spi(RawSyntax) import SwiftSyntax` in ASTGen.swift to `@_spi(BumpPtrAllocator) import SwiftSyntax`.

That way, ASTGen doesn’t need to import SwiftSyntax with `@_spi(RawSyntax)`.

**Comment by ChiduAnush** [comment]
hello, I am a total newbie to open source. Would be great if I could start woking on this. just confirming, i just need to find and replace right?.
thank you

**Comment by ahoppen** [comment]
Yes, should be quite straightforward. Just note that the apple/swift side of this issue depends on https://github.com/apple/swift/pull/67111 being merged.

**Comment by ChiduAnush** [comment]
what does that mean? sorry if this is a very basic doubt. should I fork the repo and start to work now then? or wait?

**Comment by ahoppen** [comment]
I think it’s probably easiest if you just wait until https://github.com/apple/swift/pull/67111 is merged.

**Comment by ChiduAnush** [comment]
ah that's great. thank you so much. will keep an eye out

**Comment by veryharsh123** [comment]
Can I work on the issue?

**Comment by AnthonyLatsis** [comment]
@ChiduAnush Are you still keen to work on this?

**Comment by ChiduAnush** [comment]
Yes, would be great if you could assign it

**Comment by AnthonyLatsis** [comment]
> Yes, would be great if you could assign it 

You're already assigned!

___

@veryharsh123 Do you mind deferring this issue to @ChiduAnush since he was already assigned?

**Comment by ChiduAnush** [comment]
can you tell me what exactly do you mean by Mark BumpPtrAllocator as @_spi(BumpPtrAllocator)?

**Comment by AnthonyLatsis** [comment]
Sure. `swift/main` depends on `swift-syntax/main`, so you need 2 simultaneous pull requests to pull this off: one in https://github.com/apple/swift-syntax that marks the `BumpPtrAllocator` class as `@_spi(BumpPtrAllocator)` instead of `@_spi(RawSyntax)`, and a second one in this repository that updates the import declaration in `ASTGen.swift`.

**Comment by ChiduAnush** [comment]
please check and let me know if everything is all right.

**Comment by ahoppen** [comment]
I think you also need to change the import of SwiftSyntax in ASTGen.swift to be `@_spi(BumpPtrAllocator)`

https://github.com/apple/swift/blob/95330bcc5bf95a1bf1ff3a00d71d701101af57eb/lib/ASTGen/Sources/ASTGen/ASTGen.swift#L7

**Comment by ChiduAnush** [comment]
I already did that. There are 2 pull requests.

**Comment by ahoppen** [comment]
Oh, sorry. I didn’t see your PR to apple/swift. In general, if you have two PRs that are linked like that, it’s good practice to reference the accompanying PR in the other repo in the PR’s description.
