### ISSUE TITLE
Add `SWIFT_NAME` attributes for all functions in CASTBridging.h

### ISSUE THREAD

**Issue by ahoppen** [apple/swift#68353]
https://github.com/apple/swift/pull/67111 adds `SWIFT_NAME` attributes to many functions in CASTBridging.h. We should add `SWIFT_NAME` attributes to all functions in that file.

**Comment by jakedves** [comment]
Hey Alex, could this be a good starter issue? I've had a look at that PR and it seems it's a pretty standard pattern just renaming C++ parameter names into more Swifty ones.

My only question would be are the function signatures with parameter names already defined somewhere else that we are bringing in, or are we coming up with them in this issue?

Thanks!

**Comment by ahoppen** [comment]
Yes, I think this would be a good starter issue. Do you want to do it?

The parameter names aren’t defined anywhere yet but their naming should be fairly straightforward.

**Comment by ahoppen** [comment]
I expect https://github.com/apple/swift/pull/67111 to get merged soon-ish (within the next couple of weeks). I think the best thing to do, would be if you base your branch on top of https://github.com/apple/swift/pull/67111 but create a PR that targets `main`. After https://github.com/apple/swift/pull/67111 has been merged, you can rebase your branch and we’ll get a clean PR of yours. 

I’d prefer to not target https://github.com/apple/swift/pull/67111 with your changes because that PR is already huge.

**Comment by AnthonyLatsis** [comment]
> Should I work to make a new PR or a PR into https://github.com/apple/swift/pull/67111

Thank you for being considerate! If nothing else comes up there, I’m hoping to land it in a few days time.

**Comment by jakedves** [comment]
Hey Alex & Anthony, made this draft PR, lmk if there's anything that I should change #68492

**Comment by ahoppen** [comment]
Thank you @jakedves. I will look at it after we merge https://github.com/apple/swift/pull/67111.

**Comment by adamcarter93** [comment]
Just spotted this on my journeys to find a good first Swift task for myself and saw that #67111 is now merged in 🎉 

@ahoppen Does this draft PR need a pair of eyes on it?
Maybe the label needs removing too as it looks like it’s basically done 👌🏻

**Comment by adamcarter93** [comment]
> @adamcarter93 See https://github.com/apple/swift/pull/70849#discussion_r1523087470. I think it’s OK to close the issue at this point, but we could keep it open if you wish to work on what remains to be done.

Sure I'll take a look!

**Comment by thefool76** [comment]
is this open to work?

**Comment by ahoppen** [comment]
It looks like this issue has already been resolved [ASTBridging.h](https://github.com/apple/swift/blob/main/include/swift/AST/ASTBridging.h) has `SWIFT_NAME` attributes on all of its declarations.
