### ISSUE TITLE
Strange behavior with `Hashable`

### ISSUE THREAD

**Issue by Vaida12345** [apple/swift#68424]
**Description**
In this following code:
```swift
struct Color: Hashable {
    let name: String
    let value: Double
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(self.name)
    }
}

var set: Set<Color> = [.init(name: "a", value: 0)]
print(set.insert(Color(name: "a", value: 2)))
print(set) // two values
```

The new color was successfully inserted, but it shouldn't right? As in this `Hashable` implementation, I only fed the `name`, not the `value`.

**Steps to reproduce**

Please refer to the *description*.

**Expected behavior**

The new color shouldn't been inserted.

**Environment**
- Swift compiler version info: 5.8.1 and 5.9
- Xcode version info: 14.3.1 and 10.0 beta 8
- Deployment target: any

**Comment by glessard** [comment]
While you do get a hash collision, your two instances of `Color` are not _equal_. Equality is the ultimate discriminator. Note that even with a correctly-implemented, high-quality hashing function, there is a non-zero chance that two unrelated items will get the same hash value. Your partial hashing effectively increases the likelihood of a hash collision.
