### ISSUE TITLE
Static property (mehtod) added by ExtensionMacro is not visible to compiler

### ISSUE THREAD

**Issue by red-beeard** [apple/swift#68515]
**Description**
When I try to access a static property (function) from another file, I get an error: "Type 'TypeName' has no member 'member'".

**Steps to reproduce**
1. Create a macro that generates a static property or method
2. Attach the macro to the model
3. Access a static method or property from another file

**Expected behavior**
The code compiles without errors.

<img width="336" alt="Снимок экрана 2023-09-14 в 12 49 35" src="https://github.com/apple/swift/assets/54406512/60210d6c-cc6d-4aac-a5ac-ee33c529ce60">
<img width="619" alt="Снимок экрана 2023-09-14 в 12 49 55" src="https://github.com/apple/swift/assets/54406512/fd2145a9-9eef-4a0d-bbc2-537d7f216d6f">

**Environment**
- Swift compiler version info swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) Target: x86_64-apple-macosx13.0
- Xcode version info: Xcode 15.0 Build version 15A240d
- Deployment target: iOS 17.0

**Additional context**

Swift forum [topic](https://forums.swift.org/t/the-static-method-generated-by-extensionmacro-is-not-visible-to-compiler/67075)
A [demo](https://github.com/red-beeard/demo-macro) that reproduces this problem

**Comment by red-beeard** [comment]
Still reproduce with environment
- Swift compiler version info: `1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.51 clang-1500.1.0.2.2) Target: arm64-apple-macosx14.0`
- Xcode version info: `Xcode 15.1 Build version 15C5042i`
- Deployment target: iOS 17.0

**Comment by xedin** [comment]
Looks like this has been fixed by https://github.com/apple/swift/pull/71717/commits/a6d53aa75ad0743e0d3e276e6562c9acc85407b3 . Please use swift.org Trunk Development toolchain to verify, if something comes up please re-open the issue.

**Comment by red-beeard** [comment]
Great, I downloaded swift-DEVELOPMENT-SNAPSHOT-2024-06-11-a. It fixes the problem. Maybe other similar problems (#68683 #69013 #70085) are fixed.
