### ISSUE TITLE
An unempty OptionSet.contains(param) returns true if the given parameter is an empty OptionSet.

### ISSUE THREAD

**Issue by ShikiSuen** [apple/swift#68537]
**Description**
An unempty OptionSet.contains(param) returns true if the given parameter is an empty OptionSet.

**Steps to reproduce**
```swift
import AppKit

let a: NSEvent.ModifierFlags = []
let b: NSEvent.ModifierFlags = .shift
print(b.contains(a))
```

**Expected behavior**
Returning "False" except: Only an empty OptionSet contains an empty parameter.

**Environment**
- Swift compiler version info: swift-driver version: 1.75.2 Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)
- Xcode version info Xcode 14.3.1
- Deployment target: macOS 13
<img width="558" alt="image" src="https://github.com/apple/swift/assets/3164826/8564c183-ea32-46ae-92bc-92a17b6483c0">

**Comment by ShikiSuen** [comment]
Update: Looks like this is likely an intended behavior -- it mathematically makes sense.

If this really is an intended behavior, then please close this issue.

**Comment by AnthonyLatsis** [comment]
This is indeed [expected](https://github.com/apple/swift/issues/52520#issuecomment-1108358258). The behavior can be inferred from the [`SetAlgebra` axioms](https://developer.apple.com/documentation/swift/setalgebra#Conforming-to-the-SetAlgebra-Protocol): `OptionSet.contains(_:)` when `Element == Self` [forwards](https://github.com/apple/swift/blob/19271140ef6248aa9e9d6c10970b054a5d9b8cfc/stdlib/public/core/OptionSet.swift#L217) to `isSuperset(of:)`, `x.isSuperset(of: y)` implies `x.union(y) == x`, and `x.union([]) == x`.

But to be fair, this is hardly clear at all to the casual reader and there seems to be nothing stating that `x.isSuperset(of: [])`, or that the `contains(_:)` in question is equivalent to `isSuperset(of:)`, so please feel free to report this in a new issue.

@natecook1000 Are we documenting this behavior anywhere?

**Comment by stephentyrone** [comment]
This is actually pretty weird mathematically; the set {1, 2, 3} does not contain the empty set. OptionSet, as a pragmatic consideration for how it actually gets used, conflates the base set with its power set, leading to this confusion. Unfortunately, there's not a lot we can do about this other than documenting the behavior of `.contains()` more clearly.

(The "power set" of a set S is the set of all subsets of S; using our example from before, the power set of {1, 2, 3} is {∅, {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}}, which _does_ contain the empty set ∅.)

**Comment by ShikiSuen** [comment]
... Okay. I admit that my mathematic is of bull****.
(My bachelor degree is not science. I'm a music bachelor. My math in high school was bad, too. I learnt Swift by myself, still.)

**Comment by AnthonyLatsis** [comment]
> This is actually pretty weird mathematically; the set {1, 2, 3} does not contain the empty set

Between sets, containment is synonymous to inclusion (⊆), so I think it does make sense for `OptionSet where `Element == Self`. IMO In this sense the things that are off about this particular `contains` is that the parameter label is still `member` rather than `subset`, and that the doc comment is not specialized to speak about inclusion rather than membership.
