### ISSUE TITLE
Assert that position is within buffer bounds in `BridgedSourceLoc.init`

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#68610]
Currently, we construct a null location if the input position is out of bounds, meaning the position is invalid or the buffer is null/wrong. Neither is ever expected to happen in ASTGen, and if it does, we don’t want it to go unnoticed or cause a less informative failure downstream.

**Comment by saehejkang** [comment]
I would like to pick up this issue please 👍🏽

**Comment by saehejkang** [comment]
this issue can now be closed @AnthonyLatsis

**Comment by saehejkang** [comment]
@AnthonyLatsis I did not know how else to reach out to you. Do you have any recommendations for `good first issues` that are up to date and not super old? Or are there any regular issues that are good for me to work on?
