### ISSUE TITLE
The extension macro designed to add `Sendable` conformance generates an unexpected warning

### ISSUE THREAD

**Issue by Matejkob** [apple/swift#68728]
**Description**  
The extension macro designed to add `Sendable` conformance generates an unexpected warning.

**Steps to Reproduce**  
1. Using Xcode 15.0, implement a `Sendable` macro as shown in the following link: [Apple Swift GitHub Repository](https://github.com/apple/swift/blob/40362469cacce597944f38fdba8a245ff0335f46/test/Serialization/Inputs/def_macro_plugin.swift#L55C1-L78C2).

    ```swift
    public struct SendableMacro: ExtensionMacro {
      public static func expansion(
        of node: AttributeSyntax,
        attachedTo: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
      ) throws -> [ExtensionDeclSyntax] {
        if protocols.isEmpty {
          return []
        }
    
        let sendableExtension: DeclSyntax =
          """
          extension \(type.trimmed): Sendable {}
          """
    
        guard let extensionDecl = sendableExtension.as(ExtensionDeclSyntax.self) else {
          return []
        }
    
        return [extensionDecl]
      }
    }
    
    @main
    struct AddSendablePlugin: CompilerPlugin {
        let providingMacros: [Macro.Type] = [
            SendableMacro.self
        ]
    }
    ```

2. Create an interface:

    ```swift
    @attached(extension, conformances: Sendable)
    public macro AddSendable() = #externalMacro(module: "AddSendableMacros", type: "SendableMacro")
    ```
  
3. Utilize the macro in an executable:

    ```swift
    import AddSendable
    
    @AddSendable
    final class Message {
    }
    ```
4. Build it using `swift build`.
5. Produced warning:
```
/var/folders/lj/1_d6kbt94zb2wb7dtqvnl4kr0000gn/T/swift-generated-sources/@__swiftmacro_17AddSendableClient7Message0aB0fMe_.swift:1:1: warning: conformance to 'Sendable' must occur in the same source file as class 'Message'; use '@unchecked Sendable' for retroactive conformance
extension Message: Sendable {
^
AddSendable/Sources/AddSendableClient/main.swift:4:7: note: in expansion of macro 'AddSendable' here
final class Message {
      ^~~~~~~~~~~~~~~
```

**Environment**
- Swift compiler version: swift-driver 1.87.1, Apple Swift 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Xcode version: 15.0 (Build version 15A240d)
- Deployment target: macOS 14.0 (23A339)

**Comment by mansbernhardt** [comment]
I’m running into this warning as well and it is still an issue in Xcode 15.1 beta 3. Perhaps it has been adressed in later builds? Ping @hborla

**Comment by hborla** [comment]
It's still an issue. I've put up a fix in https://github.com/apple/swift/pull/70185

**Comment by SimplyDanny** [comment]
Has the fix for this issue been cherry-picked to the `release/6.0` branch yet? From Git history scraping and the fact that I still see the warning in the latest nightly toolchain when `Sendable` conformance is applied by a macro, I conclude that's still absent from the release branch. Are there any plans to apply it before the official release?
