### ISSUE TITLE
Error for switch expression with Swift 5.9

### ISSUE THREAD

**Issue by roanutil** [apple/swift#68764]
**Description**
When using Swift 5.9's switch expression, the compiler may inappropriately error if the expression includes an optional cast (`as?`). 

**Steps to reproduce**
[Fiddle example](https://swiftfiddle.com/wm67vivsdjdmfbfja5dvapgdbm)

```swift
final class Box {
    private var _value: Any

  func value<V>(as type: V.Type) -> V? {
    switch "\(type)" {
    case "\(Double.self)":
      _value as? V
    case "\(Float.self)":
      _value as? V
    default:
      nil
    }
  }

  init(value: Any) {
    self._value = value
  }
}
```

Attempting to build the above code with the 5.9 compiler, will result in an error, `error: variable '<unknown>' captured by a closure before being initialized` on each of the `as?` casts. The above example is contrived but I ran into this problem in some tests for production code.

**Expected behavior**
I expected the example code to compile and run. Swift 5.9 added support for switch expressions as described in [SE-0380](https://github.com/apple/swift-evolution/blob/main/proposals/0380-if-switch-expressions.md). Each case is a single line and single expression.

**Environment**
- swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Version 15.0 (15A240d)

**Comment by hamishknight** [comment]
Reduced down to:

```swift
func foo<V>(_ x: Any) -> V? {
  switch 0 {
  default:
    x as? V
  }
}
```

I suspect this may have been fixed by https://github.com/apple/swift/pull/68705

**Comment by hamishknight** [comment]
Okay yes I can confirm this is fixed by https://github.com/apple/swift/pull/68705, please verify using a trunk development snapshot from https://swift.org/download. I've filed https://github.com/apple/swift/issues/68802 for the underlying definite initialization bug.

**Comment by hamishknight** [comment]
Test added in https://github.com/apple/swift/pull/68803, and opened 5.10 cherry-pick https://github.com/apple/swift/pull/68804
