### ISSUE TITLE
Variable that is in scope is not found.

### ISSUE THREAD

**Issue by alexwal** [apple/swift#68825]
**Description**
Swift compiler cannot find a variable in scope when in fact it is in scope.

**Steps to reproduce**
```swift
func x(a: Any) {
    let _ = a is a  // Cannot find type 'a' in scope
}
```

**Expected behavior**
A more useful error message.

**Environment**
- Swift compiler version info swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) Target: arm64-apple-macosx14.0
- Xcode version info Xcode 15.0 Build version 15A240d
- Deployment target: iOS 17.0

**Comment by xedin** [comment]
I think this is correct, the diagnostic talks about a "type" not being found because it points to the second `a` after `is` keyword.

**Comment by AnthonyLatsis** [comment]
Yeah, the error itself is expected. I labeled this as a diagnostic QoI issue thinking we could come up with a better message for this case.

**Comment by xedin** [comment]
Something like - `type check operator 'is' expects a type on its right-hand side (got: parameter 'a')`?

**Comment by dancamarotto** [comment]
@xedin @AnthonyLatsis what error messages should be expected for:

```swift
func x(a: Any) {
    _ = a is a // ?
    _ = a as b // ?
}
```

**Comment by AnthonyLatsis** [comment]
> what error messages should be expected for:
> 
> ```swift
> func x(a: Any) {
>     _ = a is a // ?
>     _ = a as b // ?
> }
> ```

What do you think?

**Comment by AnthonyLatsis** [comment]
> Something like - `type check operator 'is' expects a type on its right-hand side (got: parameter 'a')`? 

I’ll take that. Or `expected type on right-hand side of type-casting operator 'is', but found <descriptive decl kind> <base name>` (type-casting operator is a TSPL term).

**Comment by dancamarotto** [comment]
> > Something like - `type check operator 'is' expects a type on its right-hand side (got: parameter 'a')`?
> 
> I’ll take that. Or `expected type on right-hand side of type-casting operator 'is', but found <descriptive decl kind> <base name>` (type-casting operator is a TSPL term).

I like this message and I find it to be very descriptive, but I have a couple of questions:
- the `'is'` can't be hard-coded in the message as we might have situations where the operator is `as` instead - but I couldn't figure out how to dynamically get the cast operator to build the message.
- Taking the example code above, what would be printed as the `<descriptive decl kind>` ?

Also, I appreciate your help as this is my first time working in this project.

**Comment by xedin** [comment]
> the 'is' can't be hard-coded in the message

"as" is not a type check operator though, it's a type cast operator so we'd need a separate message for that I think.

>  what would be printed as the <descriptive decl kind>

It's going to be 'parameter' but I think with some recent changes we can actually use `const ValueDecl *` like: `"type check operator 'is' expects a type on its right-hand side (got: %0)", (const ValueDecl *)`

**Comment by dancamarotto** [comment]
@xedin but currently both `is` and `as` fall to the same function under `TypeCheckType` - hence using the message `type check operator 'is' expects...` would be inappropriate as it would be presented for when `as` is used.

That's why in my PR I had changed the message to `cast expression expects a type on its right-hand side (got: %0)`

**Comment by AnthonyLatsis** [comment]
I think it’s fine to simply say "type-casting operator" without mentioning exactly which one it is.
