### ISSUE TITLE
"Looking for Assistance and Community Support in Apple Repository Contributions"

### ISSUE THREAD

**Issue by satyampsoni** [apple/swift#68878]
Greetings,

I am a newcomer to this platform and am keen on acquiring knowledge about contributing to Apple's repositories. I am in search of guidance regarding the initial steps to engage in this endeavor. Additionally, I am curious if there exists a supportive community that can assist me in clarifying any doubts I may encounter during this process. I would be immensely grateful for any information or assistance provided in this regard. My intention is to mark this inquiry as resolved once I receive a satisfactory response.

Thank you for your consideration.

**Comment by Anthony-Eid** [comment]
https://github.com/apple/swift/blob/581b9d8a95c52ef8746d6b21665fd90b75a2673e/CONTRIBUTING.md

I would start by reading the README and documentation on how this project works. Then checking out issues tagged with "good first issue".  Also, postings new issues are usually meant for bugs and feature requests not asking questions.

**Comment by Saqibadnan0011** [comment]
Let me handle that and help out. Just waiting for  your response

**Comment by satyampsoni** [comment]
> I would start by reading the README and documentation on how this project works. Then checking out issues tagged with "good first issue".

Thanks for the help. 

> Also, postings new issues are usually meant for bugs and feature requests not asking questions.

I am really sorry about that, I couldn't find a community around it to ask the question so I asked it here and that is the reason why I mentioned I'll make the issue as resolved as soon as I get a satisfactory response. Apologies!

**Comment by Anthony-Eid** [comment]
@satyampsoni No worries! I'm realizing now that I was too blunt in my response and I didn't direct you to the correct place to ask for help either.

Here's a link to the general swift information: https://www.swift.org/about/ and a link to the swift forms where you could ask questions: https://forums.swift.org. Also, reading the README of the code could help as well.

I wish I could help more but I'm in the same boat as you. I just graduated and compilers was one of my favorite classes so I'm looking to learn enough to be able to contribute. Hopefully we both get to contribute in the future, good luck learning!!
