### ISSUE TITLE
Incorrect tuple destructure

### ISSUE THREAD

**Issue by mattyoung** [apple/swift#68915]
**Description**

The compiler generates incorrect tuple destructure code, where the 2nd and rest of the tuple elements get the wrong values.

**Steps to reproduce**
Compile and run this on the command line:

```
struct Foo {
    let value: Int

    let (aaa, bbb) = ("aaa", "bbb")     // bbb is wrong! it's "aaa" but should be "bbb"

        // uncomment this to make the compiler fail with non-zero exit
//    let (z1, z2, z3) = ("one", 1, Double.pi)


    func tellMe() {
        print(foo.aaa)
        print(foo.bbb)          // output:  aaa


        assert(aaa == "aaa")
        assert(bbb == "bbb", "bbb should be bbb but it's \(bbb)")
    }

}


let foo = Foo(value: 1)


foo.tellMe()




print("Hello")
```

**Expected behavior**
`let (aaa, bbb) = ("aaa", "bbb")` `bbb` should get "bbb", but it gets "aaa"

Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)

**Comment by tbkka** [comment]
Re:  rdar://116343732

**Comment by tbkka** [comment]
Probably the same underlying issue as #68916
