### ISSUE TITLE
[Source compatibility suite] swift-testing failing to build on ubuntu

### ISSUE THREAD

**Issue by justice-adams-apple** [apple/swift#69279]
**Description**
The [swift-testing](https://github.com/apple/swift-testing) project is failing to build on Ubuntu.
The error seen in the log is
```
swift-testing/Sources/TestingInternals/Discovery.cpp:15:10: fatal error: 'span' file not found
#include <span>
         ^~~~~~
1 error generated.
```

* [Build log](https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/314/artifact/build/swift-source-compat-suite/XFAIL_swift-testing_5.0_BuildSwiftPackage.log)

**Steps to reproduce**
To reproduce the issue, you can use the [source compatibility suite](https://github.com/apple/swift-source-compat-suite) on an Ubuntu machine or with the nightly `swiftlang/swift:nightly-5.10-focal` docker image and run
```
./runner.py --swift-branch main --projects projects.json --include-actions 'action.startswith("Build")' --include-repos 'path == "swift-testing"' --swiftc /usr/bin/swiftc --build-config debug
```

**Expected behavior**
The project should build fine

**Environment**
```
Swift version 5.11-dev (LLVM 4b3046825b8aba9, Swift 41dc4661084f76b)
Target: x86_64-unknown-linux-gnu
```
https://ci.swift.org/job/swift-source-compat-suite-ubuntu-2004/314/

rdar://117215039

**Comment by stmontgomery** [comment]
Fixed by apple/swift-testing#90
