### ISSUE TITLE
Closure as repetition pattern in pack expansion not allowed

### ISSUE THREAD

**Issue by AnthonyLatsis** [apple/swift#69282]
**Steps to reproduce**

https://github.com/apple/swift/blob/251becbbddd3710a272bbd5291efd419f24643b6/test/Constraints/pack-expansion-expressions.swift#L611-L614

**Expected behavior**

The above test case and SE-0393, which is marked as implemented and doesn’t place limitations on the kind of expression used as a repetition pattern, suggest this should work.

**Subissues**

* #66917

**Environment**
- Swift version 5.11-dev (LLVM 5601e23279f85d8, Swift 140caf63be3f0fe)

**Comment by xedin** [comment]
I think we have a few dupes of this already, pack expansions in closures are just not yet implemented.

**Comment by xedin** [comment]
Yes, I am sure a saw this before, anything reported against pack and closure is effectively the same thing with different manifestation.

**Comment by AnthonyLatsis** [comment]
Let's have this serve as an umbrella issue so that whoever implements this has easy access to all reported examples.

**Comment by xedin** [comment]
Sounds good!

**Comment by maximkrouk** [comment]
I'm not sure if it's related, was just searching for the solution for some other issue, but recently got this one, which seems kinda related to the topic (Xcode doesn't show any description for the error)

I'd like to implement those functions. It might be not possible yet and in that case compiler should return some human readable error, however the code compiles successfully if those functions are not used, and compilation fails as soon as I add a caller.

```swift
/// Packs function parameters into a single tuple parameter
func pack<each Arg, Output>(
  _ f: @escaping (repeat each Arg) -> Output
) -> ((repeat each Arg)) -> Output {
  return { (arg: (repeat each Arg)) in
    f(repeat each arg)
  }
}

/// Destructures single tuple function parameter into separate args
func unpack<each Arg, Output>(
  _ f: @escaping ((repeat each Arg)) -> Output
) -> (repeat each Arg) -> Output {
  return { (arg: repeat each Arg) in
    f((repeat each arg))
  }
}

//// Compilation succeeds if this code is commented
//// Fails with "nonzero exit code" otherwise
//
//func test() {
//  typealias OriginalSignatute = (Int, String, Bool) -> Void
//  typealias PackedSignature = ((Int, String, Bool)) -> Void
//  typealias UnpackedSignature = OriginalSignatute
//
//  let f: OriginalSignatute = { int, string, bool in
//    print(int, string, bool)
//  }
//
//  let f_packed: PackedSignature = pack(f)
//  let f_packed_unpacked: UnpackedSignature = unpack(f_packed)
//}
```

**Comment by AnthonyLatsis** [comment]
That’s a different beast, opened #69320. This one is about applying `repeat` to a closure.

> UPD: Collected some examples of weirdly failing variadic generics into a package

Thanks! We already have an issue for the first error in `Handler.swift` (#68369), I’ll handle reporting the rest. Please consider reporting any future issues directly to us as well.
