### ISSUE TITLE
Can Swift invoke C++ library directly?

### ISSUE THREAD

**Issue by MarcSteven** [apple/swift#69316]
**Motivation**

I know Swift can invoke C directly, but when invoked C++ library, it always need bridge head file using Objective-C, I know someone is doing this job, but two years was passed, I reviewed the blog about the release , cannot find the feature .

**Solution**

**Alternatives considered**

**Comment by icanzilb** [comment]
Hey Marc, maybe I don't understand some subtlety in your question but according to swift.org using C++ libraries is supported: https://swift.org/documentation/cxx-interop/

**Comment by MarcSteven** [comment]
@icanzilb  I know  in order for Swift code to consume C++ code we must create an Objective-C wrapper or bridging code earlier. You mean it can support C++ libraries without bridge header......
