### ISSUE TITLE
Typo in NameLookup.cpp

### ISSUE THREAD

**Issue by varundhand** [apple/swift#69394]
**Description**

There is a typo in NameLookup.cpp file. The word _"paramter"_ is used, and it should be corrected to _"parameter"_ for accuracy and clarity in the code.

**Comment by AnthonyLatsis** [comment]
For the future: Reporting typos and such is OK and welcome as a first-time contribution exercise, but, *otherwise*, I don’t think an issue of this caliber is worth a report if you’re about to open a pull request that fixes it.

**Comment by varundhand** [comment]
I'll keep that in mind from next time.
