### ISSUE TITLE
[Windows] Support skipping update-checkout in utils/build-windows-toolchain.bat

### ISSUE THREAD

**Issue by shahmishal** [apple/swift#69483]
To build the nightly toolchain for Windows, we need to check out specific SHA. However, currently utils/build-windows-toolchain.bat overwrites the checkout from CI. We need a way to disable update-checkout in utils/build-windows-toolchain.bat

**Comment by compnerd** [comment]
`SKIP_UPDATE_CHECKOUT` should skip over that step. With `build.ps1`, we should be able to structure the tools however we need as it focuses only on the build portion and leaves syncing the repositories to the developer.
