### ISSUE TITLE
build-windows-toolchain.bat does not exit with non-zero exit code

### ISSUE THREAD

**Issue by compnerd** [apple/swift#69583]
Windows builds are currently broken due to a syntactic error in LLDB or Swift:

https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/986/console

Changes to LLDB should be gated on Windows Swift toolchain builds to prevent this type of regression.

**Comment by compnerd** [comment]
You're welcome, happy to see the error tracking resolved. I think that we still need to track down the issue as we won't be able to get a green build otherwise.

**Comment by shahmishal** [comment]
Can you file a new GitHub issue with the Windows failure?
