### ISSUE TITLE
dyld: Symbol not found _swift_getExtendedExistentialTypeMetadata

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift#69606]
**Description**

The generated code in DemoKit contains a call to `_swift_getExtendedExistentialTypeMetadata`. 

However such symbol does not exist on Swift 5.6 Runtime.

So it will cause a dylb crash.

Full context: https://forums.swift.org/t/67842/4

**Steps to reproduce**

1. Download [DemoKit.zip](https://github.com/apple/swift/files/13239372/DemoKit.zip)
2. Run DemoKitTests on Xcode 15(Swift 5.9 + iOS 17 SDK) with iOS 15.5(19F70) Simulator(Swift 5.6 Runtime)

**Expected behavior**

Not crash

**Comment by slavapestov** [comment]
This was fixed by https://github.com/apple/swift/pull/69475

**Comment by Kyle-Ye** [comment]
> This was fixed by #69475

This is effecting app build by Xcode 15.0. Should it be cherry-picked and release a new Xcode version before we close the issue 🤔
