### ISSUE TITLE
Windows CI seems broken

### ISSUE THREAD

**Issue by neonichu** [apple/swift#69646]
```
-- Installing: T:/Library/curl-8.4.0/usr/lib/x64/cmake/CURL/CURLConfig.cmake
[0/1][  0%][0.023s] Install the project...
[2023-11-03 19:49:55] Finished building 'C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\curl' to 'T:\x64\curl-8.4.0' for arch 'x64' in 00:00:38.1017227

Copy-Item : Could not find a part of the path 'C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\icu\icu4c\'.
At C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift\utils\build.ps1:971 char:7
+       Copy-Item $SourceCache\swift-installer-scripts\shared\ICU\CMake ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand
 

swift-ci@EC2AMAZ-JCVOGM7 C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows>set ec=1 

swift-ci@EC2AMAZ-JCVOGM7 C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows>del C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows\swift\utils\..\..\tmp\call-build.cmd 

swift-ci@EC2AMAZ-JCVOGM7 C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows>exit /b 1 
Build step 'Execute Windows batch command' marked build as failure
```

These errors seem to be happening continuously today, e.g. on
https://github.com/apple/swift-package-manager/pull/7047
https://github.com/apple/swift-package-manager/pull/7023

**Comment by neonichu** [comment]
cc @compnerd @shahmishal

**Comment by compnerd** [comment]
This doesn't make sense:

> swift-ci@EC2AMAZ-JCVOGM7 C:\Users\swift-ci\jenkins\workspace\swiftpm-PR-windows>set "args=--scheme main --skip-repository swiftpm --skip-repository ninja --skip-repository icu" 

If you look at build-windows-toolchain.bat on main, you will find that it does not have the `--skip-repository icu` in there. I don't know where this is coming from.

**Comment by shahmishal** [comment]
Jenkins Job updated to not skip ICU repo now it's part of update-checkout.

**Comment by shahmishal** [comment]
This is resolved now.

**Comment by finagolfin** [comment]
@shahmishal, the Windows CI for swift-driver has been [failing with the same ICU error](https://ci-external.swift.org/job/swift-driver-PR-windows/679/console) for [the last week](https://ci-external.swift.org/job/swift-driver-PR-windows/672/console): maybe more Swift repos need to be adjusted for this issue?

**Comment by shahmishal** [comment]
This is resolved for swift-driver PR testing now.
