### ISSUE TITLE
smoke test and merge may allow early submission

### ISSUE THREAD

**Issue by compnerd** [apple/swift#69650]
https://github.com/apple/swift/pull/69591

It is unclear what the timeline here was.  The Windows test indicates that it marked it as a failure but that failure never showed up on the PR.  It appears that the CI merged without completion of the Windows job.  It would be good to understand what happened here.

**Comment by shahmishal** [comment]
We should drop support for test and merge. Users can now use "auto-merge" feature to avoid waiting for testing to complete. 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by shahmishal** [comment]
https://forums.swift.org/t/dropping-support-for-swift-ci-test-and-merge-in-favor-of-auto-merge-feature-on-github/68297
