### ISSUE TITLE
Issues with NumberFormatter since iOS 17.0

### ISSUE THREAD

**Issue by TheMalip** [apple/swift#69666]
**Description**
Hey there!
Since iOS 17 I’m having issues using the NumberFormatter in my code. Here is a small example:

```swift
struct ContentView: View {
	@State var number1: Double? = 0
	@State var number2: Double? = 0

    var body: some View {
        VStack {
		TextField("number1", value: $number1, format: .number.precision(.fractionLength(2)))
		TextField("number2", value: $number2, format: .number.precision(.fractionLength(2)))
        }
        .padding()
    }
}
```

**Steps to reproduce**
Using this code under iOS 16.x everything works as expected, but starting with iOS 17 the NumberFormatter is not working properly. With input such as „2“, „3,“, „4.00000“, „5.000“ (inputs which are not changing the underlying value) and so on the UI is not updating anymore and the values are not getting formatted. This can be fixed manually using an own formatter such as:

```swift
var myFormatter: NumberFormatter = {
	let formatterIntern = NumberFormatter()
	formatterIntern.numberStyle = .decimal
	formatterIntern.minimumFractionDigits = 2
	formatterIntern.maximumFractionDigits = 2
	return formatterIntern
}()
```

But after using this an other bug appears: Once any value is set to nil (eg: users deletes input) the corresponding variable can’t be set anymore. After typing a new value to this textField and on leaving it the value gets immediately deleted. 
In this state the app is getting completely useless.

**Expected behavior**
NumberFormatted works same as prior iOS 17.

**Screenshots**
[Simulator Screenshot - iOS 16.4](https://github.com/apple/swift/assets/60074504/2f6a3edc-952e-4c0a-a059-0618034a22fe)
[Simulator Screenshot - iOS 17](https://github.com/apple/swift/assets/60074504/317ab669-b876-4e1d-9773-7f28c159813d)

**Tested under**
- Xcode 15.0.1
- Xcode 15.1 Beta 2
Both with Deployment Target 16.0

**Comment by AnthonyLatsis** [comment]
This looks a lot more like a SwiftUI issue than an issue with Foundation‘s NumberFormatter. That said, this repository — most notably — hosts the Swift compiler, standard library, and SourceKit, and hence does not track issues with closed-source Apple frameworks. Please report this to Apple’s feedback assistant instead.

cc @parkera Just in case.
