### ISSUE TITLE
Some function calls with operators have incorrect syntax highlighting on Xcode

### ISSUE THREAD

**Issue by Visckmart** [apple/swift#69736]
**Description**

Some function calls' syntax highlighting are not correct. I've noticed this happening when the first argument is an operator such as `>` and the first argument label is omitted. In such cases, the function name is colored black instead of the color of a function name declared in the same project. From what I've tested this happens to all functions, static methods and instance methods.

The code compiles and the Jump to Definition action still works as expected. The color seems to be the only problem here.

**Steps to reproduce**

This image describes multiple situations with right and wrong syntax highlighting to help us nail down the problem.
<img width="1311" alt="Xcode_Screenshot" src="https://github.com/apple/swift/assets/5529302/5371b9f2-27a9-46eb-976c-f53cb2012039">

<details>
<summary>Code</summary>

    func comparison(_ operation: (Int, Int) -> Bool) { }
    comparison(>)
    comparison(<)
    
    // ❌ Extra argument
    func comparisonAndValue(_ operation: (Int, Int) -> Bool, value: Int) { }
    comparisonAndValue(>, value: 10)
    
    // ❌ Named operation type
    typealias IntComparison = (Int, Int) -> Bool
    func intComparison(_ operation: IntComparison) { }
    intComparison(>)
    
    // ❓ Some operators work
    comparison(>=)
    comparison(<=)
    comparison(==)
    comparison(!=)
    
    // ✅ Named operation value
    let greaterThan: (Int, Int) -> Bool = (>)
    comparison(greaterThan)
    
    // ✅ Named argument
    func comparisonWithName(operation: (Int, Int) -> Bool) { }
    comparisonWithName(operation: >)
    
    // ✅ Variadic parameter
    func multipleComparisons(_ operations: ((Int, Int) -> Bool)...) { }
    multipleComparisons(>)
    
    // ❓ Does not compile but the color is correct, might help with the debugging
    comparison(>,)
    comparison(>!)
    
    
    class MyClass {
        func comparison(_ operation: (Int, Int) -> Bool) { }
        static func comparison(_ operation: (Int, Int) -> Bool) { }
    }
    
    MyClass().comparison(>)
    MyClass.comparison(>)
</details>

**Expected behavior**

The names of the functions/methods should be colored according to the selected theme, and not always black as they are being colored now.

**Environment**
- Swift compiler:
  - swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) Target: arm64-apple-macosx13.0
  - swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.51 clang-1500.1.0.2.2) Target: arm64-apple-macosx13.0
  - Apple Swift version 5.11-dev (LLVM e22c96610989bdb, Swift bd372c2d6861ce3) Target: arm64-apple-macosx13.0 (This is the October 30th 2023 trunk developent snapshot)
- Xcode version:
  - 15.0.1 (15A507)
  - Xcode 15.1 beta (15C5042i)
- Deployment target: macOS 13.5

**Additional context**
I tried taking a look at the SourceKit output and it looked fine for me, which might indicate this is a bug on Xcode and not on the open-source tools, but I don't have a lot of experience on it so someone with more experience might want to check it one more time.

**Comment by bnbarham** [comment]
> I tried taking a look at the SourceKit output and it looked fine for me, which might indicate this is a bug on Xcode and not on the open-source tools, but I don't have a lot of experience on it so someone with more experience might want to check it one more time.

Yeah, this is on the Xcode side. A feedback request would be appreciated, though I have also passed it along 🙇‍♂️
