### ISSUE TITLE
[cxx-interop] NSNotification.Name has no member

### ISSUE THREAD

**Issue by tcollins590** [apple/swift#69914]
**Description**
I have a swift package that I am trying to add c++ interop to. The package compiles until I add `swiftSettings: [.interoperabilityMode(.Cxx)]`. I'm then presented with a few errors in my existing swift code

The code
```swift
NotificationCenter.default.addObserver(self,
                                       selector: #selector(self.changeCamera),
                                       name: NSNotification.Name.AVCaptureDeviceWasConnected,
                                       object: nil)
        
NotificationCenter.default.addObserver(self,
                                          selector: #selector(self.changeCamera),
                                          name: NSNotification.Name.AVCaptureDeviceWasDisconnected,
                                          object: nil)
```

The error
`Type 'NSNotification.Name' has no member 'AVCaptureDeviceWasConnected`
`Type 'NSNotification.Name' has no member 'AVCaptureDeviceWasDisconnected`

**Steps to reproduce**
Add an observer to the NotificationCenter to observe `NSNotification.Name.AVCaptureDeviceWasDisconnected`. Compile without swift interop and then attempt to compile with swift interop

**Expected behavior**
I expect this to compile with swift interop just as it does without interop enabled

**Environment**
- Swift compiler version info `swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0`
- Xcode version info `Xcode 15.0
Build version 15A240d`
- Deployment target: iOS and iOS simulator

**Comment by AnthonyLatsis** [comment]
cc @egorzhdan

**Comment by egorzhdan** [comment]
Thanks, this is tracked internally as rdar://115424525, and we're working to fix this in https://github.com/apple/swift/pull/69776

**Comment by egorzhdan** [comment]
@tcollins590 yes, please! The issues with `NSNotification.Name` are all caused by the same underlying problem, so there's no need to report them, but other cases of source breakage caused by C++ interop are definitely worth reporting separately.

**Comment by ElJabato** [comment]
> @knielsen-foreflight sorry for the delay in response. As a temporary workaround I implemented a polling based solution for the specific use case. In my case I needed to see if an external camera was attached. To achieve this I poll the camera configuration to see if there is one attached. This is not an optimal fix but allowed me to solve the issue while I wait for a future fix in swift.

There is a workaround, based in "init raw value". Swift code:

NotificationCenter.default.addObserver(forName: Notification.Name.GCControllerDidConnect, object: nil, queue: nil, using: connectMFIController)

Is equivalent to

NotificationCenter.default.addObserver(forName: Notification.Name.init(rawValue: "GCControllerDidConnectNotification"), object: nil, queue: nil, using: connectMFIController)

Find the string name is possible with "print" (swift):

print(Notification.Name.GCControllerDidConnect)

Output this:

NSNotificationName(_rawValue: GCControllerDidConnectNotification)

(Of course you must set interop to "C / Objective C" firstly).

**Comment by schwa** [comment]
This just hit me and I spent way too long trying to understand what caused it. Is there an ETA?

**Comment by AnthonyLatsis** [comment]
> Is there an ETA?

Apparently this was not nominated for 5.10, so it will ship with 6.0, the next release.
