### ISSUE TITLE
`swift demangle` failed to demangle a symbol

### ISSUE THREAD

**Issue by mingchen** [apple/swift#69931]
Hi,

My iOS app crashes upon startup because it cannot locate the required symbol:

> dyld[5215]: Symbol not found: __ZN5swift39swift51override_conformsToSwiftProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEN7__swift9__runtime4llvm9StringRefEPFPKNS_35TargetProtocolConformanceDescriptorIS1_EES4_S8_SC_E

I want to identity this symbol is and I'm unable demangle it by `swift demangle`:

> % swift demangle
__ZN5swift39swift51override_conformsToSwiftProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEN7__swift9__runtime4llvm9StringRefEPFPKNS_35TargetProtocolConformanceDescriptorIS1_EES4_S8_SC_E
__ZN5swift39swift51override_conformsToSwiftProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEN7__swift9__runtime4llvm9StringRefEPFPKNS_35TargetProtocolConformanceDescriptorIS1_EES4_S8_SC_E

I've examined https://github.com/apple/swift/blob/main/docs/ABI/Mangling.rst and couldn't identify suitable types for manually demangling this symbol. Can someone provide guidance on demangling this symbol? I suspect it doesn't originate from my code. Any insights on its origin would be appreciated.

Environment:
Xcode: 14.1 ~ 15.0
OS: iOS 15.0 and above.

**Comment by herrernst** [comment]
I have the same crash (only on device, not in Simulator on Apple Silicon) and no idea where it comes from. How did you solve it?
