### ISSUE TITLE
Remote target (for distributed actor) arguments are not properly deinitialized

### ISSUE THREAD

**Issue by ser-0xff** [apple/swift#70004]
Remote target arguments reconstructed on the remote side of the distributed actor are not properly deinitialised.
If the remote target argument is a struct with enum with an associated value then some class instance references are never released causing a memory leak.

Probably related to similar [issue](https://github.com/apple/swift/issues/65853)

We implemented minimised [test](https://github.com/ordo-one/external-reproducers/tree/main/swift/distributed-system-leak)
It perform a remote call on the distributed actor with a struct argument having an enumeration with associated struct value.

```
wrk % git clone https://github.com/ordo-one/external-reproducers.git
Cloning into 'external-reproducers'...
remote: Enumerating objects: 267, done.
remote: Counting objects: 100% (267/267), done.
remote: Compressing objects: 100% (181/181), done.
remote: Total 267 (delta 105), reused 180 (delta 44), pack-reused 0
Receiving objects: 100% (267/267), 50.19 KiB | 1.32 MiB/s, done.
Resolving deltas: 100% (105/105), done.
wrk % cd external-reproducers/swift/distributed-system-leak 
distributed-system-leak % swift test
Building for debugging...
[5/5] Linking DistributedSystemPackageTests
Build complete! (11.44s)
Test Suite 'All tests' started at 2023-11-22 17:21:03.526.
Test Suite 'DistributedSystemPackageTests.xctest' started at 2023-11-22 17:21:03.527.
Test Suite 'DistributedSystemTests' started at 2023-11-22 17:21:03.527.
Test Case '-[DistributedSystemTests.DistributedSystemTests test1]' started.
Test Case '-[DistributedSystemTests.DistributedSystemTests test1]' passed (0.001 seconds).
Test Suite 'DistributedSystemTests' passed at 2023-11-22 17:21:03.529.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'DistributedSystemPackageTests.xctest' passed at 2023-11-22 17:21:03.529.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.001) seconds
Test Suite 'All tests' passed at 2023-11-22 17:21:03.529.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.001 (0.003) seconds
assign<TestActor>: 1
actorReady<TestActor>: 1
resolve<TestActor>
ArgumentType.init: 0x00006000028703a0
InnerStruct.init: 0x00006000028703c0
recordArgument
remoteCallVoid
ArgumentType.init: 0x0000600002870460
InnerStruct.init: 0x0000600002870480
value=100
ArgumentType.deinit: 0x00006000028703a0
InnerStruct.deinit: 0x00006000028703c0
distributed-system-leak % 
```

There are 2 instances of `ArgumentType` and `InnerStruct` each were initialised, but only one `ArgumentType` instance and only one `InnerStruct` instance were deinitialized. The expected behaviour would be both instances of `ArgumentType` and both instances of `InnerStruct` would be deinitialized.

**Environment**
- Swift compiler version info 
```
distributed-system-leak % swift --version
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

- Xcode version info 
- Deployment target: 
```
distributed-system-leak % uname -a
Darwin mbpro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64
```

**Comment by hassila** [comment]
friendly ping @ktoso

**Comment by HK-Sterven26** [comment]
Later 😄

**Comment by ser-0xff** [comment]
A little addition just in case: we actually have a more complex associated value in the enum with some other references to class instances, and it seems like they are not released as well.

**Comment by ser-0xff** [comment]
We updated the minimised test with an additional inner struct which members are not released as well.
The test still available on [github](https://github.com/ordo-one/external-reproducers/tree/main/swift/distributed-system-leak) and attached [distributed-system-leak.zip](https://github.com/apple/swift/files/13614807/distributed-system-leak.zip) to the comment. To run the test unzip it and the execute `cd distributed-system-leak && swift test`

**Comment by ktoso** [comment]
Sorry I missed the ping. I’ll investigate — we fixed something similar — the fix would be on mainline right now. I’ll confirm though, thanks

**Comment by dukhnyak** [comment]
Many thanks @ktoso !

**Comment by ser-0xff** [comment]
We tried to run a test with the Swift development snapshot toolchain and seems there is still a leak.
```
distributed-system-leak % swift --version 
Apple Swift version 5.11-dev (LLVM 91cd37b9110872c, Swift 703a4719b0c6f3a)
Target: arm64-apple-macosx14.0
distributed-system-leak %
```

**Comment by ktoso** [comment]
Fix incoming https://github.com/apple/swift/pull/70806

Sorry for the delay over new year's break

**Comment by hassila** [comment]
Awesome, thanks @ktoso

**Comment by dukhnyak** [comment]
Thank you so much, especially for back porting it to 5.10! Minimised test passed, will try end to end test shortly.
