### ISSUE TITLE
error: value of type 'URL' has no member 'appending'

### ISSUE THREAD

**Issue by abegehr** [apple/swift#70017]
**Description**
I'm trying to compile a vapor api on Docker image with base `swift:5.9-jammy`. 
After adding some basic URL functionality to a local package, it fails:

```swift
import Foundation

public extension FlottAPICall {
    var path: String { Self.path }
    var queryItems: [URLQueryItem] { [] }
    
    func buildUrl(baseUrl: URL) -> URL {
        baseUrl.appending(path: path).appending(queryItems: queryItems)
    }
    
    /// CustomStringConvertible
    var description: String {
        self.buildUrl(baseUrl: URL(string: "https://www.flott.app")!).path()
    }
}
```

```log
#0 12.87 [14/881] Compiling FlottCommon FlottEndpoint.swift
#0 12.87 /build/common/Sources/FlottCommon/Endpoints/FlottEndpoint.swift:31:17: error: value of type 'URL' has no member 'appending'
#0 12.87         baseUrl.appending(path: path).appending(queryItems: queryItems)
#0 12.87         ~~~~~~~ ^~~~~~~~~
#0 12.87 /build/common/Sources/FlottCommon/Endpoints/FlottEndpoint.swift:36:71: error: cannot call value of non-function type 'String'
#0 12.87         self.buildUrl(baseUrl: URL(string: "https://www.flott.app")!).path()
#0 12.87                                                                       ^   ~~
#0 12.87                                                                           
#0 12.87 error: fatalError
```

It compiles fine on macOS

**Steps to reproduce**

Take the code snippet from above and try to compile to on `swift:5.9-jammy`. 

**Expected behavior**

I'd expect it to have the appending URL function.

**Environment**
(dev-env that does work)
- Swift compiler version info: swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
- Xcode version info: Version 15.0.1 (15A507)
- Deployment target: macOS 14.1.1 (23B81)

**Additional context**
- Docker image base: <https://hub.docker.com/layers/library/swift/5.9-jammy/images/sha256-3fdc5ac4d86fdcf953e11aba87cd0b32e56c1d7a39d1b0db8e48839f87172382?context=explore>
- Build command: `RUN swift build -c release --static-swift-stdlib`
- Vapor version: 4.86.2

**Comment by abegehr** [comment]
Looking through <https://github.com/apple/swift-corelibs-foundation/blob/36a411b304063de2cbd3fe06adc662e7648d5a9d/Sources/Foundation/URL.swift> it seems that Foundation forelimb still uses `appendingPathComponent()` (TBD) instead of the newer `appending(path:)`.

Also, it's referenced on the `swift-foundation` repo, that work on URL will happen this year, so I assume this functionality is not available on linux yet: https://github.com/apple/swift-foundation#development-focus-for-2023

**Comment by abegehr** [comment]
For anyone running into this, you can choose to use the deprecated appendingPathComponent, add a conditional compilation block based on the os (see [here](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/statements/#Conditional-Compilation-Block)) or simply don't share URL code/functions between client and server. (I'm going with option 3 for now)

**Comment by AnthonyLatsis** [comment]
@parkera Could we have this transferred?
