### ISSUE TITLE
"Extra arguments" error when passing a parameter pack into a function that also accepts a closure argument.

### ISSUE THREAD

**Issue by simanerush** [apple/swift#70056]
### Description

When trying to use a function that accepts a parameter pack and a closure as its arguments, I'm getting the "extra arguments" error.

### Reproduction

```swift
func test<each T>(_ pack: repeat each T, callback: (repeat each T) -> Void) {}

test(1, 2, 3, callback: { _ in })
```

The error:
```
error: extra arguments at positions #2, #3 in call
test(1, 2, 3, callback: { _ in })
    ^
note: 'test(_:callback:)' declared here
func test<each T>(_ pack: repeat each T, callback: (repeat each T) -> Void) {
     ^
```

### Expected behavior

The above code should compile because `1, 2, 3` is a valid parameter pack, and should be used as a first argument to the function.

### Environment

Swift version 5.11-dev (LLVM d50917983d84235, Swift 98e65d015979c7b)

### Additional information

The following code, with `(repeat each T)` replaced with `(Int)` in the type of the closure, works fine:
```swift
func test<each T>(_ pack: repeat each T, callback: (Int) -> Void) {}

test(1, 2, 3, callback: { _ in })
```

**Comment by hborla** [comment]
I think this is a misleading error message. The real issue is the closure doesn't have enough arguments. This builds fine

```swift
func test<each T>(_ pack: repeat each T, callback: (repeat each T) -> Void) {}

test(1, 2, 3, callback: { _, _, _ in })
```

**Comment by simanerush** [comment]
Ah, I totally missed that. Thank you Holly!

**Comment by AnthonyLatsis** [comment]
Opened #70228 to track the bad diagnostic.

**Comment by simanerush** [comment]
Sorry.. thanks for adding the appropriate labels!
