### ISSUE TITLE
Bad interaction between SE-0269 and SE-0345

### ISSUE THREAD

**Issue by jumhyn-browser** [apple/swift#70089]
### Description

SE-0269 included a check to make sure that the implicit self behavior was only permitted if you had indeed captured the `self` param (or another capture thereof) and not some other rebound `self`. SE-0345 allowed implicit `self` for rebound `weak self` which results in a bogus (or at least confusing) diagnostic. See reproduction below.

### Reproduction

```swift
class C {
    var x: Int = 0

    func f() {
        g { [weak self] in
            guard let self else { return }
            h { [self] in
                x += 1
            }
        }
    }
}

func g(_: @escaping () -> Void) {}
func h(_: @escaping () -> Void) {}
```
```
error: MyPlayground.playground:8:17: error: reference to property 'x' in closure requires explicit use of 'self' to make capture semantics explicit
                x += 1
                ^

MyPlayground.playground:7:18: note: variable other than 'self' captured here under the name 'self' does not enable implicit 'self'
            h { [self] in
                 ^
```

### Expected behavior

Compiles

### Environment

Fails on nightly

**Comment by jumhyn-browser** [comment]
cc @calda I know you flagged some odd interactions between these proposals already, not sure if this is already filed somewhere. I probably won't have a chance to look at this right away so if you're interested/available feel free to tackle.

**Comment by calda** [comment]
Here's a fix: https://github.com/apple/swift/pull/70575

**Comment by jumhyn-browser** [comment]
@calda major props landing this fix!! Didn't realize what a slog it would turn into when I tagged you 😭
