### ISSUE TITLE
Unable to execute macOS CI from apple/swift-tools-support-core

### ISSUE THREAD

**Issue by compnerd** [apple/swift#70090]
### Description

https://github.com/apple/swift-tools-support-core/pull/442 has been unable to execute the macOS CI job for a while across-multiple requests.

**Comment by shahmishal** [comment]
One build is causing an issue trigger other build 
https://ci.swift.org/view/Pull%20Requests/job/pr-swift-tools-support-core-macos/317/

**Comment by shahmishal** [comment]
Fixed: builds are now starting - https://ci.swift.org/view/Pull%20Requests/job/pr-swift-tools-support-core-macos/
