### ISSUE TITLE
Compiler bug with consume keyword

### ISSUE THREAD

**Issue by mishacausur** [apple/swift#70234]
### Description

I'm delving deep into ownership concepts in Swift 5.9 and received a prompt from Xcode to report a bug here, so here I am.
Xcode informs me as follows:

`'consume' applied to value that the compiler does not support. This is a compiler bug. Please file a bug with a small example of the bug`

### Reproduction

```swift
func mutateText(_ rawText: NSString?) -> String {
        guard let text = consume rawText else {
            return "text unavailable"
        }
        
        return String(text)
    }
```

### Expected behavior

The compiler doesn't inform about its bug

### Environment

Apple Swift version 5.9

**Comment by Grubl0rd** [comment]
Just chiming in to report that I also got this error with the following code—

### Reproduction
```swift
let a: [Any] = []
_ = consume a // 'consume' applied to value that the compiler does not support. This is a compiler bug. Please file a bug with a small example of the bug
```

### Environment
Swift 5.9.2, macOS 14.2.1

### Additional information
Seems to occur regardless of array element type (`[Int]`, `[String]`, etc), and whether or not the array is empty

**Comment by eecs441staff** [comment]
On Xcode 15.3 beta on macOS 14.4 beta, I got the same error message with the following CLI code:
```
func f(_ c: Int) -> Bool { return c < 0 }
func h() {
    var g = 0
    f(consume g)   // 'consume' applied to value that the compiler does not support. 
               // This is a compiler bug. Please file a bug with a small example of the bug
}
h()
```

Changing `var` to `let` allows the code to build and run, but the second `print()` runs without any complaint from the compiler that `g`'s lifetime was ended at [1].
```
func p() {
    let g = 0            // [1]
    print(f(consume g))
    print(g)              // no complaints from compiler that g's lifetime was ended at [1]
}
p()
```

**Comment by nate-chandler** [comment]
Fixed by https://github.com/apple/swift/pull/72256 , which adds regression tests for all three examples in this ticket.
