### ISSUE TITLE
Unicode ZWNJ Recognition Issue

### ISSUE THREAD

**Issue by urijan44** [apple/swift#70266]
### Description

It appears that there is an issue with storing the Unicode U+200C in a String type. The U+200C Unicode is not recognized except at the first position in the string.
```swift
let zwnj = "\u{200c}"
let study = "abc\(zwnj)ddd\(zwnj)ggg" // count 9
print(study.components(separatedBy: zwnj))
// print ["aaadddggg"]
```

If the ZWNJ is at the beginning of the string, then only that is recognized.

```swift
let zwnj = "\u{200c}"
let study = "\(zwnj)abc\(zwnj)ddd\(zwnj)ggg" // count 10
print(study.components(separatedBy: zwnj))
// prints ["", "aaadddggg"]

```

However, other Unicodes (like U+007C) are recognized correctly.
```swift
let vertical = "\u{007c}"
let study2 = "abc\(vertical)ddd\(vertical)ggg" // count 11
print(study2.components(separatedBy: vertical))
// prints ["abc", "ddd", "ggg"]

```

Bridging to NSString, the string is recognized correctly.
```swift
print((study as NSString).components(separatedBy: zwnj))
// prints ["abc", "ddd", "ggg"]

```

It seems that this issue started occurring with the iOS 17 beta, and it is likely related to Swift 5.9.

### Reproduction

```swift
let zwnj = "\u{200c}"
let study = "abc\(zwnj)ddd\(zwnj)ggg" // count 9
print(study.components(separatedBy: zwnj))
// print ["aaadddggg"]
```

### Expected behavior

```swift
let zwnj = "\u{200c}"
let study = "abc\(zwnj)ddd\(zwnj)ggg" // count 11
print(study.components(separatedBy: zwnj))
// print ["abc", "ddd", "ggg"]
```

### Environment

swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0

**Comment by Azoy** [comment]
It seems Foundation recently changed how `components(separatedBy:)` works and operates on `String`'s character view now. By operating on the character view there is no longer a ZWNJ element in the string, instead there are `c\(zwnj)` and `d\(zwnj)`. As a workaround, you can use the standard library API `split(separator:)` on the `UnicodeScalarView` to achieve the previous behavior:

```swift
let zwnj = "\u{200c}"
let zwnjScalar = Unicode.Scalar(0x200C)!
let study = "abc\(zwnj)ddd\(zwnj)ggg" // count 9
let split = study.unicodeScalars.split(separator: zwnjScalar).map {
  String($0)
}

// abc
// ddd
// ggg
for s in split {
  print(s)
}
```
