### ISSUE TITLE
swift 5.10/nightly: struct 'OpaquePointer' does not conform to the 'Sendable' protocol

### ISSUE THREAD

**Issue by blindspotbounty** [apple/swift#70396]
### Description

Haven't found whether it was reported or not yet...

OpaquePointer is Sendable by [documentation](https://developer.apple.com/documentation/swift/opaquepointer) and was Sendable in 5.7/5.8.
But in 5.10/nightly I see the following:
```
09:35:04 Swift.OpaquePointer:1:23: note: struct 'OpaquePointer' does not conform to the 'Sendable' protocol
09:35:04 @frozen public struct OpaquePointer {
```

### Reproduction

```swift
final class Foo: Sendable {
    let v: OpaquePointer
    
    init(v: OpaquePointer) {
        self.v = v
    }
}
```
Result:
```
<source>:2:9: warning: stored property 'v' of 'Sendable'-conforming class 'Foo' has non-sendable type 'OpaquePointer'
    let v: OpaquePointer
        ^
Swift.OpaquePointer:1:23: note: struct 'OpaquePointer' does not conform to the 'Sendable' protocol
@frozen public struct OpaquePointer {
                      ^
Compiler returned: 0
```

Or build https://github.com/swift-server/swift-kafka-client with 5.10/nightly.

### Expected behavior

OpaquePointer should be Sendable by documentation, no warning should be emitted.

### Environment

swift nightly: https://ci.swiftserver.group/job/swift-kafka-client-swift-nightly-prb/310/console
swift 5.10: https://ci.swiftserver.group/job/swift-kafka-client-swift510-prb/47/console

### Additional information

It is a little bit strange that compiler emits this warning as `OpaquePointer` is struct and should be Sendable by default (according to [documentation](https://developer.apple.com/documentation/swift/sendable))

There is additionally 
[Reproducible example at godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:swift,selection:(endColumn:2,endLineNumber:7,positionColumn:2,positionLineNumber:7,selectionStartColumn:2,selectionStartLineNumber:7,startColumn:2,startLineNumber:7),source:'final+class+Foo:+Sendable+%7B%0A++++let+v:+OpaquePointer%0A++++%0A++++init(v:+OpaquePointer)+%7B%0A++++++++self.v+%3D+v%0A++++%7D%0A%7D'),l:'5',n:'0',o:'Swift+source+%231',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:swiftnightly,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:swift,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+swiftc+nightly+(Editor+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+swiftc+nightly',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+swiftc+nightly+(Compiler+%231)',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by xedin** [comment]
Opaque pointer just like other unsafe pointer types no longer synthesize conformance to Sendable because otherwise they could be used to transfer non-Sendable types across concurrency domains. See https://github.com/apple/swift-evolution/blob/main/proposals/0331-remove-sendable-from-unsafepointer.md for more details.

**Comment by blindspotbounty** [comment]
Thank you, would be nice to update it in documentation as well
