### ISSUE TITLE
[SymbolGraphGen] passing `-application-extension` removes symbols with `@available(iOSApplicationExtension, unavailable)` from the symbol graph file

### ISSUE THREAD

**Issue by MarcoEidinger** [apple/swift#70489]
### Description

```swift
@available(iOS 15.0, *)
@available(iOSApplicationExtension, unavailable)
/// API to be used in app but not in extension
public class MyApi {...}
```

in an iOS framework gets NOT included in documentation output from DocC when Build Setting `APPLICATION_EXTENSION_API_ONLY = YES;`

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

The expectation is that API gets documented as it can be used in an application.

FYI:
in an iOS framework gets included in documentation output from Jazzy when Build Setting `APPLICATION_EXTENSION_API_ONLY = NO;`

![DocC Good](https://github.com/MarcoEidinger/DocUnavailableRepro/blob/main/images/docc_APPLICATION_EXTENSION_API_ONLY_no.png?raw=true)

### Actual behavior

![Jazzy Bad](https://github.com/MarcoEidinger/DocUnavailableRepro/blob/main/images/docc_APPLICATION_EXTENSION_API_ONLY_yes.png?raw=true)

### Steps To Reproduce

Use https://github.com/MarcoEidinger/DocUnavailableRepro to reproduce the issue and build documentation from Xcode

### Swift-DocC Version Information

DocC bundled with Xcode 15.1 Beta 3

**Comment by AnthonyLatsis** [comment]
cc @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
I'm in agreement with @d-ronnqvist here - the way that that description is written, i would think that setting it would remove APIs that are unavailable to app extensions, like how that class is marked. In effect, it seems that turning that setting on restricts your API to just those that are available to app extensions. In that sense i'd say this is working as intended.

For completeness, this is the help message in `swiftc -help` about `-application-extension`:

```
  -application-extension  Restrict code to those available for App Extensions
```

**Comment by MarcoEidinger** [comment]
@QuietMisdreavus please re-consider because the symbol is available and accessible for application targets on iOS. It is merely not available in an extension target. Not including it in the symbol graph and consequently not including it in API documentation seems wrong because developers would only discover this symbol by accident!

**Comment by QuietMisdreavus** [comment]
@MarcoEidinger By setting `APPLICATION_EXTENSION_API_ONLY=YES`, you're building a version of your framework that only has extension APIs in it. If you want your documentation to reflect the state of your API that can be used in applications, then base it on the version of your framework that will actually have that API available.

A symbol graph is by its nature a filtered view of a framework's/package's APIs, whether that's for visibility, SPI, or target availability. There are various flags available to change this view when generating them; `-application-extension` is one of them.

**Comment by MarcoEidinger** [comment]
> If you want your documentation to reflect the state of your API that can be used in applications, then base it on the version of your framework that will actually have that API available.

@QuietMisdreavus: how do I do that? I use Xcode's "Build documentation" feature targeting the iOS platform and the symbol  is generally available on iOS with the exception when using the framework in an extension target.

**Comment by MarcoEidinger** [comment]
@QuietMisdreavus any suggestions on how to do that?

@d-ronnqvist Apple documentation includes symbols, e.g. `UIApplication.shared`, marked as unavailable in extensions.

```
@property(class, nonatomic, readonly) UIApplication *sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
```

<img width="662" alt="Screenshot 2023-12-15 at 10 07 50 AM" src="https://github.com/apple/swift/assets/4176826/6804c0f9-8990-4741-897e-546712bf2033">

How does Apple generate such documentation?

**Comment by MarcoEidinger** [comment]
> @QuietMisdreavus any suggestions on how to do that?
> 
> @d-ronnqvist Apple documentation includes symbols, e.g. `UIApplication.shared`, marked as unavailable in extensions.
> 
> ```
> @property(class, nonatomic, readonly) UIApplication *sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
> ```
> 
> <img alt="Screenshot 2023-12-15 at 10 07 50 AM" width="662" src="https://private-user-images.githubusercontent.com/4176826/290902583-6804c0f9-8990-4741-897e-546712bf2033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMDg0ODIsIm5iZiI6MTcwNDMwODE4MiwicGF0aCI6Ii80MTc2ODI2LzI5MDkwMjU4My02ODA0YzBmOS04OTkwLTQ3NDEtODk3ZS01NDY3MTJiZjIwMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMTg1NjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk4ZGIxZTRjN2FmMGYzMWQxZDU2Yjg4OGRiZThiNjY1ZjZkNmVjYjYyMGE4ZTFmN2ZiZjZhODhlYWQ2MGIwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rJDCm7lGANvBFLc_eY8WDdDv_yueOhCqyvmZuAQJCq8">
> How does Apple generate such documentation?

Any input you can provide @QuietMisdreavus or @d-ronnqvist?

I think it's not ok to force framework developers to change build settings, i.e. APPLICATION_EXTENSION_API_ONLY=NO, to get documentation for symbols annotated with `@available(iOSApplicationExtension, unavailable)`

**Comment by olejnjak** [comment]
Well, when building a documentation catalog it can actually be ok to force devs to change the build settings. 

What I think that isn't correct is that devs get warning when compiling their framework in Xcode 15.3 (15E204a) with `RUN_DOCUMENTATION_COMPILER = YES` and `APPLICATION_EXTENSION_API_ONLY`.

<img width="680" alt="Screenshot 2024-04-22 at 16 34 21" src="https://github.com/apple/swift/assets/3148214/a41b985f-6317-45ea-94b5-b077ddc72413">

I think this warning is just untrue.
