### ISSUE TITLE
Infinite loop in `RandomNumberGenerator.next(upperBound:)`

### ISSUE THREAD

**Issue by fumoboy007** [apple/swift#70557]
### Description

There is an infinite loop in [`RandomNumberGenerator.next(upperBound:)`](https://github.com/apple/swift/blob/f6dba90cf2b3b646de748b0fc4fbfbd1f65cb0a3/stdlib/public/core/Random.swift#L91-L121) that can be triggered when `RandomNumberGenerator.next()` returns `0` repeatedly. I discovered this issue when I implemented a fake `RandomNumberGenerator` type for automated tests that always returned `0` from its `next()` method.

The `RandomNumberGenerator.next(upperBound:)` implementation was changed in https://github.com/apple/swift/commit/2bc648c26baccd95847cde2ad025c8c1b1fd0375 to use [Lemire’s Nearly Divisionless Random Integer Generation](https://arxiv.org/abs/1805.10941) algorithm. (CC @palimondo @stephentyrone) As far as I can tell, the Swift implementation does match the [reference implementation](https://lemire.me/blog/2019/06/06/nearly-divisionless-random-integer-generation-on-various-systems/), which I have copy-pasted below:
```c
uint64_t nearlydivisionless ( uint64_t s ) {
  uint64_t x = random64 () ;
  __uint128_t m = ( __uint128_t ) x * ( __uint128_t ) s;
  uint64_t l = ( uint64_t ) m;
  if (l < s) {
    uint64_t t = -s % s;
    while (l < t) {
      x = random64 () ;
      m = ( __uint128_t ) x * ( __uint128_t ) s;
      l = ( uint64_t ) m;
    }
  }
  return m >> 64;
}
```

However, to my inexperienced eyes, it seems like the reference implementation does not handle the case where `random64()` returns `0` repeatedly. It’s also totally possible that this was intentional. Perhaps @lemire can help clarify this edge case?

### Reproduction

```swift
struct RandomNumberGeneratorFake: RandomNumberGenerator {
   func next() -> UInt64 {
      return 0
   }
}
var randomNumberGenerator = RandomNumberGeneratorFake()

let randomNumber = randomNumberGenerator.next(upperBound: UInt64.max)
print(randomNumber)
```

### Expected behavior

I expected a number to be printed. In reality, the `RandomNumberGenerator.next(upperBound:)` method call never returns.

### Environment

```
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: x86_64-apple-macosx14.0
```

**Comment by lemire** [comment]
I will comment today, thanks for the ping!

**Comment by stephentyrone** [comment]
As Daniel said, returning `0` repeatedly is not a valid conformance to `RandomNumberGenerator`; algorithms are that consume its output are not expected to behave correctly when its semantic constraints are not satisfied (nor could they--if they didn't enter an infinite loop, they would instead return biased data, which would also constitute an error).

**Comment by fumoboy007** [comment]
@lemire Thanks so much for taking the time to write a detailed explanation! I didn’t fully understand but overall makes sense to me.

@stephentyrone Perhaps let me expand on my use case a little bit more. I wrote [automated tests](https://github.com/fumoboy007/swift-retry/blob/7635848030b0abaf371d99a4efa2ee54ed02e824/Tests/RetryTests/FullJitterExponentialBackoffTests.swift#L27) for an [exponential backoff algorithm](https://github.com/fumoboy007/swift-retry/blob/7635848030b0abaf371d99a4efa2ee54ed02e824/Sources/Retry/Backoff/Algorithms/FullJitterExponentialBackoff.swift#L23) that [generates random numbers](https://github.com/fumoboy007/swift-retry/blob/7635848030b0abaf371d99a4efa2ee54ed02e824/Sources/Retry/Backoff/Algorithms/FullJitterExponentialBackoff.swift#L82-L83) to add jitter. In order to reliably and conveniently test certain behavior, I used a [fake `RandomNumberGenerator` implementation](https://github.com/fumoboy007/swift-retry/blob/7635848030b0abaf371d99a4efa2ee54ed02e824/Tests/RetryTests/Fakes/RandomNumberGeneratorFake.swift#L23) that either returns `0` or the upper bound.

Have we considered adding [`next(upperBound:)`](https://github.com/apple/swift/blob/d540f4895add9207bd63000c0547f24caf3656da/stdlib/public/core/Random.swift#L91-L121) (and [`next<T>()`](https://github.com/apple/swift/blob/d540f4895add9207bd63000c0547f24caf3656da/stdlib/public/core/Random.swift#L77-L89)) to the [protocol requirements](https://github.com/apple/swift/blob/d540f4895add9207bd63000c0547f24caf3656da/stdlib/public/core/Random.swift#L54-L64)? Real `RandomNumberGenerator` implementations could still only override `next()`, relying on the default implementations for the other two methods. However, a fake `RandomNumberGenerator` implementation could override all of the methods to return a constant value. This way, the fake implementation would avoid internally breaking the semantic constraint.

**Comment by stephentyrone** [comment]
`RandomNumberGenerator` is a badly-named protocol. It should really have been something like `RandomBitStream`--it does not generate random numbers, it is a source of random bits that other API consume to produce random values.

**Comment by tbkka** [comment]
Even better:  Define your own protocol to provide test jitter.  You can then have an implementation that provides no jitter (always zero) and another that uses a standard random number generator to provide that jitter.

**Comment by fumoboy007** [comment]
> `RandomNumberGenerator` is a badly-named protocol. It should really have been something like `RandomBitStream`--it does not generate random numbers, it is a source of random bits that other API consume to produce random values.

@stephentyrone Hmm yes, I think `RandomBitStream` would have been a lot clearer. In that ideal world, hypothetically speaking, could there be a separate “random number generator” protocol that contains the `next(upperBound:)` and `next<T>()` methods?

For example:
```swift
// Currently named `RandomNumberGenerator`.
protocol RandomBitStream {
  mutating func next() -> UInt64
}

// Does not currently exist.
protocol RandomNumberGenerator {
  mutating func next<T: FixedWidthInteger & UnsignedInteger>() -> T
  mutating func next<T: FixedWidthInteger & UnsignedInteger>(upperBound: T) -> T
}

// Currently named `SystemRandomNumberGenerator`.
struct SystemRandomBitStream: RandomBitStream {
  …
}

// An implementation of `RandomNumberGenerator ` that currently exists as
// an extension of the `RandomBitStream` protocol.
struct StandardRandomNumberGenerator<RandomBitStreamType>: RandomNumberGenerator
where RandomBitStreamType: RandomBitStream {
  init(using randomBitStream: RandomBitStreamType) {
    …
  }

  …
}

extension FixedWidthInteger {
  // Currently exists but accepts a lower-level `RandomBitStream` instead of
  // a higher-level `RandomNumberGenerator`.
  static func random<T: RandomNumberGenerator>(
    in range: Range<Self>,
    using generator: inout T
  ) -> Self {
    …
  }

  // Same convenient API as before.
  static func random(in range: Range<Self>) -> Self {
    var generator = StandardRandomNumberGenerator(using: SystemRandomBitStream())
    return random(in: range, using: &generator)
  }
}
```

In this design, concerns are properly separated and one could easily use their own implementations of `next(upperBound:)` and `next<T>()` by creating a new type conforming to `RandomNumberGenerator`.

---

> Even better: Define your own protocol to provide test jitter. You can then have an implementation that provides no jitter (always zero) and another that uses a standard random number generator to provide that jitter.

@tbkka Good idea! I guess that is what I will do for now. I will probably not make the protocol specific to jitter but will make it more general. I don’t know what to name it though. `RandomNumberGenerator` would be apt since that is what the protocol is doing buuut … 😅

---

It’s a little unfortunate that one has to know the intricacies of random number generation and know to define a new protocol rather than using the existing `RandomNumberGenerator` protocol. I imagine this use case would be common when testing code that relies on random numbers. Perhaps with some changes similar to what I proposed above, it could be a lot simpler?

Practically speaking though, given that we cannot rename `RandomNumberGenerator` to `RandomBitStream` due to backwards compatibility, what name could we give the new protocol?
