### ISSUE TITLE
"init accessors" don't work with actors

### ISSUE THREAD

**Issue by KeithBauerANZ** [apple/swift#70550]
### Description

`init` accessors don't seem to be usable from `actor` initializers (I expected that `accesses:` might not work, but `initializes:` doesn't either, which seems like a bug)

### Reproduction

The example from the "init accessors" SE, with `struct` changed to `actor`,

```swift
final actor Angle {
  var degrees: Double
  var radians: Double {
    @storageRestrictions(initializes: degrees)
    init(initialValue)  {
      degrees = initialValue * 180 / .pi
    }

    get { degrees * .pi / 180 }
    set { degrees = newValue * 180 / .pi }
  }

  init(degrees: Double) {
    self.degrees = degrees // initializes 'self.degrees' directly
  }

  init(radians: Double) {
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
  }
}
```

produces

```
ActorInitAccessor.swift:18:10: warning: actor-isolated property 'radians' can not be mutated from a non-isolated context; this is an error in Swift 6
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
         ^
ActorInitAccessor.swift:3:7: note: mutation of this property is only permitted within the actor
  var radians: Double {
      ^
ActorInitAccessor.swift:18:18: warning: cannot access property 'degrees' here in non-isolated initializer; this is an error in Swift 6
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
    ~~~~~~~~~~~~~^~~~~~~~~
ActorInitAccessor.swift:18:18: note: after making a copy of 'self', only non-isolated properties of 'self' can be accessed from this init
    self.radians = radians // calls init accessor for 'self.radians', passing 'radians' as the argument
    ~~~~~~~~~~~~~^~~~~~~~~
```

### Expected behavior

I think this should compile.

### Environment

(Xcode 15.1)

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx13.0

**Comment by xedin** [comment]
Are you running with `-warnings-as-errors`? It seems like isolation checker is just confused about reference to init accessor but it does build and run fine without `-warnings-as-errors` or `-swift-version 6` mode.

**Comment by xedin** [comment]
`main` compiler does produce a warning but a different one.

**Comment by xedin** [comment]
@kavon should init accessor properties be handled just like stored properties by `memberAccessHasSpecialPermissionInSwift5` because they are only allowed to access stored properties inside?...

**Comment by kavon** [comment]
@xedin the short answer is yes, they should be treated like stored properties, and in `memberAccessHasSpecialPermissionInSwift5` in the spot where it says in a comment, "Later, flow-isolation pass will check and emit a warning if needed." That should handle the first warnings.

It looks like the second warning is coming from the FlowIsolation pass, as it probably is misunderstanding those init accessors. Notice that it's complaining about a copy of `self`, that's definitely a point where analysis stops as it's assumed `self` has "escaped" after that point.
