### ISSUE TITLE
missing entries in libstdc++ modulemap

### ISSUE THREAD

**Issue by Trass3r** [apple/swift#70586]
### Motivation

I noticed a few missing headers in https://github.com/apple/swift/blob/main/stdlib/public/Cxx/libstdcxx/libstdcxx.modulemap when trying to build LLVM with modules.

### Proposed solution

Here's how I patched it:
```sh
        sudo wget -nv -O /usr/include/c++/13/module.modulemap https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Cxx/libstdcxx/libstdcxx.modulemap
        sudo wget -nv -O /usr/include/c++/13/libstdcxx.h https://raw.githubusercontent.com/apple/swift/main/stdlib/public/Cxx/libstdcxx/libstdcxx.h
        sudo sed -i '50i header "string_view"\
          header "cmath"\
          header "optional"\
          header "variant"' /usr/include/c++/13/module.modulemap
        sudo sed -i 's/header "cassert"/textual header "cassert"/' /usr/include/c++/13/module.modulemap
```

**Comment by egorzhdan** [comment]
This modulemap isn't designed to be used as is, it is basically a template for the compiler-generated modulemap.

These three headers are not present in all of the distros that Swift supports, so we have to rely on the modulemap generation logic to have them added to the modulemap that will be used by Clang during compilation.

https://github.com/apple/swift/blob/a1f406fd400766685b780c7b768f9550791cb6a5/lib/ClangImporter/ClangIncludePaths.cpp#L330-L335
