### ISSUE TITLE
Missing compiler warning

### ISSUE THREAD

**Issue by bastie** [apple/swift#70630]
typo - see error description 2 days later 🥺

### Description

In result of overload functions / methods with same name but more parameters **and** these parameters get default values (line 23) the "simple" function (line 20) appears uncallable.

<img width="1512" alt="Bildschirmfoto 2023-12-26 um 16 45 33" src="https://github.com/apple/swift/assets/654217/c1a0a1e8-1743-488c-ba6f-2f47e4474840">

### Reproduction

```swift
//
//  main.swift
//  MissingInitInfo
//
//  Created by Sebastian Ritter on 26.12.23.
//

import Foundation

// ✅ expected error
//let _ = Printable ()

// 🆘 name is not set, but called is init with param *as name* and ignoring init without second parameter
let _ = Printable (from: "Sebastian")

// ✅ expected result
let _ = Printable (from: "Sebastian", as: "Mr. Ritter")

public class Printable {
  public init (form sender : String) { // 🆘 uncallable (?) init method but no compiler message
    print ("Hello from \(sender)!")
  }
  public init (from sender : String, as name : String = "Bastie") {
    print ("Hello from \(name)?")
  }
}

```

### Expected behavior

Compiler warning at line 20 as uncallable method / function

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by msrutek-paylocity** [comment]
Is the typo
```swift
init (form sender : String)
```

vs

```swift
init (from sender : String, as name : String = "Bastie")
```

`form` vs `from` intentional?

**Comment by bastie** [comment]
I like my German "Autokorrektur"... and so I see the missing compiler message some lines below, or please tell how default value can be used...

```swift 5.9
//
//  main.swift
//  MissingInitInfo
//
//  Created by Sebastian Ritter on 26.12.23.
//

import Foundation

// ✅ expected error
//let _ = Printable ()

// ✅ expected result
let _ = Printable (from: "Sebastian")

// ✅ expected result
let _ = Printable (from: "Sebastian", as: "Mr. Ritter")

public class Printable {
  public init (from sender : String) {
    print ("Hello from \(sender)!")
  }
  public init (from sender : String, as name : String = "Bastie") { // 🆘  in result of init with one parameter unusable default value "Bastie" from init method
    print ("Hello from \(name)?")
  }
}

```

**Comment by Kyle-Ye** [comment]
This is expected behavior. See https://github.com/apple/swift/blob/main/docs/ReferenceGuides/UnderscoredAttributes.md#_disfavoredoverload

**Comment by Kyle-Ye** [comment]
Feel free to ask further. If no reply is received, I think we can close it later.

**Comment by AnthonyLatsis** [comment]
Per Swift overload ranking rules the function that best matches the `Printable(from: "Sebastian")` call is `Printable.init(form:)`. If you want to call `Printable.init(from:as:)` with the default argument without rethinking anything, you must disambiguate: 

```swift
let fn = Printable.init(from:as:)
let _ = fn("Sebastian")

// or

let _ = Printable.init(from:as:)("Sebastian")
```

`@_disfavoredOverload`, as Kyle suggests, is one other option that requires minimal change, but please note that this is not a public feature! There are no promises made about its stability or existence.

> [!Important]
> Whether any of this is reasonable depends on the actual use case.

**Comment by Kyle-Ye** [comment]
Thanks for sharing the `Printable.init(from:as:)("Sebastian")` tip. Don't know it before.

**Comment by AnthonyLatsis** [comment]
> Compiler warning at line 20 as uncallable method / function

I do not think a warning is justified here. The API design expectation behind this sort of overloading is that `Printable(from:)` behaves exactly like `Printable(from:as:)` in most, if not all, sensible implementations.

**Comment by Kyle-Ye** [comment]
> ```swift
> let fn = Printable.init(from:as:)
> let _ = fn("Sebastian")
> 
> // or
> 
> let _ = Printable.init(from:as:)("Sebastian")
> ```

The second way can be compiled, and the former will report a compiler error - "Missing argument for parameter #2 in call"

**Comment by AnthonyLatsis** [comment]
> the former will report a compiler error

Right, thanks. Function values do not retain default arguments.
