### ISSUE TITLE
Cannot find 'CFString' when build with CoreFoundation in Linux

### ISSUE THREAD

**Issue by WindowsMEMZ** [apple/swift#70652]
### Description

I'm trying to use CFString in Linux, but Swift compiler threw `error: cannot find type 'CFString' in scope`. It seems like it doesn't find this in CoreFoundation.

### Reproduction

```swift
import CoreFoundation

var str: CFString = "Hello, world!" // Error: cannot find type 'CFString' in scope
```

### Expected behavior

It should define a CFString correctly.

### Environment

```
Swift version 5.9.2 (swift-5.9.2-RELEASE)
Target: aarch64-unknown-linux-gnu
```

**Comment by finagolfin** [comment]
[CoreFoundation and `CFString` have been removed on non-Darwin platforms for years](https://forums.swift.org/t/formalizing-the-unavailability-of-core-foundation/40216) now.
