### ISSUE TITLE
#70580 seems to be breaking code in some cases

### ISSUE THREAD

**Issue by kkk669** [apple/swift#70733]
### Description

#70580 seems to be breaking code in some cases.

### Reproduction

Here is a minimal reproducible example. Please read the README.md.

https://github.com/kkk669/mre-70580/

### Expected behavior

`swift build` will succeed.

### Environment

- Arch Linux aarch64 (I used Ubuntu 22.04 toolchains installed via swiftly)
- swift-DEVELOPMENT-SNAPSHOT-2024-01-03-a
- swift-DEVELOPMENT-SNAPSHOT-2024-01-04-a

```console
$ swift --version
Swift version 5.11-dev (LLVM 1eeb3faad9a9a2a, Swift e2f888b311665f1)
Target: aarch64-unknown-linux-gnu
```

### Additional information

The same issue is also happening here.

https://github.com/kkk669/zyphy/

**Comment by DougGregor** [comment]
Found  and fixed the issue, thanks!
