### ISSUE TITLE
Closures containing parameter packs

### ISSUE THREAD

**Issue by NoahKamara** [apple/swift#70747]
### Description

Callbacks that take a parameter pack can not be stored

I am trying to achieve something similar to this but with parameter packs
```swift
struct Call<T,J> {
    var callback: (T,J) -> String
    
    init(callback: @escaping (T,J) -> String) {
        self.callback = callback
    }
}
```

### Reproduction

```swift
struct PackCall<each T> {
    let callback: (repeat each T) -> Void
    
    init(callback: @escaping (repeat each T) -> Void) {
        self.callback = callback // X - Type of expression is ambiguous without a type annotation
    }
}
```

### Expected behavior

it should work similar to the code in the description

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

**Comment by vanvoorden** [comment]
@NoahKamara looks like [68369](https://github.com/apple/swift/issues/68369).

**Comment by slavapestov** [comment]
This was fixed by https://github.com/apple/swift/pull/70457.
