### ISSUE TITLE
Formatting UnitLength Measurement on iOS 16 does not consider user's Measurement System settings

### ISSUE THREAD

**Issue by rgariful** [apple/swift#70876]
### Description

Starting from iOS 16 iPhone users can choose Measurement System in Settings app. However, this settings does not affect formatting UnitLength Measurement values in iOS 16, while on iOS 17 it works as expected.

### Reproduction

```swift
    let measurement = Measurement(value: 100, unit: UnitLength.kilometers)
    let locale_us_metric = Locale(identifier: "en_US@measure=metric")
    print(measurement.formatted(.measurement(width: .abbreviated, usage: .road).locale(locale_us_metric)))
```
In iOS 16 this prints: `62 mi`
While in iOS 17: `100 km`
The same can also be achieved by manually changing Measurement System setting in Settings app.

### Expected behavior

Both iOS versions should produce the same result, i.e. if Measurement System is set to metric, the formatted value should be in kilometres.

### Environment

Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)

### Additional information

It seems like in iOS 16 when formatting kilometres and miles, only region is taken into consideration, i.e. is US is set as region, then all the formatted strings will be in miles. While in iOS 17, Measurement System setting affects the formatting so even if the selected region is US but the measurement system is metric, the value will be in meters/kilometres.

**Comment by tbkka** [comment]
This is an issue with Apple's SDK, not with the Swift programming language.  Such concerns should be filed with Apple, for example at feedbackassistant.apple.com

I doubt that Apple can fix this in iOS 16, since that has already shipped.  :grin:
