### ISSUE TITLE
Nested any existential cannot be converted

### ISSUE THREAD

**Issue by GeorgeElsham** [apple/swift#70999]
### Description

I'm not 100% sure if this is expected behaviour, so I'll file an issue, but please do correct me if I'm misunderstanding. This may either be expected behaviour that I can't understand the limitation reasons for, or some sort of type-checker bug.

### Reproduction

```swift
protocol A {}
protocol B: A {}

struct Foo: B {}

struct Bar<Value> {
    let value: Value
}

struct Baz {
    let a: Bar<any A>
}

let foo: any B = Foo()

// Method 1: 🛑
let bar = Bar(value: foo)
let baz = Baz(a: bar)

// Method 2: ✅
let baz = Baz(a: Bar(value: foo))
```

### Expected behavior

I would expect method 1 to compile and run correctly. Currently, the following error is displayed:

> Cannot convert value of type 'Bar&lt;any B&gt;' to expected argument type 'Bar&lt;any A&gt;'

If `Bar` wasn't wrapping any value here, then a value of `any B` can be passed to a function taking `any A` just fine. However, adding `Bar` which wraps the `any` existential causes this compile error.

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0

### Additional information

This will compile fine if you manually cast to `Bar<any A>`:

```swift
/* ... */

let bar = Bar(value: foo) as Bar<any A>
let baz = Baz(a: bar)
```

**Comment by AnthonyLatsis** [comment]
This is expected. In `let baz = Baz(a: bar)`, `baz` has type `Bar<any B>`, which—in the Swift type system—is indeed unrelated to the expected argument type `Bar<any A>`. In the inline version, `let baz = Baz(a: Bar(value: foo))`, type inference concludes that the type of `foo` must be `any A`, and all it takes to solve the system is to wrap it in an implicit upcast as in `let _: any A = foo`.

> This will compile fine if you manually cast to `Bar<any A>`

This works for the same reason, with `as` fulfilling the type inference source role.
