### ISSUE TITLE
Menu items causing blank spaces when nested inside a Section on macCatalyst app

### ISSUE THREAD

**Issue by gMustafa42** [apple/swift#71079]
### Description

Blank rows are observed for certain options when attempting to utilize a `Divider` within the `Menu` list, specifically when it is nested inside a `Section`. The root cause may be related to the implementation of SwiftUI views on macCatalyst app.

<img width="304" alt="Screenshot 2024-01-23 at 4 03 39 AM" src="https://github.com/apple/swift/assets/23383207/9224f46a-2d96-468d-81fd-c96dd8a2cd76">

### Reproduction

```swift
struct ContentView: View {
    var body: some View {
        Menu("Button") {
            Section {
                Button("Option 1") { }
                Divider()
                Button("Option 2") { }
            }
        } 
    }
}
```

### Expected behavior

The `Menu` should show a list of items that are nested inside a `Section` with a divider instead of blank spaces similar to iOS with exact code.

<img width="247" alt="Screenshot 2024-01-23 at 4 05 56 AM" src="https://github.com/apple/swift/assets/23383207/99203314-9fb4-4aa5-8c25-bb2797604ff3">

### Environment

swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Xcode version: 15.1 (15C65)
macOS version: 14.2 (23C64)

**Comment by tbkka** [comment]
Issues with SwiftUI, MacCatalyst, and other Apple-proprietary products should be filed at feedbackassistant.apple.com

This repository is for the cross-platform Swift open-source language project.
