### ISSUE TITLE
Could it be closures with global actors should be Sendable?

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#71098]
### Description

I was recently confronted with the following bit of code.

It does not produce any warnings. But then I was like "wait second, the compiler knows this is a @MainActor function, so I shouldn't need it *also* restrict it to be Sendable. Yet the compiler thinks I do and I do not understand why that would be.

### Reproduction

```swift
func sendableMainActorFunction(task: @escaping @Sendable @MainActor () -> Void) {
	Task.detached {
		await task()
	}
}
```

### Expected behavior

I would expect that the global actor annotation is all that's needed to capture this function in other @Sendable closures.

### Environment

Swift 5.10 Development Snapshot 2024-01-18

**Comment by hborla** [comment]
Fixed by https://github.com/apple/swift/commit/99fee4eea291b3a4f7559cecc63283cc48242c9c

**Comment by hborla** [comment]
Note that this change is behind `-enable-upcoming-feature GlobalActorIsolatedTypesUsability` / `-swift-version 6`
