### ISSUE TITLE
How can self be accessible in a non-isolated async function of a non-Sendable type?

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#71097]
### Description

I was thinking about the code from https://github.com/apple/swift/issues/65315. And I kept coming back to the same core problem:

How is it that self could *ever* be safe to access in a non-isolated context like this? Is there any way to actually use the async function of this non-Sendable type in a safe way?

### Reproduction

```swift
struct Counter {
    private var counter = 0
    mutating func increment() async {
        self.counter += 1 <- access self somehow ok?
    }
}
```

### Expected behavior

I would expect a warning about accessing self in a non-isolated context.

### Environment

Swift 5.10 Development Snapshot 2024-01-18

**Comment by hborla** [comment]
> Is there any way to actually use the async function of this non-Sendable type in a safe way?

Yes! If you create the non-`Sendable` type in a `nonisolated async` context, then it's totally fine to call a `nonisolated async` method. In that case, the non-`Sendable` value is effectively isolated to the task that it's created in, and it can never be passed over a task boundary.

**Comment by hborla** [comment]
I'm going to close this as correct behavior, but I'm happy to answer follow up questions either here or on the forums.

**Comment by mattmassicotte** [comment]
No this actually makes perfect sense. Thank you so much!

**Comment by hborla** [comment]
> because the method is async, there's always an actor hop in calling it, which ensures that self has been "sent". So no, this is never safe?

If the method is not actor isolated, as in this example, then there's a hop to the generic executor. If the caller is already on the generic executor at runtime, there will be no switch at runtime. I maintain my original answer that this is safe if the caller is on the generic executor already. There are more restrictions when calling from an actor-isolated context: the non-Sendable value must be in a region that is disconnected from the actor's region in order for the async call to be safe.
