### ISSUE TITLE
Function with isolated parameter of globally-isolated type does not produce a warning

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#71177]
### Description

There is a warning for globally-isolated functions that also have isolated parameters. But, no warning when the entire type is isolated. Seems like the same thing to me.

### Reproduction

```swift
@MainActor
final class MainIsolated1 {
	public func isolatedParameter(on actor: isolated any Actor) {
	}
}

final class MainIsolated2 {
	@MainActor
	public func isolatedParameter(on actor: isolated any Actor) {
	}
}
```

### Expected behavior

I'd expect a warning for both of this situations.

### Environment

Swift 5.10
Xcode Version 15.3 beta (15E5178i)

**Comment by hborla** [comment]
It isn't the same; if you write `@MainActor` on the type, a different isolation annotation on a method will cause the `@MainActor` from the type to not be inferred on the method. If you write both isolation annotations on the method, then it's an error because the isolation cannot be both.
