### ISSUE TITLE
Solutiuon to #68887 references incorrect path

### ISSUE THREAD

**Issue by jhenzie** [apple/swift#71251]
### Description

#68887 solutuon (renaming of dinput.lib) refernces the include path rather than the lib path.  Not a big deal but probably worth correcting.

Should be:  `C:\Program Files (x86)\Windows Kits\10\Lib\[SDKVersion]\um\dinput8.lib`

### Reproduction

Attempt build on windows.

### Expected behavior

Solution to #68887 should reference the correct path.

### Environment

N/A

**Comment by compnerd** [comment]
The solution was a fix to the modulemap, the comment there is just a workaround which should no longer be needed.
