### ISSUE TITLE
compiler doesn't flag multiple calls to consuming func

### ISSUE THREAD

**Issue by eecs441staff** [apple/swift#71306]
### Description

When `struct S` below is declared `~Copyable`, Xcode 15.3 beta tags its instance (`s`) as being consumed more than once. But if `S` is declared without `~Copyable`, Xcode doesn't give an error message and the consuming function `value()` can be called more than once on the instance.

### Reproduction

```swift
struct S: ~Copyable {
    let v = "hi"
    consuming func value() -> String { return v }
}

func f() {
    let s = S()   // Xcode 15.3 beta error message: 's' consumed more than once
    print(s.value())
    print(s.value())
}

f()
```
but:
```swift
struct Sc  { // or class
    let v = "hi"
    consuming func value() -> String { return v }
}

func g() {
    let s = Sc()             // no error message
    print(s.value())
    print(s.value())      // prints out a second time
}

g()
```

### Expected behavior

Xcode gives the same error message in both cases and the second call to `s.value()` an error (as per [SE-0377](https://github.com/apple/swift-evolution/blob/main/proposals/0377-parameter-ownership-modifiers.md#syntax-of-parameter-ownership-modifiers)).

### Environment

Xcode 15.3 beta on macOS 14.4 beta CLI.

**Comment by tbkka** [comment]
This is expected.  The compiler is allowed to freely make copies of a Copyable type.  I've added comments below to clarify how this works in this case:
```
func g() {
    let s = Sc()
    // Because `s` will be used again, the compiler will actually
    // create a copy for this first call.  That copy gets consumed here:
    print(s.value())
    // The original value can then be consumed here:
    print(s.value())
}
```

**Comment by eecs441staff** [comment]
Thanks. I realized a copy has been made after posting the issue.  The following prevents the compiler from making a copy of `s`:

```
func h(_ s: consuming Sc) {  // error: s consumed more than once
    print(s.value())   // consumed here
    print(s.value())   // consumed again here
}
h(Sc())
```
Perhaps there Is a compiler flag/Xcode setting that gives a warning when a copy is made for a value about to be consumed? Thanks.
