### ISSUE TITLE
Unnecessary nonisolated(unsafe) produces no warning

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#71546]
### Motivation

During the process of migrating a system towards supporting concurrency, you might need to use `nonisolated(unsafe)` from SE-0412.

```swift
public final class ActuallySendableClass {
	public init() {
	}
}

struct NonIsolatedContainer {
	nonisolated(unsafe) static let a = ActuallySendableClass()
}
```

But, later on, the class might be updated to conform to `Sendable`.  Today, no diagnostics are produced.

```swift
public final class ActuallySendableClass: Sendable {
	public init() {
	}
}

struct NonIsolatedContainer {
	// now unnecessary
	nonisolated(unsafe) static let a = ActuallySendableClass()
}
```

### Proposed solution

I think a warning would be appropriate here now that `nonisolated(unsafe)` is no longer required.

**Comment by hborla** [comment]
I think this is a good idea. There are cases where `nonisolated` is still necessary (e.g. for a public actor property), but in those cases we can still warn about removing the `(unsafe)` part.

**Comment by hborla** [comment]
@simanerush This is a good concurrency starter bug! Interested in taking a look?
