### ISSUE TITLE
can no longer consume a local `let` binding that used deferred initialization

### ISSUE THREAD

**Issue by tayloraswift** [apple/swift#71607]
### Description

it told me to file a bug

```
<stdin>:12:17: error: 'consume' applied to value that the compiler does not support. This is a compiler bug. Please file a bug with a small example of the bug
    _ = consume x
                ^
```

### Reproduction

```swift
func f() 
{
    let x:[Int] ; x = []
    _ = consume x
}
```

### Expected behavior

it worked on 5.9

### Environment

Swift version 5.11-dev (LLVM 1bcf1d71b715d0d, Swift 009a93a0f83dd5c)
Target: x86_64-unknown-linux-gnu

### Additional information

it also happens [on 5.10](https://swiftfiddle.com/?c=H4sIAAAAAAAAA6tWSlayUkorzUtWSNPQVIjJq47JUwCCnNQShQqraM%2B8klgFa4UKBVuF6FiITDyQnZyfV1yam6pQEZNXq6SjVAY0Ii8zPaMkp1LXVM%2FQQKkWAEocwEpXAAAA)

**Comment by nate-chandler** [comment]
Fixed by https://github.com/apple/swift/pull/72211 .  Regression test added in https://github.com/apple/swift/pull/72225 .
