### ISSUE TITLE
can no longer consume local `var` binding

### ISSUE THREAD

**Issue by tayloraswift** [apple/swift#71605]
### Description

it told me to file a bug 

```
error: 'consume' applied to value that the compiler does not support. This is a compiler bug. Please file a bug with a small example of the bug
    _ = consume x
                ^
error: fatalError
```

### Reproduction

```swift
func f()
{
    var x:[Int] = []
    _ = consume x
}
```

### Expected behavior

it worked in 5.9

### Environment

Swift version 5.10-dev (LLVM dbfaba0078e9380, Swift 63c8b551eb2f613)
Target: x86_64-unknown-linux-gnu

### Additional information

it happens [on 5.10](https://swiftfiddle.com/?c=H4sIAAAAAAAAA6tWSlayUkorzUtWSNPQjMmrjslTAIKyxCKFCqtoz7ySWAVbhehYiGg8kJ2cn1dcmpuqUBGTVxuTp6SjVAbUn5eZnlGSU6lrqmdooFQLAB0e%2BjdUAAAA) and also happens [on main](https://swiftfiddle.com/?c=H4sIAAAAAAAAA6tWSlayUkorzUtWSNPQjMmrjslTAIKyxCKFCqtoz7ySWAVbhehYiGg8kJ2cn1dcmpuqUBGTVxuTp6SjVAbUn5eZnlGSU6mbm5iZp1QLAOh%2FH2VUAAAA)

**Comment by arennow** [comment]
Seeing the same thing on Xcode 15.3.0 RC 1 (`Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)`)

It seems like most uses of `consume` don't work in this build, including [the example](https://github.com/apple/swift-evolution/blob/main/proposals/0366-move-function.md#proposed-solution-consume-operator) given in the Swift Evolution proposal for this feature

**Comment by nate-chandler** [comment]
Fixed by https://github.com/apple/swift/pull/72211 .  Regression test added in https://github.com/apple/swift/pull/72220 .
