### ISSUE TITLE
[NoncopyableGenerics] Unexpected implicit relaxation of copyability of generic types

### ISSUE THREAD

**Issue by lorentey** [apple/swift#71690]
### Description

I do not expect the `Copyable` constraint to get implicitly relaxed on type definitions, but it appears that there are some sort of inference rules that make types conditionally(?!) copyable if they have potentially non-copyable type parameters.

### Reproduction

```swift
struct Rigid: ~Copyable {}
struct Thing<T: ~Copyable> {}

func test<T>(_ value: T) {}

let t = Thing<Rigid>()
test(t)
```

```
foo.swift:7:1: error: global function 'test' requires that 'Rigid' conform to 'Copyable'
test(t)
^
foo.Thing<T>:1:11: note: requirement from conditional conformance of 'Thing<Rigid>' to 'Copyable'
extension Thing : Copyable {
          ^
```

### Expected behavior

I strongly expect `Thing` to be copyable, as I did not explicitly ask for it to be non-copyable.

I _especially_ did not ask for it to be conditionally copyable if `T` happens to be copyable.

### Environment

main, `--enable-experimental-noncopyable-generics true`

rdar://123251893

**Comment by tbkka** [comment]
CC: @kavon @slavapestov

**Comment by kavon** [comment]
This is part of the proposed design:

https://github.com/apple/swift-evolution/blob/9c83d4c9caa0de397c4f4ab49fdc04a7c052cde1/proposals/NNNN-noncopyable-generics.md#automatic-synthesis-of-conditional-copyable-conformance

This is good feedback that it's probably unexpected behavior.
