### ISSUE TITLE
Non-sensical fix-it (and weird error message) when trying to multiply a Duration by an integer

### ISSUE THREAD

**Issue by wadetregaskis** [apple/swift#72085]
### Reproduction

```swift
let origin = SuspendingClock.now
let duration = Duration.seconds(1)

let overallOffset = .now - origin
let loopIndex = overallOffset / duration
let durationOfCompletedLoops = loopIndex * duration // 🤨 Operator argument #2 must precede operator argument #1
                                                    // ❌ Replace 'loopIndex * duration' with 'durationloopIndex'
```

### Expected behavior

1. It shouldn't care what order the operands are for the multiplication, it's a commutative operation.
2. The fix-it is just bizarre.  It makes no sense; it synthesises a non-existent variable reference out of basically nothing.

### Environment

swift-driver version: 1.90.10.1 Apple Swift version 5.10 (swiftlang-5.10.0.12.7 clang-1500.3.9.3)
Target: x86_64-apple-macosx14.0

**Comment by AnthonyLatsis** [comment]
> It shouldn't care what order the operands are for the multiplication, it's a commutative operation.

This part is expected behavior. Swift does not support argument permutations, operator or not. If the `Duration` parameter comes first in the declaration, so must the corresponding argument in the call:
https://github.com/apple/swift/blob/8c0db3fe7e4f9510fd7b694c567857131cc334c4/stdlib/public/core/Duration.swift#L308-L311

**Comment by CrazyFanFan** [comment]
@AnthonyLatsis  I'd like to work on this.  Can you assign me as the assignee please?

**Comment by tbkka** [comment]
Looks like the fix-it might have been intended to suggest `duration * loopIndex`.  If so, this might be a very easy fix.

**Comment by AnthonyLatsis** [comment]
Yeah, the intended fix-it is to swap the arguments.
