### ISSUE TITLE
[Source compatibility suite] RxReactiveObjC fails to build on main with `error: 'TARGET_OS_IOS' is not defined`

### ISSUE THREAD

**Issue by xymus** [apple/swift#72133]
### Description

```
/Users/ec2-user/jenkins/workspace/swift-main-source-compat-suite/swift-source-compat-suite/project_cache/RxReactiveObjC/.build/checkouts/ReactiveObjC.swiftpm/Sources/ReactiveObjC/MKAnnotationView+RACSignalSupport.m:1:6: error: 'TARGET_OS_IOS' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
    1 | #if (TARGET_OS_IOS)
      |      ^
1 error generated.
```

### Reproduction

```swift
```

### Expected behavior

Expect the project to build.

### Environment

Swift main branch.

### Additional information

https://ci.swift.org/job/swift-main-source-compat-suite/704/artifact/swift-source-compat-suite/FAIL_RxReactiveObjC_4.2_BuildSwiftPackage.log
https://ci.swift.org/job/swift-main-source-compat-suite/704/artifact/swift-source-compat-suite/FAIL_RxReactiveObjC_5.0_BuildSwiftPackage.log

**Comment by zixu-w** [comment]
Hi @igor-makarov !

I believe this is an actual project issue in https://github.com/SwiftPM-Packages/ReactiveObjC.swiftpm.
This error means that at the point of the check `#if (TARGET_OS_IOS)`, the target conditional macro `TARGET_OS_IOS` is not defined. Before we introduced this diagnostic (`-Wundef-prefix=TARGET_OS_`), the compiler would silently evaluate the macro to zero, meaning the checks are not doing what you expect them to do.

To make sure that your code is built properly with the target conditional macro guards, please make sure to add `#import <TargetConditionals.h>` before any reference to the `TARGET_OS_*` macros.

(Same as https://github.com/apple/swift/issues/57554)

**Comment by xymus** [comment]
Duplicate of #57554
