### ISSUE TITLE
`GeneratedAssetSymbols.swift` will show warning when Strict Concurrency Checking is on

### ISSUE THREAD

**Issue by frogcjn** [apple/swift#72141]
### Description

`GeneratedAssetSymbols.swift` will show warning when Strict Concurrency Checking is on.
The error message is:
```
/Users/username/Library/Developer/Xcode/DerivedData/projectname-uuid.noindex/projectname.build/Debug/projectname.build/DerivedSources/GeneratedAssetSymbols.swift:35:16 

Static property 'assetName' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6

```

### Reproduction

1. Create a new Xcode Project
2. Put some image asset in the Assets.xcassets
3. Turn on "Strict Concurrency Checking" in the build settings of the target or the entire project.
4. Build

### Expected behavior

Should not show the static variable isolation warning error

### Environment

Swift 5.10, Xcode 15.3

**Comment by hborla** [comment]
This is resolved in Xcode 15.4: https://developer.apple.com/documentation/xcode-release-notes/xcode-15_4-release-notes#Asset-Catalogs
