### ISSUE TITLE
adding global actor erroneously allowed when overriding an ObjC class's method

### ISSUE THREAD

**Issue by KeithBauerANZ** [apple/swift#72238]
### Description

Normally, you can't add a global actor annotation when overriding a method (obviously!); this is disallowed:

```swift
class Base {
    func a() {}
}

class Inherited: Base {
    @MainActor
    override func a() {}
}
```

```
MainActorOverride.swift:7:19: error: main actor-isolated instance method 'a()' has different actor isolation from nonisolated overridden declaration
    override func a() {}
                  ^
MainActorOverride.swift:2:10: note: overridden declaration is here
    func a() {}
         ^
```

However, when the method being overridden is from an Objective-C class, this is erroneously allowed.

### Reproduction

```swift
import Foundation

class Inherited: UserDefaults {
    @MainActor
    override func object(forKey: String) -> Any? {
        nil
    }
}
```

### Expected behavior

The override of `object(forKey:)` should produce the same error as the override of `a` in the initial example.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by 0xsoria** [comment]
Hey! I'd like to try to fix this issue, do you have any tips on where to start?

I wrote this test in the `actor_isolation_objc.swift` and it of course fails, now I have to figure out how to make it pass.

```
class Broom: NSObject {
  @MainActor
  override func isProxy() -> Bool { // expected-error {{main actor-isolated instance method 'isProxy()' has different actor isolation from nonisolated overridden declaration}}
	false
  }
}
```

**Comment by hborla** [comment]
Sorry @0xsoria, I put up a fix before I saw you were interested in taking a look! I can help you find another issue to tackle if you're still interested.

**Comment by hborla** [comment]
Fixed by https://github.com/apple/swift/pull/74238
