### ISSUE TITLE
It is possible to call a @MainActor-bound closure in a closure that is not @MainActor-bound

### ISSUE THREAD

**Issue by dfed** [apple/swift#72382]
### Description

I have a reproducible case on Swift 5.10 with Strict Concurrency Checking turned on where I can assign a `@MainActor`-bound closure to a non-`@MainActor`-bound closure and execute the non-`@MainActor`-bound closure in a non-Main context synchronously.

### Reproduction

```swift
final class TestMainActorErasingClosure {
    @MainActor
    final class SomeMainActor {
        init() {}
    }

    struct Builder<T> {
        let build: () -> T
    }

    func build() {
        _ = builder?.build()
    }

    @MainActor
    func assign() {
        builder = Builder {
            SomeMainActor()
        }
    }

    private var builder: Builder<SomeMainActor>?
}
```

### Expected behavior

`assign()` method fails to compile because we're passing in a `@MainActor`-bound closure to a non-`@MainActor`-bound `() -> T` closure.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

### Additional information

Strict concurrency checking is turned on. I have not tested whether this compiles on the Swift 6 branch.

Note that `assign()` doesn’t compile if I remove the `@MainActor` decoration, which I fully expect. But what I didn’t expect is that `assign()` would compile after adding the `@MainActor` decoration, since we're effectively erasing the `@MainActor` attribute from `SomeMainActor.init`.

**Comment by hborla** [comment]
This is correct behavior, and it happens because the type of your closure is not `Sendable`:

```
let build: () -> T
```

This means that `Builder` itself is not `Sendable`, so it can never leave the context it's formed in. Thus, the closure is implicit isolated to `@MainActor`, which is why the example fails to compile without the `@MainActor` annotation on `assign()`.
