### ISSUE TITLE
Undefined reference when subclassing class with internal/private methods

### ISSUE THREAD

**Issue by finnvoor** [apple/swift#72890]
### Description

**Embedded Swift**:

Sort of similar to #72531, subclassing an open class with a private or internal method from a module causes a linker failure.

This only happens when using `-O` or `-Osize`, not `-Onone`.

### Reproduction

```swift
// File1.swift
open class Foo {
    public init() {}
    
    func fizz() {}
}
```

```swift
// File2.swift
import File1

class Bar: Foo {}
```

```console
swiftc -O -wmo -enable-experimental-feature Embedded -c File1.swift -emit-module -o Modules/File1.o
swiftc -O -wmo -enable-experimental-feature Embedded -I Modules/ -c File2.swift -o Modules/File2.o
objdump -t Modules/File2.o | swift demangle > dump.txt
```

In `dump.txt`:
```
*UND* File1.Foo.fizz() -> ()
```

### Expected behavior

File1.Foo.fizz should be defined.

### Environment

Nightly Swift

Apple Swift version 6.0-dev (LLVM ed26ccb500109e5, Swift b3b2f37262690ca)
Target: arm64-apple-macosx14.0

### Additional information

cc @kubamracek

**Comment by kubamracek** [comment]
Reproduced. And yes, interestingly, it only happens under -O and -Osize.

**Comment by kubamracek** [comment]
rdar://126044717
