### ISSUE TITLE
Opaque return type sendability checking hole

### ISSUE THREAD

**Issue by orobio** [apple/swift#72926]
### Description

For a `Sendable` opaque return type, the compiler allows the actual type to be non-`Sendable`.

### Reproduction

```swift
extension AsyncSequence {
    func makeSendable() -> some (AsyncSequence<Element, Failure> & Sendable) {
        self
    }
}
```

### Expected behavior

Depending on checking level, an error or warning should be emitted indicating that Self is not `Sendable`.

### Environment

nightly-6.0-jammy: swift-6.0-DEVELOPMENT-SNAPSHOT-2024-04-06-a

Swift version 6.0-dev (LLVM c7c963afc327ad1, Swift bca5018bca30ddf)

Tested with both -strict-concurrency=complete and -swift-version 6.

**Comment by hborla** [comment]
This is fixed in https://github.com/apple/swift/pull/73697
