### ISSUE TITLE
(type checker) regression on main in subtyping rules for tuple labels

### ISSUE THREAD

**Issue by tayloraswift** [apple/swift#73207]
### Description

forums discussion here: https://forums.swift.org/t/did-the-subtyping-rules-for-tuple-labels-change-in-swift-6/71408

on main, it seems it is no longer allowed to ignore tuple labels when binding to an unlabeled tuple.

### Reproduction

```swift
func size(_ levels:[Range<Int>]) 
{
    for (i, leaves):(Int, Range<Int>) in levels[...].enumerated() 
    {
    }
}
```

Fiddle: https://swiftfiddle.com/?c=H4sIAAAAAAAAA0XOwQqDMAzG8VcJObXQ9QHK2H3XXa1I0egKNQNbC5v47kYQFr7jnx%2FZsEeH48o95Pgj1UGiSim75hV4ovuTy6PV4HnzDHLjZwEVjVShUtZOSWDg32qIfBGNtba1xOtMSyg0qJM5jYvaPcvQYJUPOE7vkr63OUTG%2FQCfa1LelgAAAA%3D%3D

### Expected behavior

it should compile as it did in Swift 5.10

### Environment

Swift version 6.0-dev (LLVM b3d7c45a25a792f, Swift 81534a6c151c6ed)
Target: x86_64-unknown-linux-gnu

**Comment by xedin** [comment]
Thank you for filling this!
