### ISSUE TITLE
Protocol becomes impossible to implement in this situation

### ISSUE THREAD

**Issue by Luminaron** [apple/swift#73201]
### Description

When protocol has `static func +` with all `any` types as its arguments and return type. This protocol becomes impossible to implement. However, swift does compile the code. Furthermore, when using `extension` to provide a default implementation, this problem can hide deeper.

### Reproduction

```swift
protocol P
{
    var x: Int { get }
    
    static func + (a: any P, b: any P) -> any P
}
/// The above code alone compiles with no problem

/// Problem 1: A concrete type cannot implement + operator
// struct A: P
// {
//     var x: Int = 0
//     
//     // Error: Member operator '+' must have at least one argument of type 'A'
//     static func + (a: any P, b: any P) -> any P { A(x: 0) }
// }

/// Problem 2: extension hides the problem EVEN further
// struct A: P { var x: Int = 0 }
// struct B: P { var x: Int = 0 }
//
// extension P
// {
//     static func + (a: any P, b: any P) -> any P { A() }
// }

/// Code for problem 2 compiles up until this line.
/// However, as soon as I use `+` operator, things break.
/// Also, in the above code, the almost cyclic-like reference structure between
/// protocol and types is very weird. Are they also allowed?
// let _ = A() + B() // Error: Generic parameter 'Self' could not be inferred

```

### Expected behavior

It would be nice if Swift compiler can detect and prevent impossible code like this to be compiled.

### Environment

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0

**Comment by HardikMaru21** [comment]
I have reviewed problem 1 and problem 2. If you consider using the adapter pattern or bridge pattern, it could potentially solve the existing issues. These patterns also provide the option to incorporate new alternatives to address both problem 1 and problem 2. My solution might not having 100% accuracy. I am jut trying to resolve the problem.
