### ISSUE TITLE
Incompatibility of `borrowing` with `any` type in function arguments

### ISSUE THREAD

**Issue by rofle100lvl** [apple/swift#73525]
### Reproduction

```swift
protocol K {
    var a: Int { get }
}

protocol B {
    init(k: any K)
}

struct A: B {
    let a: Int
    
    init(k: borrowing K) {
        self.a = k.a
    }
}
```

### Expected behavior

When using the borrowing operator with a function argument of type any pointing to a protocol, the compiler should successfully parse and handle this combination

### Environment

Apple Swift version 6.0-dev (LLVM 7b8e6346027d2b1, Swift 763421cee31dc8f)
Target: arm64-apple-macosx14.0

swift 5.10 as well

### Additional information

Now we get compile error: "Usage of no-implicit-copy value that the compiler can't verify. This is a compiler bug. Please file a bug with a small example of the bug"

**Comment by tbkka** [comment]
CC: @kavon

**Comment by nate-chandler** [comment]
Regression test added in https://github.com/apple/swift/pull/74343 .
