### ISSUE TITLE
@_noLocks doesn't work with ~Copyable types

### ISSUE THREAD

**Issue by jcavar** [apple/swift#73582]
### Description

A simple usage of `@_noLocks` fails to compile when using `~Copyable` types. I am not sure if this is genuine issue or a bug in performance annotation implementation.

### Reproduction

```swift

// this code performs reference counting operations which can cause locking
struct Test: ~Copyable {
}

@_noLocks
@_noAllocation
func test() {
    Test()
}

```

### Expected behavior

Code compiles and doesn't perform reference counting

### Environment

It fails on both 5.10 and nightly snapshots

cc @eeckstein

**Comment by tbkka** [comment]
CC: @eeckstein @kavon

**Comment by tbkka** [comment]
@jcavar   The code you've written -- without any annotations at all -- should not perform any reference counting because there are no `class` values.

**Comment by eeckstein** [comment]
Fix: https://github.com/apple/swift/pull/73611

**Comment by eeckstein** [comment]
6.0: https://github.com/apple/swift/pull/73637

**Comment by jcavar** [comment]
Thank you @eeckstein! I've downloaded the latest Swift 6 toolchain and don't get the error anymore.

I do get a similar issue further down the line that I described here:

https://github.com/apple/swift/issues/73951
