### ISSUE TITLE
miscompile: assigning a subclass instance to existential causes base class methods to be called instead of subclass methods

### ISSUE THREAD

**Issue by tayloraswift** [apple/swift#73962]
### Description

assigning an instance of a subclass to a stored property of **boxed** existential type (e.g. no `AnyObject` constraint) causes the subclass instance to lose its dynamic type, causing it to behave as if it were an instance of the base class.

the only occurs when compiling in release mode, so i suspect an optimizer bug.

```
$ swiftc -O -parse-as-library test.swift 
$ ./test 
SecureContext
BaseContext
```

```
$ swiftc -parse-as-library test.swift 
$ ./test 
SecureContext
SecureContext
```

from fuzzing the test program this appears to be a really nasty interaction between the `required convenience` initializer, the `private` access level on the designated init, and some sort of unsound initializer inheritance.

### Reproduction

```swift
protocol ResponseContext
{
    init(_:Int)

    func f()
}
class BaseContext:ResponseContext
{
    private
    init()
    {
    }

    convenience required
    init(_:Int)
    {
        self.init()
    }

    func f()
    {
        print("BaseContext")
    }
}
final
class SecureContext:BaseContext
{
    override
    func f()
    {
        print("SecureContext")
    }
}


protocol ServerEndpoint
{
    associatedtype Context:ResponseContext

    func response(context:Context)
}
extension ServerEndpoint
{
    func response()
    {
        let context:Context = .init(1)
        self.response(context: context)
    }
}

struct A:ServerEndpoint
{
    struct S
    {
        let context:any ResponseContext

        init(context:any ResponseContext)
        {
            context.f()
            //  Why does this change the (dynamic) type of `context`?
            self.context = context
            self.context.f()
        }
    }

    typealias Context = SecureContext

    func response(context:SecureContext)
    {
        let _:S = .init(context: context)
    }
}

@main public
enum Main
{
    static
    func main()
    {
        let a:A = .init()

        a.response()
    }
}

```

### Expected behavior

both calls to `f` should print `SecureContext`

### Environment

$ swift --version
Swift version 5.10 (swift-5.10-RELEASE)
Target: x86_64-unknown-linux-gnu

### Additional information

as far as i can tell, this miscompile [also occurs on main](https://swiftfiddle.com/?c=H4sIAAAAAAAAA41Uy26DMBD8lRUnkNpEvSJVVVr10Gs59IKUWGYJlsia2gYVRfx7zfsV0hoOBu%2FMzu4sXB3u%2BE6mpJFcpvCJOpOk8U2SwR8T0jUksEuQMO7R%2FyDjhdS%2BinPiELv2uQqJp0xreGUD0t9iypQomMEJrdfuu%2FOq5%2BeSCiSBxBEUfudCYXRDzARaL41pvJvSVmu9C4hVRMYNnYn60BnR9o4FsbQvMkCeq6HMKagvURaolIjwn3lnhIvM9TWYE6CyzO8UZdIih3RWlOTC9jQyZYawacBEjurOXN4Fd0GtmXaDpIWkrYxzjnVlKRpYMMMztLY8eQuzVlp66KIR2qicGzj4G6K68%2BCuGkblesbH0EbhndiJ9kmCblrrgN1gdL%2F2e4CvpIRIogaTCA08YXRGu0dwo5LYRXAPGutkDKeO6PQyp2laxYde8l77VsxcSLX4FupsLBVMw2jPfAzvTsss9Lb9Rz8YLP%2FD2JBqAPMPA6D5x7BxMjznwSnsb4rEOTFp%2BXhhgpzqFxH0o9e7BAAA).

**Comment by slavapestov** [comment]
Reduction:

```
class C {
  private init() {}

  convenience init(_: Int) {
    self.init()
  }
}

class D: C {}

print(D(1))
```

This prints D at -Onone and C at -O.

**Comment by tayloraswift** [comment]
i also remember noticing something resembling that yesterday, but the simplified example otherwise behaves correctly if you observe something besides the reflected description (e.g. calling an instance method). for some reason, i could only observe it actually dispatching to the wrong method when it goes through all the “steps” in the original test program.

**Comment by slavapestov** [comment]
The convenience initializer does a virtual dispatch:

```
  %7 = class_method %1 : $@thick C.Type, #C.init!allocator : (C.Type) -> () -> C, $@convention(method) (@thick C.Type) -> @owned C // user: %8
```

However the subclass doesn't override the allocating entry point:

```
sil_vtable C {
  #C.init!allocator: (C.Type) -> () -> C : @$s3cls1CCACyc33_1CC8E09DD8881006B82691EF1AA7E2C6LlfC        // C.__allocating_init()
  #C.deinit!deallocator: @$s3cls1CCfD   // C.__deallocating_deinit
}

sil_vtable D {
  #C.init!allocator: (C.Type) -> () -> C : @$s3cls1CCACyc33_1CC8E09DD8881006B82691EF1AA7E2C6LlfC [inherited]    // C.__allocating_init()
  #D.deinit!deallocator: @$s3cls1DCfD   // D.__deallocating_deinit
}
```

The problem is specifically because the designated init is private. You can make it public to work around the issue until its fixed.

**Comment by tayloraswift** [comment]
ah, that makes sense. thanks!

**Comment by slavapestov** [comment]
> for some reason, i could only observe it actually dispatching to the wrong method when it goes through all the “steps” in the original test program.

Depending on what you do with the class instance and what the optimizer does, we may have enough static type information to dispatch method calls properly (especially since your subclass was originally final). And if your subclass doesn't add stored properties you might have a hard time observing the fact that the isa pointer is incorrect, unless you use reflection as you did.

**Comment by slavapestov** [comment]
So this is a bug in the type checker, perhaps, and not an optimizer issue at all. The optimizer just makes the problem more apparent.

**Comment by tayloraswift** [comment]
does that mean the base class designated init was “supposed” to be `public` and the `private` init is missing a diagnostic?

**Comment by slavapestov** [comment]
> does that mean the base class designated init was “supposed” to be public and the private init is missing a diagnostic?

It's supposed to work the way it's written without a diagnostic. The case we can't implement is

```
open class Base {
  public init() {}  // need at least one public designated init for subclasses to be definable
  private init(x: Int) {}
  public required convenience init() { self.init(x: 123) }  // calls the private init
}

// In some other module:

public class Derived: Base {}  // error: you must implement the required convenience init by hand
```
