### ISSUE TITLE
Hyphenation difference between "nonisolated" and other forms of isolation diagnostics

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#73982]
### Description

Everywhere I can find, hyphenation is used both in documentation and diagnostics for isolation. "actor-isolated", "task-isolated". But in this example, the warning uses "nonisolated".

```
14 | 
15 | 	await updateUI(with: style)
   |        |- error: sending 'style' risks causing data races
   |        `- note: sending 'style' to main actor-isolated global function 'updateUI(with:)' risks causing data races between main actor-isolated and local nonisolated uses
16 | 
17 | 	style.store()
   |        `- note: access can happen concurrently
18 | }
19 | 
```

### Reproduction

```swift
// Non-Sendable reference type
class Style {
	func store() {
	}
}

@MainActor
func updateUI(with style: Style) {
}

// a non-isolated use
func refresh() async {
	let style = Style()

	await updateUI(with: style)

	style.store()
}
```

### Expected behavior

I would expect this to use "non-isolated:

```
note: sending 'style' to main actor-isolated global function 'updateUI(with:)' risks causing data races between main actor-isolated and local non-isolated uses
```

### Environment

Apple Swift version 6.0-dev (LLVM 4b0b1f9e1a69523, Swift 91a3abcf816bc36)
Target: arm64-apple-macosx14.0

**Comment by xwu** [comment]
This seems fine to me: it’s an accepted spelling and matches the contextual keyword `nonisolated`. There is no inconsistency, as we are not describing something being isolated to or by some entity called a “non.”

**Comment by ktoso** [comment]
Agreed that it’s best to stick to the “actor-isolated” and “nonisolated”… we don’t have “nonIsolated” and the word seems to be spelled as “nonisolated” properly after all: https://en.wiktionary.org/wiki/nonisolated

so the current spellings in docs etc seem good to me

**Comment by mattmassicotte** [comment]
Thanks for the research here - sorry for making you do it!
