### ISSUE TITLE
Undefined symbol linker errors when enabling GlobalActorIsolatedTypesUsability 

### ISSUE THREAD

**Issue by Jnosh** [apple/swift#74009]
### Description

When enabling GlobalActorIsolatedTypesUsability via `-enable-upcoming-feature GlobalActorIsolatedTypesUsability`, some code fails to build with linker errors:

### Reproduction

```swift
// Undefined symbols for architecture arm64:
//  "static Swift.MainActor.assumeIsolated<A where A: Swift.Sendable>(_: @Swift.MainActor @Sendable () throws -> A, file: Swift.StaticString, line: Swift.UInt) throws -> A",
MainActor.assumeIsolated {}


// Undefined symbols for architecture arm64:
//  "(extension in SwiftUI):DeveloperToolsSupport.Preview.init(_: Swift.String?, traits: DeveloperToolsSupport.PreviewTrait<DeveloperToolsSupport.Preview.ViewTraits>..., body: @Swift.MainActor @Sendable () -> SwiftUI.View) -> DeveloperToolsSupport.Preview"
import SwiftUI
#Preview {
    EmptyView()
}
```

### Expected behavior

Enabling GlobalActorIsolatedTypesUsability should not cause linker errors.

### Environment

Swift 6.0 Development Snapshot 2024-05-26 (a)

Apple Swift version 6.0-dev (LLVM 5b202efbc95a8bf, Swift https://github.com/apple/swift/commit/a17d360d1cc66ababfdd5a2e4df86cc9bcbdc471)
Target: arm64-apple-macosx14.0

**Comment by hborla** [comment]
Fixed in https://github.com/apple/swift/pull/74510

**Comment by Jnosh** [comment]
Working perfectly with the Xcode 16 beta 2 toolchain.
