### ISSUE TITLE
Swift 6 fails to compile for-await loop when it is scoped inside #available conditional

### ISSUE THREAD

**Issue by tonyarnold** [apple/swift#74377]
### Description

When executing the following code in Xcode 16.0 beta 1, compilation fails with the error: 

```
error: 'next(isolation:)' is only available in macOS 15.0 or newer
```

### Reproduction

```swift
let results = await withTaskGroup(of: [String].self) { group  in
    group.addTask {
        return [
            "Chilli",
            "Bandit",
            "Bingo",
            "Bluey"
        ]
    }

    var allResults = [String]()

    if #available(macOS 13.0, iOS 15.0, tvOS 15.0, visionOS 1.0, *) {
        for await results in group {
            allResults.append(contentsOf: results)
        }
    } else {
        for await results in group {
            allResults.append(contentsOf: results)
        }
    }

    return allResults
}

print(results)
```

### Expected behavior

The code compiles, just as it did with Swift 5.x.

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by ktoso** [comment]
Thanks for the report! Well look into it

**Comment by DougGregor** [comment]
Thank you for the report! This was fixed in https://github.com/apple/swift/pull/73913, but it didn't make it into beta 1.

**Comment by tonyarnold** [comment]
Thanks, Doug! Roll on beta 2 :beers:
