### ISSUE TITLE
"each Element" from a parameter pack will crash the compiler when used in the type of a closure.

### ISSUE THREAD

**Issue by JessyCatterwaul** [apple/swift#74391]
### Description

You can get the concept to work, but it requires a form of indirection which isn't always possible.

### Reproduction

Calling `parameterAndClosure` directly crashes the compiler.

```swift
func ƒ<each Parameter>(
  _ parameter: repeat each Parameter
) {
  repeat parameterAndClosure(each parameter) { _ in }
}

func parameterAndClosure<Parameter>(_: Parameter, _: (Parameter) -> Void) { }
```

But put another function in between, and that works fine.

```swift
func ƒ<each Parameter>(
  _ parameter: repeat each Parameter
) {
  repeat justAParameter(each parameter)
}

func justAParameter<Parameter>(_ parameter: Parameter) {
  parameterAndClosure(parameter) { _ in }
}
```

### Stack dump

```text
Command SwiftCompile failed with a nonzero exit code
```

### Expected behavior

You don't need to have a function whose only job is to provide the closure.

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by slavapestov** [comment]
https://github.com/apple/swift/pull/74039
