### ISSUE TITLE
Main actor-isolated static method issue - Xcode 16 beta, Swift 6

### ISSUE THREAD

**Issue by rsyncOSX** [apple/swift#74448]
### Description

I have installed Xcode16 beta, enabled strict concurrency and Swift version 6. Settings in Xcode project are:
```
SWIFT_STRICT_CONCURRENCY = complete; 
SWIFT_VERSION = 6.0; 
```
Ahead of installing Xcode16 beta, strict concurrency was enabled in Swift5. I am extending the Commands by the Commands protocol and now it will *not* compile in version 6 of Swift. And I don't know how to solve the issue? Xcode issue this error:
```
/Users/thomas/GitHub/RsyncUI/SwiftUI.Commands:6:51 Main actor-isolated static method '_makeCommands(content:inputs:)' cannot be used to satisfy nonisolated protocol requirement
```
The code which does not compile in Xcode 16beta and Swift 6 enabled is:

### Reproduction

```swift
import SwiftUI

struct ExecuteCommands: Commands {
    @FocusedBinding(\.aborttask) private var aborttask
    var body: some Commands {
        CommandMenu("Abort") {
            Abborttask(aborttask: $aborttask)
        }
    }
}

struct Abborttask: View {
    @Binding var aborttask: Bool?

    var body: some View {
        Button {
            aborttask = true
        } label: {
            Label("Abort task", systemImage: "play.fill")
        }
        .keyboardShortcut("k", modifiers: [.command])
    }
}

struct FocusedAborttask: FocusedValueKey {
    typealias Value = Binding<Bool>
}

extension FocusedValues {
    var aborttask: FocusedAborttask.Value? {
        get { self[FocusedAborttask.self] }
        set { self[FocusedAborttask.self] = newValue }
    }
}
```

### Expected behavior

It should compile

### Environment

swift-driver version: 1.109.2 Apple Swift version 6.0 (swiftlang-6.0.0.3.300 clang-1600.0.20.10)
Target: arm64-apple-macosx14.0

**Comment by bigadz** [comment]
I'm hitting the same problem. I can repeat this after creating a new Swift App.

I'm finding that just having the following in my code base causes the issue. (I don't need to _use_ the commands, just include the following for compilation.)

```
import SwiftUI

struct AppCommands: Commands {

	@CommandsBuilder @MainActor @preconcurrency var body: some Commands {
		CommandGroup(replacing: CommandGroupPlacement.appSettings) {
			Button("Settings...") {
					print("Settings...")
			}.keyboardShortcut(KeyEquivalent(","), modifiers: .command)
		}
	}
}
```

**Comment by hborla** [comment]
This is a known bug in SwiftUI. It has already been reported via Apple's Feedback Assistant.
