### ISSUE TITLE
How are top-level nonisolated functions supposted to behave?

### ISSUE THREAD

**Issue by mattmassicotte** [apple/swift#74490]
### Description

I'm having trouble deciding exactly how this code is supposed to behave. But, it seems like this code is in conflict. It certainly appears like this context is both MainActor and also non-isolated...

### Reproduction

```swift
nonisolated func work() {
  MainActor.assertIsolated()
}

@MainActor
func alsoWork() {
    MainActor.assertIsolated()
}

MainActor.assertIsolated()

// shouldn't this actually be implictly asynchronous?
work()
alsoWork()
```

### Expected behavior

I expected the compiler to require an `await` to change actor context switch for the `work` function.

### Environment

Apple Swift version 6.0-dev (LLVM 6e13b8be259f20f, Swift 372de4670b9cd55)
Target: arm64-apple-macosx14.0

**Comment by Jnosh** [comment]
Doesn't a synchronous nonisolated function just run in the current isolation of the caller though, so no await is needed? 
It doesn't guarantee any particular isolation statically but in this instance it happens to be MainActor isolated dynamically as it is invoked from there.

**Comment by mattmassicotte** [comment]
No this is just me getting confused. But I appreciate you intrepreting it kindly!
