### ISSUE TITLE
Autolinking of proposal IDs

### ISSUE THREAD

**Issue by benrimmington** [apple/swift#74576]
A proposal ID such as SE-0387 is currently autolinked to

<https://apple.github.io/swift-evolution/#?proposal=SE-0387>

which is a "404: Not Found" error page (because the repository has been transferred).

---

**Settings → Integrations → Autolink references**

The old autolink could be removed (unless it can be edited).

The new autolink could have:

* a *Numeric* format (to disallow SE-ABCD).

* an `SE-` reference prefix.

* a target URL of

  ```
  https://www.swift.org/swift-evolution/#?proposal=SE-<num>
  ```

**Comment by AnthonyLatsis** [comment]
Should be fixed. Thanks, Mishal!

**Comment by AnthonyLatsis** [comment]
@shahmishal Are we deliberately linking to `swiftlang.github.io`, and not `swift.org`?
